Repository bytebase/bytebase, pull requests merged in 2023-05, with the labels that each got.

#5860 chore(mybatis): using non-recursive algorithm to build xml ast
  backend/plugin/parser/mybatis/ast/data_node.go
  backend/plugin/parser/mybatis/ast/mapper_node.go
  backend/plugin/parser/mybatis/ast/node.go
  backend/plugin/parser/mybatis/ast/query_node.go
  backend/plugin/parser/mybatis/parser.go
  backend/plugin/parser/mybatis/parser_test.go
  backend/plugin/parser/mybatis/test-data/test_simple_mapper.yaml
Labels: cla-signed

#5863 chore: add ssh types to frontend
  frontend/src/components/InstanceForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/common.ts
  frontend/src/types/dataSource.ts
  frontend/src/types/instance.ts
  frontend/src/types/sql.ts
  frontend/src/utils/instance.ts
Labels: cla-signed

#5865 feat(mybatis): support `if` `choose` `when` `otherwise` element in mybatis xml
  backend/plugin/parser/mybatis/ast/dymamic_node.go
  backend/plugin/parser/mybatis/parser.go
  backend/plugin/parser/mybatis/parser_test.go
  backend/plugin/parser/mybatis/test-data/test_dynamic_sql_mapper.yaml
  backend/plugin/parser/mybatis/test-data/test_simple_mapper.yaml
Labels: cla-signed

#5866 chore: add basic frontend form for connection over ssh
  backend/server/instance.go
  backend/server/sql.go
  backend/store/instance.go
  frontend/src/components/InstanceForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5870 chore: migrate rollbackStatement to sheet
  backend/legacyapi/issue.go
  backend/legacyapi/task.go
  backend/migrator/migration/prod/1.18/0001##migrate_task_payload_statement_to_sheet.sql
  backend/runner/rollbackrun/runner.go
  backend/runner/taskrun/scheduler.go
  backend/store/task.go
  backend/tests/rollback_test.go
  frontend/src/components/Issue/rollback/RollbackStatus.vue
  frontend/src/types/pipeline/task.ts
Labels: cla-signed

#5871 fix(test): restore mybatis xml to sql test should pass sql parse phase
  backend/plugin/parser/mybatis/ast/data_node.go
  backend/plugin/parser/mybatis/ast/dymamic_node.go
  backend/plugin/parser/mybatis/ast/query_node.go
  backend/plugin/parser/mybatis/parser_test.go
  backend/plugin/parser/mybatis/test-data/test_dynamic_sql_mapper.yaml
  backend/plugin/parser/mybatis/test-data/test_simple_mapper.yaml
Labels: cla-signed

#5872 chore: update bufbuild references
  frontend/src/types/proto/google/api/client.ts
  frontend/src/types/proto/google/api/expr/v1alpha1/syntax.ts
  frontend/src/types/proto/google/api/http.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/duration.ts
  frontend/src/types/proto/google/protobuf/empty.ts
  frontend/src/types/proto/google/protobuf/field_mask.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/google/type/expr.ts
  frontend/src/types/proto/store/activity.ts
  frontend/src/types/proto/store/approval.ts
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/store/idp.ts
  frontend/src/types/proto/store/issue.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/store/sheet.ts
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/store/user.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/types/proto/v1/bookmark_service.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/environment_service.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/types/proto/v1/logging_service.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/proto/v1/review_service.ts
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/proto/v1/role_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/types/proto/v1/subscription_service.ts
  proto/buf.gen.yaml
  proto/buf.lock
Labels: cla-signed

#5873 chore: update project member index
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/1.18/0002##update_project_member_index.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#5874 chore: add force option to project deletion
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/v1/project_service.proto
Labels: cla-signed

#5875 chore: implement project force deletion
  backend/api/v1/project_service.go
Labels: cla-signed

#5876 feat(mybatis): support mybatis xml `foreach` dynamic sql node
  backend/plugin/parser/mybatis/ast/dymamic_node.go
  backend/plugin/parser/mybatis/parser.go
  backend/plugin/parser/mybatis/test-data/test_dynamic_sql_mapper.yaml
Labels: cla-signed

#5878 chore: limit instance count for free plan
  backend/enterprise/config/config.go
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed, backport release/1.17.0

#5880 chore: add row status for policy metric
  backend/metric/collector/policy_count.go
  backend/metric/metric.go
Labels: cla-signed

#5882 chore: move disallow-signup feature to enterprise plan
  backend/legacyapi/plan.go
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/types/plan.yaml
Labels: cla-signed

#5881 fix: fix query limit in Oracle 11
  backend/plugin/db/util/driverutil.go
  backend/plugin/db/util/driverutil_test.go
Labels: cla-signed

#5883 chore: introduce force option to instance deletion
  backend/api/v1/instance_service.go
  backend/server/instance.go
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/v1/instance_service.proto
Labels: cla-signed

#5884 chore: select project owners who are not workspace owner or DBA first
  backend/runner/taskrun/scheduler.go
Labels: cla-signed

#5886 chore: select project owners who are not workspace owner or DBA first (Frontend)
  frontend/src/plugins/issue/logic/initialize/assignee.ts
Labels: cla-signed

#5885 feat: implement PostgreSQL AI-based index advisor
  backend/api/v1/database_service.go
  backend/plugin/parser/sql/ast/index_def.go
  backend/store/db_schema.go
  go.mod
  go.sum
Labels: cla-signed

#5887 chore: change schema version to 2.0
  backend/migrator/migration/prod/2.0/0000##add_sheet_source_bytebase_artifact.sql
  backend/migrator/migration/prod/2.0/0001##migrate_task_payload_statement_to_sheet.sql
  backend/migrator/migration/prod/2.0/0002##update_project_member_index.sql
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
Labels: cla-signed

#5889 feat: implement MySQL AI-based index advisor
  backend/api/v1/database_service.go
  backend/store/db_schema.go
Labels: cla-signed

#5890 feat: fetch index advice
  frontend/src/components/SlowQuery/Panel/AdviseIndex.vue
Labels: cla-signed

#5888 chore: update role.go
  backend/plugin/db/clickhouse/role.go
Labels: cla-signed

#5893 feat: allow click slow query log item for PostgreSQL to display index advice
  frontend/src/components/SlowQuery/Panel/DetailPanel.vue
  frontend/src/components/SlowQuery/Panel/LogTable.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
Labels: cla-signed

#5894 chore: remove dev guard and add feature guard for index advisor
  backend/api/v1/database_service.go
  frontend/src/components/SlowQuery/Panel/AdviseIndex.vue
  frontend/src/components/SlowQuery/Panel/DetailPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5898 chore(differ): add test for column format
  backend/plugin/parser/sql/differ/mysql/column_test.go
Labels: cla-signed

#5897 chore: oracle11 compatible
  backend/plugin/db/oracle/sync.go
Labels: cla-signed

#5896 chore: index-advisor guard
  backend/api/v1/database_service.go
  backend/legacyapi/plan.go
  frontend/src/types/plan.ts
Labels: cla-signed

#5900 feat(mybatis): support mybatis xml `property` element
  backend/plugin/parser/mybatis/ast/data_node.go
  backend/plugin/parser/mybatis/ast/dymamic_node.go
  backend/plugin/parser/mybatis/ast/mapper_node.go
  backend/plugin/parser/mybatis/ast/node.go
  backend/plugin/parser/mybatis/ast/query_node.go
  backend/plugin/parser/mybatis/parser.go
  backend/plugin/parser/mybatis/test-data/test_dynamic_sql_mapper.yaml
  backend/plugin/parser/mybatis/test-data/test_simple_mapper.yaml
Labels: cla-signed

#5895 feat(sso): support skip TLS verify
  backend/api/v1/auth_service.go
  backend/api/v1/idp_service.go
  backend/plugin/idp/oauth2/oauth2.go
  backend/plugin/idp/oauth2/oauth2_test.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/oidc/oidc_test.go
  frontend/src/components/IdentityProviderCreateForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/idp.ts
  frontend/src/types/proto/v1/idp_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/idp.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/store/idp.proto
  proto/v1/idp_service.proto
Labels: cla-signed

#5901 fix: should not reset instance_change_history in demo reset
  backend/migrator/demo/reset.sql
  backend/migrator/migrator.go
Labels: cla-signed

#5902 chore: implement IAM condition store
  backend/api/v1/project_service.go
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.0/0002##update_project_member_index.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/store/project_member.go
Labels: cla-signed

#5903 chore: append a suffix to the schema version string
  backend/plugin/db/driver.go
  backend/server/webhook.go
  backend/store/project_member.go
  backend/tests/schema_update_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#5904 chore: remove unused code
  backend/legacyapi/project.go
  backend/legacyapi/project_member.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/project.go
Labels: cla-signed

#5906 chore: mssql connection info
  frontend/src/components/CreateDataSourceExample.vue
Labels: cla-signed

#5907 chore: add simple oracle connection info
  frontend/src/components/CreateDataSourceExample.vue
Labels: cla-signed

#5908 chore: add redshift connection info
  frontend/src/components/CreateDataSourceExample.vue
Labels: cla-signed

#5910 chore: revert PR/5904
  backend/legacyapi/project.go
  backend/legacyapi/project_member.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/project.go
Labels: cla-signed

#5909 feat(frontend): support searching SQL review rule title and description
  frontend/src/components/SQLReview/components/useSQLRuleFilter.ts
Labels: cla-signed

#5912 fix: use sheetId in rollback issue creation
  frontend/src/components/Issue/IssueDetailLayout.vue
  frontend/src/components/Issue/logic/common.ts
  frontend/src/components/Issue/rollback/RollbackStatus.vue
Labels: cla-signed

#5911 feat(mybatis): support gitops sql-review for mybatis
  backend/plugin/parser/mybatis/configuration/parser.go
  backend/plugin/parser/mybatis/configuration/parser_test.go
  backend/plugin/parser/mybatis/mapper/ast/data_node.go
  backend/plugin/parser/mybatis/mapper/ast/dymamic_node.go
  backend/plugin/parser/mybatis/mapper/ast/mapper_node.go
  backend/plugin/parser/mybatis/mapper/ast/node.go
  backend/plugin/parser/mybatis/mapper/ast/query_node.go
  backend/plugin/parser/mybatis/mapper/parser.go
  backend/plugin/parser/mybatis/mapper/parser_test.go
  backend/plugin/parser/mybatis/mapper/test-data/test_dynamic_sql_mapper.yaml
  backend/plugin/parser/mybatis/mapper/test-data/test_simple_mapper.yaml
  backend/server/webhook.go
  backend/server/webhook_test.go
  backend/store/catalog.go
Labels: cla-signed

#5915 feat(frontend): instance ssh form improvement
  frontend/src/components/InstanceForm.vue
  frontend/src/components/InstanceForm/SshConnectionForm.vue
  frontend/src/components/InstanceForm/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5914 chore: add feature guard for index advisor
  frontend/src/bbkit/BBNotification.vue
  frontend/src/components/SlowQuery/Panel/DetailPanel.vue
  frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5916 fix: datasource patch ssh config
  backend/server/database.go
Labels: cla-signed

#5917 chore: support line mapping to point the precise line number in mybatis mapper xml
  backend/plugin/parser/mybatis/mapper/ast/data_node.go
  backend/plugin/parser/mybatis/mapper/ast/node.go
  backend/plugin/parser/mybatis/mapper/ast/query_node.go
  backend/plugin/parser/mybatis/mapper/parser.go
  backend/plugin/parser/mybatis/mapper/parser_test.go
  backend/plugin/parser/mybatis/mapper/test-data/test_dynamic_sql_mapper.yaml
  backend/server/webhook.go
Labels: cla-signed

#5918 chore: pretty format mysql yaml
  backend/tests/test-data/sql_review_mysql.yaml
Labels: cla-signed

#5921 fix: convert sheetId to number
  frontend/src/components/Issue/logic/common.ts
Labels: cla-signed

#5919 chore: update gitlab ci summary message
  backend/server/webhook.go
  backend/server/webhook_test.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#5920 chore(frontend): feature guard to instance SSH connection
  backend/legacyapi/plan.go
  frontend/src/components/InstanceForm.vue
  frontend/src/components/InstanceForm/SshConnectionForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
Labels: cla-signed

#5913 chore: sort by advice level (error first)
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/sql_review.go
  backend/tests/test-data/sql_review_mysql.yaml
  backend/tests/test-data/sql_review_pg.yaml
Labels: cla-signed

#5923 fix(frontend): migration change history shows "<<Unknown database>>" error
  frontend/src/components/AnomalyTable.vue
Labels: cla-signed

#5922 feat(mybatis): only enable mybatis sql review for enterprise plan
  backend/legacyapi/plan.go
  backend/server/webhook.go
Labels: cla-signed

#5924 chore: update version to 2.0.0
  scripts/VERSION
Labels: cla-signed

#5925 chore: introduce PLSQL parser
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
  go.mod
  go.sum
Labels: cla-signed

#5926 fix: avoid infinite for-loop
  backend/server/webhook.go
Labels: cla-signed, backport release/2.0.0

#5927 fix: fix batch update database query when database is empty
  backend/store/database.go
Labels: cla-signed, backport release/2.0.0

#5931 chore: add junyi to backend owner
  CODEOWNERS
Labels: cla-signed

#5929 feat: add exporter and querier roles
  backend/common/role.go
  backend/legacyapi/issue.go
  backend/store/role.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/RoleSelect.vue
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/ConditionGroup.vue
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
  frontend/src/components/Role/Setting/components/RoleTableRow.vue
  frontend/src/components/v2/Select/ProjectRolesSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/project.ts
  frontend/src/utils/role.ts
Labels: cla-signed

#5932 fix: fix get mysql pringerprint for comments
  backend/plugin/parser/sql/utils.go
  backend/plugin/parser/sql/utils_test.go
Labels: cla-signed, backport release/2.0.0

#5933 chore: add secret description
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5937 chore: mybatis sql review match name case insensitive
  backend/server/webhook.go
Labels: cla-signed, backport release/2.0.0

#5939 chore: fix sheet backfill DML
  backend/migrator/migration/prod/2.0/0001##migrate_task_payload_statement_to_sheet.sql
Labels: cla-signed

#5936 chore(frontend): allow project owners to rollout tasks
  backend/runner/taskrun/scheduler.go
  backend/server/stage.go
  backend/server/task.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
  backend/tests/ghost_test.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
  frontend/src/components/Issue/logic/transition.ts
Labels: cla-signed, backport release/1.17.0, backport release/2.0.0

#5945 fix: route params format transform for task statements
  frontend/src/components/Issue/logic/common.ts
Labels: cla-signed

#5944 chore: delete deprecated code
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/server/server.go
Labels: cla-signed

#5943 feat: support grant request issue
  backend/api/v1/review_service.go
  backend/legacyapi/issue.go
  backend/legacyapi/sql.go
  backend/runner/approval/runner.go
  backend/server/issue.go
  backend/store/risk.go
  frontend/src/types/proto/store/issue.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/issue.pb.go
  proto/store/issue.proto
Labels: cla-signed

#5946 fix(frontend): should not show schemaless database list for change data scenario
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
Labels: cla-signed

#5950 fix: update sheet payload with issue information
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/components/Issue/logic/GhostModeProvider.ts
  frontend/src/components/Issue/logic/TenantModeProvider.ts
  frontend/src/components/Issue/logic/common.ts
  frontend/src/utils/sheet.ts
  frontend/src/views/SheetDashboard.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/IssueLink.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/SheetTable.vue
Labels: cla-signed

#5949 chore: support project UID in the name
  backend/api/v1/common.go
  backend/api/v1/project_service.go
Labels: cla-signed

#5948 feat: implement Oracle require PK rule
  .golangci.yaml
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/db/db.go
  backend/plugin/advisor/oracle/advisor_table_require_pk.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/parser.go
  backend/plugin/advisor/oracle/test/table_require_pk.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
Labels: cla-signed

#5954 fix(frontend): editor height on issue detail page
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#5956 feat(frontend): put diff and generated DDL in separate tabs
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SyncDatabaseSchema/DiffViewPanel.vue
  frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
Labels: cla-signed

#5955 chore(frontend): use single selector for environment condition when configuring deployment pipeline
  frontend/src/components/DeploymentConfigTool/LabelSelect.vue
  frontend/src/components/DeploymentConfigTool/SelectorItem.vue
Labels: cla-signed

#5952 feat: implement Oracle table no FK rule and add oracle advisor template
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/generator/main.go
  backend/plugin/advisor/generator/oracle.template
  backend/plugin/advisor/oracle/advisor_table_no_foreign_key.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/table_no_foreign_key.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#5957 chore: drop issue pipeline_id not null
  backend/migrator/migration/dev/20230509000000##drop_issue_pipeline_id_not_null.sql
  backend/migrator/migration/dev/LATEST.sql
Labels: cla-signed

#5958 feat: implement Oracle table naming convention
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_naming_table.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/parser.go
  backend/plugin/advisor/oracle/test/naming_table.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#5953 feat(frontend): batch transfer out databases from project
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/TransferOutDatabaseForm/Label.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/TransferOutDatabaseForm/common.ts
  frontend/src/components/TransferOutDatabaseForm/index.ts
  frontend/src/components/v2/Model/InstanceName.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/types/common.ts
Labels: cla-signed

#5964 fix(frontend): auto resize for sql chat mode
  frontend/src/plugins/ai/components/ChatView/CodeView.vue
Labels: cla-signed

#5962 refactor(frontend): shipping to project v1 API (part.1)
  frontend/src/components/ProjectListSidePanel.vue
  frontend/src/components/ProjectTable.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/components/v2/Model/index.ts
  frontend/src/store/modules/auth.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/index.ts
  frontend/src/types/v1/index.ts
  frontend/src/types/v1/project.ts
  frontend/src/utils/index.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/project.ts
  frontend/src/utils/v1/slug.ts
  frontend/src/views/Archive.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/SettingWorkspaceProject.vue
Labels: cla-signed

#5963 chore: make pipeline uid optional in the backend
  backend/legacyapi/issue.go
  backend/runner/approval/runner.go
  backend/runner/apprun/runner.go
  backend/runner/taskrun/scheduler.go
  backend/server/issue.go
  backend/server/task.go
  backend/store/issue.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#5966 chore: update pricing contract part
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
Labels: cla-signed

#5967 chore: refactor ssh
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/util/ssh.go
Labels: cla-signed

#5968 refactor: pg driver
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#5972 chore(frontend): add a dot to updated columns in schema diagram
  frontend/src/components/SchemaDiagram/ER/TableNode.vue
Labels: cla-signed

#5970 refactor(frontend): use v1 API in project settings
  frontend/src/components/Breadcrumb.vue
  frontend/src/components/Project/ProjectSetting/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/ProjectMemberPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/router/index.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#5969 refactor(frontend): create project via v1 API
  frontend/src/components/ProjectCreate.vue
  frontend/src/store/modules/project.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/types/project.ts
  frontend/src/types/v1/project.ts
Labels: cla-signed

#5973 fix: list policy by wildcard -
  backend/api/v1/org_policy_service.go
Labels: cla-signed

#5974 refactor(frontend): ship to project V1 API (part.4)
  frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
  frontend/src/components/Project/ProjectSetting/ProjectGeneralSettingPanel.vue
  frontend/src/components/ProjectActivityPanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/components/ProjectMigrationHistoryPanel.vue
  frontend/src/components/ProjectOverviewPanel.vue
  frontend/src/store/modules/v1/project.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#5975 fix: list issues with nil pipeline
  backend/server/issue.go
Labels: cla-signed

#5978 chore: grant privileges when the grant request issue is approved
  backend/api/v1/review_service.go
Labels: cla-signed

#5979 fix(frontend): auto adjust editor height later
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#5977 refactor(frontend): ship to project v1 API (part.5)
  backend/api/v1/project_service.go
  frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
  frontend/src/components/DeploymentConfigTool/DeploymentConfigTool.vue
  frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
  frontend/src/components/DeploymentConfigTool/DeploymentStage.vue
  frontend/src/components/DeploymentConfigTool/LabelSelect.vue
  frontend/src/components/DeploymentConfigTool/SelectorItem.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue
  frontend/src/store/modules/deployment.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/v1/deploymentConfig.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/types/common.ts
  frontend/src/types/deployment.ts
  frontend/src/types/id.ts
  frontend/src/types/index.ts
  frontend/src/types/store.ts
  frontend/src/utils/deployment.ts
  frontend/src/utils/label.ts
  frontend/src/utils/v1/deploymentConfig.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/label.ts
Labels: cla-signed

#5976 feat: implement Oracle required column rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_column_require.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/parser.go
  backend/plugin/advisor/oracle/test/column_required.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#5982 fix(sql-editor): filter bugs
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
Labels: cla-signed

#5983 feat: implement Oracle column disallow list rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_column_type_disallow_list.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/column_type_disallow_list.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/parser/sql/plsql.go
Labels: cla-signed

#5980 chore: dml for backfilling querier and exporter
  backend/migrator/migration/dev/20230510000000##backfill_project_role.sql
Labels: cla-signed

#5981 feat: implement create grant request querier issue(part1)
  frontend/src/components/DatabasesSelectPanel.vue
  frontend/src/components/Issue/GrantRequestForm.vue
  frontend/src/components/Issue/GrantRequestIssueSidebar.vue
  frontend/src/components/Issue/IssueHighlightPanel.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/layout/GrantRequestDetail.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/components/Issue/logic/grantRequest.ts
  frontend/src/components/Issue/logic/index.ts
  frontend/src/components/Issue/review/CurrentApprover.vue
  frontend/src/components/Issue/table/IssueTable.vue
  frontend/src/components/Issue/table/WaitingForMyApprovalIssueTable.vue
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/Project/ProjectSetting/common.ts
  frontend/src/components/ProjectMemberPanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/logic/initialize/grantRequest.ts
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/activity.ts
  frontend/src/store/modules/issue.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/common.ts
  frontend/src/types/issue.ts
  frontend/src/types/principal.ts
  frontend/src/utils/issue/expr.ts
  frontend/src/utils/issue/index.ts
  frontend/src/utils/project.ts
  frontend/src/views/Home.vue
  frontend/src/views/IssueDashboard.vue
Labels: cla-signed

#5985 chore: don't convert uppercase to lowercase in github action ci yaml
  backend/plugin/vcs/github/bytebase-sql-review.yml
Labels: cla-signed, backport release/2.0.0

#5987 refactor: query refactoring
  backend/server/sql.go
Labels: cla-signed

#5989 chore(frontend): legacy project API compatibility
  frontend/src/components/ProvideDashboardContext.vue
Labels: cla-signed

#5990 chore: set BBCheckbox default value to false
  frontend/src/bbkit/BBCheckbox.vue
Labels: cla-signed

#5992 chore(frontend): make the radio buttons disabled when not allowed to edit
  frontend/src/components/Project/ProjectSetting/ProjectGeneralSettingPanel.vue
Labels: cla-signed

#5993 chore(frontend): adjust horizontal scrollable range for deployment matrix
  frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
Labels: cla-signed

#5996 chore: use exportFormat flag
  backend/legacyapi/sql.go
  frontend/src/types/sql.ts
Labels: cla-signed

#5994 chore: add cel query attributes evaluator
  backend/server/sql.go
  backend/server/sql_test.go
Labels: cla-signed

#5988 feat: implement grant request exporter issue
  frontend/src/components/Issue/GrantRequestIssueSidebar.vue
  frontend/src/components/Issue/IssueBanner.vue
  frontend/src/components/Issue/IssueSidebar.vue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/components/Issue/logic/transition.ts
  frontend/src/components/QuickActionPanel.vue
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/database.ts
  frontend/src/types/issue.ts
Labels: cla-signed

#5995 feat: implement Oracle maximum char length rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_column_maximum_character_length.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/column_maximum_character_length.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#5999 fix: fail open for connect to local ssh agent
  backend/plugin/db/util/ssh.go
Labels: cla-signed, backport release/2.0.0

#6001 cherrypick(5999): fix: fail open for connect to local ssh agent
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#5997 chore: update policy v1 api
  backend/api/v1/environment_service.go
  backend/api/v1/org_policy_service.go
  backend/legacyapi/policy.go
  backend/server/policy.go
  backend/store/policy.go
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#5998 chore: migrate sql review to policy v1 api
  frontend/src/components/Environment/ProductionEnvironmentIcon.vue
  frontend/src/components/EnvironmentForm.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/SQLReviewInfo.vue
  frontend/src/components/SQLReview/SQLReviewPolicyTable.vue
  frontend/src/components/SQLReview/components/SQLReviewTemplateSelector.vue
  frontend/src/components/SQLReview/components/utils.ts
  frontend/src/grpcweb/index.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/sqlReview.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/environment.ts
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/sqlReview.ts
  frontend/src/utils/environment.ts
  frontend/src/utils/slug.ts
  frontend/src/views/SettingWorkspaceSQLReviewCreate.vue
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#6000 chore: evaluate project IAM policy in query
  backend/server/sql.go
Labels: cla-signed

#6003 fix(frontend): user id in [GET] /api/issue
  frontend/src/store/modules/v1/project.ts
  frontend/src/utils/pipeline.ts
  frontend/src/views/Home.vue
  frontend/src/views/IssueDashboard.vue
Labels: cla-signed

#6004 fix: compose project webhook in v1 api
  backend/api/v1/project_service.go
Labels: cla-signed

#6007 feat: implement Oracle require WHERE rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_where_require.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/statement_where_require.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#6005 chore: remove exporter binding on export()
  backend/server/sql.go
Labels: cla-signed

#6008 chore: migrate slow query policy to gRPC
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
  frontend/src/store/modules/slowQueryPolicy.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/policy.ts
  frontend/src/utils/slowQuery.ts
Labels: cla-signed

#6009 feat: implement Oracle INSERT must specify column rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_insert_must_specify_column.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/statement_insert_must_specify_column.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#6010 feat: implement export button in grant exporter issue
  frontend/src/bbkit/BBSpin.vue
  frontend/src/components/Issue/IssueBanner.vue
  frontend/src/components/Issue/IssueHighlightPanel.vue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/action/ExportDataButton.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/router/index.ts
Labels: cla-signed

#6011 chore: trim role prefix
  backend/api/v1/review_service.go
  backend/legacyapi/member.go
Labels: cla-signed

#6013 fix: grant request context default value
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
Labels: cla-signed

#6014 chore: initial project and database list in global
  frontend/src/main.ts
  frontend/src/store/modules/project.ts
Labels: cla-signed

#6012 chore: allow everyone to list all projects and databases
  backend/api/v1/project_service.go
  backend/server/acl.go
  backend/server/acl_database_test.go
  backend/server/acl_project_test.go
  backend/server/database.go
  backend/server/project.go
Labels: cla-signed

#6017 chore: hide db changes buttons
  frontend/src/components/Issue/action/ExportDataButton.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/views/DatabaseDetail.vue
Labels: cla-signed

#6018 feat: check query action permission
  frontend/src/components/Issue/action/ExportDataButton.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/store/modules/sqlEditor.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
Labels: cla-signed

#6016 chore: several fix
  backend/runner/taskrun/scheduler.go
  backend/server/acl.go
  backend/server/acl_issue_test.go
  backend/server/sql.go
Labels: cla-signed

#6023 chore: update check allow create issue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
Labels: cla-signed

#6022 chore: migrate sensitive data policy to gRPC
  frontend/src/components/ColumnTable.vue
  frontend/src/store/modules/policy.ts
  frontend/src/store/modules/slowQueryPolicy.ts
  frontend/src/store/modules/sqlReview.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/policy.ts
  frontend/src/types/schemaEditor/index.ts
  frontend/src/views/SettingWorkspaceSensitiveData.vue
  frontend/src/views/TableDetail.vue
Labels: cla-signed

#6024 chore: use github runner except backend tests
  .github/workflows/backend-tests-default.yml
  .github/workflows/backend-tests.yml
  .github/workflows/build-push-ci-image.yml
  .github/workflows/frontend-tests-default.yml
  .github/workflows/frontend-tests.yml
Labels: cla-signed

#6025 chore: update i18n for grant request issue
  frontend/src/components/DatabasesSelectPanel.vue
  frontend/src/components/Issue/action/ExportDataButton.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/RequiredStar.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/logic/initialize/grantRequest.ts
Labels: cla-signed

#6026 fix(bbc): correctly handle `next` field in pagination
  backend/plugin/vcs/bitbucket/bitbucket.go
Labels: cla-signed

#6027 chore: fix issue routes
  backend/server/acl.go
  backend/server/acl_issue_test.go
Labels: cla-signed

#6029 chore: update issue description title
  frontend/src/components/Issue/IssueDescriptionPanel.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6028 feat: implement Oracle index key number limit rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_index_key_number_limit.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/index_key_number_limit.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#6030 chore: add all mode to database select
  frontend/src/components/DatabaseSelect.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
Labels: cla-signed

#6031 chore: remove unused error notification
  frontend/src/components/Issue/action/ExportDataButton.vue
Labels: cla-signed

#6032 feat: introduce webhook id
  backend/api/v1/common.go
  backend/api/v1/project_service.go
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/v1/project_service.proto
Labels: cla-signed

#6037 chore: remove dev guard for grant request
  frontend/src/components/QuickActionPanel.vue
  frontend/src/views/IssueDetail.vue
Labels: cla-signed

#6036 chore: migrate access control policy to gRPC
  backend/api/v1/org_policy_service.go
  frontend/src/components/AccessControl/AddRuleForm.vue
  frontend/src/components/DatabaseTable.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/store/modules/connectionTree.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/policy.ts
  frontend/src/utils/policy.ts
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/SettingWorkspaceAccessControl.vue
  frontend/src/views/TableDetail.vue
Labels: cla-signed

#6035 chore: allow add "EXPORTER"/"QUERIER" roles in non-enterprise plan
  frontend/src/components/Project/ProjectSetting/ProjectMemberTable/PrincipalTable.vue
  frontend/src/components/v2/Select/ProjectRolesSelect.vue
Labels: cla-signed

#6034 feat: implement Oracle column no null rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_column_no_null.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/column_no_null.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#6033 fix(sql-editor): restrict instance/database connection scope to provide different suggestion items
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
  frontend/src/plugins/sql-lsp/server/complete/index.ts
  frontend/src/plugins/sql-lsp/server/server.ts
  frontend/src/plugins/sql-lsp/types/index.ts
  frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
  frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
Labels: cla-signed

#6038 feat: implement Oracle column require default rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/oracle/advisor_column_no_null.go
  backend/plugin/advisor/oracle/advisor_column_require_default.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/column_require_default.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#6044 chore: update project data prepare
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/components/ProjectListSidePanel.vue
  frontend/src/components/ProjectSelect.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/project.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/views/Archive.vue
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/ProjectDashboard.vue
Labels: cla-signed

#6041 refactor(frontend): use project v1 when creating databases
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/CreateDatabasePrepForm/DatabaseLabelForm.vue
  frontend/src/components/CreateDatabasePrepForm/DatabaseNameTemplateTips.vue
  frontend/src/components/CreateDatabasePrepForm/logic.ts
Labels: cla-signed

#6040 refactor(frontend): ship project webhook to v1 API
  frontend/src/components/ProjectWebhookCard.vue
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/components/ProjectWebhookPanel.vue
  frontend/src/router/index.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/projectWebhook.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/store/modules/v1/projectWebhook.ts
  frontend/src/types/common.ts
  frontend/src/types/index.ts
  frontend/src/types/mfa.ts
  frontend/src/types/projectWebhook.ts
  frontend/src/types/store.ts
  frontend/src/types/v1/index.ts
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/utils/slug.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/project.ts
  frontend/src/utils/v1/projectWebhook.ts
  frontend/src/utils/v1/slug.ts
  frontend/src/views/ProjectDetail.vue
  frontend/src/views/ProjectWebhookCreate.vue
  frontend/src/views/ProjectWebhookDetail.vue
Labels: cla-signed

#6039 chore: environment is no longer a parent of instance in v1 API
  backend/api/v1/acl.go
  backend/api/v1/anomaly_service.go
  backend/api/v1/common.go
  backend/api/v1/common_test.go
  backend/api/v1/database_service.go
  backend/api/v1/instance_role_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/org_policy_service.go
  backend/server/instance.go
  backend/server/server.go
  backend/store/instance.go
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/components/SlowQuery/Panel/types.ts
  frontend/src/store/modules/slowQuery.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/v1/anomaly_service.proto
  proto/v1/database_service.proto
  proto/v1/instance_role_service.proto
  proto/v1/instance_service.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#6045 fix: accessible database list in sql editor
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/utils/policy.ts
Labels: cla-signed

#6048 chore: update exporter project selector fields
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
Labels: cla-signed

#6046 feat: implement Oracle max varchar length rule
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/oracle/advisor_column_maximum_varchar_length.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/column_maximum_varchar_length.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
Labels: cla-signed
