Repository bytebase/bytebase, pull requests merged in 2023-06, with the labels that each got.

#6376 chore: migrate test to sheet v1
  backend/server/instance.go
  backend/server/project.go
  backend/server/server.go
  backend/server/sheet.go
  backend/store/sheet.go
  backend/tests/external_approval_test.go
  backend/tests/ghost_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sheet.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#6382 feat(proto): vcs pushEvent
  frontend/src/types/proto/store/vcs.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/vcs.pb.go
  proto/store/vcs.proto
Labels: cla-signed

#6381 chore: migrate repo to v1
  backend/api/v1/project_service.go
  frontend/src/components/ProjectVersionControlPanel.vue
  frontend/src/components/RepositoryConfigPanel.vue
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/RepositoryPanel.vue
  frontend/src/components/RepositorySelectionPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/store/modules/oauth.ts
  frontend/src/store/modules/repository.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/repository.ts
  frontend/src/store/modules/vcs.ts
  frontend/src/types/project.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/repository.ts
  frontend/src/types/store.ts
  frontend/src/utils/slug.ts
  frontend/src/views/ProjectDetail.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/externalvs_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/v1/externalvs_service.proto
  proto/v1/project_service.proto
Labels: cla-signed

#6385 chore(frontend): upgrade @popperjs/core to 2.11.8
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#6386 feat: implement database/schema group selector in alter schema form
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/SelectSchemaGroupsTable.vue
  frontend/src/store/modules/dbGroup.ts
  frontend/src/utils/databaseGroup/issue.ts
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/SchemaGroupDetail.vue
Labels: cla-signed

#6388 chore: add tooltip to all database in querier request issue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6390 chore: migrate the repository store to v1
  backend/api/v1/common.go
  backend/api/v1/externalvs_service.go
  frontend/src/components/RepositoryTable.vue
  frontend/src/components/SQLReview/SQLReviewInfo.vue
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/repository.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/repository.ts
  frontend/src/types/common.ts
  frontend/src/types/repository.ts
  frontend/src/types/v1/index.ts
  frontend/src/types/v1/repository.ts
  frontend/src/utils/environment.ts
  frontend/src/views/SettingWorkspaceVCSDetail.vue
  proto/v1/externalvs_service.proto
Labels: cla-signed

#6387 fix: fix query panic
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#6389 chore(frontend): better auto height for sql editor
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#6392 feat(frontend): update quick action list according to roles and subscription plan
  frontend/src/components/QuickActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/types/common.ts
  frontend/src/types/index.ts
  frontend/src/types/quickAction.ts
Labels: cla-signed

#6395 feat: migrate instance change history to protobuf and return push event in v1 api
  backend/api/v1/database_service.go
  backend/migrator/migrator.go
  backend/plugin/db/driver.go
  backend/runner/taskrun/executor.go
  backend/store/instance_change_history.go
  backend/utils/utils.go
Labels: cla-signed

#6396 chore: update requesting for matched database/table list
  frontend/src/bbkit/BBLoader.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupSelect.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/SchemaGroupDetail.vue
Labels: cla-signed

#6398 fix: fix three bugs in Query API
  backend/api/v1/sql_service.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/parser/sql/plsql.go
Labels: cla-signed

#6397 chore: add sharding feature type
  backend/legacyapi/plan.go
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/FeatureBadge.vue
  frontend/src/locales/en-US.json
  frontend/src/types/plan.ts
Labels: cla-signed

#6374 refactor(frontend): change history v1 API
  frontend/src/components/BackupTable.vue
  frontend/src/components/Breadcrumb.vue
  frontend/src/components/ChangeHistory/ChangeHistoryStatusIcon.vue
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/components/ChangeHistory/index.ts
  frontend/src/components/DatabaseChangeHistoryPanel.vue
  frontend/src/components/DatabaseDetail/ChangeHistoryBrief.vue
  frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
  frontend/src/components/DatabaseSelect.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/Issue/IssueSidebar.vue
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/components/Issue/TaskRunTable.vue
  frontend/src/components/MigrationHistoryStatusIcon.vue
  frontend/src/components/MigrationHistoryTable.vue
  frontend/src/components/ProjectChangeHistoryPanel.vue
  frontend/src/components/ProjectMigrationHistoryPanel.vue
  frontend/src/components/RequestDatabasePrepForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSingleDatabase.vue
  frontend/src/main.ts
  frontend/src/plugins/issue/logic/initialize/index.ts
  frontend/src/plugins/pitr/index.ts
  frontend/src/router/index.ts
  frontend/src/shims-vue-globals.d.ts
  frontend/src/store/modules/database.ts
  frontend/src/store/modules/instance.ts
  frontend/src/store/modules/issue.ts
  frontend/src/store/modules/router.ts
  frontend/src/store/modules/sql.ts
  frontend/src/store/modules/v1/changeHistory.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/types/common.ts
  frontend/src/types/utils.ts
  frontend/src/utils/slug.ts
  frontend/src/utils/task.ts
  frontend/src/utils/util.ts
  frontend/src/utils/v1/changeHistory.ts
  frontend/src/utils/v1/database.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/review.ts
  frontend/src/views/ChangeHistoryDetail.vue
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/ProjectDetail.vue
  frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/views/SyncDatabaseSchema/index.vue
Labels: cla-signed

#6401 chore: update pnpm version
  .github/workflows/build-artifacts-and-draft-release.yml
  .github/workflows/frontend-tests.yml
  frontend/pnpm-lock.yaml
Labels: cla-signed

#6402 chore: fix the name format
  backend/api/v1/common.go
Labels: cla-signed

#6404 chore: add i18n for database group
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#6403 chore: migrate vcs to v1
  backend/api/v1/externalvs_service.go
  frontend/src/components/ProjectVersionControlPanel.vue
  frontend/src/components/RepositoryConfigPanel.vue
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/RepositoryPanel.vue
  frontend/src/components/RepositorySelectionPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/components/RepositoryVCSProviderPanel.vue
  frontend/src/components/VCSCard.vue
  frontend/src/components/VCSProviderBasicInfoPanel.vue
  frontend/src/components/VCSProviderOAuthPanel.vue
  frontend/src/components/VCSSetupWizard.vue
  frontend/src/router/index.ts
  frontend/src/store/modules/gitlab.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/oauth.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/repository.ts
  frontend/src/store/modules/v1/vcs.ts
  frontend/src/store/modules/vcs.ts
  frontend/src/types/oauth.ts
  frontend/src/types/project.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/store.ts
  frontend/src/types/vcs.ts
  frontend/src/utils/slug.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/vcs.ts
  frontend/src/views/SettingWorkspaceVCS.vue
  frontend/src/views/SettingWorkspaceVCSDetail.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/externalvs_service.pb.go
  proto/v1/externalvs_service.proto
Labels: cla-signed

#6406 fix: migrate vcs type in payload
  backend/migrator/migration/prod/2.2/0004##update_vcs_type_in_payload.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#6407 refactor(frontend): migrate database backup to v1
  backend/api/v1/database_service.go
  frontend/src/components/BackupTable.vue
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseBackup/BackupTable.vue
  frontend/src/components/DatabaseBackup/DatabaseBackupSettingForm.vue
  frontend/src/components/DatabaseBackup/index.ts
  frontend/src/components/DatabaseBackupPanel.vue
  frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
  frontend/src/components/misc/HumanizeDate.vue
  frontend/src/plugins/pitr/index.ts
  frontend/src/store/modules/backup.ts
  frontend/src/store/modules/v1/backup.ts
  frontend/src/store/modules/v1/dataSource.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/utils/v1/backup.ts
  frontend/src/utils/v1/changeHistory.ts
  frontend/src/utils/v1/database.ts
  frontend/src/utils/v1/index.ts
  frontend/src/views/EnvironmentDetail.vue
Labels: cla-signed

#6409 fix: compose environment of instance
  frontend/src/store/modules/v1/instance.ts
Labels: cla-signed

#6408 refactor(frontend): migrate query readonly API to v1
  frontend/src/components/Issue/action/ExportDataButton.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/sql.ts
  frontend/src/store/modules/sqlEditor.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/tab.ts
  frontend/src/types/v1/index.ts
  frontend/src/types/v1/sql.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/sql.ts
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/index.ts
  frontend/src/views/sql-editor/EditorCommon/index.ts
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
  frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
  frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#6399 feat: support create issue using table group
  backend/server/issue.go
Labels: cla-signed

#6410 fix: v1 task status
  backend/api/v1/rollout_service.go
Labels: cla-signed

#6411 feat: add feature guard of sharding in backend
  backend/api/v1/project_service.go
  backend/server/issue.go
  backend/server/server.go
Labels: cla-signed

#6412 perf: add cache of database group
  backend/store/database_group.go
  backend/store/store.go
Labels: cla-signed

#6414 fix: add name in create plan rollout
  backend/api/v1/rollout_service.go
Labels: cla-signed

#6417 fix: update vcs type sql
  backend/migrator/migration/prod/2.2/0004##update_vcs_type_in_payload.sql
Labels: cla-signed

#6418 chore: update error handler for database group requests
  backend/api/v1/project_service.go
  backend/legacyapi/plan.go
  backend/server/issue.go
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/logic/assignee.ts
  frontend/src/components/v2/Form/ResourceIdInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/dbGroup.ts
  frontend/src/types/dbGroup.ts
  frontend/src/types/plan.ts
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/EnvironmentDashboard.vue
Labels: cla-signed

#6419 refactor(frontend): clean up legacy project use cases
  frontend/src/components/OnboardingGuide.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/router/index.ts
  frontend/src/store/modules/project.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#6420 chore: add parsed expr to iampolicy binding
  backend/api/v1/cel_service.go
  backend/api/v1/project_service.go
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#6405 feat: add AdminExecute API proto
  backend/api/v1/sql_service.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/parser/sql/parser.go
  backend/plugin/parser/sql/utils.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#6421 fix: click view all closed on my issue page should navigate to the issue page for current user
  frontend/src/views/Home.vue
Labels: cla-signed

#6422 chore: delete deprecated code
  backend/server/database.go
  backend/server/instance.go
  backend/server/project.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
  backend/tests/project.go
  backend/tests/schema_update_test.go
  backend/tests/start_test.go
  backend/tests/tests.go
Labels: cla-signed

#6423 chore: rename list backups
  backend/api/v1/database_service.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
  frontend/src/store/modules/v1/backup.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#6424 chore: deprecate legacy migration history
  backend/legacyapi/data_source.go
  backend/legacyapi/database.go
  backend/legacyapi/instance.go
  backend/legacyapi/label_test.go
  backend/legacyapi/member.go
  backend/legacyapi/policy.go
  backend/server/acl.go
  backend/server/acl_database_test.go
  backend/server/acl_test_helper.go
  backend/server/instance.go
  backend/server/server.go
  backend/store/database.go
  backend/store/environment.go
  backend/tests/instance.go
  backend/tests/schema_update_test.go
  backend/tests/sync_schema_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#6425 chore: update project GitOps API
  backend/api/v1/common.go
  backend/api/v1/project_service.go
  backend/tests/schema_update_test.go
  frontend/src/store/modules/v1/repository.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#6426 chore: sync instance on creation
  backend/api/v1/instance_service.go
  backend/component/state/state.go
  backend/runner/schemasync/syncer.go
  backend/server/server.go
  backend/server/sql.go
Labels: cla-signed

#6427 chore: clear project policy cache
  backend/store/principal.go
Labels: cla-signed

#6428 chore: migrate vcs to v1
  .golangci.yaml
  backend/api/v1/project_service.go
  backend/server/project.go
  backend/server/server.go
  backend/server/vcs.go
  backend/store/repository.go
  backend/tests/schema_update_test.go
  backend/tests/sheet_vcs_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
  backend/tests/vcs.go
Labels: cla-signed

#6429 chore: deprecate legacy deployment config API
  backend/server/project.go
  backend/tests/ghost_test.go
  backend/tests/project.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
Labels: cla-signed

#6430 chore: migrate query to v1
  backend/plugin/db/sqlite/sqlite.go
  backend/tests/ghost_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql.go
  backend/tests/sql_review_test.go
  backend/tests/tenant_test.go
  backend/tests/test-data/book_3_schema.result
  backend/tests/test-data/book_schema.result
  backend/tests/test-data/ghost_test_schema1.result
  backend/tests/test-data/ghost_test_schema2.result
  backend/tests/tests.go
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#6431 chore: handle tidb sequences
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed, backport release/2.1.0

#6433 chore: change risk expression to unparsed struct
  backend/api/v1/risk_service.go
  backend/common/convert.go
  backend/runner/approval/runner.go
  backend/server/server.go
  backend/store/risk.go
Labels: cla-signed

#6434 chore: dual write condition API
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/risk_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/risk_service.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#6435 chore: backfill approval setting
  backend/api/v1/setting_service.go
  backend/common/convert.go
  backend/runner/approval/runner.go
  backend/server/server.go
  backend/store/setting.go
Labels: cla-signed

#6436 docs: update doc link
  backend/migrator/migration/prod/1.0/0001##initial_data.sql
  frontend/public/help/en/help.environment.md
  frontend/public/help/en/help.instance.md
  frontend/public/help/en/help.issue.detail.md
  frontend/public/help/en/help.member.md
  frontend/public/help/en/help.project.md
  frontend/public/help/zh/help.environment.md
  frontend/public/help/zh/help.instance.md
  frontend/public/help/zh/help.issue.detail.md
  frontend/public/help/zh/help.member.md
  frontend/public/help/zh/help.project.md
Labels: cla-signed

#6437 chore: update batch change link
  README.md
  docs/design/source-code-tour.snb.md
  frontend/src/components/ProjectDeploymentConfigPanel.vue
Labels: cla-signed

#6438 docs: update SDL doc
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/components/RepositoryForm.vue
Labels: cla-signed

#6439 chore: update database-access-control link
  README.md
  frontend/src/components/AccessControl/AddRuleForm.vue
  frontend/src/views/SettingWorkspaceAccessControl.vue
Labels: cla-signed

#6440 feat: implement table-level query permission check for MySQL and Oracle
  backend/api/v1/sql_service.go
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
  backend/plugin/parser/sql/utils.go
  backend/store/db_schema.go
Labels: cla-signed

#6441 chore: update secret doc link
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
Labels: cla-signed

#6442 docs: update readme with change-query-secure-govern
  README.md
  docs/assets/change-query-secure-govern.webp
Labels: cla-signed

#6443 fix(vcs): unable to load list of external repositories when enable GitOps
  frontend/src/components/RepositorySelectionPanel.vue
  frontend/src/store/modules/gitlab.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/v1/vcs.ts
Labels: cla-signed

#6445 chore: update check database accessible
  frontend/src/components/DatabaseTable.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/SelectDatabaseResourceForm/common.ts
  frontend/src/components/Issue/form/SelectDatabaseResourceForm/index.vue
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/utils/policy.ts
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#6447 fix: filter databases in default project
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
Labels: cla-signed

#6446 fix(frontend): clean up temp edit statement state when they are no more valid
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/main.ts
  frontend/src/store/modules/v1/sheet.ts
Labels: cla-signed

#6448 fix: invalid database name
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/components/Issue/logic/base.ts
Labels: cla-signed

#6450 chore: update edit button style
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#6449 docs: update webhook doc link
  README.md
  frontend/src/components/DatabaseBackupPanel.vue
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/views/SettingWorkspaceIMIntegration.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#6451 feat: implement Postgres table-level query permission check
  backend/api/v1/sql_service.go
  backend/plugin/parser/sql/utils.go
  backend/plugin/parser/sql/utils_test.go
Labels: cla-signed

#6452 chore: update check if has schema property
  frontend/src/components/Issue/form/SelectDatabaseResourceForm/common.ts
  frontend/src/utils/database.ts
Labels: cla-signed

#6453 chore: update version to 2.2.0
  scripts/VERSION
Labels: cla-signed

#6454 chore: upgrade plsql parser and ANTLR4 golang runtime
  backend/plugin/advisor/generator/oracle.template
  backend/plugin/advisor/oracle/advisor_column_add_not_null_column_require_default.go
  backend/plugin/advisor/oracle/advisor_column_maximum_character_length.go
  backend/plugin/advisor/oracle/advisor_column_maximum_varchar_length.go
  backend/plugin/advisor/oracle/advisor_column_no_null.go
  backend/plugin/advisor/oracle/advisor_column_require.go
  backend/plugin/advisor/oracle/advisor_column_require_default.go
  backend/plugin/advisor/oracle/advisor_column_type_disallow_list.go
  backend/plugin/advisor/oracle/advisor_index_key_number_limit.go
  backend/plugin/advisor/oracle/advisor_insert_must_specify_column.go
  backend/plugin/advisor/oracle/advisor_naming_identifier_case.go
  backend/plugin/advisor/oracle/advisor_naming_identifier_no_keyword.go
  backend/plugin/advisor/oracle/advisor_naming_table.go
  backend/plugin/advisor/oracle/advisor_naming_table_no_keyword.go
  backend/plugin/advisor/oracle/advisor_select_no_select_all.go
  backend/plugin/advisor/oracle/advisor_syntax_test.go
  backend/plugin/advisor/oracle/advisor_table_no_foreign_key.go
  backend/plugin/advisor/oracle/advisor_table_require_pk.go
  backend/plugin/advisor/oracle/advisor_where_no_leading_wildcard_like.go
  backend/plugin/advisor/oracle/advisor_where_require.go
  backend/plugin/advisor/oracle/parser.go
  backend/plugin/parser/sql/plsql.go
  go.mod
  go.sum
Labels: cla-signed

#6456 feat(schema): add phone to principal table
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.3/0000##add_phone_to_principal.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#6458 feat(proto): add phone to user
  frontend/src/types/proto/v1/auth_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#6459 chore: add expired time field to exporter form
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/form/GrantRequestQuerierForm.vue
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
Labels: cla-signed

#6460 fix: typo
  frontend/src/types/proto/v1/auth_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#6466 chore: tweak database group wording and add pricing
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed

#6464 feat: principal.phone create & update
  backend/api/v1/auth_service.go
  backend/store/principal.go
  go.mod
  go.sum
Labels: cla-signed

#6467 feat: creator column should be the last in the issue list
  frontend/src/components/Issue/table/IssueTable.vue
Labels: cla-signed

#6468 cherrypick: creator column should be the last in the issue list (#6467)
  frontend/src/components/Issue/table/IssueTable.vue
Labels: cla-signed

#6471 chore: migrate admin execute API in tests
  backend/api/auth/auth.go
  backend/api/v1/acl.go
  backend/api/v1/debug.go
  backend/plugin/db/util/driverutil.go
  backend/server/server.go
  backend/tests/backup_restore_test.go
  backend/tests/data_source_test.go
  backend/tests/database_edit_test.go
  backend/tests/environment.go
  backend/tests/external_approval_test.go
  backend/tests/ghost_test.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#6463 chore: allow backend engineer dev with hot reloading easily
  frontend/package.json
Labels: cla-signed

#6462 fix: regenerate schema version of task created in UI
  backend/runner/taskrun/scheduler.go
Labels: cla-signed

#6473 chore: fix PLSQL parser
  backend/plugin/advisor/oracle/advisor_syntax_test.go
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
Labels: cla-signed, backport release/2.2.0

#6475 fix: avoid trigger multiple actions
  backend/store/repository.go
  frontend/src/components/ProjectVersionControlPanel.vue
  frontend/src/components/RepositoryPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/store/modules/v1/repository.ts
  frontend/src/store/modules/v1/vcs.ts
Labels: cla-signed, backport release/2.2.0

#6477 cherrypick: fix: avoid trigger multiple actions #6475
  backend/store/repository.go
  frontend/src/components/ProjectVersionControlPanel.vue
  frontend/src/components/RepositoryPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/store/modules/v1/repository.ts
  frontend/src/store/modules/v1/vcs.ts
Labels: cla-signed

#6478 chore: migrate repository store to v2
  backend/api/v1/externalvs_service.go
  backend/api/v1/project_service.go
  backend/api/v1/sheet_service.go
  backend/legacyapi/repository.go
  backend/runner/taskrun/executor.go
  backend/server/project.go
  backend/store/project.go
  backend/store/project_webhook.go
  backend/store/repository.go
  backend/utils/utils.go
  frontend/src/components/RepositorySetupWizard.vue
Labels: cla-signed

#6476 chore: add back export button in SQL Editor
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/plugins/issue/logic/initialize/grantRequest.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed, backport release/2.2.0

#6482 chore: update export data button in `SingleResultView.vue` for admin mode
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed, backport release/2.2.0

#6481 chore: add back create table group button
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/v2/Form/ResourceIdInput.vue
Labels: backport release/2.2.0

#6488 chore: add scripts/.air.toml in .gitignore
  .gitignore
  scripts/.air.toml
Labels: cla-signed

#6485 chore: grpc server 10 sec shutdown period
  backend/server/server.go
Labels: cla-signed

#6490 chore: revert #6488 and using git update-index --assume-unchanged instead
  .gitignore
  scripts/.air.toml
Labels: cla-signed

#6494 chore(frontend): remove log
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
Labels: cla-signed, backport release/2.2.0

#6493 feat: log grpc call error
  backend/api/v1/debug_interceptor.go
  backend/server/server.go
Labels: cla-signed

#6498 chore: handle schema group list empty value
  frontend/src/plugins/issue/logic/common.ts
Labels: cla-signed, backport release/2.2.0

#6496 fix: instance change history in migrator
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  backend/store/instance_change_history.go
Labels: cla-signed

#6486 chore: remove the number of table groups checked by the backend creation issue
  backend/server/issue.go
Labels: cla-signed

#6501 docs: update anomaly center doc
  README.md
  docs/design/source-code-tour.snb.md
Labels: cla-signed

#6497 feat(frontend): ship some quick action dialogs to drawers
  frontend/src/bbkit/BBModal.vue
  frontend/src/bbkit/BBModalStack.vue
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepButtonGroup.vue
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepPanel.vue
  frontend/src/components/CreateDatabasePrepForm/index.ts
  frontend/src/components/DatabaseBackup/BackupTable.vue
  frontend/src/components/DatabaseBackup/RestoreTargetForm.vue
  frontend/src/components/DatabaseDetail/ChangeHistoryBrief.vue
  frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
  frontend/src/components/EnvironmentForm.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/Project/ProjectCreatePanel.vue
  frontend/src/components/ProjectCreate.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/RequestDatabasePrepForm.vue
  frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Container/Drawer.vue
  frontend/src/components/v2/Container/DrawerContent.vue
  frontend/src/components/v2/Container/index.ts
  frontend/src/components/v2/index.ts
  frontend/src/locales/en-US.json
  frontend/src/types/quickAction.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/SettingWorkspaceProject.vue
Labels: cla-signed

#6502 feat: implement export center
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/store/modules/v1/sql.ts
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/ExportCenter/ExportDataButton.vue
  frontend/src/views/ExportCenter/ExportRecordTable.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/ExportCenter/types.ts
Labels: cla-signed

#6503 chore: migrate vcs and repo to v2 store
  backend/api/v1/sheet_service.go
  backend/legacyapi/repository.go
  backend/legacyapi/vcs.go
  backend/server/oauth.go
  backend/server/project.go
  backend/server/webhook.go
  backend/server/webhook_test.go
  backend/store/repository.go
  backend/store/store.go
  backend/store/vcs.go
Labels: cla-signed

#6505 chore: update empty expression string to `true`
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/cel/logic/stringify.ts
Labels: cla-signed, backport release/2.2.0

#6507 fix: pushEvent commits field name
  backend/migrator/migration/prod/2.2/0005##update_vcs_push_event_field_name.sql
Labels: cla-signed

#6509 feat: add placeholder field to db group
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/SelectSchemaGroupsTable.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/components/v2/Model/DatabaseV1Table.vue
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/dbGroup.ts
Labels: cla-signed

#6512 fix(2.2.0): schema version
  backend/migrator/migrator_test.go
Labels: cla-signed

#6513 fix: add different suffixes to the schema version of different tasks of a database
  backend/server/issue.go
Labels: cla-signed, backport release/2.2.0

#6506 chore: enable websockets
  backend/server/server.go
Labels: cla-signed

#6515 chore(grpc-websocket): skip origin check
  backend/server/server.go
Labels: cla-signed

#6516 chore: migrate backup setting
  backend/api/v1/acl_config.go
  backend/api/v1/environment_service.go
  backend/server/acl_casbin_policy_dba.csv
  backend/server/acl_casbin_policy_owner.csv
  backend/server/environment.go
  backend/server/server.go
  backend/store/backup.go
  frontend/src/components/DatabaseBackup/DatabaseBackupSettingForm.vue
  frontend/src/components/DatabaseBackup/utils.ts
  frontend/src/components/DatabaseBackupPanel.vue
  frontend/src/store/modules/backup.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/v1/backup.ts
  frontend/src/types/backup.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/environment_service.ts
  frontend/src/types/store.ts
  frontend/src/views/EnvironmentDetail.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/environment_service.pb.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/environment_service_grpc.pb.go
  proto/v1/database_service.proto
  proto/v1/environment_service.proto
Labels: cla-signed

#6517 chore: add unique index for (db_group_id, placeholder)
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.2/0002##database_schema_group.sql
  backend/migrator/migration/prod/LATEST.sql
Labels: cla-signed

#6519 chore: add database group prev editor modal
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
  frontend/src/components/DatabaseGroup/SelectDatabaseGroupTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/logic/common.ts
  frontend/src/plugins/issue/logic/initialize/tenant.ts
  frontend/src/store/modules/dbGroup.ts
  frontend/src/utils/databaseGroup/issue.ts
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/SchemaGroupDetail.vue
Labels: cla-signed

#6518 chore: cleanup legacy backup setting
  backend/api/v1/database_service.go
  backend/legacyapi/backup.go
  backend/runner/backuprun/runner.go
  backend/server/acl_casbin_policy_dba.csv
  backend/server/acl_casbin_policy_developer.csv
  backend/server/acl_casbin_policy_owner.csv
  backend/server/database.go
  backend/store/backup.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
Labels: cla-signed

#6520 chore: policy cel condition support environment
  backend/api/v1/cel_service.go
  backend/api/v1/project_service.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#6521 chore: migrate query to export
  backend/server/openapi_sql.go
  backend/server/sql.go
  backend/server/sql_test.go
  frontend/src/components/Issue/action/ExportDataButton.vue
Labels: cla-signed

#6522 chore: move phone to 2.2.0 schema
  backend/migrator/migration/prod/2.2/0006##add_phone_to_principal.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#6525 chore(frontend): minor improvements and bug fixes
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/bbkit/BBAlert.vue
  frontend/src/bbkit/BBAlertDialog.vue
  frontend/src/bbkit/BBModal.vue
  frontend/src/bbkit/BBModalStack.vue
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/factor.ts
  frontend/src/plugins/ai/components/AIChatToSQL.vue
  frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
Labels: cla-signed

#6524 chore: allow owners to create user and service accounts even when self-signup is disabled
  backend/api/v1/auth_service.go
Labels: cla-signed

#6526 feat: initial create context from tasks for grouping issue
  frontend/src/components/Issue/logic/TenantModeProvider.ts
  frontend/src/plugins/issue/logic/initialize/helper.ts
  frontend/src/plugins/issue/logic/initialize/tenant.ts
  frontend/src/types/issue.ts
  frontend/src/types/pipeline/task.ts
Labels: cla-signed

#6527 chore: use statement editor in database group detail page
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/views/DatabaseGroupDetail.vue
Labels: cla-signed

#6528 chore: add phone number
  backend/api/v1/auth_service.go
Labels: cla-signed

#6529 chore: resolve the approved query approval issue
  backend/api/v1/review_service.go
Labels: cla-signed

#6530 chore: add dev guard to export center
  frontend/src/views/DashboardSidebar.vue
Labels: cla-signed

#6531 chore: Revert "chore: resolve the approved query approval issue"
  backend/api/v1/review_service.go
Labels: cla-signed

#6523 feat(group): support create grouping issue
  backend/legacyapi/issue.go
  backend/legacyapi/task.go
  backend/server/issue.go
  backend/store/issue.go
Labels: cla-signed

#6532 feat(frontend): use export v1 API in sql editor
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/useExportData.ts
  frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
  frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#6535 feat: add new project webhook type issue approval notify
  backend/api/v1/project_service.go
  frontend/src/components/Issue/IssueActivityPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/activity.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/v1/projectWebhook.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#6536 feat: add database group / schema group name in issue payload and task payload
  backend/legacyapi/issue.go
  backend/legacyapi/task.go
  backend/server/issue.go
  backend/store/database_group.go
  backend/store/store.go
  frontend/src/types/proto/store/issue.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/issue.pb.go
  proto/store/issue.proto
Labels: cla-signed

#6538 chore: disallow edit task for grouping issue
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/components/Issue/logic/TenantModeProvider.ts
  frontend/src/components/Issue/logic/common.ts
  frontend/src/plugins/issue/logic/initialize/helper.ts
  frontend/src/types/issue.ts
  frontend/src/types/pipeline/task.ts
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#6537 fix: skip if no approval template
  backend/api/v1/review_service.go
  backend/runner/approval/runner.go
Labels: cla-signed

#6539 fix: post webhook list
  backend/common/retry.go
  backend/component/activity/manager.go
Labels: cla-signed

#6541 feat: support dispatch statement to different task
  backend/server/issue.go
Labels: cla-signed

#6465 feat: introduce MySQL parser
  backend/api/v1/sql_service.go
  backend/plugin/advisor/catalog/walk_through.go
  backend/plugin/advisor/mysql/parser.go
  backend/plugin/db/mysql/mysql_test.go
  backend/plugin/parser/sql/differ/mysql/constraint_test.go
  backend/plugin/parser/sql/differ/mysql/utils_test.go
  backend/plugin/parser/sql/mysql.go
  backend/plugin/parser/sql/mysql_test.go
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
  backend/plugin/parser/sql/split_multi_sql_test.go
  backend/plugin/parser/sql/tokenizer.go
  backend/plugin/parser/sql/transform/mysql/transform_test.go
  backend/plugin/parser/sql/utils.go
  backend/plugin/parser/sql/utils_test.go
  backend/tests/test-data/sql_review_mysql.yaml
  go.mod
  go.sum
Labels: cla-signed

#6543 chore(frontend): introduce grpc-web auth interceptor middleware
  frontend/src/grpcweb/index.ts
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/grpcweb/middlewares/index.ts
Labels: cla-signed

#6444 fix(github): unable to load big files
  backend/plugin/vcs/github/github.go
  backend/plugin/vcs/github/github_test.go
  backend/plugin/vcs/internal/oauth/oauth.go
  backend/tests/fake/github.go
Labels: cla-signed

#6547 fix: readonly for task statement
  frontend/src/components/Issue/logic/common.ts
Labels: cla-signed, backport release/2.2.0

#6549 fix: localization
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6546 feat(frontend): disallow to approve review when some task checks didn't pass
  frontend/src/bbkit/BBTooltipButton.vue
  frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6550 chore: validate expr when creating group
  backend/api/v1/project_service.go
Labels: cla-signed

#6551 fix(frontend): minor bug fixes
  frontend/src/bbkit/BBModal.vue
  frontend/src/components/AlterSchemaPrepForm/ProjectTenantView.vue
  frontend/src/components/v2/Model/DatabaseV1Table.vue
Labels: cla-signed, backport release/2.2.0

#6552 chore: fix lots of issues of database grouping
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
  frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
  frontend/src/components/v2/Model/DatabaseGroupName.vue
  frontend/src/plugins/cel/types/operator.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/router.ts
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/SchemaGroupDetail.vue
Labels: cla-signed

#6540 feat: add REJECTED to approver status
  frontend/src/types/proto/store/activity.ts
  frontend/src/types/proto/store/approval.ts
  frontend/src/types/proto/v1/review_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/activity.pb.go
  proto/generated-go/store/approval.pb.go
  proto/generated-go/v1/review_service.pb.go
  proto/generated-go/v1/review_service.pb.gw.go
  proto/generated-go/v1/review_service_grpc.pb.go
  proto/store/activity.proto
  proto/store/approval.proto
  proto/v1/review_service.proto
Labels: cla-signed

#6553 chore: fix some grouping issues
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/SchemaGroupTable.vue
  frontend/src/components/DatabaseGroup/SelectDatabaseGroupTable.vue
  frontend/src/components/DatabaseGroup/common/ExprEditor/ConditionGroup.vue
  frontend/src/components/Issue/logic/TenantModeProvider.ts
  frontend/src/components/v2/Model/DatabaseGroupName.vue
  frontend/src/plugins/cel/logic/resolve.ts
  frontend/src/views/DatabaseGroupDetail.vue
Labels: cla-signed

#6556 chore: add validate issue in prev editor
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/store/modules/dbGroup.ts
Labels: cla-signed

#6554 chore: validate expr when updating group
  backend/api/v1/project_service.go
Labels: cla-signed

#6558 chore(frontend): fix displayed environment id
  frontend/src/components/EnvironmentForm.vue
Labels: cla-signed, backport release/2.2.0

#6555 feat: allow approver commenting
  frontend/src/types/proto/v1/review_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/review_service.pb.go
  proto/v1/review_service.proto
Labels: cla-signed

#6560 chore: skip create table option for OceanBase
  backend/plugin/db/mysql/dump.go
Labels: cla-signed

#6561 feat: impl RejectReview
  backend/api/v1/review_service.go
  backend/api/v1/review_service_test.go
  backend/utils/utils.go
Labels: cla-signed

#6562 feat(proto): request review
  frontend/src/types/proto/v1/review_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/review_service.pb.go
  proto/generated-go/v1/review_service.pb.gw.go
  proto/generated-go/v1/review_service_grpc.pb.go
  proto/v1/review_service.proto
Labels: cla-signed

#6566 chore: decouple project members from setting
  frontend/src/components/Project/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/ProjectSetting/index.ts
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/RoleDescription.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/UserTable.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/index.ts
  frontend/src/components/ProjectMember/ProjectMemberTable/types.ts
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#6567 feat: impl RequestReview
  backend/api/v1/review_service.go
Labels: cla-signed

#6563 feat: ApproveReview, pass comment to activity
  backend/api/v1/review_service.go
Labels: cla-signed

#6565 feat(frontend): allow to cancel waiting approval issue in issue detail page
  frontend/src/components/Issue/IssueHighlightPanel.vue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/PipelineGhostFlow.vue
  frontend/src/components/Issue/PipelinePITRFlow.vue
  frontend/src/components/Issue/PipelineSimpleFlow.vue
  frontend/src/components/Issue/PipelineTenantFlow.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/BatchTaskActionDialog.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/BatchTaskActionForm.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/CombinedRolloutButtonGroup.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/IssueStatusTransitionDialog.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/StandaloneIssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/StatusTransitionForm.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/TaskExtraActionsButton.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/TaskStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/TaskStatusTransitionDialog.vue
  frontend/src/components/Issue/StatusTransitionButtonGroup/common.ts
  frontend/src/components/Issue/StatusTransitionButtonGroup/index.ts
  frontend/src/components/Issue/index.ts
  frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
  frontend/src/components/MonacoEditor/MonacoEditor.vue
Labels: cla-signed

#6568 chore: add query and export risk source
  frontend/src/types/proto/v1/risk_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/risk_service.pb.go
  proto/v1/risk_service.proto
Labels: cla-signed

#6569 chore: deprecate legacy database schema API
  backend/server/database.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
  backend/tests/schema_update_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
Labels: cla-signed

#6570 chore: implement sync instance and database
  backend/api/v1/database_service.go
  backend/api/v1/instance_service.go
  backend/server/server.go
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/v1/database_service.proto
  proto/v1/instance_service.proto
Labels: cla-signed
