Repository bytebase/bytebase, pull requests merged in 2023-09, with the labels that each got.

#7888 chore(sql-editor): upgrade monaco-editor and lsp client
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/monaco-editor-workers/.gitignore
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/components/MonacoEditor/useMonaco.ts
  frontend/src/plugins/sql-lsp/client/createLanguageClient.ts
  frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
  frontend/src/types/utils.ts
  frontend/vite.config.ts
Labels: cla-signed

#7884 chore: migrate backup restore test to new CI/CD
  backend/tests/backup_restore_test.go
  backend/tests/issue.go
  backend/tests/rollout.go
Labels: cla-signed

#7892 chore: make tab more condensed
  frontend/src/bbkit/BBTabFilter.vue
  frontend/src/components/v2/TabFilter/TabFilter.vue
Labels: cla-signed

#7894 chore: condense sidebar
  frontend/src/layouts/BodyLayout.vue
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/SettingSidebar.vue
Labels: cla-signed

#7891 chore: support set classification in template and designer
  backend/api/v1/setting_service.go
  frontend/src/components/ColumnTable.vue
  frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
  frontend/src/components/SchemaDesigner/EditSchemaDesignPanel.vue
  frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
  frontend/src/components/SchemaDesigner/common/context.ts
  frontend/src/components/SchemaDesigner/common/type.ts
  frontend/src/components/SchemaDesigner/common/util.ts
  frontend/src/components/SchemaDesigner/index.vue
  frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/SelectClassificationDrawer.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/setting.ts
  frontend/src/types/schemaEditor/atomType.ts
Labels: cla-signed

#7879 feat: schemasyncer sync interval
  backend/api/v1/database_service.go
  backend/runner/schemasync/syncer.go
  backend/store/database.go
Labels: cla-signed

#7896 feat: impl update instance options sync_interval
  backend/api/v1/instance_service.go
  backend/store/instance.go
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#7897 chore(frontend): robustness
  frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
Labels: cla-signed

#7526 feat: add announcement banner configuration
  backend/legacyapi/plan.go
  frontend/src/components/BannersWrapper.vue
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/GeneralSetting/index.ts
  frontend/src/components/v2/Select/AnnouncementLevelSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/views/BannerAnnouncement.vue
  frontend/src/views/BannerUpgradeSubscription.vue
  frontend/src/views/SettingWorkspaceGeneral.vue
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#7900 fix: close response body
  backend/plugin/app/relay/relay_client.go
  backend/plugin/idp/oauth2/oauth2.go
  backend/plugin/vcs/gitlab/gitlab.go
  backend/runner/backuprun/runner.go
  backend/tests/fake/bitbucket.go
  backend/tests/fake/github.go
  backend/tests/fake/gitlab.go
  backend/tests/schema_update_test.go
  backend/tests/tests.go
Labels: cla-signed

#7901 fix: localization json format
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7899 chore: flatten the member list
  backend/api/v1/org_policy_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#7903 chore: update instance count wording for FREE plan
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#7905 feat(advanced-masking-policy): retire sensitive in plsql calculator
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_plsql.go
Labels: cla-signed

#7906 feat(advanced-masking-policy): retire sensitive in snowsql calculator
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
Labels: cla-signed

#7908 chore: reverse the dev schedule flag
  backend/tests/backup_restore_test.go
  backend/tests/change_history_test.go
  backend/tests/data_source_test.go
  backend/tests/database_edit_test.go
  backend/tests/environment_test.go
  backend/tests/ghost_test.go
  backend/tests/grouping_change_test.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sheet_vcs_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
  backend/tests/subscription_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
Labels: cla-signed

#7909 chore: migrate tests (part 9)
  backend/tests/issue.go
  backend/tests/rollout.go
  backend/tests/schema_update_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#7910 chore: migrate test (part 10)
  backend/tests/issue.go
  backend/tests/mysql.go
  backend/tests/rollback_test.go
  backend/tests/rollout.go
Labels: cla-signed

#7912 fix: delete the legacy data
  backend/migrator/migration/prod/2.7/0000##migrate_sensitive_data_policy_to_proto_json.sql
Labels: cla-signed

#7913 feat: delete the bb.issue.general issue related
  backend/migrator/migration/prod/2.7/0005##delete_general_issue_related.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#7911 chore: migrate test (part 11)
  backend/tests/grouping_change_test.go
  backend/tests/rollback_test.go
  backend/tests/rollout.go
Labels: cla-signed

#7914 chore: clear push event
  backend/migrator/migration/prod/2.7/0006##clean_pushevent.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#7917 feat(advanced-masking-policy): retire sensitive in tsql calculator
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_tsql.go
Labels: cla-signed

#7918 chore: clean sheet payload
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/api/v1/schema_design_service.go
  backend/api/v1/sheet_service.go
  backend/runner/rollbackrun/runner.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/webhook.go
  backend/store/sheet.go
  backend/store/store.go
Labels: cla-signed

#7919 chore: clean push event from task payload
  backend/api/v1/database_service.go
  backend/api/v1/rollout_service_task.go
  backend/legacyapi/task.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_baseline_executor.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_sdl_executor.go
  backend/server/issue.go
Labels: cla-signed

#7920 fix(advanced-masking-policy): filter the exception policy by action
  backend/api/v1/sql_service.go
Labels: cla-signed

#7921 chore(advanced-masking-policy): retire sensitive fully
  backend/api/v1/sql_service.go
  backend/plugin/db/driver.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_mysql.go
  backend/plugin/db/util/mask_sensitive_data_psql.go
Labels: cla-signed

#7924 fix: backfill rollout policy assignee group value
  backend/api/v1/org_policy_service.go
  backend/migrator/migration/prod/2.7/0007##fix_policy_rollout.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#7922 chore: support configure masking and exception policy
  backend/api/v1/org_policy_service.go
  frontend/src/bbkit/BBTable/BBTable.vue
  frontend/src/components/ColumnTable.vue
  frontend/src/components/SensitiveData/GlobalMaskingRule.vue
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnList.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/SensitiveData/components/MaskingLevelDropdown.vue
  frontend/src/components/SensitiveData/components/MaskingLevelRadioGroup.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/components/SensitiveData/index.ts
  frontend/src/components/SensitiveData/types.ts
  frontend/src/components/SensitiveData/utils.ts
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/TableTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/views/SettingWorkspaceSensitiveData.vue
Labels: cla-signed

#7929 chore: vcs wording tweak
  frontend/src/components/VCSProviderBasicInfoPanel.vue
  frontend/src/components/VCSProviderConfirmPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceVCSDetail.vue
Labels: cla-signed

#7925 fix: announcement banner
  backend/enterprise/api/plan.yaml
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/v2/Select/AnnouncementLevelSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/role.ts
  frontend/src/views/BannerAnnouncement.vue
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#7930 chore: use depot to build docker image
  .github/workflows/build-push-ci-image-depot.yml
Labels: cla-signed

#7931 fix: login dockerhub
  .github/workflows/build-push-ci-image-depot.yml
Labels: cla-signed

#7932 chore: secret
  .github/workflows/build-push-ci-image-depot.yml
Labels: cla-signed

#7904 feat(sql-editor): introducing new layout of SQL Editor
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/tab.ts
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
  frontend/src/views/sql-editor/EditorCommon/ConnectionHolder.vue
  frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
  frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/InfoTabPane.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/AlterSchemaButton.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/ColumnList.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/ExternalLinkButton.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaDiagramButton.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/SecondarySidebar.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetItem.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/TabItem.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/common.ts
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetTabPane.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/ToggleSecondarySidebarButton.vue
  frontend/src/views/sql-editor/SecondarySidebar/context.ts
  frontend/src/views/sql-editor/SecondarySidebar/index.ts
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#7928 feat(advanced-masking-policy): support partial mask
  backend/api/v1/org_policy_service.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#7933 chore: use depot for release images
  .github/workflows/build-push-release-image.yml
Labels: cla-signed

#7934 feat(audit-log): support select sql export in audit log
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/auditLog.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
Labels: cla-signed, backport release/2.7.0

#7935 fix: delete data refer issue table
  backend/migrator/migration/prod/2.7/0005##delete_general_issue_related.sql
Labels: cla-signed, backport release/2.7.0

#7856 chore: implement dumpTable for Oracle
  backend/plugin/db/oracle/dump.go
Labels: cla-signed

#7938 chore: support deployment config target
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/plan.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#7939 fix: backfill project webhook taskrun status update
  backend/migrator/migration/prod/2.7/0008##backfill_webhook.sql
  backend/migrator/migrator_test.go
Labels: cla-signed, backport release/2.7.0

#7941 fix: default sign in frequency to 7 days
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
Labels: cla-signed

#7942 chore(advanced-masking-policy): add log of eval masking level
  backend/api/v1/sql_service.go
Labels: cla-signed

#7943 chore: result order
  .github/workflows/backend-tests.yml
  .github/workflows/build-artifacts-and-draft-release.yml
  .github/workflows/build-push-ci-image.yml
  backend/tests/grouping_change_test.go
Labels: cla-signed

#7944 chore(frontend): respect feature guard for task rollout schedule time feature
  frontend/src/components/IssueV1/components/StageSection/Actions/EarliestAllowedTime.vue
Labels: cla-signed

#7946 chore(frontend): support SKIPPED task run status
  frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionIcon.vue
  frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionSentence.vue
  frontend/src/types/pipeline/task.ts
Labels: cla-signed

#7947 chore: add back frontend build to docker
  .github/workflows/build-push-ci-image-depot.yml
  .github/workflows/build-push-release-image.yml
  scripts/Dockerfile
  scripts/build_bytebase_docker.sh
Labels: cla-signed

#7948 chore: change the query history clipboard icon
  frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
Labels: cla-signed

#7949 chore: change “setting” to “profile” under profile dropdown
  frontend/src/components/ProfileDropdown.vue
Labels: cla-signed

#7950 chore: update global masking rules
  frontend/src/components/SensitiveData/DataFeatureView.vue
  frontend/src/components/SensitiveData/GlobalMaskingRule.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/components/SensitiveData/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/policy.ts
  frontend/src/views/SettingWorkspaceSensitiveData.vue
Labels: cla-signed

#7951 chore: revert "chore: upgrade monaco-editor and lsp client (#7888)"
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/monaco-editor-workers/.gitignore
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/components/MonacoEditor/useMonaco.ts
  frontend/src/plugins/sql-lsp/client/createLanguageClient.ts
  frontend/src/plugins/sql-lsp/client/useLanguageClient.ts
  frontend/src/types/utils.ts
  frontend/vite.config.ts
Labels: cla-signed

#7952 fix: update styles of elements
  frontend/src/views/BannerAnnouncement.vue
Labels: cla-signed

#7955 chore: condense dashboard header
  frontend/src/components/BytebaseLogo.vue
  frontend/src/components/ProfileBrandingLogo.vue
  frontend/src/components/ProfileDropdown.vue
  frontend/src/views/DashboardHeader.vue
Labels: cla-signed

#7953 chore: retire ActivityPipelineTaskStatusUpdate in project webhook activities
  backend/legacyapi/activity.go
  backend/migrator/migration/prod/2.7/0009##remove_task_status_update_from_project_webhook.sql
  backend/migrator/migrator_test.go
  frontend/src/types/v1/projectWebhook.ts
Labels: cla-signed

#7954 chore: set classification to project during creation
  backend/api/v1/project_service.go
  backend/store/project.go
Labels: cla-signed

#7945 fix: all in activity type task run status update
  backend/component/activity/manager.go
  backend/legacyapi/task_run.go
Labels: cla-signed

#7956 fix: createPendingTaskRuns iso level serializable
  backend/store/task_run.go
Labels: backport release/2.7.0

#7960 feat: impl dump indexes for Oracle
  backend/plugin/db/oracle/dump.go
Labels: cla-signed

#7958 chore: support classification in global rules
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
  backend/common/convert.go
  frontend/src/components/SchemaTemplate/ClassificationLevelBadge.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/plugins/cel/types/operator.ts
  frontend/src/types/setting.ts
Labels: cla-signed

#7957 chore: condense quickaction button to save vertical space
  frontend/src/components/QuickActionPanel.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/router/index.ts
  frontend/src/types/quickAction.ts
Labels: cla-signed

#7966 fix: use the default if instance syncInterval is zero
  backend/runner/schemasync/syncer.go
Labels: cla-signed

#7965 chore: delete drawer v1 component
  frontend/src/components/Drawer.vue
Labels: cla-signed

#7968 feat(frontend): custom instance scan interval configuration
  backend/legacyapi/plan.go
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
Labels: cla-signed

#7969 fix: feature attention
  backend/legacyapi/setting.go
  backend/server/server.go
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/types/setting.ts
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#7970 chore: deprecate developmentUseV2Scheduler flag
  .github/workflows/backend-tests-default.yml
  .github/workflows/backend-tests.yml
  backend/api/v1/actuator_service.go
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
  backend/runner/backuprun/runner.go
  backend/runner/rollbackrun/runner.go
  backend/runner/taskrun/executor.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/webhook.go
  backend/tests/tests.go
  scripts/.air.toml
Labels: cla-signed

#7975 refactor: delete code part 1
  backend/api/v1/issue_service.go
  backend/runner/approval/runner.go
  backend/runner/relay/runner.go
  backend/runner/taskrun/scheduler.go
  backend/server/issue.go
  backend/utils/utils.go
Labels: cla-signed

#7976 chore: delete unused code (part 2)
  backend/api/v1/issue_service.go
  backend/runner/approval/runner.go
  backend/runner/relay/runner.go
  backend/runner/taskcheck/database_connect_executor.go
  backend/runner/taskcheck/executor.go
  backend/runner/taskcheck/ghost_sync_executor.go
  backend/runner/taskcheck/pitr_mysql_executor.go
  backend/runner/taskcheck/scheduler.go
  backend/runner/taskcheck/statement_advisor_composite_executor.go
  backend/runner/taskcheck/statement_affected_rows_report_executor.go
  backend/runner/taskcheck/statement_affected_rows_report_executor_test.go
  backend/runner/taskcheck/statement_type_executor.go
  backend/runner/taskcheck/statement_type_executor_test.go
  backend/runner/taskcheck/statement_type_report_executor.go
  backend/runner/taskcheck/statement_type_report_executor_test.go
  backend/runner/taskrun/scheduler.go
  backend/runner/taskrun/schedulerv2.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/stage.go
  backend/server/task.go
  backend/server/webhook.go
  backend/store/task_check_run.go
  backend/utils/utils.go
Labels: cla-signed

#7977 chore: delete unused code (part 3)
  backend/server/issue.go
  backend/server/issue_test.go
  backend/store/issue.go
  backend/tests/issue.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#7980 chore: delete unused code (part 4)
  backend/runner/taskrun/scheduler.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/stage.go
  backend/server/task.go
  backend/server/webhook.go
Labels: cla-signed

#7982 feat: sidebar recent database list
  frontend/src/components/DatabaseListSidePanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/collections.ts
Labels: cla-signed

#7983 fix: filter project list in side panel
  frontend/src/components/ProjectListSidePanel.vue
Labels: cla-signed

#7985 chore(frontend): instance sync interval's default description changed to "never"
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7984 feat: syncer, zero interval means never
  backend/runner/schemasync/syncer.go
Labels: cla-signed

#7981 chore: delete unused code (part 5)
  backend/api/v1/issue_service.go
  backend/legacyapi/issue.go
  backend/server/issue.go
  backend/store/issue.go
Labels: cla-signed

#7986 fix: jump out of sql editor page
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/AIChatToSQL.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
Labels: cla-signed

#7988 fix: activity list order
  frontend/src/store/modules/v1/activity.ts
Labels: cla-signed

#7990 chore: annotate custom role description
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7989 chore(sql-editor): minor updates
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/SecondarySidebar/SecondarySidebar.vue
Labels: cla-signed

#7987 feat: task_run attempt for optimistic locking
  backend/api/v1/rollout_service.go
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.8/0000##task_run_attempt.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/task.go
  backend/store/task_run.go
Labels: cla-signed

#7993 chore: add clean up expired roles button
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7992 chore: disable sync for read-only mode
  backend/runner/schemasync/syncer.go
  backend/server/issue.go
  backend/server/openapi_sql.go
  backend/server/server.go
  backend/server/task.go
  backend/server/webhook.go
Labels: cla-signed

#7994 chore: add statement only props to request export form for SQL Editor
  frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/index.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#7996 chore: count by active users
  backend/api/v1/auth_service.go
  backend/store/stats.go
Labels: cla-signed

#7997 feat: move anomaly scanner into schema syncer
  backend/runner/anomaly/scanner.go
  backend/runner/schemasync/syncer.go
  backend/server/server.go
Labels: cla-signed

#7998 fix: demo task run data
  backend/migrator/demo/default/10120##task_run.sql
Labels: cla-signed

#7999 feat(frontend): ci/cd UI improvements
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/ReviewActionButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadgeBar.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/IssueV1/components/StageSection/StageSection.vue
  frontend/src/components/IssueV1/components/common/ErrorList.vue
  frontend/src/components/IssueV1/logic/plan-check.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlReview.ts
Labels: cla-signed

#8000 chore: run sync all databases synchronously
  backend/runner/schemasync/syncer.go
Labels: cla-signed

#8001 chore: update change history table
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/components/DatabaseChangeHistoryPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/changeHistory.ts
Labels: cla-signed

#8002 refactor: split the transfrom logic to schema_design_transformer.go
  backend/api/v1/common.go
  backend/api/v1/common_test.go
  backend/api/v1/schema_design_service.go
  backend/api/v1/schema_design_transformer.go
  backend/api/v1/schema_design_transformer_test.go
Labels: cla-signed

#8004 chore(sql-editor): style fine tuning
  frontend/src/views/sql-editor/SecondarySidebar/ToggleSecondarySidebarButton.vue
  frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#8005 feat: update grant access and request export fields
  frontend/src/components/Issue/IssueHighlightPanel.vue
  frontend/src/components/Issue/form/GrantRequestExporterForm.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
  frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue
Labels: cla-signed

#8003 feat: implement Oracle sync schema for Table, Column and Constraint
  backend/plugin/parser/sql/differ/plsql/differ.go
  backend/plugin/parser/sql/differ/plsql/differ_test.go
  backend/plugin/parser/sql/differ/plsql/test-data/test_differ_data.yaml
  backend/plugin/parser/sql/plsql.go
Labels: cla-signed

#8007 fix: risk factors
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
Labels: cla-signed

#8006 feat: get affected rows for ddl
  backend/runner/plancheck/statement_report_executor.go
  backend/runner/plancheck/statement_report_executor_affected_rows.go
Labels: cla-signed

#8008 chore(frontend): reset state and handle callback when changing instance scan interval
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
Labels: cla-signed

#8009 feat: implement Oracle sync schema for Index
  backend/plugin/parser/sql/differ/plsql/differ.go
  backend/plugin/parser/sql/differ/plsql/test-data/test_differ_data.yaml
Labels: cla-signed

#8010 chore: show different read-only connection tip depending on the role
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
Labels: cla-signed

#8013 fix: project getter in branching
  frontend/src/components/SchemaDesigner/CreateSchemaDesignPanel.vue
Labels: cla-signed

#8011 chore: remove unused code
  backend/api/v1/docs.go
  backend/bin/server/cmd/root.go
  backend/legacyapi/external_approval.go
  backend/legacyapi/instance_user.go
  backend/legacyapi/slug.go
  backend/legacyapi/sql.go
  backend/legacyapi/stage.go
  backend/legacyapi/task.go
  backend/legacyapi/task_check_run.go
  backend/runner/approval/runner.go
  backend/server/openapi_sql.go
  backend/server/server.go
  backend/server/task.go
  backend/store/issue.go
  backend/store/task.go
  backend/store/task_check_run.go
Labels: cla-signed

#8020 chore: update frontend dependency
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#8021 feat(sql-editor): re-layout SQL Editor
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#8022 chore: Go 1.21.1
  .github/workflows/backend-tests.yml
  .github/workflows/build-artifacts-and-draft-release.yml
  README.md
  scripts/.goreleaser-for-darwin.yaml
  scripts/.goreleaser-for-linux.yaml
  scripts/Dockerfile
  scripts/Dockerfile.bb
  scripts/Dockerfile.render-demo
  scripts/Dockerfile.sql-service
  scripts/build_bytebase.sh
Labels: cla-signed

#8023 cherrypick: Go 1.21.1 to 2.7.0
  README.md
  scripts/.goreleaser-for-darwin.yaml
  scripts/.goreleaser-for-linux.yaml
  scripts/Dockerfile
  scripts/Dockerfile.bb
  scripts/Dockerfile.render-demo
  scripts/Dockerfile.sql-service
  scripts/build_bytebase.sh
Labels: cla-signed

#8026 chore: hide the entrey if users don't have permission
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#8028 chore(frontend): robustness++
  frontend/src/store/modules/task.ts
Labels: cla-signed

#8024 fix: statement report executor log
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#8025 fix(announcement): only display text when link does not exist
  frontend/src/views/BannerAnnouncement.vue
Labels: cla-signed

#8029 feat: enable Oracle sync schema
  backend/plugin/parser/sql/differ/plsql/differ.go
  backend/server/openapi_sql.go
  backend/server/server.go
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
Labels: cla-signed

#8030 fix: remove log.BBError(err) if nil
  backend/plugin/idp/oauth2/oauth2.go
  backend/server/webhook.go
Labels: cla-signed

#8031 chore: rename extractMySQLSensitiveField to extractTiDBSensitiveField
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_tidb.go
Labels: cla-signed

#8032 chore: deprecate task check run
  backend/legacyapi/task_check_run.go
  backend/runner/approval/runner.go
  backend/store/task_check_run.go
Labels: cla-signed

#8033 chore: update feature badge
  frontend/src/components/FeatureGuard/FeatureAttentionForInstanceLicense.vue
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/FeatureGuard/FeatureBadgeForInstanceLicense.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
Labels: cla-signed

#8034 chore: update condition title generator when granting access
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
Labels: cla-signed

#8035 fix: forbid edit masking rules if the instance is missing required license
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
Labels: cla-signed

#8037 chore: change Alter Schema to Edit Schema
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/AlterSchemaButton.vue
Labels: cla-signed

#8036 chore: remove stage.Active
  backend/runner/approval/runner.go
  backend/server/webhook.go
  backend/store/stage.go
  backend/utils/utils.go
Labels: cla-signed

#8038 chore: pre-fill filter state to request export panel
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/views/ExportCenter/index.vue
Labels: cla-signed

#8039 chore: 2.8.0
  scripts/VERSION
Labels: cla-signed

#8040 feat(sql-editor): improve SQL Editor layout
  frontend/src/assets/css/tailwind.css
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/AIChatToSQL.vue
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
  frontend/src/views/sql-editor/ProfileDropdown/ProfileDropdown.vue
  frontend/src/views/sql-editor/ProfileDropdown/index.ts
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/ColumnList.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableList.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/context.ts
  frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/OpenAIButton.vue
  frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue
  frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/index.ts
  frontend/src/views/sql-editor/SecondarySidebar/SecondarySidebar.vue
  frontend/src/views/sql-editor/SecondarySidebar/index.ts
  frontend/src/views/sql-editor/TabList/TabList.vue
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#8042 chore: change ghost lock timeout to 10 seconds
  backend/utils/utils.go
Labels: cla-signed

#8043 feat(cicd): use legacy API to patch tasks' rollbackEnabled for legacy issues
  frontend/src/components/IssueV1/components/StageSection/Actions/RollbackSection/common.ts
  frontend/src/components/IssueV1/logic/legacy-issue-compatibility.ts
Labels: cla-signed

#8044 fix: avoid insert data in setting
  backend/server/server.go
Labels: cla-signed

#8045 chore: add filterable to v2 selects
  frontend/src/components/User/Settings/MemberAddOrInvite.vue
  frontend/src/components/User/Settings/UserTable.vue
  frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
  frontend/src/components/v2/Select/WorkspaceRoleSelect.vue
  frontend/src/components/v2/Select/index.ts
Labels: cla-signed

#8041 feat(branching): auto merging skeleton
  backend/api/v1/schema_design_merge.go
  backend/api/v1/schema_design_merge_test.go
  backend/api/v1/schema_design_service.go
Labels: cla-signed

#8048 chore(branching): add rename table function
  frontend/src/components/SchemaDesigner/DatabaseTree.vue
  frontend/src/components/SchemaDesigner/Modals/TableNameModal.vue
Labels: cla-signed

#8046 chore(sql-editor): fix height overflow
  frontend/src/views/sql-editor/SQLEditorPage.vue
Labels: cla-signed

#8049 chore(frontend): skip validateOnly for db group issue preview
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
Labels: cla-signed

#8047 fix(masking): merge masking level
  backend/plugin/db/util/mask_sensitive_data_tidb.go
Labels: cla-signed

#8052 chore: deprecate refresh token
  backend/api/auth/auth.go
  backend/api/auth/header.go
  backend/api/v1/auth_service.go
  backend/legacyapi/setting.go
  backend/server/jwt.go
  backend/server/server.go
  backend/tests/tests.go
Labels: cla-signed

#8051 feat: support deployement config as spec target
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/common/resource_name.go
Labels: cla-signed

#8054 chore: remove grouping from issue payload
  backend/migrator/migration/prod/2.8/0001##remove_grouping_from_issue_payload.sql
  backend/migrator/migrator_test.go
  frontend/src/components/Issue/logic/common.ts
  frontend/src/types/proto/store/issue.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/issue.pb.go
  proto/store/issue.proto
Labels: cla-signed

#8055 chore: rename refresh token duration to token duration
  backend/api/v1/setting_service.go
  backend/migrator/migration/prod/2.8/0002##rename_token_duration.sql
  backend/migrator/migrator_test.go
  backend/server/server.go
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/setting.ts
  frontend/src/views/BannerUpgradeSubscription.vue
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#8057 chore: update deployment config resource name
  backend/api/v1/project_service.go
  backend/common/resource_name.go
  backend/tests/ghost_test.go
  backend/tests/tenant_test.go
  frontend/src/store/modules/v1/deploymentConfig.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/v1/project_service.proto
Labels: cla-signed

#8059 fix(mysql-differ): handle union case in get temporary view
  backend/plugin/parser/sql/differ/mysql/differ.go
  backend/plugin/parser/sql/differ/mysql/table_test.go
Labels: cla-signed

#8060 feat: use v1 selectors in creating database form
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/CreateDatabasePrepForm/DatabaseLabelForm.vue
  frontend/src/components/InstanceRoleSelect.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/components/v2/Select/EnvironmentSelect.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/ExportCenter/index.vue
Labels: cla-signed

#8061 chore: various SQL Editor Style tweak
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/ActionBar.vue
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
  frontend/src/views/sql-editor/SecondarySidebar/HistoryTabPane/HistoryTabPane.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/DatabaseSchema.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/TableSchema.vue
  frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetTabPane.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#8056 chore: print log instead of exit server if init sample data failed
  backend/server/server.go
Labels: cla-signed

#8058 chore: introduce schema diff proto
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#8062 fix: cross issue.visit step in onboarding guide after visiting new issue view
  frontend/src/views/IssueDetailV1.vue
Labels: cla-signed

#8063 chore: use v2 selectors for requesting querier/exporter roles
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/v2/Select/DatabaseSelect.vue
Labels: cla-signed

#8065 fix: cannot show the affected table drawer
  frontend/src/views/ChangeHistoryDetail.vue
Labels: cla-signed

#8067 feat(sql-editor): expand schema and tables in connection tree dynamically
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/store/modules/connectionTree.ts
  frontend/src/types/connectionTree.ts
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
  frontend/src/views/sql-editor/AsidePanel/TreeNode/Prefix.vue
  frontend/src/views/sql-editor/AsidePanel/common.ts
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/SecondarySidebar/InfoTabPane/SchemaPanel/SchemaPanel.vue
  frontend/src/views/sql-editor/SecondarySidebar/SecondaryGutterBar/SecondaryGutterBar.vue
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#8068 chore: deprecate legacy schema diff api
  backend/api/v1/database_service.go
  backend/server/openapi_sql.go
  backend/server/server.go
  backend/tests/sql.go
  backend/tests/sync_schema_test.go
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/components/IssueV1/components/StatementSection/SDLView/useSDLState.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/views/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  proto/v1/database_service.proto
Labels: cla-signed

#8066 chore: use v2 selectors in sync schema
  frontend/src/assets/css/tailwind.css
  frontend/src/bbkit/BBSelect.vue
  frontend/src/components/v2/Select/DatabaseSelect.vue
  frontend/src/views/SyncDatabaseSchema/DatabaseSchemaSelector.vue
Labels: cla-signed

#8069 chore: only show booking demo after quickstart
  frontend/src/components/Quickstart.vue
Labels: cla-signed

#8070 chore: drop deprecated task check run table
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.8/0003##deprecate_task_check_run.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#8071 chore: refactor test
  backend/tests/backup_restore_test.go
  backend/tests/change_history_test.go
  backend/tests/data_source_test.go
  backend/tests/database_edit_test.go
  backend/tests/ghost_test.go
  backend/tests/grouping_change_test.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
Labels: cla-signed

#8072 chore: refactor test
  backend/tests/data_source_test.go
  backend/tests/subscription.go
  backend/tests/subscription_test.go
  backend/tests/tests.go
Labels: cla-signed

#8073 chore: refactor test for project creation
  backend/tests/backup_restore_test.go
  backend/tests/change_history_test.go
  backend/tests/database_edit_test.go
  backend/tests/environment_test.go
  backend/tests/ghost_test.go
  backend/tests/grouping_change_test.go
  backend/tests/issue.go
  backend/tests/project.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sheet_vcs_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tests.go
Labels: cla-signed
