Repository bytebase/bytebase, pull requests merged in 2023-03, with the labels that each got.

#4907 feat: syntax checker checks SDL format for SDL issue
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/mysql/advisor_syntax.go
  backend/plugin/parser/transform/mysql/transform.go
  backend/plugin/parser/transform/transform.go
  backend/plugin/parser/utils.go
  backend/runner/taskcheck/statement_advisor_simple_executor.go
  backend/store/task.go
Labels: cla-signed

#4923 chore: add oracle/redis proto
  backend/api/v1/common.go
  backend/plugin/db/driver.go
  backend/plugin/db/spanner/migrate.go
  backend/plugin/db/util/driverutil.go
  backend/runner/anomaly/scanner.go
  backend/runner/backuprun/runner.go
  backend/server/issue.go
  frontend/src/types/proto/v1/common.ts
  proto/generated-go/v1/common.pb.go
  proto/v1/common.proto
Labels: cla-signed

#4928 fix(frontend): hide db name template when not needed
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
Labels: cla-signed, backport release/1.13.0

#4913 feat(frontend): two-phases editing for sql-review policy
  frontend/src/components/SQLReview/SQLReviewPreview.vue
  frontend/src/components/SQLReview/components/useSQLRuleFilter.ts
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#4927 chore: add proto markdown docs
  proto/buf.gen.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
Labels: cla-signed

#4922 feat(frontend): support custom sql review rule description
  frontend/src/components/Issue/TaskCheckBar.vue
  frontend/src/components/Issue/TaskCheckRunPanel.vue
  frontend/src/components/SQLReview/SQLReviewConfig.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
  frontend/src/components/SQLReview/components/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlReview.ts
  frontend/src/types/policy.ts
  frontend/src/types/sqlReview.ts
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#4932 fix(sql-editor): admin mode result table layout
  frontend/src/views/sql-editor/EditorCommon/TableView.vue
Labels: cla-signed

#4936 fix: update random logic in resource id field
  frontend/src/components/ResourceIdField.vue
Labels: cla-signed

#4935 perf: using cache
  backend/runner/taskrun/database_backup_executor.go
  backend/server/issue.go
  backend/server/server.go
  backend/store/database.go
Labels: cla-signed, backport release/1.13.0

#4938 perf: use environment ID cache
  backend/store/environment.go
Labels: cla-signed, backport release/1.13.0

#4942 fix(frontend): use case of currentUser.id
  frontend/src/store/modules/activity.ts
  frontend/src/store/modules/sheet.ts
Labels: cla-signed

#4933 chore: oracle plugin skeleton
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/oracle_migration_schema.sql
  backend/plugin/db/oracle/role.go
  backend/plugin/db/oracle/sync.go
Labels: cla-signed

#4945 feat(frontend): display error lines for SDL syntax checks
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
Labels: cla-signed

#4946 chore: don't show not found database in schema editor
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/views/DatabaseDetail.vue
Labels: cla-signed

#4948 feat(frontend): support custom sql review rule description (cherry-pick #4922)
  frontend/src/components/Issue/TaskCheckBar.vue
  frontend/src/components/Issue/TaskCheckRunPanel.vue
  frontend/src/components/SQLReview/SQLReviewConfig.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
  frontend/src/components/SQLReview/components/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlReview.ts
  frontend/src/types/policy.ts
  frontend/src/types/sqlReview.ts
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#4949 feat(sql-editor): press up/down arrow keys to walk through history items
  frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
Labels: cla-signed

#4931 feat(api): implement the anomaly service
  backend/api/v1/anomaly_service.go
  backend/api/v1/common.go
  backend/api/v1/common_test.go
  backend/server/server.go
  backend/store/anomaly.go
  frontend/src/types/proto/v1/anomaly_service.ts
  proto/generated-go/v1/anomaly_service.pb.go
  proto/v1/anomaly_service.proto
Labels: cla-signed

#4941 chore: put external-url and disallow-signup flag into setting store
  backend/api/v1/auth_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/setting_service.go
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/bin/server/cmd/root_test.go
  backend/component/activity/manager.go
  backend/component/config/profile.go
  backend/legacyapi/setting.go
  backend/runner/apprun/runner.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/server/actuator.go
  backend/server/auth.go
  backend/server/oauth.go
  backend/server/project.go
  backend/server/project_webhook.go
  backend/server/server.go
  backend/server/setting.go
  backend/server/webhook.go
  backend/store/setting.go
  backend/utils/utils.go
  backend/utils/utils_test.go
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/setting.pb.go
  proto/store/setting.proto
Labels: cla-signed

#4944 fix: skip not found db in task generation
  backend/utils/utils.go
Labels: cla-signed

#4954 feat: introduce --saas flag
  backend/api/v1/actuator_service.go
  backend/api/v1/setting_service.go
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/common/util.go
  backend/common/util_test.go
  backend/component/config/profile.go
  backend/legacyapi/actuator.go
  backend/server/actuator.go
  backend/server/project.go
  backend/server/server.go
  backend/server/server_frontend_embed.go
  backend/server/setting.go
  backend/utils/utils.go
  backend/utils/utils_test.go
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/plugins/demo/index.ts
  frontend/src/store/modules/actuator.ts
  frontend/src/types/actuator.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/views/SettingWorkspaceGeneral.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/actuator_service_grpc.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#4955 feat(transform): add normalize for transformer
  backend/plugin/parser/transform/mysql/transform.go
  backend/plugin/parser/transform/mysql/transform_test.go
  backend/plugin/parser/transform/transform.go
Labels: cla-signed

#4953 feat(sql-editor): optimize result display
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/sql.ts
  frontend/src/store/modules/sqlEditor.ts
  frontend/src/types/tab.ts
  frontend/src/types/webTerminal.ts
  frontend/src/views/sql-editor/EditorCommon/TableView.vue
  frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#4950 chore: tweak error message when archiving instance whose databases haven't been assigned
  backend/server/instance.go
Labels: cla-signed

#4957 chore: rename bb.workspace.general to bb.workspace.profile
  backend/api/v1/setting_service.go
  backend/component/config/profile.go
  backend/legacyapi/setting.go
  backend/server/server.go
  backend/server/setting.go
  backend/store/setting.go
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/store/modules/setting.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/types/setting.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/actuator_service.pb.go
  proto/store/setting.proto
Labels: cla-signed

#4958 chore: introduce LastActiveTime in actuator
  backend/api/auth/config.go
  backend/api/v1/actuator_service.go
  backend/bin/server/cmd/profile.go
  backend/component/config/profile.go
  backend/server/acl.go
  backend/server/server.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#4959 chore(frontend): don't stop tab focus on the link on the sign-in page
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#4961 fix(frontend): update numbers in filter while editing
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#4960 chore: use environment resource ID for writeback file name
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#4965 fix: spanner proto def
  backend/api/v1/common.go
  frontend/src/types/proto/v1/common.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/common.pb.go
  proto/v1/common.proto
Labels: cla-signed

#4966 fix: typo
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#4963 feat(frontend): show the status of rollbackByIssue
  frontend/src/components/Issue/rollback/RollbackStatus.vue
Labels: cla-signed

#4969 feat: add `mfa_config` fields to principal table
  backend/store/migration/dev/20230303000000##principal_mfa_config.sql
  backend/store/migration/dev/LATEST.sql
Labels: cla-signed

#4975 chore: remove idp fields for principal table
  backend/store/migration/dev/20230303000001##remove_idp_fields_in_principal.sql
  backend/store/migration/dev/LATEST.sql
Labels: cla-signed

#4971 chore(frontend): normalize engines' languages and sql dialects
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/components/Issue/logic/common.ts
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/components/MonacoEditor/sqlFormatter.ts
  frontend/src/components/SyncDatabaseSchemaPrepForm.vue
  frontend/src/plugins/sql-lsp/server/complete/index.ts
  frontend/src/plugins/sql-lsp/server/complete/utils/common.ts
  frontend/src/plugins/sql-lsp/server/complete/utils/parser-helper.ts
  frontend/src/plugins/sql-lsp/server/server.ts
  frontend/src/plugins/sql-lsp/types/sql.ts
  frontend/src/types/sqlEditor.ts
  frontend/src/utils/instance.ts
  frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
  frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
Labels: cla-signed

#4972 chore: show a button in trialing modal
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/Home.vue
Labels: cla-signed

#4970 fix: should use protojson instead of json
  backend/api/v1/setting_service.go
  backend/server/project.go
  backend/server/server.go
  backend/server/setting.go
  backend/store/setting.go
  backend/tests/tests.go
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
Labels: cla-signed

#4976 fix: 🔥mongo&spanner have no sql.db
  backend/server/sql.go
Labels: cla-signed, backport release/1.13.0

#4968 refactor(sql-editor): dialect-based keywords provider
  frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
  frontend/src/plugins/sql-lsp/server/complete/candidates/createKeywordCandidates.ts
  frontend/src/plugins/sql-lsp/server/complete/candidates/keywords/common.ts
  frontend/src/plugins/sql-lsp/server/complete/candidates/keywords/index.ts
  frontend/src/plugins/sql-lsp/server/complete/index.ts
  frontend/src/plugins/sql-lsp/server/server.ts
Labels: cla-signed

#4982 fix: refresh user after update
  frontend/src/store/modules/principal.ts
  frontend/src/store/modules/user.ts
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#4981 feat: update principal store with `MFAConfig`
  backend/store/principal.go
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/user.pb.go
  proto/store/user.proto
Labels: cla-signed

#4978 chore: add AuthorName and AuthorEmail for GitOps
  backend/plugin/vcs/github/github.go
  backend/plugin/vcs/github/github_test.go
  backend/plugin/vcs/gitlab/gitlab.go
  backend/plugin/vcs/vcs.go
  backend/runner/taskrun/executor.go
  backend/server/webhook.go
Labels: cla-signed

#4967 feat: add /v1/sql/pretty API to improve SDL task differ display
  backend/api/v1/sql_service.go
  backend/server/server.go
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/grpcweb/index.ts
  frontend/src/types/instance.ts
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#4986 chore: generate user store proto to TypeScript
  frontend/src/types/proto/store/user.ts
Labels: cla-signed

#4984 fix: create user type
  backend/api/v1/auth_service.go
Labels: cla-signed

#4985 chore: add empty line after SDL statements and SET statements
  backend/plugin/parser/differ/mysql/differ.go
  backend/plugin/parser/transform/mysql/transform.go
  backend/plugin/parser/transform/mysql/transform_test.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#4855 feat(vcs): implement core VCS logic for Bitbucket Cloud
  backend/plugin/vcs/bitbucket/bitbucket.go
  backend/plugin/vcs/bitbucket/bitbucket_test.go
  backend/plugin/vcs/github/github.go
  backend/plugin/vcs/vcs.go
Labels: cla-signed

#4973 feat: implement time-based OTP secret generator
  backend/plugin/mfa/otp/otp.go
  backend/plugin/mfa/otp/otp_test.go
  go.mod
  go.sum
Labels: cla-signed

#4987 feat: support SDL mode SQL review
  backend/runner/taskcheck/statement_advisor_composite_executor.go
  backend/server/openapi_sql.go
  backend/server/sql.go
  backend/server/webhook.go
  backend/store/catalog.go
Labels: cla-signed

#4989 chore: update for saas
  backend/api/v1/auth_service.go
  backend/store/setting.go
Labels: cla-signed

#4701 feat(frontend): improve UX for creating database with tenant database name template
  frontend/src/bbkit/BBTextField.vue
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/CreateDatabasePrepForm/DatabaseLabelForm.vue
  frontend/src/components/CreateDatabasePrepForm/DatabaseNameTemplateTips.vue
  frontend/src/components/CreateDatabasePrepForm/index.ts
  frontend/src/components/CreateDatabasePrepForm/logic.ts
  frontend/src/components/DatabaseDetail/CreatePITRDatabaseForm.vue
  frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/deployment.ts
  frontend/src/utils/label.ts
Labels: cla-signed

#4990 fix(sql-editor): use resourceId as selector key
  frontend/src/views/SheetDashboard.vue
Labels: cla-signed

#4993 chore: clone deep data source object in reference
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#4974 feat(api): implement the proto definition of the webhook part of the project service
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#4994 feat: support SDL for tenant mode GitOps
  backend/server/webhook.go
Labels: cla-signed

#4991 chore(store): moving data source option to proto in store
  backend/legacyapi/data_source.go
  backend/store/data_source.go
  frontend/src/types/proto/store/data_source.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/data_source.pb.go
  proto/store/data_source.proto
Labels: cla-signed

#4988 feat: update login api with MFA
  backend/api/v1/auth_service.go
  frontend/src/types/proto/v1/auth_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#4997 fix: typo
  backend/store/migration/prod/1.13/0001##add_instance_engine_redis_oracle.sql
  docs/api-style-guide.md
  docs/testing.md
Labels: cla-signed

#4995 feat(api): implement project webhook service
  backend/api/v1/project_service.go
  backend/component/activity/manager.go
  backend/legacyapi/project_webhook.go
  backend/legacyapi/slug.go
  backend/server/project_webhook.go
  backend/store/project.go
  backend/store/project_webhook.go
Labels: cla-signed

#4999 fix(connection): using instanceId instead of id
  backend/legacyapi/data_source.go
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#5000 chore(store): migrate anomaly legacy store to v1 store
  backend/api/v1/anomaly_service.go
  backend/legacyapi/anomaly.go
  backend/runner/anomaly/scanner.go
  backend/runner/taskrun/executor.go
  backend/server/anomaly.go
  backend/store/anomaly.go
  frontend/src/components/AnomalyTable.vue
Labels: cla-signed

#4998 feat: implement update user api for MFA
  backend/api/v1/auth_service.go
  backend/plugin/mfa/otp/otp.go
  backend/plugin/mfa/otp/otp_test.go
  backend/store/principal.go
  frontend/src/types/proto/store/user.ts
  frontend/src/types/proto/v1/auth_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/user.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/store/user.proto
  proto/v1/auth_service.proto
Labels: cla-signed

#5001 feat(store): instance change history
  backend/plugin/db/driver.go
  backend/runner/taskrun/executor.go
  backend/store/instance_change_history.go
Labels: cla-signed

#5002 feat: add skeleton for 2FA setup page
  frontend/src/components/ProfileDropdown.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed

#5004 fix(differ): improve MySQL DDL safe order
  backend/plugin/parser/differ/mysql/column_test.go
  backend/plugin/parser/differ/mysql/differ.go
  backend/plugin/parser/differ/mysql/table_test.go
Labels: cla-signed

#4980 feat(api): implement the external vcs service proto definition
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service_grpc.pb.go
  proto/generated-go/v1/anomaly_service_grpc.pb.go
  proto/generated-go/v1/auth_service_grpc.pb.go
  proto/generated-go/v1/bookmark_service_grpc.pb.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/generated-go/v1/environment_service_grpc.pb.go
  proto/generated-go/v1/externalvs_service.pb.go
  proto/generated-go/v1/externalvs_service.pb.gw.go
  proto/generated-go/v1/externalvs_service_grpc.pb.go
  proto/generated-go/v1/idp_service_grpc.pb.go
  proto/generated-go/v1/instance_role_service_grpc.pb.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/generated-go/v1/org_policy_service_grpc.pb.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/generated-go/v1/setting_service_grpc.pb.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/v1/externalvs_service.proto
Labels: cla-signed

#5005 feat(frontend): VCS configuration minor improvements and bugfixes
  frontend/src/components/ProjectGeneralSettingPanel.vue
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/VCSProviderBasicInfoPanel.vue
Labels: cla-signed

#5003 feat(sql-editor): text-to-sql demo
  backend/api/v1/setting_service.go
  backend/legacyapi/setting.go
  backend/server/server.go
  backend/server/setting.go
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/bbkit/BBSpin.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/AIDialog.vue
  frontend/src/plugins/ai/components/AIPromptButton.vue
  frontend/src/plugins/ai/components/ChatView/AIMessageView.vue
  frontend/src/plugins/ai/components/ChatView/ChatView.vue
  frontend/src/plugins/ai/components/ChatView/CodeView.vue
  frontend/src/plugins/ai/components/ChatView/PresetSuggestions.vue
  frontend/src/plugins/ai/components/ChatView/UserMessageView.vue
  frontend/src/plugins/ai/components/ChatView/index.ts
  frontend/src/plugins/ai/components/ConversationList.vue
  frontend/src/plugins/ai/components/ConversationRenameDialog.vue
  frontend/src/plugins/ai/components/PromptInput.vue
  frontend/src/plugins/ai/index.ts
  frontend/src/plugins/ai/logic/context.ts
  frontend/src/plugins/ai/logic/index.ts
  frontend/src/plugins/ai/store/conversation.ts
  frontend/src/plugins/ai/store/index.ts
  frontend/src/plugins/ai/types/context.ts
  frontend/src/plugins/ai/types/conversation.ts
  frontend/src/plugins/ai/types/index.ts
  frontend/src/plugins/ai/types/openai.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/dbSchema.ts
  frontend/src/types/setting.ts
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#5006 feat(frontend): improve SDL issue display
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/main.ts
  frontend/src/plugins/silent-request.ts
Labels: cla-signed

#5011 chore: fix connection content
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#5012 chore(catalog): check default value with column type in walk through for MySQL
  backend/plugin/advisor/catalog/test/mysql_walk_through.yaml
  backend/plugin/advisor/catalog/walk_through.go
Labels: cla-signed

#5009 feat(frontend): add activities when turned on/off sql rollback log
  frontend/src/components/Issue/rollback/common.ts
Labels: cla-signed

#5013 feat: challenge MFA when signin
  backend/api/v1/auth_service.go
  backend/store/principal.go
  frontend/src/components/MFAChallengeModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/user.ts
  frontend/src/types/index.ts
  frontend/src/types/mfa.ts
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#5016 fix: several fix
  .github/workflows/build-push-ci-image.yml
  backend/server/auth.go
  backend/server/principal.go
Labels: cla-signed

#5017 chore(sql-editor): better handling for critical errors
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/plugins/silent-request.ts
  frontend/src/views/sql-editor/EditorCommon/TableView.vue
Labels: cla-signed

#5018 chore(frontend): add a required star to "Schema path template" for SDL projects
  frontend/src/components/RepositoryForm.vue
Labels: cla-signed

#5019 chore(frontend): adjust the scrollable area of sidebar
  frontend/src/layouts/BodyLayout.vue
  frontend/src/views/DashboardSidebar.vue
Labels: cla-signed

#5007 feat: redis
  backend/plugin/db/driver.go
  backend/plugin/db/redis/migrate.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redis/role.go
  backend/plugin/db/redis/sync.go
  backend/runner/anomaly/scanner.go
  backend/runner/backuprun/runner.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/server/instance.go
  backend/server/server.go
  backend/server/sql.go
  backend/store/instance_change_history.go
  backend/utils/utils.go
  frontend/src/assets/db-redis.png
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/CreateDataSourceExample.vue
  frontend/src/components/DatabaseMigrationHistoryPanel.vue
  frontend/src/components/DatabaseName.vue
  frontend/src/components/DatabaseOverviewPanel.vue
  frontend/src/components/DatabaseTable.vue
  frontend/src/components/InstanceEngineIcon.vue
  frontend/src/components/InstanceForm.vue
  frontend/src/types/instance.ts
  frontend/src/types/sqlEditor.ts
  frontend/src/utils/instance.ts
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/sql-editor/EditorCommon/DataTable.vue
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/TerminalPanel/CompactSQLEditor.vue
  go.mod
  go.sum
Labels: cla-signed

#5010 feat(api): add some endpoints for external version control service
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/externalvs_service.pb.go
  proto/generated-go/v1/externalvs_service.pb.gw.go
  proto/generated-go/v1/externalvs_service_grpc.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/v1/externalvs_service.proto
  proto/v1/project_service.proto
Labels: cla-signed

#5014 fix: generate correct commit link for GitHub.com
  backend/plugin/vcs/github/github.go
  backend/plugin/vcs/github/github_test.go
  backend/plugin/vcs/vcs.go
  backend/runner/taskrun/executor.go
  backend/server/project.go
  frontend/src/components/Issue/IssueActivityPanel.vue
Labels: cla-signed

#5021 feat(frontend): redis shouldn't have "Create database"
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/InstanceSelect.vue
  frontend/src/utils/instance.ts
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#5022 chore: introduce sid and service name for Oracle
  backend/legacyapi/data_source.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/oracle/oracle_migration_schema.sql
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/store/database.pb.go
  proto/generated-go/store/idp.pb.go
  proto/generated-go/store/setting.pb.go
  proto/generated-go/store/user.pb.go
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/bookmark_service.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/deployment.pb.go
  proto/generated-go/v1/environment_service.pb.go
  proto/generated-go/v1/externalvs_service.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/store/data_source.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#5020 feat(sql-editor): detect DML/DDL when there are multiple statements
  frontend/src/components/MonacoEditor/sqlParser.ts
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
Labels: cla-signed

#5026 chore(frontend): add beta badge for redis instance creation
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#5027 fix: sql in instance change history
  backend/store/instance_change_history.go
Labels: cla-signed

#5024 chore: remove release guards for 2FA
  backend/store/migration/prod/1.14/0001##principal_mfa_config.sql
  backend/store/migration/prod/1.14/0002##remove_idp_fields_in_principal.sql
  backend/store/migration/prod/LATEST.sql
  backend/store/pg_engine_test.go
  backend/store/principal.go
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#5028 chore: populate sid and service name
  backend/api/v1/instance_service.go
  backend/component/dbfactory/dbfactory.go
  backend/legacyapi/data_source.go
  backend/legacyapi/instance.go
  backend/legacyapi/sql.go
  backend/plugin/db/driver.go
  backend/server/database.go
  backend/server/instance.go
  backend/server/sql.go
  backend/store/data_source.go
  backend/store/instance.go
Labels: cla-signed

#5031 fix: use silence request for github api
  frontend/src/store/modules/actuator.ts
Labels: cla-signed

#5023 feat: implement 2FA setup UI
  backend/api/v1/auth_service.go
  backend/legacyapi/plan.go
  backend/server/server.go
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/bbkit/BBModal.vue
  frontend/src/components/FeatureModal.vue
  frontend/src/components/RecoveryCodesView.vue
  frontend/src/components/RegenerateRecoveryCodesView.vue
  frontend/src/components/SchemaEditor/Modals/ActionConfirmModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed

#5030 feat: backfill instance change history
  backend/server/server.go
  backend/store/instance_change_history.go
Labels: cla-signed

#5035 chore(ci): show more issues of golangci-lint
  .github/workflows/backend-tests.yml
Labels: cla-signed

#5033 chore: update agent setting
  backend/enterprise/config/config.go
  backend/enterprise/config/config_dev.go
  backend/enterprise/config/config_release.go
  backend/enterprise/service/provider.go
  backend/legacyapi/setting.go
  frontend/src/plugins/ai/components/AIPromptButton.vue
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/setting.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/setting.pb.go
  proto/store/setting.proto
Labels: cla-signed

#5032 feat(api): implement external version control service PART I
  backend/api/v1/common.go
  backend/api/v1/externalvs_service.go
  backend/server/server.go
  backend/store/vcs.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/externalvs_service.pb.go
  proto/v1/externalvs_service.proto
Labels: cla-signed

#5025 feat(sql-editor): support multiple query results for admin mode
  frontend/naive-ui.config.ts
  frontend/src/store/modules/sql.ts
  frontend/src/types/sql.ts
  frontend/src/types/tab.ts
  frontend/src/utils/instance.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/index.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/EmptyView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/index.ts
  frontend/src/views/sql-editor/EditorCommon/TableView.vue
  frontend/src/views/sql-editor/EditorCommon/index.ts
  frontend/src/views/sql-editor/ResultPanel/ResultPanel.vue
  frontend/src/views/sql-editor/ResultPanel/index.ts
  frontend/src/views/sql-editor/SQLEditorPage.vue
  frontend/src/views/sql-editor/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#5036 feat: ping Oracle database
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/role.go
  backend/plugin/db/oracle/sync.go
  backend/server/server.go
  frontend/src/components/InstanceForm/OracleSIDAndServiceNameInput.vue
  go.mod
  go.sum
Labels: cla-signed

#5037 fix(frontend): hide tooltip for empty engine versions
  frontend/src/components/InstanceEngineIcon.vue
Labels: cla-signed

#5039 feat(sql-editor): disable schema panel for redis
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
Labels: cla-signed

#5038 feat: support Oracle read-only query
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/util/driverutil.go
  backend/runner/anomaly/scanner.go
  backend/server/sql.go
Labels: cla-signed

#5041 feat: disable database creation for Oracle
  backend/runner/taskrun/database_create_executor.go
  backend/server/issue.go
Labels: cla-signed

#5045 fix: update template fields when changing SSO type
  frontend/src/components/IdentityProviderCreateForm.vue
Labels: cla-signed

#5046 chore: increase test timeout
  .github/workflows/backend-tests.yml
Labels: cla-signed

#5043 chore: remove VCS login related APIs
  backend/server/auth.go
  backend/server/principal.go
  backend/server/server.go
Labels: cla-signed

#5042 fix: backfill instance change history
  backend/server/server.go
Labels: cla-signed

#5044 feat: the proto definition of logging service
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/v1/logging_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/logging_service.pb.go
  proto/generated-go/v1/logging_service.pb.gw.go
  proto/generated-go/v1/logging_service_grpc.pb.go
  proto/v1/logging_service.proto
Labels: cla-signed

#5048 chore: upgrade proto version
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/anomaly_service.pb.gw.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/generated-go/v1/bookmark_service.pb.gw.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/externalvs_service.pb.gw.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/logging_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/setting_service.pb.gw.go
  proto/generated-go/v1/sql_service.pb.gw.go
Labels: cla-signed

#5051 fix: spanner find migration history list query sql
  backend/plugin/db/spanner/migrate.go
Labels: cla-signed

#5050 fix: stored version
  backend/server/server.go
Labels: cla-signed

#5049 fix: redis json marshal cannot handle map[any]any
  backend/plugin/db/redis/redis.go
Labels: cla-signed

#5052 chore: skip instance change backfill for schemaless or new types of databases
  backend/runner/taskrun/executor.go
  backend/server/instance.go
  backend/server/server.go
  backend/utils/utils.go
Labels: cla-signed

#5054 feat: support Oracle DDL/DML
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#5053 chore: hide 2FA config for others
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#5055 chore: ignore redundant column collate and table options in normalize and differ
  backend/plugin/parser/differ/mysql/column_test.go
  backend/plugin/parser/differ/mysql/differ.go
  backend/plugin/parser/differ/mysql/table_test.go
  backend/plugin/parser/transform/mysql/transform.go
  backend/plugin/parser/transform/mysql/transform_test.go
Labels: cla-signed

#5056 chore: early return on redis creating db
  backend/runner/taskrun/database_create_executor.go
Labels: cla-signed

#5058 chore: ignore DEFAULT NULL in normalize
  backend/plugin/parser/transform/mysql/transform.go
  backend/plugin/parser/transform/mysql/transform_test.go
Labels: cla-signed

#5057 chore: migrate spanner to instance change history
  backend/plugin/db/spanner/migrate.go
  backend/plugin/db/spanner/spanner.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/store/pg_engine.go
  backend/utils/utils.go
Labels: cla-signed

#5059 feat: return MFA temp token when MFA enabled
  backend/api/auth/auth.go
  backend/api/v1/auth_service.go
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/auth.ts
  frontend/src/types/mfa.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/views/auth/MultiFactor.vue
  frontend/src/views/auth/Signin.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/v1/auth_service.proto
Labels: cla-signed

#5061 feat(sql-editor): chat-to-sql demo v2
  backend/legacyapi/plan.go
  frontend/src/bbkit/BBTextField.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/AIChatToSQL.vue
  frontend/src/plugins/ai/components/AIPromptButton.vue
  frontend/src/plugins/ai/components/ActionBar.vue
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/ChatView/AIMessageView.vue
  frontend/src/plugins/ai/components/ChatView/ChatView.vue
  frontend/src/plugins/ai/components/ChatView/CodeView.vue
  frontend/src/plugins/ai/components/ChatView/EmptyView.vue
  frontend/src/plugins/ai/components/ChatView/context.ts
  frontend/src/plugins/ai/components/ChatView/types.ts
  frontend/src/plugins/ai/components/HistoryPanel/ConversationList.vue
  frontend/src/plugins/ai/components/HistoryPanel/ConversationRenameDialog.vue
  frontend/src/plugins/ai/components/HistoryPanel/HistoryPanel.vue
  frontend/src/plugins/ai/components/HistoryPanel/index.ts
  frontend/src/plugins/ai/components/PromptInput.vue
  frontend/src/plugins/ai/index.ts
  frontend/src/plugins/ai/logic/index.ts
  frontend/src/plugins/ai/logic/useChatByTab.ts
  frontend/src/plugins/ai/logic/utils.ts
  frontend/src/plugins/ai/store/conversation.ts
  frontend/src/plugins/ai/types/context.ts
  frontend/src/plugins/ai/types/conversation.ts
  frontend/src/store/modules/tab.ts
  frontend/src/types/plan.ts
  frontend/src/types/tab.ts
  frontend/src/utils/tab.ts
  frontend/src/views/SettingWorkspaceGeneral.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
Labels: cla-signed

#5060 chore: instance change history drop instance_id not null constraint
  backend/plugin/db/driver.go
  backend/runner/taskrun/executor.go
  backend/server/instance.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/migration/dev/LATEST.sql
  backend/store/migration/prod/1.14/0000##add_instance_change_history.sql
  backend/store/migration/prod/LATEST.sql
  backend/utils/utils.go
Labels: cla-signed

#5062 chore: beautify home layout
  frontend/src/components/Issue/IssueTable.vue
  frontend/src/components/QuickActionPanel.vue
Labels: cla-signed

#5063 chore: wording change for ChatSQL
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5064 fix(api): find webhook
  backend/server/project_webhook.go
  backend/store/project_webhook.go
Labels: cla-signed

#5066 feat: put setting items into separate groups
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingSidebar.vue
Labels: cla-signed

#5067 feat: sync oracle database tables
  backend/plugin/db/driver.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#5070 chore(frontend): allow editing while a sql review rule is disabled
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
Labels: cla-signed

#5069 feat(frontend): feature guard for AI Augmentation configuration
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5072 fix: refresh current user
  frontend/src/store/modules/auth.ts
Labels: cla-signed

#5071 chore: use redirect instead of open a new window when sign in with SSO
  frontend/src/components/SchemaEditor/Modals/ActionConfirmModal.vue
  frontend/src/utils/sso.ts
  frontend/src/views/OAuthCallback.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#5073 feat: support Oracle multi-statements
  backend/plugin/db/oracle/oracle.go
  backend/plugin/parser/parser.go
  backend/plugin/parser/utils.go
  backend/server/sql.go
Labels: cla-signed

#5074 fix: instance change history, use rows.Err
  backend/store/instance_change_history.go
Labels: cla-signed

#5075 chore: allow user sign in with SSO after license expired
  backend/api/v1/auth_service.go
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#5076 fix: should use stored version when listing migration history
  backend/utils/utils.go
Labels: cla-signed

#5077 chore(2fa): update user doc link
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/TwoFactorSetup.vue
  frontend/src/views/auth/MultiFactor.vue
Labels: cla-signed

#5080 chore: bump version to 1.14.0
  scripts/VERSION
Labels: cla-signed

#5079 feat(sql-editor): ai-generated tips for chat-to-sql
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/ChatView/ChatView.vue
  frontend/src/plugins/ai/components/ChatView/PresetSuggestions.vue
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
  frontend/src/plugins/ai/logic/index.ts
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/plugins/ai/logic/utils.ts
Labels: cla-signed

#5082 chore: use ENV_ID instead of ENV_NAME for git file path
  backend/legacyapi/project.go
  backend/legacyapi/project_test.go
  backend/plugin/db/driver.go
  backend/plugin/db/driver_test.go
  backend/plugin/vcs/vcs_test.go
  backend/runner/taskrun/executor.go
  backend/server/project.go
  backend/server/sheet.go
  backend/server/sheet_test.go
  backend/store/demo/default/10180##repository.sql
  backend/tests/schema_update_test.go
  backend/tests/sheet_vcs_test.go
  docs/design/gh-ost-integration.md
  docs/design/tenancy.md
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/repository.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/externalvs_service.pb.go
  proto/v1/externalvs_service.proto
Labels: cla-signed

#5084 fix: upsert the external url
  backend/server/server.go
Labels: cla-signed

#5086 chore: backfill from ENV_NAME to ENV_ID
  backend/server/webhook.go
  backend/store/migration/prod/1.14/003##update_env_id.sql
  backend/store/pg_engine_test.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#5088 fix: sql review ci failure with embed frontend
  backend/server/skipper.go
  backend/server/webhook.go
Labels: cla-signed

#5090 fix: should return warning if sql review failed
  backend/server/webhook.go
Labels: cla-signed, backport release/1.14.0

#5083 feat(frontend): add tips for redis create user example
  frontend/src/components/CreateDataSourceExample.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5091 feat: define custom approval feature
  backend/legacyapi/plan.go
  frontend/src/types/plan.ts
Labels: cla-signed

#5092 chore(2fa): display secret modal
  frontend/src/components/TwoFactorSecretModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed

#5095 chore: update margin of `BBStepTab`
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/VCSSetupWizard.vue
Labels: cla-signed

#5094 feat(frontend): support multiple line for SQLRuleEditDialog
  frontend/src/components/SQLReview/components/SQLRuleEditDialog.vue
  frontend/src/components/misc/AutoHeightTextarea.vue
  frontend/src/composables/useVModel.ts
  frontend/src/utils/util.ts
Labels: cla-signed

#5098 chore: minor tweak ChatSQL UX
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
Labels: cla-signed

#5097 fix(frontend): replace placeholders in example
  frontend/src/components/RepositoryForm.vue
Labels: cla-signed

#5081 feat: migrate driverutil to instace change history
  backend/legacyapi/instance.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/sqlite/migrate.go
  backend/runner/anomaly/scanner.go
  backend/runner/backuprun/runner.go
  backend/runner/rollbackrun/runner.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskcheck/migration_schema_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/server/instance.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/pg_engine.go
  backend/store/pg_engine_test.go
  backend/utils/utils.go
Labels: cla-signed, backport release/1.14.0

#5103 chore: add `@click.stop` to inbox item
  frontend/src/components/InboxList.vue
Labels: cla-signed

#5102 cherrypick: feat: migrate driverutil to instace change history (#5081)
  backend/legacyapi/instance.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/sqlite/migrate.go
  backend/runner/anomaly/scanner.go
  backend/runner/backuprun/runner.go
  backend/runner/rollbackrun/runner.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskcheck/migration_schema_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/server/instance.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/pg_engine.go
  backend/store/pg_engine_test.go
  backend/utils/utils.go
Labels: cla-signed

#5106 chore: don't get db count if we know that it's cluster mode
  backend/plugin/db/redis/sync.go
Labels: cla-signed

#5107 fix: regenerate `auth_service.proto`
  proto/generated-go/v1/auth_service.pb.gw.go
Labels: cla-signed
