Repository bytebase/bytebase, pull requests merged in 2023-12, with the labels that each got.

#9632 fix: href url in the project sidebar
  frontend/src/components/CommonSidebar.vue
  frontend/src/components/Project/ProjectSidebar.vue
Labels: cla-signed

#9635 refactor: using closure
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#9638 feat(LSP): enable OB
  backend/plugin/parser/mysql/completion.go
Labels: cla-signed

#9637 chore: add precreate issue org policy definition
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#9643 chore: use upper case for AUTO_INCREMENT
  backend/api/v1/schema_design_transformer.go
  backend/api/v1/testdata/design.yaml
  backend/api/v1/testdata/schema.yaml
  backend/plugin/db/mysql/sync.go
Labels: cla-signed

#9642 chore: update sql query error message
  backend/api/v1/sql_service.go
Labels: cla-signed

#9646 chore: deprecate the tooltip-wrapper
  frontend/src/assets/css/tailwind.css
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
  frontend/src/components/AuditLog/AuditLogTable.vue
  frontend/src/components/DatabaseDetail/SQLEditorButton.vue
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/DatabaseDetail/index.ts
  frontend/src/components/DebugLog/DebugLogTable.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/components/InputWithTemplate/InputWithTemplate.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/index.ts
  frontend/src/components/IssueV1/components/StageSection/Actions/RollbackSection/RollbackStatus.vue
  frontend/src/components/PricingTable/FeatureItem.vue
  frontend/src/components/User/Settings/UserTable.vue
  frontend/src/components/v2/Model/DatabaseV1Table/ProjectCol.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#9647 chore: migrate to yaml v3
  backend/plugin/parser/base/span.go
  backend/plugin/parser/pg/v2/query_span_test.go
  backend/plugin/parser/pg/v2/testdata/query_span.yaml
  backend/plugin/parser/tsql/batch/batch_test.go
  go.mod
Labels: cla-signed

#9650 chore: branch branch service
  backend/api/v1/branch_service.go
Labels: cla-signed

#9651 chore: update org policy service
  backend/api/v1/org_policy_service.go
  backend/legacyapi/policy.go
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#9652 chore(frontend): re-invent instance scan interval input
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9653 chore(frontend): add restrict issue creation setting
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9654 chore: use upper case AUTO_INCREMENT for tidb
  backend/api/v1/schema_design_transformer_tidb.go
  backend/api/v1/testdata/tidb/design.yaml
Labels: cla-signed

#9655 chore: branch store fix
  backend/api/v1/branch_service.go
  backend/store/branch.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/branch.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/branch.pb.go
  proto/store/branch.proto
Labels: cla-signed

#9656 chore: use default restore flag with lowercase keyword
  backend/api/v1/schema_design_transformer_tidb.go
Labels: cla-signed

#9658 chore: update sidebar
  frontend/src/components/CommonSidebar.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
Labels: cla-signed

#9659 chore: get branch
  backend/api/v1/branch_service.go
  backend/api/v1/database_service.go
  backend/common/resource_name.go
  backend/store/branch.go
Labels: cla-signed

#9661 chore: remove history from branch
  backend/api/v1/schema_design_service.go
  backend/demo/data/next/dump.sql
  frontend/src/components/Branch/BaselineSchemaSelector.vue
  frontend/src/components/Branch/BranchBaseline.vue
  frontend/src/components/Branch/BranchDataTable.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Changelist/ChangelistDetail/BranchDetailPanel/BranchBaseline.vue
  frontend/src/store/modules/schemaDesign.ts
  frontend/src/types/proto/store/sheet.ts
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/sheet.pb.go
  proto/generated-go/v1/schema_design_service.pb.go
  proto/store/sheet.proto
  proto/v1/schema_design_service.proto
Labels: cla-signed

#9662 chore: deprecate unused parst schema string method
  backend/api/v1/schema_design_service.go
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/schema_design_service.pb.go
  proto/generated-go/v1/schema_design_service.pb.gw.go
  proto/generated-go/v1/schema_design_service_grpc.pb.go
  proto/v1/schema_design_service.proto
Labels: cla-signed

#9664 chore: rename to parent branch
  backend/api/v1/branch_service.go
  backend/api/v1/schema_design_service.go
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/components/Branch/BranchDataTable.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchTable.vue
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/components/SchemaEditorV1/index.vue
  frontend/src/components/SchemaEditorV1/utils/branch.ts
  frontend/src/store/modules/schemaDesign.ts
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/schema_design_service.pb.go
  proto/v1/schema_design_service.proto
Labels: cla-signed

#9666 chore: implement create branch
  backend/api/v1/branch_service.go
  frontend/src/types/proto/store/branch.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/branch.pb.go
  proto/store/branch.proto
Labels: cla-signed

#9668 chore: switch to branch service implementation
  backend/api/v1/branch_service.go
  backend/api/v1/schema_design_service.go
  backend/server/grpc_routes.go
Labels: cla-signed

#9670 chore: update branch proto to reverse the merge branch direction and include branch id in the create branch request
  backend/api/v1/branch_service.go
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/v1/branch_service.proto
Labels: cla-signed

#9672 chore: fix create branch
  backend/common/resource_name.go
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/router/index.ts
  frontend/src/store/modules/branch.ts
  frontend/src/types/proto/store/changelist.ts
  frontend/src/types/proto/v1/changelist_service.ts
  frontend/src/utils/v1/changelist.ts
  frontend/src/views/branch/BranchDetail.vue
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/changelist.pb.go
  proto/generated-go/v1/changelist_service.pb.go
  proto/store/changelist.proto
  proto/v1/changelist_service.proto
Labels: cla-signed

#9663 chore: remove description from issue header section
  frontend/src/components/IssueV1/components/HeaderSection/Description.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
Labels: cla-signed

#9676 chore: update branch ID
  backend/api/v1/branch_service.go
  backend/store/branch.go
  frontend/src/components/Branch/BranchDetailView.vue
Labels: cla-signed

#9677 chore: remove fetchBaselineMetadataOfBranch since branches are independent
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchSQLCheckButton.vue
  frontend/src/components/Branch/SchemaDesignEditor.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
  frontend/src/components/SchemaEditorV1/utils/branch.ts
Labels: cla-signed

#9679 chore: 2.12.0
  scripts/VERSION
Labels: cla-signed

#9681 refactor: relocate database metadata converter
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sheet_service.go
Labels: cla-signed

#9685 chore: rebase branch API
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/branch_service_grpc.pb.go
  proto/v1/branch_service.proto
  scripts/check_link_test.go
Labels: cla-signed

#9686 fix: i18n for semantic type add from templates
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed, backport release/2.11.1

#9689 fix: fetch schema_drift immediately after sync-schema
  frontend/src/components/DatabaseOverviewPanel.vue
  frontend/src/views/DatabaseDetail.vue
Labels: cla-signed

#9692 chore: add DeleteCache to allow list
  backend/api/auth/config.go
Labels: cla-signed

#9695 fix: project deployment config ui
  frontend/src/components/Project/ProjectBranchProtectionRulesSettingPanel.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
Labels: cla-signed

#9696 refactor: database converter
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.12/0000##branch.sql
  backend/migrator/migration/prod/LATEST.sql
Labels: cla-signed

#9697 chore: introduce v1 database metadata to store converter
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
Labels: cla-signed

#9699 chore: implement update branch
  backend/api/v1/branch_service.go
Labels: cla-signed

#9701 chore(frontend): avoid unexpected assignee reset when assignee is SYSTEM_BOT
  frontend/src/components/IssueV1/components/HeaderSection/Assignee/Assignee.vue
  frontend/src/components/v2/Select/UserSelect.vue
Labels: backport release/2.11.1

#9702 chore: etag for merge and rebase branch
  backend/api/v1/branch_service.go
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/v1/branch_service.proto
Labels: cla-signed

#9705 refactor: remove unused project ID code
  .github/workflows/test_link.yml
  frontend/src/components/Branch/BaselineSchemaSelector.vue
  frontend/src/components/Branch/BranchCreateView.vue
Labels: cla-signed

#9706 feat: merge branch
  backend/api/v1/branch_service.go
Labels: cla-signed

#9707 fix(sql-review): fix check-innodb rule
  backend/plugin/advisor/mysql/advisor_use_innodb.go
  backend/plugin/advisor/mysql/test/engine_mysql_use_innodb.yaml
Labels: cla-signed

#9708 feat: support upload classification
  frontend/src/components/SchemaTemplate/ClassificationTree.vue
  frontend/src/components/SchemaTemplate/SelectClassificationDrawer.vue
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/SensitiveData/components/ClassificationExampleModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceSensitiveData.vue
Labels: cla-signed

#9709 feat: rebase branch
  backend/api/v1/branch_service.go
Labels: cla-signed

#9711 chore: tweak database editor button css style
  frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
Labels: cla-signed

#9712 chore: show branches in the merge branch selector
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchSelector.vue
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/views/branch/BranchDetail.vue
Labels: cla-signed

#9713 fix: pass to argument to getDesignSchema
  backend/api/v1/branch_service.go
Labels: cla-signed

#9714 chore: change default port to 8080
  backend/bin/server/cmd/root.go
  backend/bin/sql-service/cmd/root.go
  scripts/Dockerfile
  scripts/Dockerfile.depot
  scripts/Dockerfile.render-demo
  scripts/Dockerfile.sql-service
Labels: cla-signed

#9716 fix: support branch id with slash
  frontend/src/store/modules/v1/common.ts
Labels: cla-signed

#9717 chore: improve branch
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/store/modules/branch.ts
  frontend/src/views/branch/BranchDetail.vue
Labels: cla-signed

#9718 chore: update branch merge
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9719 chore: use storepb for try merge
  backend/api/v1/branch_service.go
  backend/api/v1/schema_design_merge.go
  backend/api/v1/schema_design_merge_test.go
Labels: cla-signed

#9722 fix(branch): get type string by restoring for tidb
  backend/api/v1/schema_design_transformer_tidb.go
  backend/api/v1/testdata/tidb/design.yaml
  backend/api/v1/testdata/tidb/schema.yaml
Labels: cla-signed, backport release/2.11.1

#9723 chore: use advanced search for database and instance
  frontend/src/components/IssueV1/components/IssueSearch/AdvancedSearchBox.vue
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/ScopeTags.vue
  frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SensitiveData/components/ClassificationExampleModal.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Name.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/instance.ts
  frontend/src/utils/v1/issue/search/common.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#9724 chore: let shell take the responsibility of reading pipe
  backend/plugin/db/mongodb/mongodb.go
Labels: cla-signed

#9726 fix: fix that char with null max length
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redshift/sync.go
Labels: cla-signed, backport release/2.11.1

#9729 chore: branch metadata backfill
  backend/api/v1/branch_service.go
  backend/api/v1/schema_design_transformer.go
  backend/api/v1/schema_design_transformer_test.go
  backend/api/v1/schema_design_transformer_tidb_test.go
  backend/server/backfill.go
  backend/server/server.go
  backend/store/branch.go
Labels: cla-signed

#9730 chore: support external approval
  backend/api/v1/issue_service.go
  backend/runner/relay/runner.go
Labels: cla-signed

#9731 chore: upgrade to pgx v5
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/tests/sql_review_test.go
  backend/tests/tests.go
  go.mod
  go.sum
Labels: cla-signed

#9732 chore: go 1.21.5
  README.md
  go.mod
  scripts/.goreleaser-for-darwin.yaml
  scripts/.goreleaser-for-linux.yaml
  scripts/Dockerfile
  scripts/Dockerfile.bb
  scripts/Dockerfile.depot
  scripts/Dockerfile.render-demo
  scripts/Dockerfile.sql-service
  scripts/build_bytebase.sh
Labels: cla-signed

#9735 chore: fix table user comment field
  frontend/src/components/TableDataTable.vue
Labels: cla-signed

#9738 fix: custom logo size
  frontend/src/components/BytebaseLogo.vue
  frontend/src/components/ProfileBrandingLogo.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/views/SchemaTemplate/ColumnTypes.vue
Labels: cla-signed

#9737 chore: update README
  README.md
  docs/assets/org-role-mapping.webp
Labels: cla-signed

#9739 chore: update advanced search
  frontend/src/components/IssueV1/components/IssueSearch/AdvancedSearchBox.vue
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/InstanceDashboard.vue
Labels: cla-signed

#9743 fix: allow project number passing from the frontend
  backend/api/v1/branch_service.go
Labels: cla-signed

#9744 chore: update branch hierarchy in demo data
  backend/demo/data/next/dump.sql
Labels: cla-signed

#9745 fix: sql to get active stage
  backend/store/stage.go
Labels: cla-signed, backport release/2.11.1

#9747 chore: add project databases and issues routes
  frontend/src/components/IssueV1/components/IssueSearch/AdvancedSearchBox.vue
  frontend/src/components/Project/ProjectSidebar.vue
  frontend/src/components/Project/useCurrentProject.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/router/index.ts
  frontend/src/views/project/ProjectDatabaseDashboard.vue
  frontend/src/views/project/ProjectIssueDashboard.vue
Labels: cla-signed

#9748 chore: hide sql editor button in issue detail page with standalone mode
  frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
Labels: cla-signed

#9750 chore(frontend): add some robustness and logs
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/MonacoEditor/text-model.ts
  frontend/src/components/MonacoEditor/utils.ts
  frontend/src/views/sql-editor/EditorPanel/SQLEditor.vue
Labels: cla-signed

#9749 chore: update default data type list
  frontend/src/utils/schemaEditor/index.ts
Labels: cla-signed

#9752 chore(sql-editor): fix port NaN
  frontend/src/components/MonacoEditor/lsp-client.ts
Labels: cla-signed

#9751 chore: update scripts for aws
  backend/enterprise/plugin/aws/aws.go
  frontend/.env.release-aws
  frontend/package.json
  frontend/src/components/ReleaseRemindModal.vue
  frontend/src/store/modules/v1/subscription.ts
  scripts/Dockerfile.aws
  scripts/build_bytebase_aws.sh
Labels: cla-signed

#9753 chore: update branch list and branch table content
  frontend/src/components/Branch/BranchDataTable.vue
  frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
Labels: cla-signed

#9755 chore: update column select
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DataTypeCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/DataTypeCell.vue
  frontend/src/components/v2/Form/DropdownInput.vue
Labels: cla-signed

#9757 chore: use lower case
  frontend/src/views/SchemaTemplate/ColumnTypes.vue
Labels: cla-signed

#9756 chore: default table primary column update
  frontend/src/components/SchemaEditorLite/Modals/TableNameModal.vue
Labels: cla-signed

#9758 chore(schema-editor): open and select new tab when schema/table is created
  frontend/src/components/SchemaEditorLite/Modals/SchemaNameModal.vue
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/context/tabs.ts
Labels: cla-signed

#9759 chore: update merge and rebase branch API
  backend/api/v1/branch_service.go
  frontend/src/components/Branch/MergeBranchPanel.vue
  frontend/src/store/modules/branch.ts
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service_grpc.pb.go
  proto/v1/branch_service.proto
Labels: cla-signed

#9760 feat(Completion): support Common Table Expression(CTE)
  backend/plugin/parser/base/c3.go
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/mysql/test-data/test_completion.yaml
  go.mod
  go.sum
Labels: cla-signed

#9761 chore: diff branch database API
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/branch_service_grpc.pb.go
  proto/v1/branch_service.proto
Labels: cla-signed

#9762 chore: return merged schema for selecting diff
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/v1/branch_service.proto
Labels: cla-signed

#9763 chore: filter databases based on policy
  backend/api/v1/database_service.go
  backend/api/v1/database_service_test.go
  frontend/src/components/DatabaseListSidePanel.vue
  frontend/src/components/KBar/useDatabaseActions.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/utils/v1/database.ts
  frontend/src/views/DatabaseDashboard.vue
Labels: cla-signed

#9764 feat: adjust trial workflow
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/components/TrialModal.vue
  frontend/src/components/UpgradeSubscriptionButton.vue
  frontend/src/components/WeChatQRModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DashboardHeader.vue
Labels: cla-signed

#9765 chore: remove local trial implementation
  backend/api/v1/setting_service.go
  backend/api/v1/subscription_service.go
  backend/enterprise/plugin/hub/hub.go
  backend/legacyapi/setting.go
  backend/tests/subscription.go
  backend/tests/subscription_test.go
  proto/v1/subscription_service.proto
Labels: cla-signed

#9766 chore: consolidate trial link
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/components/TrialModal.vue
  frontend/src/components/UpgradeSubscriptionButton.vue
  frontend/src/types/common.ts
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#9767 feat(helm): support store pgpassword in secret and escape password flag
  docs/bytebase-1.1.0.tgz
  docs/index.yaml
  helm-charts/bytebase/Chart.yaml
  helm-charts/bytebase/README.md
  helm-charts/bytebase/templates/secretproviderclass.yaml
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#9771 fix: err msg typo
  backend/api/v1/issue_service.go
Labels: cla-signed

#9769 chore(sql-editor): display for the bit type in decimal
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#9772 refactor(completion): move TableReference to base package
  backend/plugin/parser/base/complete.go
  backend/plugin/parser/mysql/completion.go
Labels: cla-signed

#9770 chore: don't sync instance on instance update
  backend/api/v1/instance_service.go
Labels: cla-signed

#9773 chore: fix warning
  frontend/src/components/TrialModal.vue
Labels: cla-signed

#9774 chore: add todos
  backend/api/v1/acl_iam.go
Labels: cla-signed

#9775 feat: remove SearchDatabases
  .vscode/settings.json
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/database_service.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/generated-go/v1/subscription_service.pb.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/generated-go/v1/subscription_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#9776 fix: ui issues
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/SQLReview/components/RuleLevelSwitch.vue
  frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue
Labels: cla-signed

#9777 fix: invalid custom description
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
Labels: cla-signed

#9779 chore(standalone): minor fixes
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/views/project/ProjectDatabaseDashboard.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#9778 chore: delete sheets used for branches
  backend/migrator/migration/prod/2.12/0002##delete_branch_sheet.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#9780 chore: add more pg types
  frontend/src/utils/schemaEditor/index.ts
Labels: cla-signed

#9782 chore(frontend): don't show n/a cells in table details panel
  frontend/src/components/TableDetailDrawer.vue
Labels: cla-signed

#9783 feat: environment iam
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9784 chore: update issue creation event payload
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/plugins/window-events.ts
Labels: cla-signed

#9786 feat: issue iam
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/common/resource_name.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9787 fix: typo
  frontend/src/types/proto/v1/branch_service.ts
  frontend/src/types/proto/v1/changelist_service.ts
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/changelist_service.pb.go
  proto/generated-go/v1/sheet_service.pb.go
  proto/v1/branch_service.proto
  proto/v1/changelist_service.proto
  proto/v1/sheet_service.proto
Labels: cla-signed

#9785 fix: escape special characters
  backend/plugin/db/mongodb/mongodb.go
Labels: cla-signed

#9788 feat: implement antlr-based pg split multi-sqls
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/parser/base/base.go
  backend/plugin/parser/base/lexer.go
  backend/plugin/parser/mysql/mysql.go
  backend/plugin/parser/mysql/split.go
  backend/plugin/parser/pg/split.go
  backend/plugin/parser/pg/split_test.go
  backend/tests/test-data/sql_review_pg.yaml
  go.mod
  go.sum
Labels: cla-signed

#9789 chore: wording change
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9790 chore: deprecate sheet store proto fields
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/sheet.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/sheet.pb.go
  proto/store/sheet.proto
Labels: cla-signed

#9792 chore: double quote to prevent globbing and word splitting
  scripts/build_bytebase_docker.sh
Labels: cla-signed

#9791 chore: enable cd setting with default true
  backend/api/v1/sheet_service.go
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.12/0003##repo_enable_cd.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/repository.go
Labels: cla-signed

#9794 chore: task run execution status to prod
  backend/runner/taskrun/executor.go
Labels: cla-signed

#9795 chore: hide issue buttons in standalone mode
  frontend/src/components/IssueV1/components/ActivitySection/Activity/ActionCreator.vue
  frontend/src/components/IssueV1/components/ActivitySection/ActivitySection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageInfo.vue
  frontend/src/components/v2/Model/DatabaseV1Name.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Name.vue
Labels: cla-signed

#9796 chore: ui improvement
  frontend/src/components/DatabaseGroup/DatabaseGroupTable.vue
  frontend/src/components/InstanceAssignment.vue
  frontend/src/components/Project/ProjectSwitchModal.vue
  frontend/src/components/Project/useRecentProjects.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/ProjectLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/types/quickAction.ts
  frontend/src/views/DashboardHeader.vue
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed

#9797 chore: search databases by project assigned status
  frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/issue/search/common.ts
  frontend/src/views/DatabaseDashboard.vue
Labels: cla-signed

#9799 feat(frontend): unfinished resolved issue tooltip
  frontend/src/components/IssueV1/components/BannerSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/IssueV1/components/IssueStatusIcon.vue
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9798 chore: stop mysql query explicitly
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#9801 fix(frontend): remove unused
  frontend/src/components/IssueV1/components/IssueStatusIcon.vue
Labels: cla-signed

#9800 fix: use singleSQL instead of original statement
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#9802 chore: i18n classification sample
  frontend/src/components/SensitiveData/components/ClassificationExampleModal.vue
Labels: cla-signed

#9804 chore: show detail message for action disabled reason
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#9803 chore: do not use transaction for tidb execution
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#9805 chore(schema-editor): extract schema editor engine checks
  frontend/src/components/SchemaEditorLite/Aside/BranchTree.vue
  frontend/src/components/SchemaEditorLite/Aside/DatabaseTree.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/ForeignKeyCell.vue
  frontend/src/components/SchemaEditorLite/engine-specs.ts
  frontend/src/utils/schemaEditor/index.ts
Labels: cla-signed

#9806 fix: set ast node position by tidb splitter
  backend/plugin/advisor/catalog/walk_through.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/test/column_auto_increment_initial_value.yaml
  backend/plugin/advisor/tidb/test/column_auto_increment_must_integer.yaml
  backend/plugin/advisor/tidb/test/column_auto_increment_must_unsigned.yaml
  backend/plugin/advisor/tidb/test/column_comment.yaml
  backend/plugin/advisor/tidb/test/column_current_time_count_limit.yaml
  backend/plugin/advisor/tidb/test/column_disallow_change.yaml
  backend/plugin/advisor/tidb/test/column_disallow_change_type.yaml
  backend/plugin/advisor/tidb/test/column_disallow_changing_order.yaml
  backend/plugin/advisor/tidb/test/column_disallow_drop_in_index.yaml
  backend/plugin/advisor/tidb/test/column_disallow_set_charset.yaml
  backend/plugin/advisor/tidb/test/column_maximum_character_length.yaml
  backend/plugin/advisor/tidb/test/column_no_null.yaml
  backend/plugin/advisor/tidb/test/column_require_default.yaml
  backend/plugin/advisor/tidb/test/column_required.yaml
  backend/plugin/advisor/tidb/test/column_set_default_for_not_null.yaml
  backend/plugin/advisor/tidb/test/column_type_disallow_list.yaml
  backend/plugin/advisor/tidb/test/database_drop_empty_database.yaml
  backend/plugin/advisor/tidb/test/index_key_number_limit.yaml
  backend/plugin/advisor/tidb/test/index_no_duplicate_column.yaml
  backend/plugin/advisor/tidb/test/index_pk_type_limit.yaml
  backend/plugin/advisor/tidb/test/index_primary_key_type_allowlist.yaml
  backend/plugin/advisor/tidb/test/index_total_number_limit.yaml
  backend/plugin/advisor/tidb/test/index_type_no_blob.yaml
  backend/plugin/advisor/tidb/test/naming_column.yaml
  backend/plugin/advisor/tidb/test/naming_column_auto_increment.yaml
  backend/plugin/advisor/tidb/test/naming_index_fk.yaml
  backend/plugin/advisor/tidb/test/naming_index_idx.yaml
  backend/plugin/advisor/tidb/test/naming_index_uk.yaml
  backend/plugin/advisor/tidb/test/naming_table.yaml
  backend/plugin/advisor/tidb/test/schema_backward_compatibility.yaml
  backend/plugin/advisor/tidb/test/statement_disallow_commit.yaml
  backend/plugin/advisor/tidb/test/statement_disallow_limit.yaml
  backend/plugin/advisor/tidb/test/statement_disallow_order_by.yaml
  backend/plugin/advisor/tidb/test/statement_dml_dry_run.yaml
  backend/plugin/advisor/tidb/test/statement_insert_disallow_order_by_rand.yaml
  backend/plugin/advisor/tidb/test/statement_insert_must_specify_column.yaml
  backend/plugin/advisor/tidb/test/statement_merge_alter_table.yaml
  backend/plugin/advisor/tidb/test/statement_select_no_select_all.yaml
  backend/plugin/advisor/tidb/test/statement_where_no_leading_wildcard_like.yaml
  backend/plugin/advisor/tidb/test/statement_where_require.yaml
  backend/plugin/advisor/tidb/test/system_charset_allowlist.yaml
  backend/plugin/advisor/tidb/test/system_collation_allowlist.yaml
  backend/plugin/advisor/tidb/test/table_comment.yaml
  backend/plugin/advisor/tidb/test/table_disallow_partition.yaml
  backend/plugin/advisor/tidb/test/table_drop_naming_convention.yaml
  backend/plugin/advisor/tidb/test/table_no_foreign_key.yaml
  backend/plugin/advisor/tidb/test/table_require_pk.yaml
Labels: cla-signed

#9808 chore: change order for recent visit project
  frontend/src/components/Project/useRecentProjects.ts
Labels: cla-signed

#9807 feat: project iam
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9809 fix: using trim instead of trimRight for MongoDB statement
  backend/plugin/db/mongodb/mongodb.go
Labels: cla-signed

#9810 fix: mysql parse version
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/mysql/mysql_test.go
Labels: cla-signed

#9811 docs: capitalize data classification tab
  frontend/src/locales/en-US.json
Labels: cla-signed

#9812 refactor: check iam permission
  backend/api/v1/acl_iam.go
Labels: cla-signed

#9813 fix: table comment display
  frontend/src/components/TableDataTable.vue
Labels: cla-signed

#9818 feat: iam for risks
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9817 chore: update batch query database table
  frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
Labels: cla-signed

#9816 chore: deprecate db transfer out quick action
  frontend/src/components/Project/ProjectSwitchModal.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/database.ts
  frontend/src/types/quickAction.ts
  frontend/src/views/project/ProjectDatabaseDashboard.vue
Labels: cla-signed

#9820 feat: roles iam
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9819 feat(branch): merge schema config in v1.BranchService.MergeBranch
  backend/api/v1/branch_service.go
  backend/runner/taskrun/executor.go
  backend/utils/database_config_merge.go
  backend/utils/database_config_merge_test.go
Labels: cla-signed

#9821 fix: user selector show status
  frontend/src/components/v2/Select/UserSelect.vue
Labels: cla-signed

#9822 chore: simplify mongo statement
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
Labels: cla-signed

#9823 chore: fix pg executor typo
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#9824 chore: refactor database transfer
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/MultipleDatabaseSelector.vue
  frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/components/TransferDatabaseForm/index.ts
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ProjectDetail.vue
  frontend/src/views/project/ProjectDatabaseDashboard.vue
Labels: cla-signed

#9825 chore: clean up metadata check and sanitizer
  backend/api/v1/branch_service.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#9826 chore: simplify check database metadata
  backend/api/v1/branch_service.go
  backend/api/v1/schema_design_transformer.go
  backend/api/v1/schema_design_transformer_test.go
  backend/api/v1/schema_design_transformer_tidb_test.go
  backend/api/v1/testdata/check.yaml
  backend/api/v1/testdata/tidb/check.yaml
Labels: cla-signed

#9827 chore: instant diff metadata
  backend/api/v1/branch_service.go
  backend/api/v1/branch_service_test.go
  backend/store/model/database.go
Labels: cla-signed

#9831 chore: return pg dump errors
  backend/plugin/db/pg/dump.go
Labels: cla-signed

#9830 chore(sql-editor): update i18n of data source type
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#9829 chore(sql-editor): update default factors
  frontend/src/store/modules/sqlEditorTree.ts
  frontend/src/types/sqlEditorTree.ts
  frontend/src/views/sql-editor/AsidePanel/DatabaseHoverPanel.vue
  frontend/src/views/sql-editor/AsidePanel/TreeNode/DatabaseNode.vue
Labels: cla-signed

#9832 chore: update BBModal styles
  frontend/src/bbkit/BBModal.vue
  frontend/src/components/Project/ProjectSwitchModal.vue
Labels: cla-signed

#9834 chore: branch schema change
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.12/0004##branch_reconcile.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#9836 fix: filter removed project
  frontend/src/components/Project/useRecentProjects.ts
Labels: cla-signed

#9833 feat: iam changelist
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
Labels: cla-signed

#9835 chore: branch store update
  backend/api/v1/branch_service.go
  backend/server/backfill.go
  backend/store/branch.go
  frontend/src/types/proto/store/branch.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/branch.pb.go
  proto/store/branch.proto
Labels: cla-signed
