Repository bytebase/bytebase, pull requests merged in 2023-07, with the labels that each got.

#6892 chore: update markdown editor
  frontend/src/components/Issue/IssueActivityPanel.vue
  frontend/src/components/Issue/activity/ActivityAction.vue
  frontend/src/components/Issue/activity/Comment.ts
  frontend/src/components/Issue/activity/index.ts
  frontend/src/components/MarkdownEditor.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6896 chore: disable subscription banner in demo mode and fix demo data
  backend/bin/server/cmd/root.go
  backend/migrator/demo/default/10110##task.sql
  backend/migrator/demo/default/10130##issue.sql
  docs/schema-update-guide.md
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#6895 docs: Readme adjustment
  README.md
Labels: cla-signed

#6898 feat: hide license column for FREE plan
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
  frontend/src/views/InstanceDashboard.vue
Labels: cla-signed

#6897 feat: automatic rollout should be the default rollout policy
  backend/migrator/migration/prod/1.0/0001##initial_data.sql
  backend/migrator/migration/prod/LATEST_DATA.sql
  frontend/src/store/modules/v1/policy.ts
Labels: cla-signed

#6900 chore: add a link to the subscription page in instance license assignment control
  frontend/src/components/InstanceForm/InstanceForm.vue
Labels: cla-signed

#6899 chore: plan and version should align left/right respectively
  frontend/src/layouts/BodyLayout.vue
Labels: cla-signed

#6902 chore: fix test from default rollout policy
  backend/tests/backup_restore_test.go
  backend/tests/external_approval_test.go
  backend/tests/sql_review_test.go
Labels: cla-signed

#6901 fix: sheet_id doesn't exist in change history table
  backend/migrator/migrator.go
  backend/store/instance_change_history.go
Labels: cla-signed

#6903 chore: minor markdown editor style tweak
  frontend/src/components/MarkdownEditor.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6904 chore: enlarge y spacing between query result and toolbar
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#6906 feat: support Oracle CDB as instance and PDB as database
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/sync.go
  backend/runner/schemasync/syncer.go
  backend/store/data_source.go
  backend/store/database.go
  frontend/src/types/proto/store/database.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/database.pb.go
  proto/store/database.proto
Labels: cla-signed

#6908 fix(sql-editor): button color in dark mode
  frontend/naive-ui.config.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#6905 chore: don't put extra new line at the end of exported file
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
Labels: cla-signed

#6910 fix: use correct err variable
  backend/api/v1/sql_service.go
Labels: cla-signed

#6911 chore: introduce admin flag to export API
  backend/api/v1/sql_service.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#6913 chore: 2.4.0
  scripts/VERSION
Labels: cla-signed

#6914 fix(store, activity): list activity order by id instead of created_ts
  backend/store/activity.go
Labels: cla-signed

#6916 chore: change skip approval value to `false` in free/pro plans
  frontend/src/views/SettingWorkspaceAccessControl.vue
Labels: cla-signed

#6915 chore(frontend): add `admin` flag to `export` when needed
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/useExportData.ts
Labels: cla-signed

#6909 fix: show export button checks
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#6917 chore(sql-editor): improve displaying for oversize sheets
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
Labels: cla-signed

#6920 chore(sql-editor): update layout for "Request Query" button
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#6912 feat: add instance option column for instance
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/2.4/0002##add_options_to_instance.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto/store/instance.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/instance.pb.go
  proto/store/instance.proto
Labels: cla-signed

#6918 chore: support issue panel in markdown editor
  frontend/src/components/Issue/IssueActivityPanel.vue
  frontend/src/components/MarkdownEditor.vue
Labels: cla-signed

#6919 chore: change approval policy default value
  backend/api/v1/org_policy_service.go
  frontend/src/components/EnvironmentForm.vue
Labels: cla-signed

#6921 feat: implement instance options CRUD
  backend/api/v1/instance_service.go
  backend/store/instance.go
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#6924 feat: remove access control description for env tier
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6907 feat: calculate risk level for granting request issue
  backend/api/v1/cel_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/sql_service.go
  backend/common/convert.go
  backend/common/convert_test.go
  backend/runner/approval/runner.go
Labels: cla-signed

#6922 feat: impl sync and dump for schema as db
  backend/api/v1/instance_service.go
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/driver.go
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/sync.go
Labels: cla-signed

#6927 chore: remove table name factor in frontend
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/factor.ts
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/plugins/cel/types/operator.ts
Labels: cla-signed

#6929 chore: rename issue part 2
  backend/api/v1/issue_service.go
  backend/server/server.go
  backend/tests/external_approval_test.go
  backend/tests/issue.go
  backend/tests/tests.go
  frontend/src/grpcweb/index.ts
  frontend/src/plugins/issue/logic/review/context.ts
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/v1/review.ts
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#6931 chore(frontend): allow update sql files multiple times when creating issues
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#6930 chore: rename review to issue part 3
  backend/api/v1/common.go
  backend/api/v1/issue_service.go
  backend/api/v1/rollout_service.go
  backend/tests/external_approval_test.go
  backend/tests/issue.go
  frontend/src/components/Issue/IssueActivityPanel.vue
  frontend/src/components/Issue/rollback/common.ts
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/v1/review.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/review.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#6928 chore: append .sql to file name only when needed
  frontend/src/components/Sheet/DownloadSheetButton.vue
Labels: cla-signed

#6932 feat(helm): add external-url back in helm
  docs/bytebase-1.0.4.tgz
  docs/index.yaml
  helm-charts/bytebase/Chart.yaml
  helm-charts/bytebase/README.md
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#6934 chore(frontend): tenant deployment matrix layout improvement
  frontend/src/components/TenantDatabaseTable/DeployDatabaseTable.vue
Labels: cla-signed

#6935 chore: update database accessible checks
  frontend/src/components/DatabaseListSidePanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/v2/Model/DatabaseV1Table.vue
  frontend/src/utils/v1/database.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/TableDetail.vue
  frontend/src/views/sql-editor/SQLEditorPage.vue
Labels: cla-signed

#6936 chore: issue rename part 5
  backend/api/v1/issue_service.go
  frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
  frontend/src/store/modules/review.ts
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#6937 chore: remove deprecated sql admin API
  backend/server/server.go
  backend/server/sql.go
Labels: cla-signed

#6938 chore: allow Mongo and Redis to query in SQL Editor
  backend/api/v1/sql_service.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#6941 fix: disable check query/export permission for free/pro plan
  backend/api/v1/sql_service.go
  backend/server/server.go
Labels: cla-signed

#6939 fix: switch for risk source
  backend/runner/approval/runner.go
Labels: cla-signed

#6942 chore: update `Upgrade trial` button in access control setting
  frontend/src/components/UpgradeSubscriptionButton.vue
  frontend/src/views/SettingWorkspaceAccessControl.vue
Labels: cla-signed

#6943 fix: skip project owner for hasDatabaseAccessRights
  backend/api/v1/sql_service.go
Labels: cla-signed

#6944 chore: update project role drawer width
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
Labels: cla-signed

#6945 chore: rename issue part 6
  backend/api/v1/issue_service.go
  frontend/src/components/Issue/IssueBanner.vue
  frontend/src/components/Issue/logic/transition.ts
  frontend/src/components/Issue/review/CurrentApprover.vue
  frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
  frontend/src/components/Issue/review/IssueReviewForm.vue
  frontend/src/components/Issue/table/IssueTable.vue
  frontend/src/components/Issue/table/WaitingForMyApprovalIssueTable.vue
  frontend/src/plugins/issue/logic/review/context.ts
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/review.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/review.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#6946 feat: filter unavailable tables in sql editor panel
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/utils/v1/database.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPanel/DatabaseSchema.vue
Labels: cla-signed

#6947 chore: update for feature guard
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/role.ts
  frontend/src/views/SettingWorkspaceSubscription.vue
  frontend/src/views/SyncDatabaseSchema/index.vue
Labels: cla-signed

#6948 fix: BYT-3551
  frontend/src/components/InstanceAssignment.vue
Labels: cla-signed

#6949 chore: rename issue part 7
  backend/api/v1/common.go
  backend/api/v1/database_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/rollout_service.go
  backend/tests/external_approval_test.go
  backend/tests/issue.go
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/components/DatabaseDetail/ChangeHistoryBrief.vue
  frontend/src/components/Issue/IssueActivityPanel.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/rollback/common.ts
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/review.ts
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/proto/v1/rollout_service.ts
  frontend/src/utils/v1/review.ts
  frontend/src/views/ChangeHistoryDetail.vue
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/plan.proto
  proto/v1/database_service.proto
  proto/v1/issue_service.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#6950 fix: hide warning in free plan
  frontend/src/components/RepositoryForm.vue
Labels: cla-signed

#6953 fix: hide unassigned database
  frontend/src/components/DatabaseListSidePanel.vue
  frontend/src/views/DatabaseDashboard.vue
Labels: cla-signed

#6952 chore: rename issue part 8
  frontend/src/components/Issue/review/ExternalApprovalNodeSyncButton.vue
  frontend/src/components/Issue/review/IssueReviewButtonGroup.vue
  frontend/src/components/Issue/review/IssueReviewSidebarSection.vue
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/review.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/issue.ts
Labels: cla-signed

#6954 chore: issue rename part 9
  frontend/src/components/Issue/review/ExternalApprovalNodeSyncButton.vue
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/v1/issue.ts
Labels: cla-signed

#6956 chore: add ssh tunneling to feature list
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed

#6957 chore: update plan config
  .github/workflows/frontend-tests.yml
  .golangci.yaml
  backend/enterprise/api/license.go
  backend/enterprise/api/limit.go
  backend/enterprise/api/plan.yaml
  backend/enterprise/service/license.go
  frontend/package.json
  frontend/scripts/copy_config_files.sh
  frontend/scripts/copy_sql_review_files.sh
Labels: cla-signed

#6959 fix: update scripts
  .github/workflows/frontend-tests.yml
  frontend/package.json
  scripts/Dockerfile
  scripts/Dockerfile.render-demo
Labels: cla-signed

#6958 feat: impl Query for schema tenant mode Oracle
  backend/api/v1/sql_service.go
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#6962 fix: fix subscription banner for rollout policy
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#6960 chore: fix some warnings
  backend/api/v1/common.go
  backend/api/v1/project_service.go
  backend/server/webhook.go
Labels: cla-signed

#6966 chore: add missing ignore for config file
  .gitignore
Labels: cla-signed

#6965 fix: instance count
  frontend/src/components/QuickActionPanel.vue
Labels: cla-signed, backport release/2.3.0, backport release/2.4.0

#6970 cherrypick: instance count 6965
  frontend/src/components/QuickActionPanel.vue
Labels: cla-signed

#6968 chore: instance count limit should only count for live instances
  backend/store/instance.go
Labels: cla-signed

#6969 chore: update sheet store
  backend/api/v1/rollout_service.go
  backend/api/v1/sheet_service.go
  backend/runner/rollbackrun/runner.go
  backend/runner/taskcheck/statement_advisor_composite_executor.go
  backend/runner/taskcheck/statement_affected_rows_report_executor.go
  backend/runner/taskcheck/statement_type_executor.go
  backend/runner/taskcheck/statement_type_report_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/webhook.go
  backend/store/database.go
  backend/store/sheet.go
  backend/store/stats.go
Labels: cla-signed

#6967 fix: get claims value with path key
  backend/plugin/idp/oauth2/oauth2.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/util.go
  backend/plugin/idp/util_test.go
Labels: cla-signed

#6972 chore: update issue proto
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#6973 feat(snowflake): support snowflake data anonymization
  backend/api/v1/database_service.go
  backend/api/v1/sql_service.go
  backend/plugin/db/driver.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/snowflake_test.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
  backend/plugin/parser/sql/snowsql.go
  backend/plugin/parser/sql/snowsql_test.go
  backend/plugin/parser/sql/utils.go
  backend/plugin/parser/sql/utils_test.go
  frontend/src/components/ColumnTable.vue
  frontend/src/store/modules/v1/policy.ts
  frontend/src/utils/policy.ts
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#6975 fix(sql-editor): export query result with split SQL statement
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed, backport release/2.4.0

#6977 chore: add `toLowerCase` when getting policy
  frontend/src/store/modules/v1/policy.ts
Labels: cla-signed

#6978 fix: workspace policy name
  frontend/src/store/modules/v1/policy.ts
  frontend/src/utils/policy.ts
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#6979 feat: support CTE for oracle data anonymization
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data_plsql.go
  go.mod
  go.sum
Labels: cla-signed

#6974 chore: optimize instance assignment
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/GhostDialog.vue
  frontend/src/components/ColumnTable.vue
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseBackup/BackupTable.vue
  frontend/src/components/DatabaseDetail/PITRRestoreButton.vue
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/SshConnectionForm.vue
  frontend/src/components/Issue/IssueSidebar.vue
  frontend/src/components/Issue/IssueTaskSDLPanel.vue
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
  frontend/src/components/Project/ProjectCreatePanel.vue
  frontend/src/components/Project/ProjectGeneralSettingPanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/RepositoryPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/IssueDetail.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingWorkspaceAccessControl.vue
  frontend/src/views/SettingWorkspaceCustomApproval.vue
  frontend/src/views/SettingWorkspaceIMIntegration.vue
  frontend/src/views/SettingWorkspaceRiskCenter.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceSSODetail.vue
  frontend/src/views/SettingWorkspaceSensitiveData.vue
  frontend/src/views/SheetDashboard.vue
  frontend/src/views/SyncDatabaseSchema/index.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#6980 fix: query role checks from cel string
  frontend/src/store/modules/v1/projectIamPolicy.ts
Labels: cla-signed, backport release/2.4.0

#6982 chore: use explicit wording for locating open ai key
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#6983 chore: upgrade go-ora version
  go.mod
  go.sum
Labels: cla-signed

#6984 chore(snowsql-parser): upgrade the snowsql parser version
  backend/plugin/advisor/snowflake/test/statement_where_require.yaml
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
  go.mod
  go.sum
Labels: cla-signed

#6985 fix: 🔥approval flow and feature guard
  backend/utils/utils.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/Toolbar.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/Toolbar.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskTable.vue
Labels: cla-signed, backport release/2.4.0

#6987 feat(snowflake, data-anonymization): support correlated subquery in select clause
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
Labels: cla-signed

#6988 chore: preview rollout API proto
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#6990 chore: update for external approval demo
  backend/legacyapi/external_approval.go
  backend/plugin/app/relay/relay_client.go
  backend/runner/relay/runner.go
  backend/utils/utils.go
Labels: cla-signed

#6991 feat(snowflake, data-anonymization): support PIVOT/UNPIVOT in object ref
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
Labels: cla-signed

#6989 chore: add view full params when list change histories
  frontend/src/views/SyncDatabaseSchema/index.vue
Labels: cla-signed

#6993 fix: issue progress click handler
  frontend/src/components/Issue/table/IssueTable.vue
Labels: cla-signed

#6992 chore: update access duration
  backend/api/auth/auth.go
Labels: cla-signed, backport release/2.4.0

#6997 docs: change spanner instance connection help to the new doc link
  frontend/src/components/InstanceForm/SpannerCredentialInput.vue
  frontend/src/components/InstanceForm/SpannerHostInput.vue
Labels: cla-signed

#6998 feat(snowflake, data-anonymization): support recursive CTE
  backend/plugin/db/util/driverutil_test.go
  backend/plugin/db/util/mask_sensitive_data_snowsql.go
Labels: cla-signed

#6995 chore: move sheet type definitions to store
  backend/api/v1/rollout_service.go
  backend/api/v1/sheet_service.go
  backend/runner/rollbackrun/runner.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/webhook.go
  backend/store/principal.go
  backend/store/sheet.go
Labels: cla-signed

#6996 chore: migrate `DatabaseEdit` definition to protobuf
  frontend/src/types/proto/v1/database_edit.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_edit.pb.go
  proto/v1/database_edit.proto
Labels: cla-signed

#6999 chore: move legacy message
  backend/api/v1/rollout_service.go
  backend/legacyapi/pipeline.go
  backend/legacyapi/stage.go
  backend/legacyapi/task.go
  backend/runner/backuprun/runner.go
  backend/server/issue.go
  backend/store/issue.go
  backend/store/rollout.go
  backend/store/task.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#7000 feat: add `schema_design_service.proto`
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/schema_design_service.pb.go
  proto/generated-go/v1/schema_design_service.pb.gw.go
  proto/generated-go/v1/schema_design_service_grpc.pb.go
  proto/v1/schema_design_service.proto
Labels: cla-signed

#7002 fix: instance license count
  frontend/src/components/InstanceForm/InstanceForm.vue
Labels: cla-signed, backport release/2.4.0

#7001 chore: rename messages
  backend/api/v1/rollout_service.go
  backend/runner/backuprun/runner.go
  backend/server/issue.go
  backend/store/issue.go
  backend/store/rollout.go
  backend/store/task.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#7004 feat(sql-review, snowflake): add sql review rule statement select no select all for snowflake
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/generator/snowflake.template
  backend/plugin/advisor/snowflake/advisor_select_no_select_all.go
  backend/plugin/advisor/snowflake/snowflake_rules_test.go
  backend/plugin/advisor/snowflake/test/statement_select_no_select_all.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#7005 fix: encode export statement before btoa
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
  frontend/src/components/Issue/logic/GrantRequestModeProvider.ts
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/utils/issue/cel.ts
Labels: cla-signed, backport release/2.4.0

#7008 chore: update rollout policy and move custom approval to change management
  backend/enterprise/api/plan.yaml
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
Labels: cla-signed

#7009 chore: add schema design to sheet payload
  frontend/src/types/proto/store/sheet.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/sheet.pb.go
  proto/store/sheet.proto
Labels: cla-signed

#7007 chore: update comments of schema design proto
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/schema_design_service.pb.go
  proto/v1/schema_design_service.proto
Labels: cla-signed

#7006 feat(sql-review, snowflake): add sql review rule statement select no select all for snowflake
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/snowflake/advisor_table_drop_naming_convention.go
  backend/plugin/advisor/snowflake/snowflake_rules_test.go
  backend/plugin/advisor/snowflake/test/table_drop_naming_convention.yaml
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#7014 chore: add skipper for rate limiter
  backend/server/server.go
Labels: cla-signed, backport release/2.4.0

#7013 fix: let MySQL Execute deals with DELIMITER statements
  .github/workflows/backend-tests.yml
  backend/plugin/db/mysql/mysql.go
  backend/plugin/parser/sql/mysql.go
Labels: cla-signed, backport release/2.4.0

#7017 feat(sql-review, snowflake): implement the migration compatibility sql review rule for snowflake
  backend/api/v1/sql_service.go
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/snowflake/advisor_migration_compatibility.go
  backend/plugin/advisor/snowflake/advisor_table_no_foreign_key.go
  backend/plugin/advisor/snowflake/advisor_table_require_pk.go
  backend/plugin/advisor/snowflake/snowflake_rules_test.go
  backend/plugin/advisor/snowflake/test/schema_backward_compatibility.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/parser/sql/snowsql.go
Labels: cla-signed

#7018 chore: consolidate task message
  backend/api/v1/rollout_service.go
  backend/runner/backuprun/runner.go
  backend/server/issue.go
  backend/store/rollout.go
  backend/store/task.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#7019 chore: restruct stage and pipeline
  backend/api/v1/rollout_service.go
  backend/legacyapi/stage.go
  backend/server/issue.go
  backend/store/issue.go
  backend/store/pipeline.go
  backend/store/rollout.go
  backend/store/stage.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#7020 chore: restruct pipeline
  backend/api/v1/rollout_service.go
  backend/legacyapi/task.go
  backend/server/issue.go
  backend/store/issue.go
  backend/store/pipeline.go
  backend/store/rollout.go
  backend/store/stage.go
  backend/store/task.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#7022 chore(frontend): fix filter when transfer in databases
  frontend/src/components/TransferDatabaseForm.vue
Labels: cla-signed

#7023 chore(frontend): ui update for transferring out databases
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7021 chore(frontend): color
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
Labels: cla-signed

#7024 chore: refactor rollout v1 API
  backend/api/v1/rollout_service.go
Labels: cla-signed

#7025 chore: update owner
  CODEOWNERS
Labels: cla-signed

#7028 fix: encode statement for cel matching in backend
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
Labels: cla-signed, backport release/2.4.0

#7027 feat: impl update mask for instance options
  backend/api/v1/instance_service.go
Labels: cla-signed

#7026 feat(frontend): support oracle schema tenant mode
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/OracleSyncModeInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7012 feat: implement schema design service
  backend/api/v1/common.go
  backend/api/v1/schema_design_service.go
  backend/store/instance_change_history.go
  backend/store/sheet.go
  frontend/src/types/proto/v1/schema_design_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/schema_design_service.pb.go
  proto/v1/schema_design_service.proto
Labels: cla-signed

#7030 chore: move engine to schema design sheet payload
  backend/api/v1/schema_design_service.go
  frontend/src/types/proto/store/common.ts
  frontend/src/types/proto/store/sheet.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/common.pb.go
  proto/generated-go/store/sheet.pb.go
  proto/store/common.proto
  proto/store/sheet.proto
Labels: cla-signed

#7032 chore(frontend): update review code format
  frontend/src/components/Issue/TaskCheckRunPanel.vue
Labels: cla-signed

#7031 chore: implement preview rollout API
  backend/api/v1/rollout_service.go
Labels: cla-signed

#7033 fix: encode statement
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
Labels: cla-signed, backport release/2.4.0

#7036 chore: update func comments
  backend/api/v1/schema_design_service.go
Labels: cla-signed

#7035 chore: introduce create rollout API
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#7039 chore: add policy for disallow copy data
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#7037 chore: use parser to split multi-plsql
  backend/api/v1/sql_service.go
  backend/plugin/advisor/oracle/test/column_required.yaml
  backend/plugin/advisor/oracle/test/table_require_pk.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/db/util/mask_sensitive_data_plsql.go
  backend/plugin/parser/sql/plsql.go
  backend/plugin/parser/sql/plsql_test.go
  backend/plugin/parser/sql/split_multi_sql_test.go
  backend/plugin/parser/sql/utils.go
Labels: cla-signed

#7042 chore: add schema design pinia store
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/schemaDesign.ts
Labels: cla-signed

#7044 chore: update generated proto
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/types/proto/google/api/client.ts
  frontend/src/types/proto/google/api/expr/v1alpha1/syntax.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/duration.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/store/activity.ts
  frontend/src/types/proto/store/approval.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/store/idp.ts
  frontend/src/types/proto/store/instance_change_history.ts
  frontend/src/types/proto/store/issue.ts
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/store/sheet.ts
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/store/vcs.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/types/proto/v1/bookmark_service.ts
  frontend/src/types/proto/v1/cel_service.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/environment_service.ts
  frontend/src/types/proto/v1/externalvs_service.ts
  frontend/src/types/proto/v1/iam_policy.ts
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/types/proto/v1/inbox_service.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/proto/v1/logging_service.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/proto/v1/role_service.ts
  frontend/src/types/proto/v1/rollout_service.ts
  frontend/src/types/proto/v1/schema_design_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/proto/v1/sheet_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/types/proto/v1/subscription_service.ts
  frontend/src/types/proto/v1/vcs.ts
Labels: cla-signed

#7043 chore: deprecate access control policy
  backend/api/v1/org_policy_service.go
  backend/legacyapi/policy.go
  backend/migrator/migration/prod/2.4/0003##deprecate_access_control_policy.sql
  backend/migrator/migrator_test.go
  backend/store/policy.go
  frontend/src/components/DatabaseTable.vue
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/utils/policy.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#7045 chore: remove default approval for grant requesting issues
  backend/runner/approval/runner.go
Labels: cla-signed

#7047 feat(frontend): Environment policy for disabling copy data in SQL Editor
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceAccessControl.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/context.ts
Labels: cla-signed

#7046 chore: implement create rollout API
  backend/api/v1/rollout_service.go
  backend/store/plan.go
Labels: cla-signed

#7048 chore: get trigger statement compatible with mysql 5.6
  backend/plugin/db/mysql/dump.go
Labels: cla-signed, backport release/2.4.0

#7050 feat: initial schema designer components
  frontend/src/components/SchemaDesigner/AsidePanel.vue
  frontend/src/components/SchemaDesigner/DatabaseTree.vue
  frontend/src/components/SchemaDesigner/EmptyTips.vue
  frontend/src/components/SchemaDesigner/Modals/ActionConfirmModal.vue
  frontend/src/components/SchemaDesigner/Modals/EditColumnForeignKeyModal.vue
  frontend/src/components/SchemaDesigner/Modals/SchemaNameModal.vue
  frontend/src/components/SchemaDesigner/Modals/TableNameModal.vue
  frontend/src/components/SchemaDesigner/Panels/TableEditor.vue
  frontend/src/components/SchemaDesigner/PrepForm/SchemaDesignTable.vue
  frontend/src/components/SchemaDesigner/PrepForm/index.vue
  frontend/src/components/SchemaDesigner/TabsContainer.vue
  frontend/src/components/SchemaDesigner/common/context.ts
  frontend/src/components/SchemaDesigner/common/index.ts
  frontend/src/components/SchemaDesigner/common/type.ts
  frontend/src/components/SchemaDesigner/index.vue
  frontend/src/components/SchemaDesigner/utils/column.ts
  frontend/src/components/SchemaDesigner/utils/schema.ts
  frontend/src/components/SchemaDesigner/utils/table.ts
  frontend/src/store/modules/v1/common.ts
Labels: cla-signed

#7055 chore: update schema design service
  backend/api/v1/schema_design_service.go
  backend/server/server.go
Labels: cla-signed

#7051 feat: convert schema to database metadata(Part I)
  backend/api/v1/schema_design_service.go
  backend/plugin/parser/sql/mysql.go
Labels: cla-signed

#7056 chore: auto-approve if query/export has no approval template setup
  backend/api/v1/issue_service.go
  backend/runner/approval/runner.go
  backend/server/server.go
  backend/utils/utils.go
Labels: cla-signed

#7052 fix: deal with lower version pg_stat_statements
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#7058 chore(frontend): issue activity section pageSize
  frontend/src/store/modules/v1/activity.ts
Labels: cla-signed

#7059 chore: tweak github enterprise wording
  frontend/src/components/VCSProviderBasicInfoPanel.vue
  frontend/src/components/VCSProviderConfirmPanel.vue
  frontend/src/components/VCSProviderOAuthPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#7057 feat(idp): add BindDN-based LDAP authentication client
  backend/plugin/idp/ldap/ldap.go
  backend/plugin/idp/ldap/ldap_test.go
  go.mod
  go.sum
Labels: cla-signed

#7060 chore: update server setting
  backend/api/auth/header.go
  backend/server/server.go
  backend/sql-server/server.go
Labels: cla-signed

#7061 chore: use standard SQL tool json export style for json export
  backend/api/v1/sql_service.go
Labels: cla-signed

#7063 chore: update feishu webhook doc link
  frontend/src/components/ProjectWebhookForm.vue
Labels: cla-signed

#7062 chore: support export as xlsx
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/views/ExportCenter/ExportDataButton.vue
  frontend/src/views/ExportCenter/types.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/useExportData.ts
  go.mod
  go.sum
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#7064 feat: add a test sample instance during onboarding
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/common/util.go
  backend/component/config/profile.go
  backend/legacyapi/project.go
  backend/resources/postgres/postgres.go
  backend/server/server.go
  backend/tests/tests.go
Labels: cla-signed

#7066 chore: add log to debug sample data dir permission error
  backend/resources/postgres/postgres.go
Labels: cla-signed

#7067 fix: recursively chown of all created intermediate directory during initdb
  backend/resources/postgres/postgres.go
Labels: cla-signed

#7068 feat(frontend): feature badge for custom roles in plans not supported
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
Labels: cla-signed

#7065 chore: fix deleted resource behavior
  backend/api/v1/auth_service.go
  backend/api/v1/environment_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/instance_role_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/project_service.go
Labels: cla-signed

#7069 chore: 2.4.1 version
  scripts/VERSION
Labels: cla-signed

#7070 fix: skip empty schema for schema tenant mode
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#7071 chore(frontend): use deep copy of instance.option
  frontend/src/components/InstanceForm/InstanceForm.vue
Labels: cla-signed
