Repository bytebase/bytebase, pull requests merged in 2023-04, with the labels that each got.

#5345 chore: retire tianzhou as the schema reviewer
  CODEOWNERS
Labels: cla-signed

#5344 chore: minor wording tweak for risk center
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5346 chore: remove beta label from mongo, spanner, redis
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#5347 chore: update enforce NOT NULL column description
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/zh-CN.json
Labels: cla-signed

#5269 feat(backend): support add redshift in backend
  backend/plugin/db/redshift/dump.go
  backend/plugin/db/redshift/migrate.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/redshift/role.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/redshift/sync_test.go
  backend/plugin/parser/parser.go
  backend/plugin/parser/utils.go
  backend/runner/anomaly/scanner.go
  backend/runner/taskrun/database_create_executor.go
  backend/server/database.go
  backend/server/issue.go
  backend/server/server.go
  backend/server/sql.go
  backend/store/data_source.go
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseBackupPanel.vue
  frontend/src/components/InstanceForm.vue
  frontend/src/types/common.ts
  frontend/src/types/instance.ts
  frontend/src/utils/instance.ts
Labels: cla-signed

#5348 feat(frontend): minor optimizations for risk center and custom approval
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/common.ts
Labels: cla-signed

#5349 fix(bbc): hide SQL Review section in repo settings
  frontend/src/components/RepositoryForm.vue
Labels: cla-signed

#5352 feat(frontend): batch skip failed tasks in current stage
  frontend/src/components/Issue/BatchTaskActionForm.vue
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
  frontend/src/components/Issue/TaskExtraActionsButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/task.ts
Labels: cla-signed

#5355 feat(schema): add slow_query table
  backend/store/migration/dev/20230404000000##slow_query_table.sql
  backend/store/migration/dev/LATEST.sql
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/slow_query.proto
  proto/v1/database_service.proto
Labels: cla-signed

#5357 feat: sync instance for redshift
  backend/plugin/db/redshift/sync.go
  backend/server/instance.go
Labels: cla-signed

#5362 fix: icon path
  frontend/src/components/Issue/activity/ActionIcon.vue
Labels: cla-signed

#5356 chore(snowflake): update the privileges we need for Snowflake
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/sync.go
  frontend/src/components/CreateDataSourceExample.vue
  frontend/src/components/DatabaseBackupPanel.vue
Labels: cla-signed

#5406 chore: refine snowflake grant instruction
  frontend/src/components/CreateDataSourceExample.vue
Labels: cla-signed

#5405 chore: use grid-cols-4 for engine list in instance form
  frontend/src/components/InstanceForm.vue
Labels: cla-signed

#5407 chore(snowflake): update the privileges we need for Snowflake (#5356)
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/sync.go
  frontend/src/components/CreateDataSourceExample.vue
Labels: cla-signed

#5409 feat(frontend): display instance label for low privileged users
  frontend/src/components/Issue/IssueSidebar.vue
Labels: cla-signed

#5408 feat(sql-editor): improvements for sheets from issues.
  frontend/src/components/Issue/logic/base.ts
  frontend/src/components/Issue/logic/common.ts
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/connectionTree.ts
  frontend/src/types/sheet.ts
  frontend/src/utils/sheet.ts
  frontend/src/views/SheetDashboard.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
  frontend/src/views/sql-editor/EditorPanel/SheetForIssueTipsBar.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/Dropdown.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/IssueLink.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/SheetTable.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/index.ts
  frontend/src/views/sql-editor/Sheet/index.ts
  frontend/src/views/sql-editor/Sheet/types.ts
  frontend/tailwind.config.js
Labels: cla-signed

#5410 fix(frontend): wrong importing path
  frontend/src/components/Issue/IssueTaskStatementPanel.vue
Labels: cla-signed

#5411 chore: add pnpm release-docker build to github action
  .github/workflows/frontend-tests.yml
  frontend/src/locales/en-US.json
Labels: cla-signed

#5413 chore: frontend test action
  .github/workflows/frontend-tests.yml
Labels: cla-signed

#5415 chore: clean-up golangci-lint warning
  .github/workflows/backend-tests.yml
  backend/bin/bb/cmd/migrate.go
  backend/plugin/advisor/mysql/advisor_syntax.go
  backend/plugin/advisor/pg/parser.go
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/mysql/restore.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/vcs/internal/oauth/oauth.go
  backend/runner/anomaly/scanner.go
  backend/runner/taskcheck/statement_affected_rows_report_executor.go
  backend/runner/taskcheck/statement_type_executor.go
  backend/runner/taskcheck/statement_type_report_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/server/webhook_test.go
  backend/store/data_source.go
  backend/store/database.go
  backend/store/environment.go
  backend/store/idp.go
  backend/store/instance.go
  backend/store/issue.go
  backend/store/pg_engine_test.go
  backend/store/principal.go
  backend/store/project.go
  backend/store/project_member.go
  backend/tests/rollback_test.go
  backend/utils/utils.go
Labels: cla-signed

#5416 chore: add parent member to support filter environments, instances and databases
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/v1/database_service.proto
Labels: cla-signed

#5417 feat: add slow query policy
  backend/legacyapi/policy.go
Labels: cla-signed

#5420 fix: show configure —external-url banner properly
  frontend/src/components/BannersWrapper.vue
Labels: cla-signed

#5419 feat(frontend): workspace slow query settings
  backend/legacyapi/plan.go
  frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
  frontend/src/components/SlowQuery/Settings/components/SlowQueryPolicyTable.vue
  frontend/src/components/SlowQuery/Settings/components/index.ts
  frontend/src/components/SlowQuery/Settings/index.ts
  frontend/src/components/SlowQuery/index.ts
  frontend/src/components/v2/Form/SpinnerSwitch.vue
  frontend/src/components/v2/Form/index.ts
  frontend/src/components/v2/Model/EnvironmentName.vue
  frontend/src/components/v2/Model/InstanceName.vue
  frontend/src/components/v2/Model/index.ts
  frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
  frontend/src/components/v2/TabFilter/TabFilter.vue
  frontend/src/components/v2/TabFilter/index.ts
  frontend/src/components/v2/TabFilter/types.ts
  frontend/src/components/v2/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/slowQueryPolicy.ts
  frontend/src/types/plan.ts
  frontend/src/types/policy.ts
  frontend/src/utils/instance.ts
  frontend/src/utils/role.ts
  frontend/src/views/SettingSidebar.vue
  frontend/src/views/SettingWorkspaceSlowQuery.vue
Labels: cla-signed

#5418 chore: add delete cache api
  backend/api/v1/actuator_service.go
  backend/store/setting.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/actuator_service_grpc.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed, backport release/1.15.0

#5422 chore: cherry pick 1.15.0
  backend/api/v1/actuator_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/subscription_service.go
  backend/plugin/metric/reporter.go
  backend/plugin/metric/segment/mock.go
  backend/plugin/metric/segment/reporter.go
  backend/runner/metricreport/reporter.go
  backend/runner/taskrun/scheduler.go
  backend/server/issue.go
  backend/server/openapi_metric.go
  backend/server/openapi_sql.go
  backend/server/principal.go
  backend/server/server.go
  backend/server/sql.go
  backend/sql-server/metric.go
  backend/sql-server/server.go
  backend/store/setting.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/actuator_service_grpc.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#5423 chore: navigate external-url banner to the general setting
  frontend/src/locales/zh-CN.json
  frontend/src/views/BannerExternalUrl.vue
  frontend/src/views/SettingWorkspaceGeneral.vue
Labels: cla-signed

#5424 chore: check external url on resources depending on it
  backend/api/v1/common.go
  backend/api/v1/idp_service.go
  backend/api/v1/project_service.go
  backend/bin/server/cmd/root.go
  backend/server/project.go
  backend/server/project_webhook.go
Labels: cla-signed

#5426 chore: cleanup pg switchDB
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#5427 chore: cleanup non-pg migrator code
  backend/bin/bb/cmd/migrate.go
  backend/plugin/db/clickhouse/clickhouse_migration_schema.sql
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/collmod_migrationHistory_collection_command.json
  backend/plugin/db/mongodb/create_index_on_migrationHistory_collection_command.json
  backend/plugin/db/mongodb/migrate.go
  backend/plugin/db/mssql/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/plugin/db/mysql/mysql_migration_schema.sql
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/redis/migrate.go
  backend/plugin/db/redshift/migrate.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/snowflake/snowflake_migration_schema.sql
  backend/plugin/db/spanner/migrate.go
  backend/plugin/db/spanner/spanner_migration_schema.sql
  backend/plugin/db/sqlite/migrate.go
  backend/plugin/db/sqlite/sqlite.go
  backend/store/pg_engine.go
Labels: cla-signed

#5429 chore(frontend): translation for custom approval
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5430 chore: cleanup execute migration
  backend/bin/bb/cmd/migrate.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/migrate.go
  backend/plugin/db/mssql/migrate.go
  backend/plugin/db/mysql/migrate.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/redis/migrate.go
  backend/plugin/db/redshift/migrate.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/spanner/migrate.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/migrate.go
  backend/plugin/db/util/driverutil.go
  backend/utils/utils.go
Labels: cla-signed

#5431 feat(frontend): show current approver in issue list
  frontend/src/components/Issue/IssueTable.vue
  frontend/src/components/Issue/review/CurrentApprover.vue
  frontend/src/components/Issue/review/IssueReviewPanel.vue
  frontend/src/components/Issue/review/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/store/modules/issue.ts
Labels: cla-signed

#5428 feat: implement SyncSlowQuery for MySQL
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redis/sync.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/sync.go
  backend/plugin/parser/utils.go
  backend/plugin/parser/utils_test.go
Labels: cla-signed

#5432 chore: cleanup list migration history
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/migrate.go
  backend/plugin/db/mongodb/role.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/migrate.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/redis/migrate.go
  backend/plugin/db/redshift/migrate.go
  backend/plugin/db/snowflake/migrate.go
  backend/plugin/db/spanner/migrate.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/migrate.go
  backend/server/server.go
  backend/store/pg_engine.go
Labels: cla-signed

#5433 chore: cleanup db connection
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/clickhouse/migrate.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/migrate.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/mysql/restore.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/dump.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/sqlite/sync.go
  backend/plugin/db/util/driverutil.go
  backend/runner/rollbackrun/runner.go
  backend/runner/taskcheck/statement_advisor_composite_executor.go
  backend/runner/taskcheck/statement_affected_rows_report_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/server/issue.go
  backend/server/openapi_sql.go
  backend/server/sql.go
  backend/server/webhook.go
  backend/store/pg_engine.go
Labels: cla-signed

#5435 chore: add 2FA enabled column to member table
  frontend/src/components/MemberTable.vue
  frontend/src/views/SettingWorkspaceMember.vue
Labels: cla-signed

#5436 chore: use word rollout
  frontend/src/components/EnvironmentForm.vue
  frontend/src/components/EnvironmentForm/AssigneeGroupEditor.vue
  frontend/src/components/Issue/IssueBanner.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5434 chore: cleanup create database task code
  backend/plugin/db/redshift/redshift.go
  backend/runner/taskrun/database_create_executor.go
  backend/server/issue.go
  backend/tests/schema_update_test.go
  backend/tests/sync_schema_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#5437 chore: add `require_2fa` to workspace setting
  frontend/src/types/proto/store/setting.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/setting.pb.go
  proto/store/setting.proto
Labels: cla-signed

#5438 chore: cleanup driver interface where dump/syncdb should be applied to connected database
  backend/bin/bb/cmd/dump.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/clickhouse/dump.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/dump.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/dump.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redis/sync.go
  backend/plugin/db/redshift/dump.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/dump.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/dump.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/sqlite/sync.go
  backend/runner/anomaly/scanner.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/database_backup_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/utils/sdl_utils.go
  backend/utils/utils.go
Labels: cla-signed

#5439 chore: add require 2FA setting in UI
  frontend/src/bbkit/BBCheckbox.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5440 chore: cleanup getDBConnection()
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/sqlite/dump.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/sqlite/sync.go
  backend/server/server.go
  backend/store/pg_engine.go
  backend/store/pg_engine_test.go
  backend/store/store.go
Labels: cla-signed

#5441 chore: update redshift create database code
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#5442 chore: cleanup format error
  backend/plugin/db/util/driverutil.go
  backend/store/activity.go
  backend/store/anomaly.go
  backend/store/backup.go
  backend/store/data_source.go
  backend/store/database.go
  backend/store/db_schema.go
  backend/store/deploy.go
  backend/store/environment.go
  backend/store/external_approval.go
  backend/store/idp.go
  backend/store/inbox.go
  backend/store/instance.go
  backend/store/instance_user.go
  backend/store/issue.go
  backend/store/metric.go
  backend/store/pg_engine.go
  backend/store/pipeline.go
  backend/store/policy.go
  backend/store/principal.go
  backend/store/project.go
  backend/store/project_member.go
  backend/store/project_webhook.go
  backend/store/repository.go
  backend/store/setting.go
  backend/store/sheet.go
  backend/store/sheet_organizer.go
  backend/store/stage.go
  backend/store/stats.go
  backend/store/task.go
  backend/store/task_check_run.go
  backend/store/task_dag.go
  backend/store/task_run.go
  backend/store/vcs.go
Labels: cla-signed

#5444 fix: use the right database for metadata database for embedded case
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/store/pg_engine.go
  backend/utils/utils.go
Labels: cla-signed

#5443 chore: support outbound ip list
  backend/server/server.go
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/InstanceForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/setting.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/views/SettingWorkspaceGeneral.vue
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/setting.pb.go
  proto/store/setting.proto
Labels: cla-signed

#5445 chore: backfill metadata instance change history
  backend/bin/server/cmd/root.go
  backend/store/instance_change_history.go
  backend/store/pg_engine.go
Labels: cla-signed

#5446 chore: move metadata database schema initialization to separate function
  backend/store/pg_engine.go
  backend/store/pg_engine_test.go
Labels: cla-signed

#5448 chore: migrate metadata migration history to its own database and backfill data
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  backend/plugin/db/driver.go
  backend/server/server.go
  backend/store/instance_change_history.go
  backend/store/pg_engine.go
Labels: cla-signed

#5449 chore: use environment table to determine schema initialization
  backend/migrator/migrator.go
Labels: cla-signed

#5451 chore: cleanup deprecated pg migration functions
  backend/plugin/db/pg/migrate.go
  backend/plugin/db/pg/pg_migration_schema.sql
Labels: cla-signed

#5450 chore: cleanup bytebase database usage
  backend/migrator/migrator.go
  backend/plugin/db/driver.go
  backend/plugin/db/spanner/spanner.go
  backend/runner/taskrun/pitr_cutover_executor.go
Labels: cla-signed

#5452 chore: cleanup create database parameter
  backend/plugin/db/driver.go
  backend/plugin/db/oracle/migrate.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/util/driverutil.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/server/issue.go
  backend/utils/utils.go
Labels: cla-signed

#5453 feat(frontend): group databases by environment while transferring databases
  frontend/src/assets/css/tailwind.css
  frontend/src/bbkit/BBGrid/BBGrid.vue
  frontend/src/bbkit/types.ts
  frontend/src/components/TransferDatabaseForm/TransferMultipleDatabaseForm.vue
Labels: cla-signed

#5454 chore: cleanup change history store
  backend/store/instance_change_history.go
  backend/utils/utils.go
Labels: cla-signed

#5455 fix: use bytebase database for driver
  backend/server/server.go
Labels: cla-signed

#5456 feat(frontend): support filtering instance while transferring databases
  frontend/src/components/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/components/v2/Form/SearchBox.vue
  frontend/src/components/v2/Form/index.ts
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/components/v2/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5458 feat(frontend): support "Default" risk level as level=0
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/risk.ts
  frontend/src/utils/workspaceApprovalSetting.ts
Labels: cla-signed

#5457 chore: add require 2fa to actuator info
  backend/api/v1/actuator_service.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/activity.pb.go
  proto/generated-go/store/approval.pb.go
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/store/database.pb.go
  proto/generated-go/store/idp.pb.go
  proto/generated-go/store/issue.pb.go
  proto/generated-go/store/setting.pb.go
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/store/user.pb.go
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/bookmark_service.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/deployment.pb.go
  proto/generated-go/v1/environment_service.pb.go
  proto/generated-go/v1/externalvs_service.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/logging_service.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/review_service.pb.go
  proto/generated-go/v1/risk_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#5460 feat: add idx_slow_query_instance_id_log_date_ts on slow_query (instance_id, log_date_ts)
  backend/migrator/migration/dev/20230404000000##slow_query_table.sql
  backend/migrator/migration/dev/LATEST.sql
Labels: cla-signed

#5462 fix(frontend): make format statement feature works only for SQL language
  frontend/src/components/Issue/logic/common.ts
  frontend/src/components/MonacoEditor/MonacoEditor.vue
Labels: cla-signed

#5461 chore: update metric to add deployment mode
  backend/runner/metricreport/reporter.go
Labels: cla-signed

#5464 chore: revert BBCheckbox changes
  frontend/src/bbkit/BBCheckbox.vue
Labels: cla-signed

#5459 feat: add 2fa required page
  backend/api/v1/auth_service.go
  frontend/src/bbkit/BBAttention.vue
  frontend/src/bbkit/types.ts
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/MemberTable.vue
  frontend/src/layouts/DashboardLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/TwoFactorRequired.vue
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed

#5465 chore: use naiveui checkbox
  frontend/src/components/GeneralSetting/SecuritySetting.vue
Labels: cla-signed

#5467 chore: upgrade version to `1.16.0`
  scripts/VERSION
Labels: cla-signed

#5466 fix: stage activity begin
  backend/runner/taskrun/scheduler.go
Labels: cla-signed

#5468 feat(frontend): readable factor and operator texts for risk condition configuring
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/FactorSelect.vue
  frontend/src/components/CustomApproval/Settings/components/common/ExprEditor/components/OperatorSelect.vue
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed, backport release/1.16.0

#5472 fix(frontend): update default action key
  frontend/src/components/Issue/IssueStatusTransitionButtonGroup.vue
Labels: cla-signed

#5471 feat: add slow query syncer
  backend/component/state/state.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redis/sync.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/sync.go
  backend/runner/slowquerysync/syncer.go
  backend/server/server.go
  backend/store/policy.go
  backend/store/slow_query.go
  frontend/src/types/proto/store/slow_query.ts
  proto/gen/grpc-doc/store/README.md
  proto/generated-go/store/slow_query.pb.go
  proto/store/slow_query.proto
Labels: cla-signed

#5474 feat(sql-editor): remove incorrect actions from context menu
  frontend/src/utils/tab.ts
  frontend/src/views/sql-editor/AsidePanel/DatabaseTree.vue
Labels: cla-signed

#5475 chore: skip check external url when it's empty
  backend/api/v1/setting_service.go
  backend/server/setting.go
Labels: cla-signed, backport release/1.16.0

#5470 chore: add user emails to 2FA required warn message
  backend/api/v1/auth_service.go
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/MemberTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed, backport release/1.16.0

#5477 feat(frontend): show "waiting for my approval" section in issue list
  frontend/src/components/Issue/index.ts
  frontend/src/components/Issue/review/CurrentApprover.vue
  frontend/src/components/Issue/table/IssueTable.vue
  frontend/src/components/Issue/table/PagedIssueTable.vue
  frontend/src/components/Issue/table/WaitingForMyApprovalIssueTable.vue
  frontend/src/components/Issue/table/index.ts
  frontend/src/components/ProjectOverviewPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/logic/review/index.ts
  frontend/src/views/Home.vue
  frontend/src/views/IssueDashboard.vue
Labels: cla-signed

#5479 fix: field mask should use relative path
  backend/api/v1/acl.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_service.go
  backend/api/v1/environment_service.go
  backend/api/v1/externalvs_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/instance_role_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_service.go
  backend/api/v1/risk_service.go
  frontend/src/store/modules/idp.ts
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/risk.ts
  frontend/src/store/modules/user.ts
  frontend/src/store/modules/v1/environment.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/TwoFactorSetup.vue
Labels: cla-signed

#5482 chore: use consistent 双重认证 name for 2fa chinese
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5483 fix: remove goroutine
  backend/runner/metricreport/reporter.go
Labels: cla-signed, backport release/1.16.0

#5481 fix: support migrating instances prior to instance_change_history
  backend/migrator/migrator.go
Labels: cla-signed, backport release/1.16.0

#5488 cherrypick: [release/1.15.0]fix: remove goroutine (#5483)
  backend/runner/metricreport/reporter.go
Labels: cla-signed

#5490 feat(frontend): show a tips to configure risk rule if needed
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RiskTips.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RulesSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceCustomApproval.vue
Labels: cla-signed

#5491 chore: add redirect to SSO login
  frontend/src/utils/sso.ts
  frontend/src/views/OAuthCallback.vue
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#5493 feat(frontend): support filtering databases in project detail page's "Databases" panel
  frontend/src/components/ProjectDatabasesPanel.vue
Labels: cla-signed

#5496 fix: fetch the latest server info
  frontend/src/components/IdentityProviderCreateForm.vue
  frontend/src/components/MemberTable.vue
  frontend/src/store/modules/setting.ts
  frontend/src/views/SettingWorkspaceSSODetail.vue
  frontend/src/views/auth/MultiFactor.vue
Labels: cla-signed, backport release/1.16.0

#5498 fix: typo
  backend/server/sql.go
Labels: cla-signed

#5499 chore: disable schema version checks during migration
  backend/store/instance_change_history.go
  backend/utils/utils.go
Labels: cla-signed

#5501 chore: fetch user list when toggle 2fa required to prevent store cache
  frontend/src/components/GeneralSetting/SecuritySetting.vue
Labels: cla-signed, backport release/1.16.0

#5503 chore(frontend): feature guard for "waiting for my approval" issue list section
  frontend/src/components/ProjectOverviewPanel.vue
  frontend/src/views/Home.vue
Labels: cla-signed

#5505 chore: cleanup migration executor
  backend/migrator/migrator.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/pitr_cutover_executor.go
  backend/runner/taskrun/pitr_restore_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/utils/utils.go
Labels: cla-signed

#5506 chore: fix demo reset script to include new tables
  backend/migrator/demo/reset.sql
Labels: cla-signed

#5504 feat: implement sync slow query API
  backend/api/v1/instance_service.go
  backend/server/server.go
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#5507 fix: get projects id
  backend/api/v1/database_service.go
Labels: cla-signed

#5509 chore: remove “bytebase” as one of the PG guess dbs
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#5511 chore(frontend): update style for project overview page
  frontend/src/components/ProjectOverviewPanel.vue
Labels: cla-signed

#5519 fix: var name
  backend/server/sql.go
Labels: cla-signed

#5521 cherrypick: backend implementation of MySQL slow query logs (#5471 #5500 #5504 #5507)
  backend/api/v1/common.go
  backend/api/v1/common_test.go
  backend/api/v1/database_service.go
  backend/api/v1/instance_service.go
  backend/component/state/state.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redis/sync.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/sync.go
  backend/runner/slowquerysync/syncer.go
  backend/server/server.go
  backend/store/policy.go
  backend/store/slow_query.go
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/store/slow_query.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#5523 fix: plan type
  frontend/src/types/plan.ts
Labels: cla-signed, backport release/1.16.0

#5518 feat(frontend): add instance column to slow query log table
  frontend/src/components/SlowQuery/Panel/LogTable.vue
Labels: cla-signed

#5526 feat(frontend): update task and issue status transition limitations for assignee
  frontend/src/components/Issue/BatchIssueActions.vue
  frontend/src/components/Issue/IssueSidebar.vue
  frontend/src/components/Issue/logic/assignee.ts
  frontend/src/components/Issue/logic/transition.ts
  frontend/src/plugins/issue/logic/initialize/assignee.ts
  frontend/src/types/issue.ts
Labels: cla-signed

#5528 chore: skip sample instance during backfile history if bytebase db not found
  backend/resources/postgres/postgres.go
  backend/server/server.go
Labels: cla-signed

#5533 chore: retire seat limitation
  backend/api/v1/subscription_service.go
  backend/enterprise/api/license.go
  backend/enterprise/api/subscription.go
  backend/enterprise/config/config.go
  backend/enterprise/service/license.go
  backend/server/member.go
  backend/server/principal.go
  backend/tests/subscription_test.go
  frontend/src/locales/en-US.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/subscription.ts
  frontend/src/types/plan.ts
  frontend/src/types/plan.yaml
  frontend/src/types/proto/v1/subscription_service.ts
  frontend/src/views/SettingWorkspaceMember.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/subscription_service.proto
Labels: cla-signed

#5534 cherrypick: [release/1.16.0] chore: add more metrics (#5532)
  backend/api/v1/auth_service.go
  backend/api/v1/instance_service.go
  backend/metric/metric.go
  backend/server/instance.go
  backend/server/server.go
Labels: cla-signed

#5535 chore: bring rbac to free plan
  backend/legacyapi/plan.go
  frontend/src/types/plan.yaml
Labels: cla-signed

#5537 chore: update gitops plan
  backend/legacyapi/plan.go
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed

#5536 feat(frontend): slow query improvements
  backend/legacyapi/plan.go
  frontend/src/components/DatabaseSlowQueryPanel.vue
  frontend/src/components/SlowQuery/Panel/DetailDialog.vue
  frontend/src/components/SlowQuery/Panel/DetailPanel.vue
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/SlowQuery/Panel/LogTable.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/SlowQuery/Panel/types.ts
  frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/views/SettingWorkspaceSlowQuery.vue
Labels: cla-signed

#5540 chore: silence warning on bytebase database not found error
  backend/server/server.go
Labels: cla-signed, backport release/1.16.0

#5542 chore: update pricing plan for teams
  backend/enterprise/config/config.go
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/types/plan.yaml
Labels: cla-signed

#5547 docs: update instance limit
  frontend/src/types/plan.yaml
Labels: cla-signed

#5548 chore(cherry-pick): cherry pick #5530 to release 1.16.0
  backend/plugin/db/redshift/redshift.go
  backend/server/issue.go
  frontend/src/components/CreateDatabasePrepForm.vue
Labels: cla-signed

#5550 chore: remove shared SQL script feature from free plan
  backend/legacyapi/plan.go
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/types/plan.yaml
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#5549 refactor(frontend): extract reusable logic to judge if an instance supports collation and charset
  frontend/src/components/CreateDatabasePrepForm.vue
  frontend/src/utils/instance.ts
Labels: cla-signed

#5551 chore: check 2FA required when has feature
  frontend/src/router/index.ts
Labels: cla-signed, backport release/1.16.0

#5554 chore: switch the order of gitops workflow
  frontend/src/types/plan.yaml
Labels: cla-signed, backport release/1.16.0

#5546 fix: refresh expired license
  backend/enterprise/api/subscription.go
  backend/enterprise/service/license.go
  backend/server/server.go
  frontend/src/store/modules/subscription.ts
Labels: cla-signed, backport release/1.16.0

#5557 cherrypick: [release/1.16.0] fix: refresh expired license (#5546)
  backend/enterprise/api/subscription.go
  backend/enterprise/service/license.go
  backend/server/server.go
  frontend/src/store/modules/subscription.ts
Labels: cla-signed

#5558 chore: update pricing
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed, backport release/1.16.0

#5561 chore: skip mask sensitive data if no policy
  backend/server/sql.go
Labels: cla-signed

#5564 fix: skip JSON in ColumnDisallowSetCharset
  backend/plugin/advisor/mysql/advisor_column_disallow_set_charset.go
  backend/plugin/advisor/mysql/test/column_auto_increment_initial_value.yaml
  backend/plugin/advisor/mysql/test/column_auto_increment_must_integer.yaml
  backend/plugin/advisor/mysql/test/column_auto_increment_must_unsigned.yaml
  backend/plugin/advisor/mysql/test/column_comment.yaml
  backend/plugin/advisor/mysql/test/column_current_time_count_limit.yaml
  backend/plugin/advisor/mysql/test/column_disallow_change.yaml
  backend/plugin/advisor/mysql/test/column_disallow_change_type.yaml
  backend/plugin/advisor/mysql/test/column_disallow_changing_order.yaml
  backend/plugin/advisor/mysql/test/column_disallow_set_charset.yaml
  backend/plugin/advisor/mysql/test/column_maximum_character_length.yaml
  backend/plugin/advisor/mysql/test/column_no_null.yaml
  backend/plugin/advisor/mysql/test/column_require_default.yaml
  backend/plugin/advisor/mysql/test/column_required.yaml
  backend/plugin/advisor/mysql/test/column_set_default_for_not_null.yaml
  backend/plugin/advisor/mysql/test/column_type_disallow_list.yaml
  backend/plugin/advisor/mysql/test/database_drop_empty_database.yaml
  backend/plugin/advisor/mysql/test/engine_mysql_use_innodb.yaml
  backend/plugin/advisor/mysql/test/index_key_number_limit.yaml
  backend/plugin/advisor/mysql/test/index_no_duplicate_column.yaml
  backend/plugin/advisor/mysql/test/index_pk_type_limit.yaml
  backend/plugin/advisor/mysql/test/index_primary_key_type_allowlist.yaml
  backend/plugin/advisor/mysql/test/index_total_number_limit.yaml
  backend/plugin/advisor/mysql/test/index_type_no_blob.yaml
  backend/plugin/advisor/mysql/test/naming_column.yaml
  backend/plugin/advisor/mysql/test/naming_column_auto_increment.yaml
  backend/plugin/advisor/mysql/test/naming_index_fk.yaml
  backend/plugin/advisor/mysql/test/naming_index_idx.yaml
  backend/plugin/advisor/mysql/test/naming_index_uk.yaml
  backend/plugin/advisor/mysql/test/naming_table.yaml
  backend/plugin/advisor/mysql/test/schema_backward_compatibility.yaml
  backend/plugin/advisor/mysql/test/statement_affected_row_limit.yaml
  backend/plugin/advisor/mysql/test/statement_disallow_commit.yaml
  backend/plugin/advisor/mysql/test/statement_disallow_limit.yaml
  backend/plugin/advisor/mysql/test/statement_disallow_order_by.yaml
  backend/plugin/advisor/mysql/test/statement_dml_dry_run.yaml
  backend/plugin/advisor/mysql/test/statement_insert_disallow_order_by_rand.yaml
  backend/plugin/advisor/mysql/test/statement_insert_must_specify_column.yaml
  backend/plugin/advisor/mysql/test/statement_insert_row_limit.yaml
  backend/plugin/advisor/mysql/test/statement_merge_alter_table.yaml
  backend/plugin/advisor/mysql/test/statement_select_no_select_all.yaml
  backend/plugin/advisor/mysql/test/statement_where_no_leading_wildcard_like.yaml
  backend/plugin/advisor/mysql/test/statement_where_require.yaml
  backend/plugin/advisor/mysql/test/system_charset_allowlist.yaml
  backend/plugin/advisor/mysql/test/system_collation_allowlist.yaml
  backend/plugin/advisor/mysql/test/table_comment.yaml
  backend/plugin/advisor/mysql/test/table_disallow_partition.yaml
  backend/plugin/advisor/mysql/test/table_drop_naming_convention.yaml
  backend/plugin/advisor/mysql/test/table_no_foreign_key.yaml
  backend/plugin/advisor/mysql/test/table_require_pk.yaml
Labels: cla-signed, backport release/1.16.0

#5566 fix(risk): fall through to DEFAULT risk level correctly when risks are empty
  backend/runner/approval/runner.go
Labels: cla-signed, backport release/1.16.0

#5567 feat: update pricing and plan
  backend/legacyapi/plan.go
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/types/plan.yaml
Labels: cla-signed, backport release/1.16.0

#5569 fix: pricing
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/types/plan.ts
Labels: cla-signed, backport release/1.16.0

#5572 fix: strip task payload for saving issue response size at main page
  backend/legacyapi/task.go
  backend/store/issue.go
  backend/store/task.go
Labels: cla-signed, backport release/1.16.0

#5574 refactor: restructure metric enablement logic
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/profile_dev.go
  backend/bin/server/cmd/profile_release.go
  backend/component/config/profile.go
  backend/server/server.go
Labels: cla-signed

#5576 chore: tweak shared sql script wording
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#5577 chore: make all rules available in the free plan
  frontend/src/types/sqlReview.ts
Labels: cla-signed, backport release/1.16.0

#5579 fix: custom-approval i18n
  frontend/src/locales/subscription/en-US.json
  frontend/src/types/plan.yaml
Labels: cla-signed

#5584 chore: using 5439 as default port for redshift
  frontend/src/components/InstanceForm.vue
  frontend/src/utils/instance.ts
Labels: cla-signed, backport release/1.16.0

#5586 feat(frontend): slow query improvements 2
  frontend/src/bbkit/BBGrid/BBGrid.vue
  frontend/src/components/DatabaseSlowQueryPanel.vue
  frontend/src/components/ProjectSlowQueryPanel.vue
  frontend/src/components/SlowQuery/Panel/DetailPanel.vue
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/SlowQuery/Panel/LogTable.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/SlowQuery/Panel/types.ts
  frontend/src/components/v2/Model/ProjectName.vue
  frontend/src/components/v2/Model/index.ts
  frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/review.ts
  frontend/src/store/modules/slowQueryPolicy.ts
Labels: cla-signed

#5581 chore: improve quickstart
  frontend/public/help/en/help.project.md
  frontend/public/help/zh/help.project.md
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/Quickstart.vue
Labels: cla-signed

#5582 chore: minor touchup on setting project dashboard
  frontend/src/components/ProjectTable.vue
  frontend/src/views/Archive.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/SettingWorkspaceProject.vue
Labels: cla-signed

#5587 chore(frontend): hide service accounts in candidate list
  frontend/src/store/modules/review.ts
Labels: cla-signed

#5588 chore: remove readiness probe and external url
  docs/bytebase-1.0.2.tgz
  docs/index.yaml
  helm-charts/bytebase/Chart.yaml
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#5589 docs: remove the external url in helm README
  docs/bytebase-1.0.2.tgz
  docs/index.yaml
  helm-charts/bytebase/README.md
Labels: cla-signed

#5591 chore: update workspace id
  backend/api/v1/actuator_service.go
  backend/api/v1/subscription_service.go
  backend/runner/metricreport/reporter.go
  backend/server/project.go
  backend/server/server.go
  backend/server/webhook.go
  backend/store/setting.go
  backend/tests/schema_update_test.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed, backport release/1.16.0

#5592 chore: make proto generation easier
  proto/buf.gen.yaml
Labels: cla-signed

#5593 cherrypick: [release/1.16.0] chore: update workspace id (#5591)
  backend/api/v1/actuator_service.go
  backend/api/v1/subscription_service.go
  backend/runner/metricreport/reporter.go
  backend/server/project.go
  backend/server/server.go
  backend/server/webhook.go
  backend/store/setting.go
  backend/tests/schema_update_test.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#5594 docs: upgrade the remain version and external url in helm README
  docs/bytebase-1.0.2.tgz
  docs/index.yaml
  helm-charts/bytebase/README.md
Labels: cla-signed

#5597 feat(proto): custom role
  backend/api/v1/instance_role_service.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/role_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_role_service_grpc.pb.go
  proto/generated-go/v1/role_service.pb.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/role_service_grpc.pb.go
  proto/store/slow_query.proto
  proto/v1/actuator_service.proto
  proto/v1/database_service.proto
  proto/v1/instance_role_service.proto
  proto/v1/instance_service.proto
  proto/v1/role_service.proto
Labels: cla-signed

#5598 feat: support check slow query log enabled
  backend/api/v1/instance_service.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/sync.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/redis/sync.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/sqlite/sync.go
  backend/runner/slowquerysync/syncer.go
  backend/server/server.go
Labels: cla-signed

#5600 chore: disable auto trial
  frontend/src/views/Home.vue
  frontend/src/views/auth/Signup.vue
Labels: cla-signed, backport release/1.16.0

#5602 fix: clean duplicated email principals
  backend/migrator/migration/prod/1.16/0002##delete_email_duplicated_principal.sql
  backend/migrator/migrator_test.go
Labels: cla-signed, backport release/1.16.0

#5520 chore: only assignee can change task status
  backend/runner/taskrun/scheduler.go
  backend/server/stage.go
  backend/server/task.go
  backend/tests/backup_restore_test.go
  backend/tests/database.go
  backend/tests/ghost_test.go
  backend/tests/project_test.go
  backend/tests/rollback_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_review_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
Labels: cla-signed

#5599 chore: update slow query proto for PostgreSQL
  backend/api/v1/database_service.go
  backend/store/slow_query.go
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/slow_query.proto
  proto/v1/database_service.proto
Labels: cla-signed

#5590 feat(schema): custom role
  backend/migrator/migration/dev/LATEST.sql
  backend/migrator/migration/prod/1.17/0000##custom_role.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#5604 chore: signup to cloud directs to hub.bytebase.com/workspace
  frontend/src/views/BannerDemo.vue
Labels: cla-signed

#5596 feat(frontend): filter improvements
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/v2/Form/SearchBox.vue
  frontend/src/components/v2/Select/DatabaseSelect.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/PrincipalSelect.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/Home.vue
  frontend/src/views/IssueDashboard.vue
  frontend/src/views/ProjectDashboard.vue
Labels: cla-signed

#5595 chore(frontend): update slow log filter layout
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
Labels: cla-signed

#5605 chore: change contact us to Google form
  frontend/src/components/PricingTable/PricingTable.vue
Labels: cla-signed

#5608 fix: request token
  backend/enterprise/service/provider.go
Labels: cla-signed, backport release/1.16.0
