Repository bytebase/bytebase, pull requests merged in 2024-10, with the labels that each got.

#13914 chore: ddl filter
  backend/api/v1/database_service.go
  backend/plugin/db/driver.go
  backend/runner/schemasync/syncer.go
  frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/utils.ts
  frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
  frontend/src/store/modules/v1/changeHistory.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/utils/v1/changeHistory.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#13922 chore: pg-like timestamp
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/query.go
  backend/plugin/db/risingwave/risingwave.go
Labels: cla-signed

#13939 chore: sync instance button
  backend/api/v1/instance_service.go
  frontend/src/components/Instance/InstanceSyncButton.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
  frontend/src/store/modules/v1/instance.ts
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#13992 chore: revert 13925
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#13993 chore: mssql time
  backend/plugin/db/mssql/query.go
Labels: cla-signed

#13996 chore: mask on exceeded error
  backend/api/v1/query_result_masker.go
Labels: cla-signed

#13998 chore: oracle timestamptz
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/query.go
Labels: cla-signed

#13999 chore: oracle-like timestamptz
  backend/plugin/db/dm/dm.go
  backend/plugin/db/dm/query.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/obo/query.go
Labels: cla-signed

#14000 chore: timestamp proto
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14001 chore: use dedicated timestamptz proto
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/dm/query.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/obo/query.go
  backend/plugin/db/oracle/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/risingwave/query.go
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/utils/v1/sql.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14002 chore: mysql timestamp
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/mysql/query.go
  backend/plugin/db/starrocks/query.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/query.go
  backend/plugin/db/tidb/tidb.go
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#14003 chore: pg timestamp
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/risingwave/query.go
Labels: cla-signed

#14004 chore: mssql/oracle timestamp
  backend/plugin/db/dm/query.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/obo/query.go
  backend/plugin/db/oracle/query.go
Labels: cla-signed

#14006 chore: oracle package
  backend/api/v1/database_converter.go
  backend/common/db_schema.go
  backend/plugin/db/oracle/sync.go
  backend/store/model/database.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14009 feat: implement lsp ping
  backend/api/lsp/handler.go
Labels: cla-signed

#14010 fix: missing record when switch the project
  frontend/src/router/useRecentVisit.ts
Labels: cla-signed

#14007 chore: bump version
  backend/demo/data/default/README.md
  helm-charts/bytebase/values.yaml
  scripts/VERSION
Labels: cla-signed

#14005 fix: timestamp export
  backend/api/v1/sql_service_export_utils.go
  backend/component/masker/masker.go
Labels: cla-signed

#14011 fix(restore): use original set field text
  backend/plugin/parser/pg/restore.go
  backend/plugin/parser/pg/test-data/test_restore.yaml
Labels: cla-signed

#14013 feat(proto): preview plan
  backend/migrator/migration/dev/20240924000001##revision.sql
  frontend/src/types/proto/store/revision.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/generated-go/v1/plan_service.pb.gw.go
  proto/generated-go/v1/plan_service_grpc.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#14012 chore: add missing feature guard
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/index.vue
Labels: cla-signed

#14014 chore: mariadb ghost rule
  backend/plugin/advisor/mysql/advisor_online_migration.go
  backend/plugin/advisor/sql_review.go
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14017 chore: preview plan
  backend/api/v1/database_service_revision.go
  backend/api/v1/plan_service.go
  backend/api/v1/release_service.go
  backend/common/resource_name.go
  backend/store/release.go
  backend/store/revision.go
Labels: cla-signed

#14019 fix: typo
  backend/plugin/advisor/mysql/advisor_table_comment_convention.go
  backend/plugin/advisor/tidb/advisor_table_comment_convention.go
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14018 chore: update ghost checks for mariadb
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#14020 feat(query-span): support variables in function for PG
  backend/plugin/parser/pg/pg.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/test-data/query_span.yaml
  go.mod
  go.sum
Labels: cla-signed

#14023 chore: allow onboarding project modify sql and auto resolve
  backend/server/onboard.go
Labels: cla-signed

#14024 fix: expect null in mysql show create func
  backend/plugin/db/mysql/sync.go
Labels: cla-signed

#14026 chore: update proto to configure DDL/DML in sql editor
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#14027 fix(completion): break for the first statement
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/partiql/completion.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/plsql/completion.go
  backend/plugin/parser/tsql/completion.go
Labels: cla-signed

#14028 fix: nil vcs source
  backend/api/v1/release_service.go
Labels: cla-signed

#14030 chore: show error message when failed to request openid configuration
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#14029 chore: configure exec ddl/dml environment policy
  backend/api/v1/org_policy_service.go
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/EditorCommon/ExecutingHintModal.vue
Labels: cla-signed

#14031 fix(restore): pg set target
  backend/plugin/parser/pg/pg.go
  backend/plugin/parser/pg/restore.go
  backend/plugin/parser/pg/test-data/test_restore.yaml
Labels: cla-signed

#14032 chore: update release related pages
  backend/api/v1/release_service.go
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/MigrationFileTable/MigrationFileTable.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabaseButton.vue
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/ProjectReleaseDetail.vue
Labels: cla-signed

#14033 chore(sql-editor): minor fixes for auto-table resizing
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/useTableResize.ts
Labels: cla-signed

#14035 chore: add statement to `release.file`
  backend/api/v1/release_service.go
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/DatabaseAndGroupSelector/index.ts
  frontend/src/components/DatabaseAndGroupSelector/types.ts
  frontend/src/components/Release/ReleaseDetail/MigrationFileTable/MigrationFileTable.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabaseButton.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14036 fix: task run sync db log
  backend/runner/taskrun/schema_update_executor.go
Labels: cla-signed

#14034 chore: check ddl/dml policy
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14037 feat(restore): implement MSSQL one-click restore
  backend/plugin/parser/tokenizer/tokenizer.go
  backend/plugin/parser/tsql/restore.go
  backend/plugin/parser/tsql/restore_test.go
  backend/plugin/parser/tsql/test-data/test_restore.yaml
  backend/plugin/parser/tsql/tsql.go
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
Labels: cla-signed

#14038 refactor: execute migration
  backend/migrator/migrator.go
  backend/plugin/db/driver.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/utils/utils.go
Labels: cla-signed

#14039 chore: add release file detail panel
  frontend/src/components/Release/ReleaseDetail/MigrationFileTable/index.ts
  frontend/src/components/Release/ReleaseDetail/ReleaseDetail.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/index.ts
Labels: cla-signed

#14042 fix: avoid creating existed schema
  backend/api/v1/branch_service.go
  backend/api/v1/branch_service_test.go
Labels: cla-signed

#14044 chore: update
  backend/migrator/migration/dev/20240924000000##release.sql
  backend/migrator/migration/dev/20240924000001##revision.sql
Labels: cla-signed

#14043 fix(query-span): fix nil ctx
  backend/plugin/parser/tsql/query_span_extractor.go
Labels: cla-signed

#14047 refactor: migrate context
  backend/common/resource_name.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
Labels: cla-signed

#14048 feat: store release source in plan
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/store/plan.proto
  proto/v1/plan_service.proto
Labels: cla-signed

#14050 chore: show release info in issue page
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/useTaskSheet.ts
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/MonacoEditor/lsp-client.ts
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/store/cache.ts
  frontend/src/store/modules/release.ts
  frontend/src/store/modules/v1/policy.ts
Labels: cla-signed

#14051 feat(sql-editor): AI Assistant improvements
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/ActionBar.vue
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/ChatView/AIMessageView.vue
  frontend/src/plugins/ai/components/ChatView/Markdown/CodeBlock.vue
  frontend/src/plugins/ai/components/ChatView/Markdown/InsertAtCaretIcon.vue
  frontend/src/plugins/ai/components/ChatView/Markdown/Markdown.vue
  frontend/src/plugins/ai/components/ChatView/UserMessageView.vue
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
  frontend/src/plugins/ai/components/HistoryPanel/HistoryPanel.vue
  frontend/src/plugins/ai/components/PromptInput.vue
  frontend/src/plugins/ai/components/editor-actions.ts
  frontend/src/plugins/ai/logic/prompt.ts
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/views/sql-editor/EditorCommon/OpenAIButton/OpenAIButton.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DefinitionViewer.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/common/CodeViewer.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#14053 chore: update release title
  backend/api/v1/release_service.go
  backend/store/release.go
  frontend/src/components/Release/ReleaseDetail/NavBar/TitleEditor.vue
Labels: cla-signed

#14049 feat: task release source
  backend/api/v1/rollout_service_task.go
  frontend/src/types/proto/store/task.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/task.pb.go
  proto/store/task.proto
Labels: cla-signed

#14052 feat: ignore alloydbmetadata database
  backend/plugin/parser/pg/system_objects.go
Labels: cla-signed

#14055 docs: improve error
  backend/api/v1/org_policy_service.go
Labels: cla-signed

#14058 chore: use `Expr` instead of `ParsedExpr` to avoid the redundant `SourceInfo`
  backend/api/v1/cel_service.go
  backend/api/v1/project_service.go
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RuleTemplateTable.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/plugins/cel/logic/build.ts
  frontend/src/store/modules/dbGroup.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/cel_service.ts
  frontend/src/types/proto/v1/iam_policy.ts
  frontend/src/utils/databaseGroup/cel.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/utils/v1/cel.ts
  frontend/src/utils/v1/iam.ts
  frontend/src/utils/workspaceApprovalSetting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/cel_service.pb.go
  proto/generated-go/v1/iam_policy.pb.go
  proto/store/setting.proto
  proto/v1/cel_service.proto
  proto/v1/iam_policy.proto
Labels: cla-signed

#14057 chore: update ghost checks for release
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/Project/ProjectReleasesPanel.vue
Labels: cla-signed

#14059 feat(lsp): return all columns for the no table case
  backend/plugin/parser/pg/completion.go
Labels: cla-signed

#14060 chore: rollback schema
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/Instance/InstanceSyncButton.vue
  frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
  frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/ProjectSyncDatabasePanel.vue
Labels: cla-signed

#14061 chore: file path url escape
  backend/api/v1/plan_service.go
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/store/task.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/plan.pb.go
  proto/generated-go/store/task.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/store/plan.proto
  proto/store/task.proto
  proto/v1/plan_service.proto
Labels: cla-signed

#14062 feat(lsp): return all columns for MySQL no table case
  backend/plugin/parser/mysql/completion.go
Labels: cla-signed

#14063 feat(plsql-lsp): return all columns for no table
  backend/plugin/parser/plsql/completion.go
  backend/plugin/parser/plsql/test-data/test_completion.yaml
Labels: cla-signed

#14064 fix: typo
  backend/legacyapi/task.go
Labels: cla-signed

#14065 feat(mssql-lsp): return all columns for no table
  backend/api/lsp/completion.go
  backend/plugin/parser/tsql/completion.go
  backend/plugin/parser/tsql/test-data/test_completion.yaml
Labels: cla-signed

#14068 chore: add phone country code prefix in the hint
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14066 fix(lsp): append definition to candidate ID
  backend/plugin/parser/base/complete.go
  backend/plugin/parser/plsql/test-data/test_completion.yaml
Labels: cla-signed

#14069 feat: insert revision on success
  backend/common/resource_name.go
  backend/runner/taskrun/executor.go
  backend/store/revision.go
Labels: cla-signed

#14072 chore(sql-editor): default route for EDITOR mode should go before isDev
  frontend/src/DummyRootView.ts
Labels: cla-signed

#14071 chore(sql-editor): AI assistant minor updates
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
  frontend/src/plugins/ai/components/ProvideAIContext.vue
  frontend/src/plugins/ai/logic/prompt.ts
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/plugins/ai/types/context.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/state.ts
Labels: cla-signed

#14070 chore: allow_missing for group and role
  backend/api/v1/group_service.go
  backend/api/v1/role_service.go
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
  frontend/src/store/modules/role.ts
  frontend/src/store/modules/v1/group.ts
  frontend/src/types/proto/v1/group.ts
  frontend/src/types/proto/v1/role_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/group.pb.go
  proto/generated-go/v1/group.pb.gw.go
  proto/generated-go/v1/role_service.pb.go
  proto/v1/group.proto
  proto/v1/role_service.proto
Labels: cla-signed

#14067 chore: update release detail page
  frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseDetail.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
Labels: cla-signed

#14075 fix: fix unit tests
  backend/plugin/parser/tsql/completion_test.go
  backend/plugin/parser/tsql/test-data/test_completion.yaml
Labels: cla-signed

#14073 chore: dev release revision sql
  backend/migrator/migration/dev/20241014000000##release.sql
  backend/runner/taskrun/executor.go
  backend/store/revision.go
Labels: cla-signed

#14074 feat(pg): changed resources support DML
  backend/plugin/parser/pg/resource_change.go
  backend/plugin/parser/pg/resource_change_test.go
Labels: cla-signed

#14076 chore: add statement to revision
  backend/api/v1/database_service_revision.go
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14078 feat(oracle): changed resources support DML
  backend/plugin/parser/plsql/resource_change.go
  backend/plugin/parser/plsql/resource_change_test.go
Labels: cla-signed

#14079 feat: detect duplicate version in revisions
  backend/runner/taskrun/executor.go
  backend/store/revision.go
Labels: cla-signed

#14080 chore: fix revision order by
  backend/store/revision.go
Labels: cla-signed

#14083 feat: add revisions tab to database detail page
  frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/Revision/PagedRevisionTable.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/Revision/index.ts
  frontend/src/views/DatabaseDetail.vue
Labels: cla-signed

#14086 chore(store): implement deleting release&revision
  backend/api/v1/instance_service.go
  backend/migrator/migration/dev/20241014000001##release.sql
  backend/store/instance.go
  backend/store/release.go
  backend/store/revision.go
Labels: cla-signed

#14082 chore: disallow to create issue if generate statement failed
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/SchemaDesignEditorLite.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/components/SchemaEditorLite/common.ts
  frontend/src/components/SchemaEditorLite/utils/metadata.ts
Labels: cla-signed

#14088 chore: implement delete/undelete release
  backend/api/v1/release_service.go
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/generated-go/v1/release_service.pb.gw.go
  proto/generated-go/v1/release_service_grpc.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14087 chore: implement delete revision
  backend/api/v1/database_service_revision.go
  backend/common/resource_name.go
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14089 fix: failed to set expiration time
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
Labels: cla-signed

#14090 feat: scheduler versioned
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/task.go
Labels: cla-signed

#14091 chore(api): implement get revision
  backend/api/v1/database_service_revision.go
  backend/api/v1/plan_service.go
  backend/common/resource_name.go
  backend/runner/taskrun/executor.go
  backend/store/revision.go
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/generated-go/v1/release_service.pb.go
  proto/generated-go/v1/release_service.pb.gw.go
  proto/v1/database_service.proto
Labels: cla-signed

#14092 chore(sql-editor): cherry-pick some AI Assistant fixes to 2.23.1
  frontend/src/DummyRootView.ts
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
  frontend/src/plugins/ai/components/ProvideAIContext.vue
  frontend/src/plugins/ai/logic/prompt.ts
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/plugins/ai/types/context.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/state.ts
Labels: cla-signed

#14093 chore: revision detail panel
  backend/api/v1/rollout_service.go
  backend/store/task_run.go
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/revision.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14095 fix: missing issue description from plan
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
Labels: cla-signed

#14096 feat(fe): scheduler info blocking task for versioned
  backend/runner/taskrun/schedulerv2.go
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
Labels: cla-signed

#14097 feat: introduce DiffSchema ignore backup schema for API
  frontend/src/components/IssueV1/components/StatementSection/SDLView/useSDLState.ts
  frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14094 chore(sql-editor): reset unrelated view state when adding new tab
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#14102 chore: revert(14097) introduce DiffSchema ignore backup schema for API
  frontend/src/components/IssueV1/components/StatementSection/SDLView/useSDLState.ts
  frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14099 chore(sql-editor): show spinner while initializing AI chat
  frontend/src/plugins/ai/components/ChatPanel.vue
Labels: cla-signed

#14100 feat(sql-review-rule): require algorithm/lock options for mysql&mariadb
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mysql/advisor_stmt_require_algorithm_or_lock_options.go
  backend/plugin/advisor/mysql/mysql_rules_test.go
  backend/plugin/advisor/mysql/test/statement_require_algorithm_option.yaml
  backend/plugin/advisor/mysql/test/statement_require_lock_option.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#14103 feat: impl previewPlan files warning
  backend/api/v1/plan_service.go
  backend/common/resource_name.go
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#14105 chore: remove dev guard
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
Labels: cla-signed

#14104 chore(sql-editor): auto-route should go to sql-editor routes only when databaseChangeMode is EDITOR
  frontend/src/utils/auto-route.ts
Labels: cla-signed

#14107 feat(differ): ignore backup schema for PG in schema synchronization
  backend/api/v1/database_service.go
  backend/plugin/parser/pg/filter.go
  backend/plugin/parser/pg/filter_test.go
  backend/plugin/parser/pg/pg.go
  backend/plugin/parser/pg/test-data/filter.yaml
  frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/utils/v1/instance.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14108 feat: introduce new google sql parser
  backend/plugin/parser/bigquery/bigquery.go
  go.mod
  go.sum
Labels: cla-signed

#14106 feat: seperate rules for mixing ddl&dml
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mssql/advisor_statement_disallow_mix_in_ddl.go
  backend/plugin/advisor/mssql/advisor_statement_disallow_mix_in_dml.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_mix_in_ddl.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_mix_in_dml.go
  backend/plugin/advisor/oracle/advisor_statement_disallow_mix_in_ddl.go
  backend/plugin/advisor/oracle/advisor_statement_disallow_mix_in_dml.go
  backend/plugin/advisor/pg/advisor_statement_disallow_mix_in_ddl.go
  backend/plugin/advisor/pg/advisor_statement_disallow_mix_in_dml.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/advisor_statement_disallow_mix_in_ddl.go
  backend/plugin/advisor/tidb/advisor_statement_disallow_mix_in_dml.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.dev.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14111 test: fix unit tests
  backend/plugin/parser/mysql/completion_test.go
  backend/plugin/parser/mysql/test-data/test_completion.yaml
  backend/plugin/parser/pg/completion_test.go
  backend/plugin/parser/pg/test-data/test_completion.yaml
  backend/plugin/parser/plsql/completion_test.go
  backend/plugin/parser/plsql/test-data/test_completion.yaml
Labels: cla-signed

#14110 chore(query-span): ignore cluster name for StarRocks
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/span.go
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/query_span_test.go
  backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml
Labels: cla-signed, backport release/2.23.1

#14113 feat(sql-review): table comment convention for postgres
  backend/plugin/advisor/code.go
  backend/plugin/advisor/pg/advisor_table_comment_convention.go
  backend/plugin/advisor/pg/pg_rules_test.go
  backend/plugin/advisor/pg/test/table_comment.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/sql/engine/pg/convert.go
  backend/tests/sql_review_test.go
  backend/tests/test-data/sql_review_pg.yaml
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14116 fix(iam): batch update issue status
  backend/api/v1/acl.go
Labels: cla-signed, backport release/2.23.0, backport release/2.23.1

#14120 feat(test): disallow mix in ddl/dml
  backend/plugin/advisor/mssql/mssql_rules_test.go
  backend/plugin/advisor/mssql/test/statement_disallow_mix_in_ddl.yaml
  backend/plugin/advisor/mssql/test/statement_disallow_mix_in_dml.yaml
  backend/plugin/advisor/mysql/mysql_rules_test.go
  backend/plugin/advisor/mysql/test/statement_disallow_mix_in_ddl.yaml
  backend/plugin/advisor/mysql/test/statement_disallow_mix_in_dml.yaml
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/statement_disallow_mix_in_ddl.yaml
  backend/plugin/advisor/oracle/test/statement_disallow_mix_in_dml.yaml
  backend/plugin/advisor/pg/pg_rules_test.go
  backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
  backend/plugin/advisor/pg/test/statement_disallow_mix_in_ddl.yaml
  backend/plugin/advisor/pg/test/statement_disallow_mix_in_dml.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/test/statement_disallow_mix_in_ddl.yaml
  backend/plugin/advisor/tidb/test/statement_disallow_mix_in_dml.yaml
  backend/plugin/advisor/tidb/tidb_rules_test.go
  backend/plugin/advisor/utils_for_tests.go
Labels: cla-signed

#14121 feat(sql-review): table comment convention for oracle
  backend/plugin/advisor/code.go
  backend/plugin/advisor/oracle/advisor_table_comment_convention.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/table_comment.yaml
  backend/plugin/advisor/pg/advisor_column_comment_convention.go
  backend/plugin/advisor/pg/advisor_table_comment_convention.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/plsql/util.go
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14124 fix: remove sql review rule without engine
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed

#14109 chore: query permissions
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
Labels: cla-signed

#14127 chore: add table comment rule to oceanbase oracle
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14128 feat(proto): introduce function signature
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14130 feat(sql-review): column comment convention for oracle
  backend/plugin/advisor/code.go
  backend/plugin/advisor/oracle/advisor_column_comment_convention.go
  backend/plugin/advisor/oracle/advisor_table_comment_convention.go
  backend/plugin/advisor/oracle/advisor_table_no_foreign_key.go
  backend/plugin/advisor/oracle/advisor_table_require_pk.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/parser.go
  backend/plugin/advisor/oracle/test/column_comment.yaml
  backend/plugin/advisor/sql_review.go
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14129 fix: exec ddl/dml
  frontend/src/composables/useExecuteSQL.ts
Labels: cla-signed

#14132 chore: implement delete revisions of database
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/Database/context.ts
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/revision.ts
  frontend/src/views/DatabaseDetail.vue
Labels: cla-signed

#14131 feat(sql-editor): show function signature instead of name
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
Labels: cla-signed

#14134 chore: update revision detail panel
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14135 chore: move masking column page to data masking tab
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/components/v2/Select/GroupSelect.vue
  frontend/src/components/v2/Select/UserSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/router/index.ts
  frontend/src/router/sqlEditor.ts
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/SettingWorkspaceDataAccessControl.vue
  frontend/src/views/SettingWorkspaceDataMasking.vue
  frontend/src/views/sql-editor/EditorCommon/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/Setting/AccessControl/AccessControl.vue
  frontend/src/views/sql-editor/Setting/AccessControl/index.ts
  frontend/src/views/sql-editor/Setting/AuditLog/AuditLog.vue
  frontend/src/views/sql-editor/Setting/DataClassification/DataClassification.vue
  frontend/src/views/sql-editor/Setting/DataMasking/DataMasking.vue
  frontend/src/views/sql-editor/Setting/Database/Database.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  frontend/src/views/sql-editor/Setting/Members/Members.vue
  frontend/src/views/sql-editor/Setting/Profile/Profile.vue
  frontend/src/views/sql-editor/Setting/Project/Project.vue
  frontend/src/views/sql-editor/Setting/Roles/Roles.vue
  frontend/src/views/sql-editor/Setting/SSO/SSO.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
  frontend/src/views/sql-editor/Setting/Subscription/Subscription.vue
Labels: cla-signed

#14133 fix(sql-review): run set role for Query
  backend/plugin/advisor/mysql/advisor_insert_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
  backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/mysql/advisor_statement_query_minumum_plan_level.go
  backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go
  backend/plugin/advisor/oracle/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/pg/advisor_insert_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/tidb/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/utils.go
Labels: cla-signed

#14136 feat(bigquery): bigquery query span simple select *
  backend/plugin/parser/bigquery/query_span_extractor.go
  backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
  go.mod
  go.sum
Labels: cla-signed

#14137 feat: migrate disallow mix ddl dml
  backend/migrator/migration/prod/3.0/0000##migrate_ddl_dml_mix_rule.sql
  backend/migrator/migrator_test.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mssql/advisor_statement_disallow_mix_ddl_dml.go
  backend/plugin/advisor/mssql/mssql_rules_test.go
  backend/plugin/advisor/mssql/test/statement_disallow_mix_ddl_dml.yaml
  backend/plugin/advisor/mysql/advisor_statement_disallow_mix_ddl_dml.go
  backend/plugin/advisor/mysql/mysql_rules_test.go
  backend/plugin/advisor/mysql/test/statement_disallow_mix_ddl_dml.yaml
  backend/plugin/advisor/oracle/advisor_statement_disallow_mix_ddl_dml.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/statement_disallow_mix_ddl_dml.yaml
  backend/plugin/advisor/pg/advisor_statement_disallow_mix_ddl_dml.go
  backend/plugin/advisor/pg/test/statement_disallow_mix_ddl_dml.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/advisor_statement_disallow_mix_ddl_dml.go
  backend/plugin/advisor/tidb/test/statement_disallow_mix_ddl_dml.yaml
  backend/plugin/advisor/utils_for_tests.go
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.dev.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14138 chore: bump version to 3.0.0
  scripts/VERSION
Labels: cla-signed

#14140 chore(sql-review-rules): require charset/collation for tables in mysql
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mysql/advisor_table_require_charset.go
  backend/plugin/advisor/mysql/advisor_table_require_collation.go
  backend/plugin/advisor/sql_review.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14141 chore(sql-review-rules): require charset/collation for columns in mysql
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mysql/advisor_column_require_charset.go
  backend/plugin/advisor/mysql/advisor_column_require_collation.go
  backend/plugin/advisor/sql_review.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14142 fix: i18n
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14143 chore: introduce database owner and schema owner
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14144 fix: update approval setting checks
  frontend/src/utils/workspaceApprovalSetting.ts
Labels: cla-signed

#14146 feat: sync pg owner
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/sync.go
  backend/tests/schema_update_test.go
  backend/tests/syncer_test.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14145 chore: update the link
  docs/schema-update-guide.md
Labels: cla-signed

#14147 chore: negative serial number
  go.mod
Labels: cla-signed

#14149 fix: only show statement exec policy for environment resource
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
Labels: cla-signed

#14151 fix: mysql limit rewriter should respect `LIMIT m,n`
  backend/plugin/db/mysql/query.go
  backend/plugin/db/mysql/query_test.go
Labels: cla-signed, backport release/2.22.3

#14155 fix: add conciseHistory for Postgres and Oracle in ProjectSyncDatabasePanel
  frontend/src/views/project/ProjectSyncDatabasePanel.vue
Labels: cla-signed

#14150 chore: optimize database resource selector
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/index.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/types/member.ts
  frontend/src/types/quickAction.ts
  frontend/src/views/project/ProjectDatabaseMaskingAccess.vue
Labels: cla-signed

#14163 chore: use database resource selector for masking exception
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/index.vue
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/components/SensitiveData/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#14159 feat: preview plan before creating issue
  backend/api/v1/plan_service.go
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/utils.ts
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/v2/Form/StepTab.vue
  frontend/src/components/v2/Model/DatabaseView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14158 chore(sql-editor): wording
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#14156 feat(sql-editor): support upload sql file
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/misc/SQLUploadButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/UploadFileButton.vue
Labels: cla-signed

#14164 chore: get query type interface
  backend/plugin/parser/base/interface.go
Labels: cla-signed

#14167 feat: changelog sync_history
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_baseline_executor.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_sdl_executor.go
  backend/store/changelog.go
  backend/store/sync_history.go
  frontend/src/types/proto/store/changelog.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/changelog.pb.go
  proto/store/changelog.proto
Labels: cla-signed

#14166 chore: allow select any databases or tables for masking exception
  backend/api/v1/masking_evaluator.go
  backend/api/v1/org_policy_service.go
  backend/common/cel.go
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/components/MaskingLevelDropdown.vue
  frontend/src/components/SensitiveData/utils.ts
  frontend/src/components/v2/Button/MiniActionButton.vue
  frontend/src/locales/zh-CN.json
  frontend/src/types/member.ts
Labels: cla-signed

#14157 feat(sql-review): implement object owner check rule
  backend/plugin/advisor/builtin_rules.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/pg/advisor_builtin_object_owner_check.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/sql/ast/variable_set_stmt.go
  backend/store/model/database.go
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
Labels: cla-signed

#14161 feat: bigquery simple projecter
  backend/plugin/parser/bigquery/query_span_extractor.go
  backend/plugin/parser/bigquery/query_span_test.go
  backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
  go.mod
  go.sum
Labels: cla-signed

#14168 chore: better error for wrong API url
  backend/server/server.go
Labels: cla-signed

#14173 docs: update readme
  README.md
Labels: cla-signed

#14175 chore: remove unused release when creating issue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
Labels: cla-signed

#14172 refactor: merge query span query type
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/span.go
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/query_span_test.go
  backend/plugin/parser/mysql/query_type.go
  backend/plugin/parser/mysql/query_type_test.go
  backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
  backend/plugin/parser/mysql/test-data/query-span/query_type.yaml
  backend/plugin/parser/mysql/test-data/query-span/standard.yaml
  backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml
  backend/plugin/parser/mysql/test-data/test_query_type.yaml
  backend/plugin/schema/oracle/get_design_schema_test.go
Labels: cla-signed

#14176 chore: add checkbox for allow out of order
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14174 chore: masking exception user table
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/types.ts
  frontend/src/types/member.ts
  frontend/src/utils/issue/cel.ts
Labels: cla-signed

#14177 feat: upgrade pgquery go to solve cursor type parsing
  go.mod
  go.sum
Labels: cla-signed

#14178 chore: unify inputs size
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#14180 chore(sql-editor): fix auto height when zoomed
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#14181 fix: typo
  backend/api/v1/sql_service.go
Labels: cla-signed
