Repository bytebase/bytebase, pull requests merged in 2024-09, with the labels that each got.

#13621 fix: stringify table default value
  backend/plugin/schema/mysql/stringify_table.go
Labels: cla-signed

#13620 fix: allow json and jsonb to recordset
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/test-data/query_span.yaml
Labels: cla-signed

#13622 chore(sql-editor): move the Text2SQL button
  frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/OpenAIButton.vue
Labels: cla-signed

#13623 feat(backup): backup in one table for large scale update statements for mssql
  backend/plugin/parser/tsql/backup.go
  backend/plugin/parser/tsql/test-data/test_backup.yaml
Labels: cla-signed

#13624 chore: extend expiration time
  backend/plugin/webhook/wecom/app.go
Labels: cla-signed

#13625 chore(sql-editor): prevent accidentally triggering the browsers go back gesture in SQL editor's result data table
  frontend/src/utils/dom.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#13626 fix: correct proto cmp
  backend/api/v1/branch_service.go
Labels: cla-signed

#13628 chore: fix user avatar title
  frontend/src/components/IssueV1/components/IssueTableV1.vue
Labels: cla-signed

#13627 chore: use `NEllipsis` in task run log detail cell
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DatabaseSyncCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/ErrorCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/StatusUpdateCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/TransactionControlCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
Labels: cla-signed

#13629 chore: tweak index name for mysql&tidb
  frontend/src/components/SchemaEditorLite/Aside/Tree.vue
  frontend/src/components/SchemaEditorLite/Modals/TableNameModal.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorLite/edit.ts
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#13630 chore: skip domain checks for workspace admin
  backend/api/v1/auth_service.go
Labels: cla-signed

#13631 fix: webhook notifs should skip deleted users
  backend/component/webhook/manager.go
Labels: cla-signed

#13632 chore: improve SQL review policy wording
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13633 feat: equal table tests foreign key
  backend/common/db_schema.go
Labels: cla-signed

#13634 feat: handle update table comment
  backend/api/v1/branch_merge.go
Labels: cla-signed

#13636 fix: lsp handle textDocument/didChange Range in UTF-16
  backend/api/lsp/completion.go
  backend/api/lsp/fs.go
  backend/api/lsp/utils.go
  backend/api/lsp/utils_test.go
  backend/api/lsp/utls.go
Labels: cla-signed

#13635 chore: support AAD group sync with members
  backend/api/directory-sync/webhook.go
  frontend/src/components/User/Settings/AADSyncDrawer.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#13637 chore(schema-editor): fix partition edit status pollution by name
  frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/PreviewPane.vue
Labels: cla-signed

#13638 chore: tweak linter warning
  frontend/src/components/User/Settings/AADSyncDrawer.vue
Labels: cla-signed

#13640 chore(schema-editor): keep tab status when toggling edit mode
  frontend/src/components/SchemaEditorLite/Aside/Tree.vue
  frontend/src/components/SchemaEditorLite/algorithm/rebuild.ts
Labels: cla-signed

#13642 chore: tweak prior backup check wording
  backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
  backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go
Labels: cla-signed

#13639 chore(schema-editor): default sub partition type
  frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
Labels: cla-signed

#13644 chore: tweak rollback issue description to add spacing
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
Labels: cla-signed

#13641 chore: split where required rule into separate rules for select statements and update/delete statements
  backend/plugin/advisor/change_type.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mssql/advisor_statement_where_requirement_for_select.go
  backend/plugin/advisor/mssql/advisor_statement_where_requirement_for_update_delete.go
  backend/plugin/advisor/mssql/mssql_rules_test.go
  backend/plugin/advisor/mssql/test/statement_where_require.yaml
  backend/plugin/advisor/mssql/test/statement_where_require_select.yaml
  backend/plugin/advisor/mssql/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/mysql/advisor_stmt_where_requirement_for_select.go
  backend/plugin/advisor/mysql/advisor_stmt_where_requirement_for_update_delete.go
  backend/plugin/advisor/mysql/mysql_rules_test.go
  backend/plugin/advisor/mysql/test/statement_where_require_select.yaml
  backend/plugin/advisor/mysql/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/oracle/advisor_where_require_for_select.go
  backend/plugin/advisor/oracle/advisor_where_require_for_update_delete.go
  backend/plugin/advisor/oracle/oracle_rules_test.go
  backend/plugin/advisor/oracle/test/statement_where_require.yaml
  backend/plugin/advisor/oracle/test/statement_where_require_select.yaml
  backend/plugin/advisor/oracle/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/pg/advisor_stmt_where_required_select.go
  backend/plugin/advisor/pg/advisor_stmt_where_required_update_delete.go
  backend/plugin/advisor/pg/pg_rules_test.go
  backend/plugin/advisor/pg/test/statement_where_require.yaml
  backend/plugin/advisor/pg/test/statement_where_require_select.yaml
  backend/plugin/advisor/pg/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/snowflake/advisor_where_require_select.go
  backend/plugin/advisor/snowflake/advisor_where_require_update_delete.go
  backend/plugin/advisor/snowflake/snowflake_rules_test.go
  backend/plugin/advisor/snowflake/test/statement_where_require_select.yaml
  backend/plugin/advisor/snowflake/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/advisor_stmt_where_required_for_select.go
  backend/plugin/advisor/tidb/advisor_stmt_where_required_for_update_delete.go
  backend/plugin/advisor/tidb/test/statement_where_require.yaml
  backend/plugin/advisor/tidb/test/statement_where_require_select.yaml
  backend/plugin/advisor/tidb/test/statement_where_require_update_delete.yaml
  backend/plugin/advisor/tidb/tidb_rules_test.go
  backend/plugin/advisor/utils_for_tests.go
  backend/tests/sql.go
  backend/tests/test-data/sql_review_mysql.yaml
  backend/tests/test-data/sql_review_pg.yaml
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.dev.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#13646 fix: config
  backend/api/v1/branch_service.go
Labels: cla-signed

#13645 chore: i18n for builtin rule
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
Labels: cla-signed

#13647 chore: add change type to apply changelist to database drawer
  frontend/src/components/AlterSchemaPrepForm/SchemalessDatabaseTable.vue
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/changelist.ts
Labels: cla-signed

#13648 fix(sql-editor): wrong partition field name
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/PartitionsTable.vue
Labels: cla-signed

#13649 fix: add `changelists.update` permission for project developer
  backend/component/iam/acl.yaml
Labels: cla-signed

#13651 chore(schema-editor): only allow to editor the first partition/sub-partition
  frontend/src/components/SchemaEditorLite/Panels/PartitionsEditor/PartitionsEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
Labels: cla-signed

#13653 chore: no need to update config again
  backend/api/v1/branch_service.go
Labels: cla-signed

#13655 chore(sql-editor): hide open ai button in admin mode
  frontend/src/views/sql-editor/EditorCommon/OpenAIButton.vue
Labels: cla-signed

#13658 chore(sql-editor): one-way sync for currentTabId
  frontend/src/store/modules/sqlEditor/tab.ts
Labels: cla-signed

#13654 feat: allow to set schema in query requests
  backend/api/v1/sql_service.go
  backend/plugin/db/driver.go
  backend/plugin/db/pg/pg.go
  backend/plugin/parser/pg/query_span.go
  backend/plugin/parser/pg/query_span_extractor.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#13659 chore: clear database change history cache
  frontend/src/components/IssueV1/logic/poll.ts
  frontend/src/store/modules/v1/changeHistory.ts
Labels: cla-signed

#13652 feat: prior backup check for Oracle
  backend/api/v1/database_service.go
  backend/plugin/advisor/builtin_rules.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/plsql/backup.go
  backend/plugin/parser/plsql/completion.go
  backend/plugin/parser/plsql/plsql.go
  backend/plugin/parser/plsql/query_span_extractor.go
  backend/plugin/parser/plsql/util.go
Labels: cla-signed

#13661 chore(sql-editor): open new browser tab when creating issue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
Labels: cla-signed

#13662 feat: add schema to execute and admin execute requests
  backend/api/v1/sql_service.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#13663 fix(sql-editor): parent key of column nodes
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
Labels: cla-signed

#13660 chore(sql-editor): split keyword for each tab
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
Labels: cla-signed

#13664 fix: use correct regexp to check VACUUM statements
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#13665 chore(sql-editor): set minimal query interval to 1 second
  frontend/src/composables/useExecuteSQL.ts
Labels: cla-signed

#13666 chore: use queryContext.schema for other engines
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/plsql/query_span_test.go
  backend/plugin/parser/snowflake/query_span_extractor.go
  backend/plugin/parser/tsql/query_span_extractor.go
Labels: cla-signed

#13667 feat: implement plsql backup for multi-updates
  backend/plugin/parser/plsql/backup.go
  backend/plugin/parser/plsql/test-data/test_backup.yaml
Labels: cla-signed

#13668 chore: admin executing explain analyze returns correct result
  backend/plugin/parser/mysql/query.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/tidb/query.go
  backend/plugin/parser/tidb/query_test.go
Labels: cla-signed

#13669 feat: refine last updater
  backend/api/v1/branch_merge.go
  backend/api/v1/branch_merge_test.go
  backend/api/v1/branch_service.go
Labels: cla-signed

#13670 refactor: refactor some update info in branch code
  backend/api/v1/branch_merge.go
  backend/api/v1/branch_service.go
  backend/api/v1/branch_service_test.go
Labels: cla-signed

#13671 chore: expose antlr runtime raw error message in syntax checking
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/base/base.go
Labels: cla-signed

#13672 chore: worksheet iam
  backend/component/iam/acl.yaml
Labels: cla-signed

#13673 fix: worksheet permission check
  backend/api/v1/worksheet_service.go
Labels: cla-signed

#13674 fix: worksheet permission check
  backend/api/v1/worksheet_service.go
  frontend/src/store/modules/v1/worksheet.ts
  frontend/src/utils/v1/worksheet.ts
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#13676 feat: add schema to lsp arguments
  backend/api/lsp/commands.go
  backend/api/lsp/completion.go
  backend/api/lsp/handler.go
  backend/plugin/parser/base/complete.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/tsql/completion.go
  frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
Labels: cla-signed

#13678 chore: bump helm to v2.22.3
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#13677 feat: introduce backup policy in project
  frontend/src/types/proto/store/project.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/project.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/project.proto
  proto/v1/project_service.proto
Labels: cla-signed

#13679 feat: enable drift detection for oracle and mssql
  backend/runner/schemasync/syncer.go
Labels: cla-signed, backport release/2.22.3

#13681 fix: stringify on update
  backend/plugin/schema/mysql/stringify_table.go
Labels: cla-signed

#13682 chore: update i18n for creating database issue title
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13684 fix: password check
  backend/api/v1/auth_service.go
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#13685 feat: introduce error for backup comments
  frontend/src/types/proto/store/issue_comment.ts
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/issue_comment.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/store/issue_comment.proto
  proto/v1/issue_service.proto
Labels: cla-signed

#13683 refactor: introduce diagnose interface
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/base/diagnose.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/diagnose.go
Labels: cla-signed

#13675 feat(sql-editor): schema chooser
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/webTerminal.ts
  frontend/src/utils/v1/instance.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
Labels: cla-signed

#13688 fix: naiveui warning
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
Labels: cla-signed

#13690 chore: fix schema chooser overflow
  frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue
Labels: cla-signed

#13691 chore: allow to select encoding in changelist
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/Changelist/import.ts
  frontend/src/components/FileContentPreviewModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/common.ts
Labels: cla-signed

#13693 feat: diagnose for PostgreSQL/Oracle/Snowflake/SQL Server
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/pg/diagnose.go
  backend/plugin/parser/plsql/diagnose.go
  backend/plugin/parser/snowflake/diagnose.go
  backend/plugin/parser/tsql/diagnose.go
Labels: cla-signed

#13694 chore: allow redis keys command
  backend/plugin/parser/redis/query.go
Labels: cla-signed

#13696 chore: tweak position of issue action bar
  frontend/src/components/IssueV1/components/IssueTableV1.vue
Labels: cla-signed

#13697 docs: remove one liner install
  README.md
Labels: cla-signed

#13698 chore: auto-login for sql-editor.com
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#13699 fix: slow query email
  backend/runner/mail/slow_query_weekly_mail.go
Labels: cla-signed

#13702 fix: return internal error code for request query shortpath
  backend/api/v1/sql_service.go
Labels: cla-signed

#13701 feat: allow to omit semicolon for the last statement in diagnose
  backend/plugin/parser/mysql/diagnose.go
  backend/plugin/parser/pg/diagnose.go
  backend/plugin/parser/plsql/diagnose.go
  backend/plugin/parser/snowflake/diagnose.go
  backend/plugin/parser/tsql/diagnose.go
Labels: cla-signed

#13704 refactor: uniform trim right space
  backend/api/v1/branch_service.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/oracle/query.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/parser/bigquery/bigquery.go
  backend/plugin/parser/mysql/fingerprint.go
  backend/plugin/parser/partiql/partiql.go
  backend/plugin/parser/plsql/split.go
  backend/plugin/parser/snowflake/snowflake.go
  backend/plugin/parser/standard/split.go
  backend/plugin/parser/tidb/resource_change.go
  backend/plugin/parser/tsql/resource_change.go
  backend/plugin/parser/tsql/tsql.go
  backend/utils/utils.go
Labels: cla-signed

#13706 chore: restructure workspace sidebar
  frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/SettingWorkspaceDataAccessControl.vue
  frontend/src/views/SettingWorkspaceDataClassification.vue
  frontend/src/views/SettingWorkspaceDataMasking.vue
  frontend/src/views/sql-editor/EditorCommon/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/SensitiveDataIcon.vue
Labels: cla-signed

#13703 feat: implement skip backup error
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#13707 chore: oracle parser compatibility
  backend/plugin/parser/plsql/plsql_test.go
  go.mod
  go.sum
Labels: cla-signed

#13708 chore: allow to edit the name of foreign keys in schema editor
  frontend/src/components/SchemaEditorLite/Modals/EditColumnForeignKeyModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13709 chore: update classification upload format
  backend/api/v1/setting_service.go
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
Labels: cla-signed

#13711 feat: add cockroachdb in proto
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/common.ts
  frontend/src/types/proto/v1/common.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/common.pb.go
  proto/generated-go/v1/common.pb.go
  proto/store/common.proto
  proto/v1/common.proto
Labels: cla-signed

#13712 feat(backup): support CTE for MySQL
  backend/plugin/parser/mysql/backup.go
  backend/plugin/parser/mysql/test-data/test_backup.yaml
Labels: cla-signed

#13713 chore(sql-editor): do not expand dummy database node
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
Labels: cla-signed, backport release/2.22.3

#13717 chore: add missing project setting
  backend/api/v1/project_service.go
Labels: cla-signed

#13719 fix(walk-through): check if exists for drop index for pg
  backend/plugin/advisor/catalog/test/pg_walk_through.yaml
  backend/plugin/advisor/catalog/walk_through_for_pg.go
Labels: cla-signed

#13718 feat: ping cockroachdb
  backend/api/v1/common.go
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/cockroachdb/cockroachdb_test.go
  backend/plugin/db/cockroachdb/dump.go
  backend/plugin/db/cockroachdb/role.go
  backend/plugin/db/cockroachdb/stats.go
  backend/plugin/db/cockroachdb/sync.go
  backend/plugin/db/cockroachdb/sync_test.go
  backend/plugin/db/cockroachdb/util.go
  backend/server/ultimate.go
  frontend/src/assets/db-cockroachdb.png
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
  frontend/src/components/InstanceForm/constants.ts
  frontend/src/components/InstanceForm/specs.ts
  frontend/src/types/v1/instance.ts
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#13720 feat: add cluster identifier in data source
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/store/data_source.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#13721 chore: proto generate
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/v1/instance_service.ts
Labels: cla-signed

#13724 chore: sync large oracle functions
  backend/plugin/db/oracle/sync.go
Labels: cla-signed

#13725 chore: fix database related permission checks
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/utils/v1/database.ts
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
Labels: cla-signed

#13727 chore: skip backup available check for pg
  backend/api/v1/database_service.go
Labels: cla-signed

#13729 fix(cockroach): sync incompatibility
  backend/plugin/db/cockroachdb/dump.go
  backend/plugin/db/cockroachdb/sync.go
Labels: cla-signed

#13731 feat: get cockroachdb index expression
  backend/plugin/db/cockroachdb/sync.go
  go.mod
  go.sum
Labels: cla-signed

#13732 chore: use `waiting approval` instead of `approval-requested`
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/MyIssues.vue
Labels: cla-signed

#13735 chore(cockroachdb): support create database and syntax checking
  backend/api/v1/rollout_service_task.go
  backend/common/util.go
  backend/component/sheet/sheet.go
  backend/plugin/parser/cockroachdb/cockroachdb.go
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
Labels: cla-signed

#13733 fix: check permission for creating project button
  frontend/src/components/Project/ProjectSwitchModal.vue
Labels: cla-signed

#13737 fix(pg-query-span): query system table
  backend/plugin/parser/pg/query_span_extractor.go
Labels: cla-signed

#13736 chore(cockroachdb): skip sync system object
  backend/plugin/db/cockroachdb/sync.go
  backend/plugin/parser/cockroachdb/system_objects.go
Labels: cla-signed

#13739 fix: missing iam binding expr check
  frontend/src/utils/v1/iam.ts
Labels: cla-signed

#13742 chore(2.20.0): cp fix: webhook notifs should skip deleted users (#13631)
  backend/component/webhook/manager.go
Labels: cla-signed

#13740 chore: add project default backup behavior setting
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13743 fix: cannot scroll in sql editor setting page
  frontend/src/views/sql-editor/SQLEditorSettingPage.vue
  frontend/src/views/sql-editor/Setting/Users/Users.vue
Labels: cla-signed

#13744 chore: show backup error issue comment
  backend/api/v1/issue_service_convert.go
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionIcon.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13745 feat(cockroachdb): tiny schema dump for cockroachdb
  backend/plugin/db/cockroachdb/dump.go
Labels: cla-signed

#13746 chore: update export results as json format
  backend/api/v1/sql_service_export_utils.go
  backend/api/v1/sql_service_export_utils_test.go
  backend/api/v1/sql_service_test.go
Labels: cla-signed

#13750 refactor: cleanup driver dump function stub
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/bigquery/dump.go
  backend/plugin/db/clickhouse/dump.go
  backend/plugin/db/cockroachdb/dump.go
  backend/plugin/db/databricks/dump.go
  backend/plugin/db/dm/dump.go
  backend/plugin/db/driver.go
  backend/plugin/db/dynamodb/dump.go
  backend/plugin/db/elasticsearch/dump.go
  backend/plugin/db/hive/dump.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mssql/dump.go
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/obo/dump.go
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/pg/dump.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/dump.go
  backend/plugin/db/risingwave/dump.go
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/spanner/dump.go
  backend/plugin/db/sqlite/dump.go
  backend/plugin/db/starrocks/dump.go
  backend/plugin/db/tidb/dump.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/utils/sdl_utils.go
  backend/utils/utils.go
Labels: cla-signed

#13751 feat(cockroachdb): simple splitter
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/parser/cockroachdb/cockroachdb.go
  backend/plugin/parser/cockroachdb/cockroachdb_test.go
  backend/plugin/parser/cockroachdb/testdata/split_sql_statement.yaml
Labels: cla-signed

#13747 feat: user profile proto & store
  backend/migrator/migration/prod/2.23/0000##principal_profile.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/principal.go
  frontend/src/types/proto/store/user.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/user.pb.go
  proto/store/user.proto
Labels: cla-signed

#13753 fix: mfa checks
  backend/api/v1/auth_service.go
Labels: cla-signed, backport release/2.22.3

#13755 chore: remove dev guard for scim
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#13758 chore: 2.23.0
  scripts/VERSION
Labels: cla-signed

#13757 fix: prepare default databases
  frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
Labels: cla-signed

#13756 chore: release cockroachdb and diagnose
  backend/api/lsp/fs_handler.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#13759 chore: move issue sql from url to local storage
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#13760 feat: enable advanced feature for cockroachdb
  backend/api/lsp/completion.go
  backend/plugin/parser/mysql/diagnose.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/pg/diagnose.go
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/pg/query_span.go
  backend/plugin/parser/pg/resource_change.go
  backend/plugin/parser/pg/split.go
  backend/plugin/parser/plsql/diagnose.go
  backend/plugin/parser/snowflake/diagnose.go
  backend/plugin/parser/tsql/diagnose.go
Labels: cla-signed

#13763 chore(2.22.2): cherry pick #13668
  backend/plugin/parser/mysql/query.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/tidb/query.go
  backend/plugin/parser/tidb/query_test.go
Labels: cla-signed

#13761 feat: postgres detail error
  backend/api/v1/audit.go
  backend/plugin/db/pg/pg.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#13764 chore: force to change the password
  backend/api/v1/auth_service.go
  backend/server/init.go
  backend/store/principal.go
  backend/store/setting.go
  frontend/src/App.vue
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/PasswordSigninForm.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/auth.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/auth.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/views/OAuthCallback.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/auth/PasswordReset.vue
  frontend/src/views/auth/Signin.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/auth_service.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#13765 fix: detailed error in admin execute response audit
  backend/api/v1/audit.go
Labels: cla-signed

#13766 chore: improve entra wording
  frontend/src/components/User/Settings/AADSyncDrawer.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#13767 feat(sql-editor): display postgresError
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/PostgresError.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#13768 chore(sql-editor): some minor fixes
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/SQLEditorSettingPage.vue
Labels: cla-signed

#13769 fix: handle case sensitivity in rollback
  backend/api/v1/rollout_service.go
  backend/plugin/parser/base/restore.go
  backend/plugin/parser/base/transform.go
  backend/plugin/parser/mysql/backup.go
  backend/plugin/parser/mysql/backup_test.go
  backend/plugin/parser/mysql/restore.go
  backend/plugin/parser/mysql/restore_test.go
  backend/plugin/parser/tidb/backup.go
  backend/plugin/parser/tidb/backup_test.go
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#13770 chore(sql-editor): minor fix
  frontend/src/components/ProvideSQLEditorContext.vue
Labels: cla-signed

#13772 chore: update default backup setting
  backend/api/v1/project_service.go
  backend/runner/taskrun/data_update_executor.go
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/project.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/project.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/project.proto
  proto/v1/project_service.proto
Labels: cla-signed

#13771 chore: feature guard for password restriction
  backend/api/v1/setting_service.go
  backend/legacyapi/plan.go
  backend/server/init.go
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
Labels: cla-signed

#13775 chore: global masking rule should not apply to unsupported engine
  backend/api/v1/query_result_masker.go
Labels: cla-signed

#13773 chore: add source for Entra ID user and group
  backend/api/directory-sync/webhook.go
  backend/api/v1/auth_service.go
  backend/api/v1/group_service.go
  frontend/src/components/Member/MemberDataTable/cells/UserNameCell.vue
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupNameCell.vue
  frontend/src/types/proto/store/group.ts
  frontend/src/types/proto/store/user.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/types/proto/v1/group.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/group.pb.go
  proto/generated-go/store/user.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/group.pb.go
  proto/store/group.proto
  proto/store/user.proto
  proto/v1/auth_service.proto
  proto/v1/group.proto
Labels: cla-signed

#13776 chore(sql-editor): set default data source for connection
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx
  frontend/src/views/sql-editor/EditorCommon/utils.ts
  frontend/src/views/sql-editor/Sheet/context.ts
Labels: cla-signed

#13779 fix: create user
  backend/api/v1/auth_service.go
  backend/store/principal.go
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#13778 refactor: dingtalk pkg
  backend/plugin/webhook/dingtalk/dingtalk.go
  backend/server/minimal.go
  backend/server/ultimate.go
Labels: cla-signed

#13781 chore(sql-editor): fix redirection after setup
  frontend/src/views/Setup/WorkspaceMode.vue
Labels: cla-signed, backport release/2.23.0

#13782 fix: pass statement
  backend/api/v1/sql_service.go
Labels: cla-signed

#13780 chore: optimize password restriction
  backend/api/v1/actuator_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/setting_service.go
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/store/modules/v1/actuator.ts
  frontend/src/store/modules/v1/setting.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/auth/PasswordReset.vue
  frontend/src/views/auth/Signup.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/actuator_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#13783 chore: update feature guard for issue project setting
  backend/api/v1/project_service.go
  backend/legacyapi/plan.go
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
Labels: cla-signed

#13784 chore: issue mode sql editor mode wording
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/Setup/WorkspaceMode.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#13777 chore(cockroachdb): more dump
  backend/plugin/db/cockroachdb/dump.go
Labels: cla-signed

#13785 chore: feature guard for directory sync
  backend/api/directory-sync/webhook.go
  backend/enterprise/api/plan.yaml
  backend/legacyapi/plan.go
  frontend/i18n.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#13786 chore: update the comment if the sql review check passed
  backend/api/gitops/common.go
  backend/api/gitops/webhook.go
Labels: cla-signed

#13787 fix: i18n
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#13788 chore(sql-editor): advanced sorting compare function
  frontend/src/utils/v1/sql.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#13789 fix: typo in websocket error
  frontend/src/components/MonacoEditor/lsp-client.ts
Labels: cla-signed

#13790 chore(sql-editor): adjust gap
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
Labels: cla-signed

#13792 chore(sql-editor): missing i18n
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13791 chore(sql-editor): enable DML/DDL by default if databaseChangeMode is EDITOR
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/types/sqlEditor/tab.ts
  frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/EditorCommon/OpenAIButton.vue
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
  frontend/src/views/sql-editor/EditorCommon/QueryModeSelect.vue
  frontend/src/views/sql-editor/EditorCommon/ReadonlyDatasourceHint.vue
  frontend/src/views/sql-editor/EditorPanel/EditorPanel.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
  frontend/src/views/sql-editor/TabList/ContextMenu.vue
  frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue
  frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#13793 feat: apply changelist to database group
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Select/DatabaseGroupSelect.vue
  frontend/src/store/modules/dbGroup.ts
  frontend/src/utils/v1/changelist.ts
Labels: cla-signed

#13794 chore(review-center): check policy when creating issue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
Labels: cla-signed

#13796 chore: tweak styles of password reset
  frontend/src/views/auth/PasswordReset.vue
Labels: cla-signed

#13795 fix: dummy execution
  backend/plugin/db/cockroachdb/cockroachdb.go
Labels: cla-signed

#13797 chore: fix i18n
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13798 chore: remove lsif action which is broken and archived
  .github/workflows/lsif.yml
Labels: cla-signed

#13801 chore: optimize ui
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/views/auth/PasswordReset.vue
Labels: cla-signed
