Repository bytebase/bytebase, pull requests merged in 2024-05, with the labels that each got.

#11904 chore: update err msg
  frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts
Labels: cla-signed

#11906 chore: frontend fix and update
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceSection.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/ProvideInstanceContext.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/layouts/InstanceLayout.vue
  frontend/src/types/v1/dataSource.ts
Labels: cla-signed

#11905 chore(sql-review): separate rule for truncate cascading
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/config/sql-review.dev.yaml
  backend/plugin/advisor/config/sql-review.prod.yaml
  backend/plugin/advisor/pg/advisor_statement_disallow_on_del_cascade.go
  backend/plugin/advisor/pg/advisor_statement_disallow_rm_tbl_cascade.go
  backend/plugin/advisor/pg/pg_rules_test.go
  backend/plugin/advisor/pg/test/statement_disallow_on_del_cascade.yaml
  backend/plugin/advisor/pg/test/statement_disallow_rm_tbl_cascade.yaml
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed

#11908 fix: obo select version
  backend/plugin/db/obo/sync.go
Labels: cla-signed

#11907 chore: add column comments to prompt
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/logic/utils.ts
Labels: cla-signed

#11909 chore: fix droppable textarea state
  frontend/src/components/misc/DroppableTextarea.vue
Labels: cla-signed

#11911 chore: fix i18n
  frontend/src/components/InstanceAssignment.vue
  frontend/src/components/InstanceUserTable.vue
  frontend/src/components/v2/Model/Instance/InstanceRoleTable/InstanceRoleTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11912 feat(proto): task run log
  frontend/src/types/proto/store/task_run_log.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/activity.pb.go
  proto/generated-go/store/approval.pb.go
  proto/generated-go/store/audit_log.pb.go
  proto/generated-go/store/branch.pb.go
  proto/generated-go/store/changelist.pb.go
  proto/generated-go/store/common.pb.go
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/store/database.pb.go
  proto/generated-go/store/export_archive.pb.go
  proto/generated-go/store/idp.pb.go
  proto/generated-go/store/instance.pb.go
  proto/generated-go/store/instance_change_history.pb.go
  proto/generated-go/store/issue.pb.go
  proto/generated-go/store/issue_comment.pb.go
  proto/generated-go/store/plan.pb.go
  proto/generated-go/store/plan_check_run.pb.go
  proto/generated-go/store/policy.pb.go
  proto/generated-go/store/project.pb.go
  proto/generated-go/store/query_history.pb.go
  proto/generated-go/store/role.pb.go
  proto/generated-go/store/setting.pb.go
  proto/generated-go/store/sheet.pb.go
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/store/task_run.pb.go
  proto/generated-go/store/task_run_log.pb.go
  proto/generated-go/store/user.pb.go
  proto/generated-go/store/vcs.pb.go
  proto/generated-go/v1/actuator_service.pb.go
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/audit_log_service.pb.go
  proto/generated-go/v1/auth_service.pb.go
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/cel_service.pb.go
  proto/generated-go/v1/changelist_service.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/environment_service.pb.go
  proto/generated-go/v1/iam_policy.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/logging_service.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/risk_service.pb.go
  proto/generated-go/v1/role_service.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/generated-go/v1/sheet_service.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/subscription_service.pb.go
  proto/generated-go/v1/vcs_connector_service.pb.go
  proto/generated-go/v1/vcs_provider_service.pb.go
  proto/generated-go/v1/worksheet_service.pb.go
  proto/store/task_run_log.proto
Labels: cla-signed

#11913 feat: add task run log table
  backend/migrator/migration/prod/2.17/0001##task_run_log.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#11915 chore(frontend): refactor extract file upload and parse logic for changelist importing
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/Changelist/import.ts
Labels: cla-signed

#11916 chore: use `NVirtualList` in matched database/table view
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/MatchedTableView.vue
Labels: cla-signed

#11917 fix: nil
  backend/plugin/advisor/mysql/advisor_online_migration.go
Labels: cla-signed

#11918 feat(frontend): upload file when creating changelist
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/Changelist/import.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11826 feat(dump): implement mssql dump
  backend/plugin/db/mssql/dump.go
Labels: cla-signed

#11914 feat: click plan check detail line anchor element will navigate to line
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/MonacoEditor/MonacoEditor.vue
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/MonacoEditor/WrappedMonacoEditor.vue
Labels: cla-signed

#11919 chore: support set issue label
  backend/api/v1/database_converter.go
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/project_service.go
  frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Project/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/ProjectIssueLabelsSettingPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/issue.ts
  frontend/src/types/proto/store/project.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/issue.pb.go
  proto/generated-go/store/project.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/issue.proto
  proto/store/project.proto
  proto/v1/issue_service.proto
  proto/v1/project_service.proto
Labels: cla-signed

#11920 chore: add filterable to affected table select
  frontend/src/components/ChangeHistory/AffectedTableSelect.vue
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/utils/v1/changeHistory.ts
Labels: cla-signed

#11921 chore: hide docs reference in standalone mode
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
Labels: cla-signed

#11922 feat: implement dump mssql indexes
  backend/plugin/db/mssql/dump.go
Labels: cla-signed

#11923 chore: filter issues by label
  backend/api/v1/issue_service.go
  backend/store/issue.go
  frontend/src/components/IssueV1/components/IssueSearch/useSearchScopeOptions.ts
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/utils/v1/issue/search/advanced-search.ts
  frontend/src/utils/v1/issue/search/common.ts
Labels: cla-signed

#11924 chore(frontend): button style and text
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
Labels: cla-signed

#11926 fix: column does not exist
  backend/plugin/advisor/catalog/test/mysql_walk_through.yaml
  backend/plugin/advisor/catalog/walk_through_for_mysql.go
Labels: cla-signed, backport release/2.16.0

#11929 chore: scan mssql (null)uniqueidentifier type
  backend/component/masker/masker.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#11932 feat: impl GetTaskRunLog v1 api
  backend/api/v1/acl_config.go
  backend/api/v1/ctx.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/store/task_run_log.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#11931 chore(frontend): specify sheet.engine if possible in CreateSheet
  frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/SyncDatabaseSchema/RawSQLEditor.vue
  frontend/src/store/modules/v1/sheet.ts
Labels: cla-signed

#11933 feat(proto): add all affected rows
  frontend/src/types/proto/store/task_run_log.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/task_run_log.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/task_run_log.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#11934 feat: sync mssql func and procedures
  backend/plugin/db/mssql/sync.go
  frontend/src/components/Database/DatabaseOverviewPanel.vue
Labels: cla-signed

#11935 feat: use raw conn to get affected rows of each stmt
  backend/api/v1/rollout_service_converter.go
  backend/plugin/db/driver.go
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#11936 fix: task run log index
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#11937 feat(proto): sheet commands
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sheet_service.pb.go
  proto/v1/sheet_service.proto
Labels: cla-signed

#11938 chore: update advanced search utils definition
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/utils/v1/advanced-search/index.ts
  frontend/src/utils/v1/advanced-search/issue/index.ts
  frontend/src/utils/v1/advanced-search/issue/ui-filter.ts
  frontend/src/utils/v1/advanced-search/issue/utils.ts
  frontend/src/utils/v1/index.ts
  frontend/src/utils/v1/issue/index.ts
  frontend/src/utils/v1/issue/search/index.ts
Labels: cla-signed

#11940 feat: convert sheet commands
  backend/api/v1/sheet_service.go
Labels: cla-signed

#11939 feat: store command indexes
  backend/api/v1/rollout_service_converter.go
  backend/plugin/db/driver.go
  backend/plugin/db/mysql/mysql.go
  frontend/src/types/proto/store/task_run_log.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/task_run_log.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/task_run_log.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#11943 chore: implement advanced search for audit logs
  backend/api/v1/audit_log_service.go
  frontend/src/components/AuditLog/AuditLogSearch/AdvancedSearchBox.vue
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/AuditLog/AuditLogSearch/ScopeMenu.vue
  frontend/src/components/AuditLog/AuditLogSearch/ScopeTags.vue
  frontend/src/components/AuditLog/AuditLogSearch/TimeRange.vue
  frontend/src/components/AuditLog/AuditLogSearch/ValueMenu.vue
  frontend/src/components/AuditLog/AuditLogSearch/index.ts
  frontend/src/components/AuditLog/AuditLogSearch/useSearchScopeOptions.ts
  frontend/src/components/AuditLog/AuditLogSearch/utils.ts
  frontend/src/grpcweb/methods.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/auditLog.ts
  frontend/src/types/auditLog.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed

#11945 feat: allow 100m via REST
  backend/server/grpc_routes.go
Labels: cla-signed

#11948 feat: duplicate the database schema metadata and add last updater related fields
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/branch.ts
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/branch.pb.go
  proto/generated-go/v1/branch_service.pb.go
  proto/store/branch.proto
  proto/v1/branch_service.proto
Labels: cla-signed

#11946 chore: update sql
  backend/store/task.go
Labels: cla-signed

#11950 chore: optimize issue labels
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
Labels: cla-signed

#11949 feat(frontend): show task run log detail
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/AffectedRowsCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DurationCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/StatementCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/common.ts
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/index.ts
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
  frontend/src/components/misc/TextOverflowPopover.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/sheet.ts
Labels: cla-signed

#11951 refactor: combine advanced search components
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/AdvancedSearch/ScopeMenu.vue
  frontend/src/components/AdvancedSearch/ScopeTags.vue
  frontend/src/components/AdvancedSearch/TimeRange.vue
  frontend/src/components/AdvancedSearch/ValueMenu.vue
  frontend/src/components/AdvancedSearch/index.ts
  frontend/src/components/AdvancedSearch/types.ts
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AuditLog/AuditLogSearch/AdvancedSearchBox.vue
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/AuditLog/AuditLogSearch/index.ts
  frontend/src/components/AuditLog/AuditLogSearch/useSearchScopeOptions.ts
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/ScopeMenu.vue
  frontend/src/components/IssueV1/components/IssueSearch/ScopeTags.vue
  frontend/src/components/IssueV1/components/IssueSearch/TimeRange.vue
  frontend/src/components/IssueV1/components/IssueSearch/ValueMenu.vue
  frontend/src/components/IssueV1/components/IssueSearch/index.ts
  frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
  frontend/src/components/Project/ProjectIssuesPanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/Home.vue
  frontend/src/views/InstanceDashboard.vue
Labels: cla-signed

#11952 chore: fix scope tags
  frontend/src/components/AdvancedSearch/ScopeTags.vue
Labels: cla-signed

#11955 fix: pass DBSchema
  backend/runner/plancheck/statement_advise_executor.go
Labels: cla-signed

#11957 fix: one migration at the same time
  backend/component/state/state.go
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#11954 chore: update search scopes for data exporting issues
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  frontend/src/views/ExportCenter/index.vue
Labels: cla-signed

#11956 chore: upgrade plsql parser
  go.mod
  go.sum
Labels: cla-signed

#11959 chore: tweak issue search styles
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/Project/ProjectIssuesPanel.vue
  frontend/src/views/Home.vue
  frontend/src/views/IssueDashboard.vue
Labels: cla-signed

#11960 chore(sql-editor): minor style tweaking
  frontend/src/views/sql-editor/EditorPanel/Welcome.vue
Labels: cla-signed

#11961 chore: only show error line for latest plan check run
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
Labels: cla-signed

#11964 chore: update request permission buttons
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#11963 chore: add expand button to plan check bar
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBadgeBar.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckModal.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
Labels: cla-signed

#11968 fix: use instance id
  frontend/src/components/DatabaseGroup/utils.ts
Labels: cla-signed

#11969 fix: sanitize comment
  backend/api/v1/branch_service.go
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
Labels: cla-signed

#11972 chore: update i18n of classification
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11973 fix: i18n test
  frontend/src/plugins/i18n.test.ts
Labels: cla-signed

#11974 chore: hide delete label button
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
Labels: cla-signed

#11979 chore(frontend): fallback to affectedRows
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/AffectedRowsCell.vue
Labels: cla-signed

#11978 fix: project ids
  backend/api/v1/ctx.go
Labels: cla-signed

#11977 feat: impl task run log for pg
  backend/component/sheet/sheet.go
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#11980 chore: store last updater in database config
  frontend/src/types/proto/store/branch.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/branch_service.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/branch.pb.go
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/branch.proto
  proto/store/database.proto
  proto/v1/branch_service.proto
  proto/v1/database_service.proto
Labels: cla-signed

#11967 feat(sql-editor): Improve the UX of project group by experience
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/types/sqlEditor/tree.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/AddFactorButton.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorPanel.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTag.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTags.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/GroupingBar.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/ProjectNode.vue
Labels: cla-signed

#11981 chore(frontend): i18n
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11982 chore: redirect to configure labels
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11983 chore: add labels column to data export issue table
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  frontend/src/views/ExportCenter/index.vue
Labels: cla-signed

#11984 feat(frontend): show task run log error
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/ErrorCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/common.ts
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/index.ts
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#11985 feat: update branch updater info
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/store/model/database.go
Labels: cla-signed

#11986 chore: update mysql task run log
  backend/api/v1/sheet_service.go
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#11987 chore: use allAffectedRows if there's a one to one mapping
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/TaskRunLogTable.vue
Labels: cla-signed

#11988 chore: update composed issue definition
  frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackSection.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageSelect.vue
  frontend/src/components/IssueV1/components/StageSection/StageSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/utils/v1/issue/issue.ts
  frontend/src/utils/v1/issue/rollout.ts
  frontend/src/views/IssueDetailV1.vue
Labels: cla-signed

#11989 chore: force to set issue labels
  backend/api/v1/project_service.go
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/Project/ProjectIssueLabelsSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/project.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/project.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/project.proto
  proto/v1/project_service.proto
Labels: cla-signed

#11991 fix(hive): typo
  backend/plugin/advisor/mysql/advisor_table_limit_size.go
Labels: cla-signed

#11992 fix: unspecific risk source
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
Labels: cla-signed

#11975 feat: support mask_inner and mask_outer
  backend/api/v1/query_result_masker.go
  backend/component/masker/masker.go
  backend/component/masker/masker_test.go
  frontend/src/types/proto/store/setting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/setting.pb.go
  proto/store/setting.proto
Labels: cla-signed

#11993 fix: fix npe in IndexTotalNumberLimitAdvisor
  backend/plugin/advisor/mysql/advisor_index_total_number_limit.go
Labels: cla-signed

#11994 chore: distinguish functions and procedures for sql server
  backend/plugin/db/mssql/sync.go
Labels: cla-signed

#11995 chore: retire task in PlanCheckRun related components
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckBar.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckModal.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckPanel.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckRunButton.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/context.ts
  frontend/src/components/IssueV1/logic/plan-check.ts
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/types/v1/issue/plan.ts
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#11996 chore: no cancel for CreateAuditLog
  backend/api/v1/audit.go
Labels: cla-signed

#11990 feat(proto): add additional host/port and replicaset name in data source proto
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/store/data_source.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#11958 feat(differ): implement mssql differ part I
  backend/api/v1/database_service.go
  backend/plugin/parser/tsql/diff_test.go
  backend/plugin/parser/tsql/differ.go
  backend/plugin/parser/tsql/test-data/test_differ_data.yaml
  backend/plugin/parser/tsql/tsql.go
  frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
Labels: cla-signed

#11998 chore: open drawer for change history
  frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/components/ChangeHistory/index.ts
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Candidates.vue
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/views/ChangeHistoryDetail.vue
Labels: cla-signed

#12000 feat(data-masking): add ui for inner and outer maskers
  backend/api/v1/setting_service.go
  frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/setting_service.pb.go
  proto/v1/setting_service.proto
Labels: cla-signed

#11953 feat(sql-review): new rule for checking no position in add column clause
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/config/sql-review.prod.yaml
  backend/plugin/advisor/mysql/advisor_statement_add_column_without_position.go
  backend/plugin/advisor/sql_review.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed

#11966 feat(sql-review): new rule that disallows dropping columns
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/config/sql-review.prod.yaml
  backend/plugin/advisor/mysql/advisor_column_disallow_drop.go
  backend/plugin/advisor/sql_review.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed

#12003 chore: no auto-complete for huge sql
  backend/api/lsp/completion.go
Labels: cla-signed

#12004 fix(frontend): Changelist issue creation failed when apply to multiple databases
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
Labels: cla-signed

#11997 feat(sql-review): new rule for OceanBase (MySQL mode) offline ddl
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/catalog/state.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/config/sql-review.prod.yaml
  backend/plugin/advisor/oceanbase/advisor_disallow_offline_ddl.go
  backend/plugin/advisor/sql_review.go
  backend/server/ultimate.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed

#12002 feat(branch): display the latest updater info in branch
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchRebaseView/RebaseBranchStep.vue
  frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
  frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
  frontend/src/components/Branch/SchemaDesignEditorLite.vue
  frontend/src/components/Branch/common/BranchComparison.vue
  frontend/src/components/Branch/common/BranchDetailViewer.vue
  frontend/src/components/SchemaEditorLite/Panels/CommonCodeEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/FunctionEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/ProcedureEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/common/LastUpdater.vue
  frontend/src/components/SchemaEditorLite/Panels/common/common.ts
  frontend/src/components/SchemaEditorLite/Panels/common/index.ts
  frontend/src/components/SchemaEditorLite/SchemaEditorLite.vue
  frontend/src/components/SchemaEditorLite/algorithm/utils.ts
  frontend/src/components/SchemaEditorLite/context/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12005 chore: support not in operator in deployment config
  backend/api/v1/project_service.go
  backend/api/v1/rollout_service_plan_check.go
  backend/api/v1/rollout_service_task.go
  backend/legacyapi/deploy.go
  backend/legacyapi/deploy_test.go
  backend/runner/taskrun/database_create_executor.go
  backend/store/deploy.go
  backend/utils/utils.go
  backend/utils/utils_test.go
  frontend/src/components/DeploymentConfigTool/SelectorItemV2.vue
  frontend/src/components/LabelEditorDrawer.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/utils/v1/deploymentConfig.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/project_service.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#12006 chore(frontend): retire activity
  frontend/src/components/ActivityTable/ActivityCommentLink.vue
  frontend/src/components/ActivityTable/ActivityTable.vue
  frontend/src/components/ActivityTable/ActivityTypeLink.vue
  frontend/src/components/ActivityTable/types.ts
  frontend/src/components/ActivityTable/utils.ts
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
  frontend/src/store/modules/v1/issueComment.ts
  frontend/src/types/activity.ts
  frontend/src/types/index.ts
  frontend/src/utils/activity.ts
  frontend/src/utils/index.ts
Labels: cla-signed

#12009 chore: silence data source update mask
  backend/api/v1/instance_service.go
Labels: cla-signed

#12010 fix: compare diff
  frontend/src/utils/v1/common.ts
Labels: cla-signed

#12011 chore: change stage wording active to current
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12008 feat: handle latest updater in create/update/merge
  backend/api/v1/branch_service.go
  backend/utils/database_config_merge.go
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#12013 chore: remove vitnamesse for now
  frontend/i18n.ts
  frontend/src/components/HelpDrawer/HelpDrawer.vue
  frontend/src/components/ProfileDropdown.vue
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/subscription/vi-VN.json
  frontend/src/locales/vi-VN.json
  frontend/src/plugins/i18n.ts
  frontend/src/views/auth/AuthFooter.vue
Labels: cla-signed

#12012 docs: improve force label wording
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12015 refactor(schema-editor): use SchemaEditorLite to replace SchemaEditorV1
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/SchemaEditorLite/index.ts
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/components/SchemaTemplate/utils.ts
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/utils/schemaEditor/index.ts
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ColumnInfo.vue
  frontend/src/views/sql-editor/SQLEditorPage.vue
Labels: cla-signed

#12016 fix: task run sheet id sql
  backend/migrator/migration/prod/2.16/0005##task_run_sheet_id.sql
Labels: cla-signed

#12018 fix: use UTC time
  backend/runner/taskrun/executor.go
Labels: cla-signed, backport release/2.17.0

#12007 feat: impl task run log for mssql oracle
  backend/component/sheet/sheet.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#12021 chore(frontend): fix allowRollback condition
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
Labels: cla-signed

#12023 chore: fix rollback switch checks
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
Labels: cla-signed

#12025 chore: support filtering no pipeline issues
  backend/api/v1/issue_service.go
  backend/store/issue.go
Labels: cla-signed

#12026 chore: check doUpdateSheet in related specs without pipeline
  backend/api/v1/rollout_service.go
Labels: cla-signed

#12027 fix(tbl-limit-size): check row count instead of table data size
  backend/plugin/advisor/mysql/advisor_table_limit_size.go
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
Labels: cla-signed

#12031 chore(frontend): retire unused SchemaEditorV1 code
  frontend/src/components/SchemaEditorV1/Aside/BranchTree.vue
  frontend/src/components/SchemaEditorV1/Aside/DatabaseTree.vue
  frontend/src/components/SchemaEditorV1/Aside/index.vue
  frontend/src/components/SchemaEditorV1/Editor.vue
  frontend/src/components/SchemaEditorV1/EmptyTips.vue
  frontend/src/components/SchemaEditorV1/Modals/ActionConfirmModal.vue
  frontend/src/components/SchemaEditorV1/Modals/ColumnDefaultValueExpressionModal.vue
  frontend/src/components/SchemaEditorV1/Modals/EditColumnForeignKeyModal.vue
  frontend/src/components/SchemaEditorV1/Modals/SchemaNameModal.vue
  frontend/src/components/SchemaEditorV1/Modals/TableNameModal.vue
  frontend/src/components/SchemaEditorV1/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/DataTypeCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/DefaultValueCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/ForeignKeyCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/LabelsCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/OperationCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/ReorderCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/SemanticTypeCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/components/index.ts
  frontend/src/components/SchemaEditorV1/Panels/TableColumnEditor/index.ts
  frontend/src/components/SchemaEditorV1/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorV1/Panels/TableList/TableList.vue
  frontend/src/components/SchemaEditorV1/Panels/TableList/components/NameCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableList/components/OperationCell.vue
  frontend/src/components/SchemaEditorV1/Panels/TableList/components/index.ts
  frontend/src/components/SchemaEditorV1/Panels/TableList/index.ts
  frontend/src/components/SchemaEditorV1/TabsContainer.vue
  frontend/src/components/SchemaEditorV1/index.vue
  frontend/src/components/SchemaEditorV1/utils/branch.ts
  frontend/src/components/SchemaEditorV1/utils/column.ts
  frontend/src/components/SchemaEditorV1/utils/columnDefaultValue.ts
  frontend/src/components/SchemaEditorV1/utils/database.ts
  frontend/src/components/SchemaEditorV1/utils/index.ts
  frontend/src/components/SchemaEditorV1/utils/metadata.ts
  frontend/src/components/SchemaEditorV1/utils/schema.ts
  frontend/src/components/SchemaEditorV1/utils/table.ts
  frontend/src/components/SchemaEditorV1/utils/useMetadataForDiagram.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/schemaEditor.ts
  frontend/src/types/v1/schemaEditor/state.ts
Labels: cla-signed

#12030 chore: update issue filter specs
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/store/issue.go
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/utils/v1/advanced-search/issue/utils.ts
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/ExportCenter/types.ts
Labels: cla-signed

#12028 fix: task run log for mssql & oracle
  backend/component/sheet/sheet.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/parser/base/base.go
  backend/plugin/parser/plsql/split.go
  backend/plugin/parser/plsql/split_test.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#12035 chore: add example for upload json file
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue
  frontend/src/components/SensitiveData/components/DataExampleModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12034 chore: go 1.22.3
  .github/workflows/backend-tests.yml
  .github/workflows/build-artifacts-and-draft-release.yml
  .github/workflows/test_link.yml
  README.md
  go.mod
  scripts/.air.toml
  scripts/.goreleaser-for-darwin.yaml
  scripts/.goreleaser-for-linux.yaml
  scripts/Dockerfile
  scripts/Dockerfile.aws
  scripts/Dockerfile.depot
  scripts/Dockerfile.render-demo
  scripts/build_bytebase.sh
Labels: cla-signed

#12036 chore: no binary
  .github/workflows/build-artifacts-and-draft-release.yml
  scripts/.goreleaser-for-darwin.yaml
  scripts/.goreleaser-for-linux.yaml
  scripts/.goreleaser-release.yaml
  scripts/build_darwin_release.sh
Labels: cla-signed

#12038 fix(frontend): use endOf the day as the upper limit of date time filter
  frontend/src/components/AdvancedSearch/TimeRange.vue
Labels: cla-signed

#12039 chore: add back i18n of review center
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12037 feat(mongodb): support mongodb replica set
  backend/api/v1/instance_service.go
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
  backend/store/data_source.go
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12040 chore(frontend): retire oracle sql rollback
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
Labels: cla-signed

#12041 chore: tweak issue options display
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
  frontend/src/components/IssueV1/components/ReviewIssueSpecSection/ReviewOptionSection/ReviewOptionSection.vue
Labels: cla-signed

#12042 fix(mysql): scientific notation
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#12043 refactor: remove to_jsonb in jsonb_build_object
  backend/store/data_source.go
  backend/store/task.go
  backend/store/vcs_connector.go
Labels: cla-signed

#12044 chore: sort issues
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskDialog.vue
  frontend/src/components/ExprEditor/ConditionGroup.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
Labels: cla-signed

#12046 Add SSL options support for MongoDB connections
  backend/plugin/db/mongodb/mongodb.go
Labels: cla-signed

#12047 feat: add direct connection in datasource proto
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/anomaly_service.pb.gw.go
  proto/generated-go/v1/audit_log_service.pb.gw.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/cel_service.pb.gw.go
  proto/generated-go/v1/changelist_service.pb.gw.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/logging_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/risk_service.pb.gw.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/setting_service.pb.gw.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/generated-go/v1/vcs_connector_service.pb.gw.go
  proto/generated-go/v1/vcs_provider_service.pb.gw.go
  proto/generated-go/v1/worksheet_service.pb.gw.go
  proto/store/data_source.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#12048 feat(mongodb): support direct connection
  backend/api/v1/instance_service.go
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/driver.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
  backend/store/data_source.go
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12049 chore: upgrade tsql parser for performance
  backend/plugin/parser/tsql/backup.go
  backend/plugin/parser/tsql/completion.go
  backend/plugin/parser/tsql/query.go
  backend/plugin/parser/tsql/query_span_extractor.go
  backend/plugin/parser/tsql/tsql.go
  go.mod
  go.sum
Labels: cla-signed

#12052 fix: bool algebra
  backend/store/principal.go
Labels: cla-signed

#12053 chore: unused proto
  frontend/src/types/proto/store/policy.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/policy.pb.go
  proto/store/policy.proto
Labels: cla-signed

#12054 chore: audit log user uid
  backend/api/gitops/webhook.go
  backend/api/v1/audit.go
  backend/api/v1/audit_log_service.go
  backend/migrator/migration/prod/2.18/0000##audit_user.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto/store/audit_log.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/audit_log.pb.go
  proto/store/audit_log.proto
Labels: cla-signed

#12057 chore: deprecate issue comment assignee change
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/migrator/migration/prod/2.18/0001##issue_comment_assignee.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto/store/issue_comment.ts
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/issue_comment.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/store/issue_comment.proto
  proto/v1/issue_service.proto
Labels: cla-signed

#12058 chore(frontend): retire assignee (more)
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/IssueV1/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Title.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionIcon.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/Assignee/Assignee.vue
  frontend/src/components/IssueV1/components/Sidebar/Assignee/index.ts
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
  frontend/src/components/IssueV1/logic/action/issue.ts
  frontend/src/components/IssueV1/logic/assignee.ts
  frontend/src/components/IssueV1/logic/index.ts
  frontend/src/components/IssueV1/logic/transition.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/index.ts
  frontend/src/plugins/types.ts
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/common.ts
  frontend/src/types/issue.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/utils/task.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/utils/v1/advanced-search/issue/utils.ts
Labels: cla-signed

#12059 chore: add user_group table
  backend/migrator/migration/prod/2.18/0002##user_group.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/sql-server/advise.go
Labels: cla-signed

#12062 chore: branch updater uid
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sheet_service.go
  backend/api/v1/sql_service.go
  backend/component/masker/masker.go
  backend/plugin/db/pg/sync.go
  frontend/src/types/proto/store/database.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/database.pb.go
  proto/store/database.proto
Labels: cla-signed

#12064 chore: use timestamptz
  backend/migrator/migration/prod/2.18/0003##fix_task_run_log_ts.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#12065 chore: fail-open for updater
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sheet_service.go
Labels: cla-signed

#12066 chore: masking exception policy uid
  backend/api/v1/masking_evaluator_test.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/query_result_masker.go
  frontend/src/types/proto/store/policy.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/policy.pb.go
  proto/store/policy.proto
Labels: cla-signed

#12067 chore: update user name in masking exceptions
  backend/migrator/migration/prod/2.18/0004##masking_exception_user_name.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#12068 chore: update UpdatePlan
  backend/api/v1/plan_service.go
  backend/store/plan.go
Labels: cla-signed

#12069 chore: optimize user cache
  backend/api/gitops/webhook.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/logging_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/query_result_masker.go
  backend/api/v1/setting_service.go
  backend/api/v1/worksheet_service.go
  backend/store/principal.go
  backend/store/store.go
Labels: cla-signed

#12070 feat: implement user group api
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/user_group.go
  backend/common/resource_name.go
  backend/server/grpc_routes.go
  backend/store/store.go
  backend/store/user_group.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/user_group.ts
  frontend/src/types/proto/v1/user_group.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/user_group.pb.go
  proto/generated-go/v1/user_group.pb.go
  proto/generated-go/v1/user_group.pb.gw.go
  proto/generated-go/v1/user_group_grpc.pb.go
  proto/store/user_group.proto
  proto/v1/user_group.proto
Labels: cla-signed

#12072 chore: bq proto
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/common.ts
  frontend/src/types/proto/v1/common.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/common.pb.go
  proto/generated-go/v1/common.pb.go
  proto/store/common.proto
  proto/v1/common.proto
Labels: cla-signed

#12073 feat: update app im setting
  backend/api/v1/setting_service.go
  backend/legacyapi/setting.go
  backend/store/setting.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#12074 chore: add sql review only checkbox when creating issue
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/DatabaseGroupPrevEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/AuditLog/AuditLogDataTable.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/components/Plan/logic/plan.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/databaseGroup/issue.ts
Labels: cla-signed

#12080 chore: handle deployement config spec
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/StepSection/StepSection.vue
Labels: cla-signed

#12079 chore: compare column default value consider case insensitive
  backend/api/v1/schema_design_merge.go
Labels: cla-signed

#12081 chore(frontend): always test connection before updating/adding datasources
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/InstanceForm/InstanceForm.vue
Labels: cla-signed

#12077 feat: implement search plans
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/plan_service.go
  backend/store/plan.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/generated-go/v1/plan_service.pb.gw.go
  proto/generated-go/v1/plan_service_grpc.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#12083 feat(proto): direct_message in Webhook
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/project_service.pb.go
  proto/v1/project_service.proto
Labels: cla-signed

#12082 fix(es): CA cert error
  backend/plugin/db/elasticsearch/elasticsearch.go
Labels: cla-signed

#12086 feat: parse to metadata write to user comment
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/parse-to-metadata/standard.yaml
  backend/plugin/schema/mysql/testdata/parse-to-metadata/view.yaml
  backend/plugin/schema/oracle/state.go
  backend/plugin/schema/pg/parse_to_metadata.go
  backend/plugin/schema/pg/testdata/parse_to_metadata.yaml
  backend/plugin/schema/tidb/state.go
  backend/plugin/schema/tidb/testdata/parse_to_metadata.yaml
Labels: cla-signed

#12087 chore: allow pg_stat_statements
  backend/plugin/parser/pg/system_objects.go
Labels: cla-signed

#12088 feat: implement user group
  backend/api/v1/auth_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/logging_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/user_group.go
  backend/store/user_group.go
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserGroupsCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberRoleSelect.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/UserNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/index.vue
  frontend/src/components/v2/Select/UserSelect.vue
  frontend/src/grpcweb/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspaceSetting.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/userGroup.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/user_group.ts
  frontend/src/views/SettingSidebar.vue
  frontend/src/views/SettingWorkspaceMember.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/user_group.pb.go
  proto/v1/user_group.proto
Labels: cla-signed

#12089 chore: bq fe
  backend/api/v1/common.go
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/bigquery/dump.go
  backend/plugin/db/bigquery/role.go
  backend/plugin/db/bigquery/sync.go
  backend/server/ultimate.go
  frontend/src/assets/bigquery.svg
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceSection.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/constants.ts
  frontend/src/types/instance.ts
  frontend/src/types/v1/instance.ts
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#12090 feat(frontend): implement plan list page
  backend/api/v1/rollout_service_converter.go
  backend/store/plan.go
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/Plan/components/PagedPlanTable.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/PlanDataTable/index.ts
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/poll.ts
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/plan_service.ts
  frontend/src/types/v1/issue/plan.ts
  frontend/src/utils/iam/permission-utils.ts
  frontend/src/views/ReviewCenter/index.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#12092 chore: retire unused issue type in frontend
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/ReviewIssuePrepForm/ReviewIssuePrepForm.vue
  frontend/src/components/ReviewIssuePrepForm/index.ts
  frontend/src/types/issue.ts
  frontend/src/utils/issue/index.ts
Labels: cla-signed
