Repository bytebase/bytebase, pull requests merged in 2024-01, with the labels that each got.

#10155 chore: renovate clickhouse sync schema
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/sqlite/sync.go
  backend/plugin/db/starrocks/sync.go
  backend/plugin/db/tidb/sync.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/parser/pg/system_objects.go
Labels: cla-signed

#10156 chore: add learn more link to rollout policy
  frontend/src/components/EnvironmentForm.vue
Labels: cla-signed

#10157 chore: ghost2
  backend/component/ghost/config.go
  backend/component/ghost/logger.go
  backend/tests/ghost_test.go
  backend/tests/test-data/ghost_test_schema2.result
  go.mod
  go.sum
Labels: cla-signed

#10158 fix: migrate role names sql
  backend/migrator/migration/prod/2.13/0002##migrate_role_names.sql
Labels: cla-signed

#10159 refactor: rename schema design to branch
  backend/api/v1/branch_service.go
  backend/store/branch.go
Labels: cla-signed

#10160 fix: workspaceDeveloper->workspaceMember
  backend/migrator/migration/prod/2.13/0002##migrate_role_names.sql
Labels: cla-signed

#10162 fix(frontend): listElRef undefined since NTree with virtual-scroll has no height explicitly
  frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
Labels: cla-signed, backport release/2.13.0

#10164 chore(frontend): update fetch org policies
  backend/component/iam/acl.yaml
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/store/modules/slowQueryPolicy.ts
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/SettingWorkspaceMember.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/org_policy_service.proto
Labels: cla-signed

#10167 chore: ListRoles lists workspace roles
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  backend/server/server.go
  backend/store/role.go
  backend/store/store.go
Labels: cla-signed

#10165 fix(frontend): sync schema page won't refresh when changing project
  frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/views/ProjectDetail.vue
Labels: cla-signed, backport release/2.13.0

#10166 chore: hide allUsers in member list
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/v2/Model/DatabaseV1Name.vue
  frontend/src/store/modules/user.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/v1/user.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/SettingWorkspaceAccessControl.vue
  frontend/src/views/SettingWorkspaceMember.vue
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
Labels: cla-signed

#10170 feat: listUser fetch all roles
  backend/api/v1/auth_service.go
  backend/store/principal.go
Labels: cla-signed

#10172 chore: return roles' permissions in role service
  backend/api/v1/project_service.go
  backend/api/v1/role_service.go
  backend/component/iam/manager.go
  backend/component/iam/permission.go
  backend/server/grpc_routes.go
Labels: cla-signed

#10171 chore(frontend): tweak roles definition
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/RoleSelect.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/IssueV1/components/GrantRequest/GrantRequestExporterForm.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberTable/ProjectMemberTable.vue
  frontend/src/components/ProjectMember/ProjectRoleTable/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectRoleTable/ProjectRoleTable.vue
  frontend/src/components/Role/Setting/components/RoleTableRow.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Select/ProjectMemberRoleSelect.vue
  frontend/src/components/v2/Select/UserSelect.vue
  frontend/src/store/modules/role.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/iam/index.ts
  frontend/src/types/iam/role.ts
  frontend/src/types/index.ts
  frontend/src/types/v1/role.ts
  frontend/src/utils/iam/index.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/utils/iam/role.ts
  frontend/src/utils/index.ts
  frontend/src/utils/role.ts
  frontend/src/utils/v1/database.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/SettingWorkspaceAccessControl.vue
Labels: cla-signed

#10174 feat: implement rollback UPDATE for MySQL
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/normalize.go
  backend/plugin/parser/mysql/rollback.go
  backend/plugin/parser/mysql/rollback_test.go
  backend/plugin/parser/mysql/test-data/test_rollback.yaml
Labels: cla-signed

#10175 chore: update role data table
  frontend/src/components/DBExtensionDataTable.vue
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationCell.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleTitleCell.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleTypeCell.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
  frontend/src/components/Role/Setting/components/RolePanel.vue
  frontend/src/components/Role/Setting/components/RoleTable.vue
  frontend/src/components/Role/Setting/components/RoleTableRow.vue
  frontend/src/components/Role/Setting/components/index.ts
  frontend/src/components/User/Settings/UserTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/role.ts
  frontend/src/utils/iam/role.ts
  frontend/src/utils/role.ts
  frontend/src/utils/v1/role.ts
Labels: cla-signed

#10176 chore: fix role format
  backend/api/v1/auth_service.go
Labels: cla-signed

#10178 chore: use iam permission checks for environment section
  frontend/src/components/EnvironmentForm.vue
  frontend/src/components/Quickstart.vue
  frontend/src/utils/role.ts
  frontend/src/views/Archive.vue
Labels: cla-signed

#10179 feat(GetDesignSchema): handle table constraint in get design schema for mysql
  backend/plugin/schema/mysql/structurer.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
Labels: cla-signed

#10180 chore: support export with password
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_v2.go
  backend/tests/sql_export_test.go
  frontend/src/components/DataExportButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/export.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/views/ExportCenter/ExportDataButton.vue
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  go.mod
  go.sum
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#10181 fix(structurer): remove field length and direction in index expressions
  backend/plugin/schema/mysql/structurer.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
  backend/plugin/schema/mysql/testdata/parse_to_metadata.yaml
Labels: cla-signed

#10183 test(branch): add index test in try merge
  backend/api/v1/testdata/schema_design_merge/try_merge.yaml
Labels: cla-signed

#10184 fix(frontend): error occurs when syncing sql from schema editor
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
Labels: cla-signed

#10186 fix: tidb txn
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#10185 chore: fix tidb txn
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#10187 chore: add version to change
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/changelist.ts
  frontend/src/types/proto/v1/changelist_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/changelist.pb.go
  proto/generated-go/v1/changelist_service.pb.go
  proto/store/changelist.proto
  proto/v1/changelist_service.proto
Labels: cla-signed

#10188 chore: tidb txn fix 2.12.0
  backend/plugin/db/mysql/mysql.go
Labels: cla-signed

#10173 feat: impl roles for Create/UpdateUser
  backend/api/v1/auth_service.go
  backend/component/iam/manager.go
  backend/store/principal.go
Labels: cla-signed

#10189 chore: tidb execution status
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#10191 chore: move tidb create index to separate transactions
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/tidb/tidb_test.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#10192 chore(frontend): adjust items' vertical spacing for issue sidebar
  frontend/src/components/IssueV1/components/Sidebar/Assignee/Assignee.vue
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
Labels: cla-signed

#10190 feat(branch): support index in schema editor
  frontend/src/components/Icon/IndexIcon.vue
  frontend/src/components/Icon/index.ts
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/IndexesEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/ColumnsCell.vue
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/OperationCell.vue
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/index.ts
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/index.ts
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#10193 chore(branch): use underscore instead of dash for random index name
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
Labels: cla-signed

#10194 chore: bring back SearchDatabases
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#10196 feat: use TransformDMLToSelect to generate statements
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/rollback.go
  backend/plugin/parser/mysql/rollback.go
  backend/plugin/parser/mysql/rollback_test.go
  backend/plugin/parser/mysql/test-data/test_rollback.yaml
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/data_update_executor_test.go
Labels: cla-signed

#10197 fix: update user
  backend/store/principal.go
Labels: cla-signed

#10198 chore: update workspace members page
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/components/User/Settings/MemberAddOrInvite.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/User/Settings/UserDataTableByRole/cells/UserNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByRole/cells/UserOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTableByRole/index.vue
  frontend/src/components/User/Settings/UserTable.vue
  frontend/src/components/User/Settings/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/role.ts
  frontend/src/store/modules/user.ts
  frontend/src/types/iam/role.ts
  frontend/src/views/SettingWorkspaceMember.vue
Labels: cla-signed

#10195 feat: iam for SearchProjects
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/project_service.go
Labels: cla-signed

#10199 chore: update disabled attr of confirm button
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#10200 refactor(structurer): split to multiple files
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/parse_to_metadata.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/structurer.go
  backend/plugin/schema/mysql/structurer_test.go
  backend/plugin/schema/mysql/utils.go
Labels: cla-signed

#10201 chore: update IAM flag default value
  backend/bin/server/cmd/profile_dev.go
  backend/component/iam/acl.yaml
Labels: cla-signed

#10202 chore(frontend): changelist improvements
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryChangeItem.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue
Labels: cla-signed

#10203 fix: update schema cache
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/store/modules/v1/dbSchema.ts
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#10206 chore(frontend): branch creating ui improvements
  frontend/src/components/Branch/BaselineSchemaSelector.vue
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#10204 chore: use the change history schema version to create plan
  backend/api/v1/changelist_service.go
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
Labels: cla-signed

#10205 chore(branch): filter out database metadata fields we do not support
  backend/api/v1/branch_service.go
Labels: cla-signed

#10207 chore(branch): pass table collation and engine
  backend/api/v1/branch_service.go
Labels: cla-signed

#10208 chore: fix create user params
  frontend/src/components/User/Settings/CreateUserDrawer.vue
  frontend/src/store/modules/auth.ts
Labels: cla-signed

#10211 fix: SQL review check view style tweaks
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckBar/PlanCheckDetail.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SQLCheck/SQLCheckDetail.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseLabelFilter.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/views/DatabaseDashboard.vue
Labels: cla-signed

#10209 chore: upgrade ghost
  backend/tests/ghost_test.go
  backend/tests/test-data/ghost_test_schema2.result
  go.mod
  go.sum
Labels: cla-signed

#10213 chore(sql-editor): remove get instance in router
  frontend/src/router/index.ts
Labels: cla-signed

#10210 fix: fix pg convert DefElemNode
  backend/plugin/parser/sql/engine/pg/convert.go
Labels: cla-signed

#10214 chore: add task created_ts to ghost filename
  backend/component/ghost/config.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_ghost_sync_executor.go
Labels: cla-signed

#10215 chore: dev IAM false
  backend/bin/server/cmd/profile_dev.go
Labels: cla-signed

#10216 fix: tidb statement type check
  backend/runner/plancheck/statement_type_executor.go
Labels: cla-signed

#10217 chore(frontend): disable create issue button when sql check running
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed

#10218 refactor: remove extract TiDB unsupported statements
  backend/plugin/db/mysql/rollback.go
  backend/plugin/parser/tidb/compatible.go
  backend/plugin/parser/tidb/compatible_test.go
  backend/plugin/parser/tidb/differ.go
  backend/plugin/parser/tidb/differ_test.go
  backend/plugin/parser/tidb/differ_utils.go
  backend/plugin/parser/tidb/differ_utils_test.go
Labels: cla-signed

#10212 fix(mysql/structurer): generate remaining index/key
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
  backend/plugin/schema/mysql/testdata/parse_to_metadata.yaml
Labels: cla-signed

#10219 chore: instance maximum connections
  backend/api/v1/instance_service.go
  backend/component/state/state.go
  backend/runner/plancheck/scheduler.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/instance.go
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/MaximumConnectionsInput.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/instance.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/instance.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/cel_service.pb.gw.go
  proto/generated-go/v1/changelist_service.pb.gw.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/externalvs_service.pb.gw.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/inbox_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/logging_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/risk_service.pb.gw.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/setting_service.pb.gw.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/store/instance.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#10220 chore: use database owner to initialize schema
  backend/migrator/migrator.go
Labels: cla-signed

#10221 chore: backfill metadata database schema object owner to database owner
  backend/migrator/migrator.go
  backend/plugin/db/pg/pg.go
  backend/runner/taskrun/pitr_restore_executor.go
Labels: cla-signed

#10222 refactor(frontend): branch tree and database tree
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/SchemaEditorLite/Aside/Aside.vue
  frontend/src/components/SchemaEditorLite/Aside/Tree.vue
  frontend/src/components/SchemaEditorLite/Aside/common.ts
  frontend/src/components/SchemaEditorLite/Aside/types.ts
Labels: cla-signed

#10223 fix(mysql/structurer): add comment of primary key
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
Labels: cla-signed

#10224 fix: return valid instance after creation
  backend/api/v1/instance_service.go
  backend/runner/schemasync/syncer.go
  backend/server/onboard.go
  frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
  frontend/src/components/SQLReview/SQLReviewPolicyTable.vue
Labels: cla-signed

#10226 chore: bump version to 2.13.1
  scripts/VERSION
Labels: cla-signed

#10225 fix: create user
  backend/store/principal.go
  backend/store/role.go
Labels: cla-signed

#10227 chore: enable pre-update-backup
  backend/bin/server/cmd/root.go
Labels: cla-signed

#10228 chore: prevent remove the last workspace admin in frontend
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#10229 feat(frontend): allow using custom role for environment rollout releaser policy
  frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/v2/Select/ProjectRoleSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/project.ts
  frontend/src/utils/projectIamPolicy.ts
  frontend/src/utils/role.ts
Labels: cla-signed

#10231 fix(frontend): use build tree options correctly
  frontend/src/components/SchemaEditorLite/Aside/Tree.vue
Labels: cla-signed

#10233 refactor: split files
  backend/plugin/schema/tidb/get_design_schema.go
  backend/plugin/schema/tidb/structurer.go
Labels: cla-signed

#10234 chore: split files
  backend/plugin/schema/mysql/get_design_schema_test.go
  backend/plugin/schema/mysql/parse_to_metadata_test.go
  backend/plugin/schema/pg/common.go
  backend/plugin/schema/pg/get_design_schema.go
  backend/plugin/schema/pg/get_design_schema_test.go
  backend/plugin/schema/pg/parse_to_metadata.go
  backend/plugin/schema/pg/parse_to_metadata_test.go
  backend/plugin/schema/tidb/get_design_schema_test.go
  backend/plugin/schema/tidb/parse_to_metadata.go
  backend/plugin/schema/tidb/parse_to_metadata_test.go
Labels: cla-signed

#10235 feat: actuator service return features
  backend/api/v1/actuator_service.go
  backend/legacyapi/plan.go
  backend/server/grpc_routes.go
  frontend/src/types/proto/v1/actuator_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/actuator_service.pb.go
  proto/v1/actuator_service.proto
Labels: cla-signed

#10236 chore: update upgrade subscription banner
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#10237 feat: validate role resource id
  backend/api/v1/resource_id.go
  backend/api/v1/resource_id_test.go
  backend/api/v1/role_service.go
Labels: cla-signed

#10239 chore(frontend): fix issue table text overflow
  frontend/src/components/EllipsisText.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/utils/util.ts
Labels: cla-signed

#10238 chore: download raw file if not provide the password
  backend/api/v1/sql_service.go
  backend/tests/sql_export_test.go
  frontend/src/components/DataExportButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ExportCenter/ExportDataButton.vue
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#10241 chore: remove unused routes
  frontend/src/router/index.ts
Labels: cla-signed

#10242 fix: backup db nil pointer
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#10243 chore(frontend): only allow to create child branches from main (parent-less) branches
  frontend/src/components/Branch/BranchCreateView.vue
Labels: cla-signed

#10244 chore(frontend): always show next button on the branch page
  frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
  frontend/src/components/Branch/BranchMergeView/SelectBranchStep.vue
  frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue
  frontend/src/components/Branch/BranchRebaseView/SelectBranchStep.vue
Labels: cla-signed

#10247 chore: split auth routes
  frontend/src/layouts/SplashLayout.vue
  frontend/src/router/auth.ts
  frontend/src/router/index.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/views/TwoFactorSetup.vue
  frontend/src/views/auth/MultiFactor.vue
Labels: cla-signed

#10249 chore: split sql editor routes
  frontend/src/App.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/layouts/SplashLayout.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/router/sqlEditor.ts
  frontend/src/views/OAuthCallback.vue
  frontend/src/views/TwoFactorRequired.vue
  frontend/src/views/TwoFactorSetup.vue
  frontend/src/views/auth/Signin.vue
  frontend/src/views/sql-editor/Sheet/SheetTable/SheetTable.vue
Labels: cla-signed

#10246 fix(structurer): compare index in get design schema
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/get_design_schema_test.go
Labels: cla-signed

#10250 feat: impl search databases
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/database_service.go
Labels: cla-signed

#10245 fix: slow query panel
  backend/store/slow_query.go
  frontend/src/components/Project/ProjectSidebar.vue
  frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/SlowQuery/Panel/LogTable.vue
  frontend/src/components/SlowQuery/Panel/types.ts
  frontend/src/store/modules/slowQuery.ts
  frontend/src/types/slowQuery.ts
Labels: cla-signed

#10248 chore(frontend): branch and schema editor UI improvements
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchMergeView/MergeBranchStep.vue
  frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
  frontend/src/components/Branch/SchemaDesignEditorLite.vue
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/MonacoEditor/editor.ts
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SchemaEditorLite/Panels/IndexesEditor/components/OperationCell.vue
  frontend/src/components/SchemaEditorLite/common.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#10252 feat: impl search instances
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/database_service.go
  backend/api/v1/instance_service.go
  backend/server/grpc_routes.go
  backend/store/instance.go
Labels: cla-signed

#10253 chore: remove beta tag from DM
  frontend/src/components/InstanceForm/specs.ts
Labels: cla-signed

#10254 chore(frontend): fix parent-less branch logic
  frontend/src/components/Branch/BranchCreateView.vue
Labels: cla-signed

#10257 chore(structurer): default value for text/blob/geometry/json
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
  backend/plugin/schema/mysql/utils.go
Labels: cla-signed

#10258 chore(structurer): nullable for text/blob/geometry/json
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
Labels: cla-signed

#10255 chore: update demo data to use ALTER_TABLE on prod as high risk
  backend/demo/data/next/dump.sql
Labels: cla-signed

#10256 chore: update change history detail page
  backend/api/v1/database_service.go
  backend/store/instance_change_history.go
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/changeHistory.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/views/ChangeHistoryDetail.vue
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#10251 chore: split dashboard routes
  frontend/src/components/KBar/KBarWrapper.vue
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/router/dashboard/database.ts
  frontend/src/router/dashboard/environment.ts
  frontend/src/router/dashboard/index.ts
  frontend/src/router/dashboard/instance.ts
  frontend/src/router/dashboard/issue.ts
  frontend/src/router/dashboard/project.ts
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceSetting.ts
  frontend/src/router/index.ts
  frontend/src/views/Page403.vue
  frontend/src/views/Page404.vue
Labels: cla-signed

#10259 chore: don't update sheet project for database project update
  backend/store/database.go
Labels: cla-signed

#10260 fix: demo data external url
  backend/demo/data/next/dump.sql
Labels: cla-signed

#10261 fix: service account email
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#10262 fix: add DROP DATABASE to the PG non-transactional statement
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#10264 fix: use uint8 length
  backend/store/instance_change_history.go
  backend/store/sheet.go
  frontend/src/components/Changelist/ChangelistDetail/RawSQLPanel/RawSQLPanel.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/SyncDatabaseSchema/RawSQLEditor.vue
  frontend/src/store/modules/v1/sheet.ts
  frontend/src/utils/index.ts
  frontend/src/utils/sheet.ts
  frontend/src/utils/v1/sheet.ts
  frontend/src/views/ChangeHistoryDetail.vue
  frontend/src/views/sql-editor/EditorPanel/SheetForIssueTipsBar.vue
Labels: cla-signed

#10265 chore: append workspaceAdmin if rbac disabled
  backend/api/v1/acl.go
  backend/api/v1/acl_config.go
Labels: cla-signed

#10268 fix: use principal.status
  backend/store/stats.go
Labels: cla-signed

#10270 feat: implement column def manipulate
  backend/plugin/parser/tidb/strings.go
  backend/plugin/parser/tidb/strings_test.go
  backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
  go.mod
  go.sum
Labels: cla-signed

#10272 fix(driver/pg): trim space before calling strings.HasPrefix
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#10267 fix: should show sheet even if the database is transfer out
  frontend/src/views/sql-editor/SecondarySidebar/SheetTabPane/SheetList/SheetList.vue
Labels: cla-signed

#10273 fix(driver/risingwave/redshift): trim space before call strings.HasPrefix
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
Labels: cla-signed

#10275 chore(frontend): show "apply to other tasks" when the project is batch mode but the database list is manually selected
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
Labels: cla-signed

#10277 fix: navie-ui transfer bug
  frontend/src/components/Issue/panel/RequestExportPanel/ExportResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/ProjectDetail.vue
  frontend/src/views/project/ProjectDatabaseDashboard.vue
Labels: cla-signed

#10276 chore(mysql/structurer): better mysql get design schema syntax
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/get_design_schema.yaml
Labels: cla-signed

#10279 fix: acl interceptor
  backend/api/v1/acl.go
Labels: cla-signed

#10280 chore: remove changelist filter on the frontend
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue
Labels: cla-signed

#10278 chore(frontend): retire inbox page
  frontend/src/components/InboxList.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/router/dashboard/workspace.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/inbox.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/views/DashboardHeader.vue
  frontend/src/views/Inbox.vue
Labels: cla-signed

#10281 chore(backend): retire inbox service
  backend/api/v1/acl_iam.go
  backend/api/v1/inbox_service.go
  backend/common/resource_name.go
  backend/component/activity/manager.go
  backend/enterprise/api/plan.yaml
  backend/legacyapi/activity.go
  backend/legacyapi/inbox.go
  backend/server/grpc_routes.go
  backend/store/inbox.go
  frontend/src/grpcweb/index.ts
  frontend/src/types/proto/store/activity.ts
  frontend/src/types/proto/v1/deployment.ts
  frontend/src/types/proto/v1/inbox_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/activity.pb.go
  proto/generated-go/v1/inbox_service.pb.go
  proto/generated-go/v1/inbox_service.pb.gw.go
  proto/generated-go/v1/inbox_service_grpc.pb.go
  proto/store/activity.proto
  proto/v1/inbox_service.proto
Labels: cla-signed

#10284 chore: only use searchDatabases if iam
  frontend/src/store/modules/v1/database.ts
Labels: cla-signed

#10283 feat: implement table constraint actions
  backend/plugin/parser/tidb/normalize.go
  backend/plugin/parser/tidb/strings.go
  backend/plugin/parser/tidb/strings_test.go
  backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
  go.mod
  go.sum
Labels: cla-signed

#10285 chore: searchInstances/Projects if iam
  frontend/src/store/modules/v1/instance.ts
  frontend/src/store/modules/v1/project.ts
Labels: cla-signed

#10286 fix(query-span): skip empty statement for query span
  backend/plugin/parser/base/interface.go
Labels: cla-signed

#10287 chore(branch): add force option on delete branch request
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/v1/branch_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/v1/branch_service.proto
Labels: cla-signed

#10288 feat(branch): return failed precondition if deleted branch contains sub branches
  backend/api/v1/branch_service.go
  backend/store/branch.go
  frontend/src/store/modules/branch.ts
Labels: cla-signed

#10290 feat: branch for tidb use manipulator
  backend/plugin/db/tidb/sync.go
  backend/plugin/parser/tidb/strings.go
  backend/plugin/parser/tidb/strings_test.go
  backend/plugin/parser/tidb/test-data/test_strings_manipulate.yaml
  backend/plugin/schema/tidb/get_design_schema.go
  backend/plugin/schema/tidb/parse_to_metadata.go
  backend/plugin/schema/tidb/testdata/get_design_schema.yaml
Labels: cla-signed

#10291 fix: ui padding without quick action buttons
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/ProjectLayout.vue
Labels: cla-signed

#10292 fix: oauth route checks
  frontend/src/router/index.ts
Labels: cla-signed, backport release/2.13.1

#10295 refactor: use route name instead of the path
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/components/Branch/BranchDataTable/cells/BranchNameCell.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchMergeView/SelectBranchStep.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangelistDetail.vue
  frontend/src/components/Changelist/ChangelistDetail/DeleteChangelistButton.vue
  frontend/src/components/CommonSidebar.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/IdentityProviderCreateForm.vue
  frontend/src/components/IdentityProviderTable.vue
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/components/Project/WebhookTypeIcon.vue
  frontend/src/components/ProjectBranchesPanel.vue
  frontend/src/components/ProjectWebhookCard.vue
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/components/ProjectWebhookPanel.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/components/RepositoryTable.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/SQLReviewPolicyTable.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/TrialModal.vue
  frontend/src/components/UpgradeSubscriptionButton.vue
  frontend/src/components/VCS/VCSCard.vue
  frontend/src/components/VCS/VCSSetupWizard.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/plugins/ai/components/MockInputPlaceholder.vue
  frontend/src/router/dashboard/database.ts
  frontend/src/router/dashboard/environment.ts
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/router/dashboard/workspaceSetting.ts
  frontend/src/router/index.ts
  frontend/src/utils/role.ts
  frontend/src/views/BannerUpgradeSubscription.vue
  frontend/src/views/DashboardHeader.vue
  frontend/src/views/DatabaseDetail.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingSidebar.vue
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceVCS.vue
  frontend/src/views/SettingWorkspaceVCSDetail.vue
  frontend/src/views/TwoFactorSetup.vue
  frontend/src/views/branch/BranchDetail.vue
  frontend/src/views/branch/BranchMerge.vue
  frontend/src/views/branch/BranchRebase.vue
  frontend/src/views/project/ProjectWebhookDetail.vue
Labels: cla-signed

#10296 feat: add materialized view proto
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#10297 chore(frontend): fix unexpected placeholder
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
Labels: backport release/2.13.1

#10300 chore(frontend): don's show earliest allowed time if not needed
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
Labels: cla-signed

#10301 fix: releaser candidates
  frontend/src/components/IssueV1/logic/releaser.ts
Labels: cla-signed, backport release/2.13.1

#10302 feat: sync materialized views and support them in getQuerySpan
  backend/api/v1/database_converter.go
  backend/api/v1/sql_service.go
  backend/plugin/db/pg/sync.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/pg/parse_to_metadata.go
  backend/plugin/schema/tidb/parse_to_metadata.go
  backend/store/model/database.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#10304 fix(structurer): keep default null for json/geometry
  backend/plugin/schema/mysql/get_design_schema.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/utils.go
Labels: cla-signed

#10305 chore(frontend): filter database metadata
  frontend/src/components/Branch/BranchRolloutView/useVirtualBranch.ts
  frontend/src/components/SchemaEditorLite/algorithm/apply-selected.ts
  frontend/src/components/SchemaEditorLite/algorithm/diff-merge.ts
  frontend/src/utils/schemaEditor/filter.ts
  frontend/src/utils/schemaEditor/index.ts
Labels: cla-signed

#10306 cherrypick: sync materialized views and support them in getQuerySpan
  backend/api/v1/database_converter.go
  backend/api/v1/sql_service.go
  backend/plugin/db/pg/sync.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/schema/tidb/structurer.go
  backend/store/model/database.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/cel_service.pb.gw.go
  proto/generated-go/v1/changelist_service.pb.gw.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/externalvs_service.pb.gw.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/inbox_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/logging_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/risk_service.pb.gw.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/setting_service.pb.gw.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#10307 chore(issue): hide learn more button in standalone mode
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackSection.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackStatus.vue
  frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
Labels: cla-signed

#10311 fix: fix mysql splitter when escaping double quote
  backend/plugin/parser/mysql/split_test.go
  go.mod
  go.sum
Labels: cla-signed

#10310 fix: iam config for CreateIssue
  backend/api/v1/acl_config.go
Labels: cla-signed

#10309 chore(frontend): double warning and force delete parent branch
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/branch.ts
Labels: cla-signed

#10308 chore: remove i18n of inbox
  frontend/public/help/routeMapList.json
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/index.ts
  frontend/src/types/common.ts
Labels: cla-signed

#10240 chore(frontend): migrate issue iam
  frontend/src/components/IssueV1/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/Title.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/Assignee/Assignee.vue
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
  frontend/src/components/IssueV1/logic/action/issue.ts
  frontend/src/components/IssueV1/logic/action/task.ts
  frontend/src/components/IssueV1/logic/assignee.ts
  frontend/src/components/IssueV1/logic/plan-check.ts
  frontend/src/components/IssueV1/logic/rollout.ts
  frontend/src/components/IssueV1/logic/transition.ts
Labels: cla-signed

#10313 fix: compare statement and schema size
  frontend/src/store/modules/v1/changeHistory.ts
Labels: cla-signed

#10320 fix: project sidebar routing
  frontend/src/components/Project/ProjectSidebarV1.vue
Labels: cla-signed

#10321 chore: project deployment config page
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/ProjectDeploymentConfigPanel.vue
Labels: cla-signed

#10323 chore: short circuit old permission checks
  backend/api/v1/acl.go
Labels: cla-signed

#10325 chore: migrate quick action with iam permissions
  frontend/src/components/CommonSidebar.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/router/dashboard/database.ts
  frontend/src/router/dashboard/environment.ts
  frontend/src/router/dashboard/instance.ts
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/router/dashboard/workspace.ts
  frontend/src/shims-vue-router.d.ts
  frontend/src/types/quickAction.ts
  frontend/src/utils/index.ts
  frontend/src/utils/quickAction.ts
Labels: cla-signed

#10326 chore: update acl yaml
  backend/component/iam/acl.yaml
Labels: cla-signed

#10327 feat: support tidb index
  backend/plugin/schema/tidb/get_design_schema.go
  backend/plugin/schema/tidb/parse_to_metadata.go
  backend/plugin/schema/tidb/testdata/get_design_schema.yaml
Labels: cla-signed

#10328 fix: invalid role for new users
  backend/api/v1/auth_service.go
Labels: cla-signed

#10331 chore(iam): remove unused functions
  frontend/src/utils/role.ts
  frontend/src/utils/v1/project.ts
Labels: cla-signed

#10332 feat: search issues
  backend/api/v1/acl_config.go
  backend/api/v1/acl_iam.go
  backend/api/v1/issue_service.go
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#10333 chore: refactor component
  frontend/src/components/SchemaTemplate/FieldTemplateView.vue
  frontend/src/components/SchemaTemplate/TableTemplateView.vue
  frontend/src/components/SensitiveData/NoDataPlaceholder.vue
  frontend/src/components/misc/NoData.vue
  frontend/src/components/misc/NoDataPlaceholder.vue
  frontend/src/views/SettingWorkspaceSSO.vue
Labels: cla-signed

#10334 chore(i18n): update approval flow description
  frontend/src/locales/zh-CN.json
Labels: cla-signed, backport release/2.13.1

#10335 fix: iam gates
  backend/api/v1/database_service.go
  backend/api/v1/project_service.go
Labels: cla-signed
