Repository bytebase/bytebase, pull requests merged in 2024-11, with the labels that each got.

#14264 chore: move the database group feature to pro plan
  backend/enterprise/api/plan.yaml
  backend/legacyapi/plan.go
Labels: cla-signed

#14272 chore: change object owner check rule
  backend/plugin/advisor/builtin_rules.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
  backend/plugin/advisor/sql_review.go
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.dev.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed, backport release/3.0.0

#14275 cherrypick: change object owner check rule
  backend/plugin/advisor/builtin_rules.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
  backend/plugin/advisor/sql_review.go
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/locales/sql-review/en-US.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.dev.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14273 chore: optimize ui
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/Project/ProjectReleasesPanel.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/components/Release/ReleaseCreate/ReleaseCreate.vue
  frontend/src/components/RepositorySetupWizard.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SensitiveData/GrantAccessForm.vue
  frontend/src/components/VCS/VCSSetupWizard.vue
  frontend/src/layouts/SettingLayout.vue
  frontend/src/views/SettingWorkspaceMailDelivery.vue
  frontend/src/views/SettingWorkspaceSQLReview.vue
  frontend/src/views/SettingWorkspaceSQLReviewCreate.vue
  frontend/src/views/SettingWorkspaceVCS.vue
  frontend/src/views/SettingWorkspaceVCSCreate.vue
  frontend/src/views/project/ProjectDatabaseGroupCreate.vue
  frontend/src/views/project/ProjectDatabaseMaskingAccessCreate.vue
  frontend/src/views/project/ProjectWebhookCreate.vue
Labels: cla-signed

#14278 chore: environment allow ddl/dml
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/Release/ReleaseCreate/ReleaseCreate.vue
  frontend/src/views/SettingWorkspaceVCS.vue
Labels: cla-signed

#14279 feat: create release via github
  backend/api/gitops/common.go
  backend/api/gitops/github.go
  backend/api/gitops/gitops.go
  backend/api/gitops/webhook.go
  backend/plugin/vcs/github/github.go
  backend/plugin/vcs/vcs.go
  backend/server/grpc_routes.go
  backend/server/server.go
  backend/store/sheet.go
Labels: cla-signed

#14280 chore: use page instead of drawer for change history detail
  frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeHistoryDetailPanel/ChangeHistoryDetailPanel.vue
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/views/ChangeHistoryDetail.vue
Labels: cla-signed

#14281 chore: use page instead of drawer for revision detail
  frontend/src/components/Changelist/ChangelistDetail/ChangeHistoryDetailPanel/ChangeHistoryDetailPanel.vue
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/DatabaseDetail/ChangeHistoryDetail.vue
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/src/views/DatabaseDetail/RevisionDetail.vue
  frontend/src/views/DatabaseDetail/index.ts
  frontend/src/views/sql-editor/Setting/Database/Detail.vue
Labels: cla-signed

#14282 refactor: ui layout
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/components/SensitiveData/GrantAccessForm.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/VCS/VCSSetupWizard.vue
  frontend/src/components/v2/Form/FormLayout.vue
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/SettingWorkspaceMailDelivery.vue
  frontend/src/views/SettingWorkspaceMembers.vue
  frontend/src/views/SettingWorkspaceUsers.vue
  frontend/src/views/project/ProjectDatabaseGroupCreate.vue
  frontend/src/views/project/ProjectDatabaseGroupDetail.vue
  frontend/src/views/project/ProjectDatabaseMaskingAccessCreate.vue
  frontend/src/views/project/ProjectWebhookCreate.vue
  frontend/src/views/project/ProjectWebhookDetail.vue
Labels: cla-signed

#14293 feat: get change log format&concise
  backend/api/v1/database_service_changelog.go
Labels: cla-signed

#14296 chore: support upsert for patch review config
  backend/api/v1/review_config_service.go
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/components/SQLReviewForResource.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicyDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlReview.ts
  frontend/src/types/proto/v1/review_config_service.ts
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/review_config_service.pb.go
  proto/v1/review_config_service.proto
Labels: cla-signed

#14295 chore: remove database change mode applicable part
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14298 fix: not use useI18n in ts file
  frontend/src/components/VCS/utils.ts
  frontend/src/plugins/i18n.ts
  frontend/src/types/plan.ts
  frontend/src/types/semanticTypes.ts
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#14300 chore: 3.0.1
  scripts/VERSION
Labels: cla-signed

#14301 chore: revert "chore: bump @intlify/unplugin-vue-i18n from 4.0.0 to 5.2.0 in /frontend"
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#14299 chore(sql-editor): always show query result pagination
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14309 feat(query): respect data source query environment policy for MySQL
  backend/api/v1/sql_service.go
Labels: cla-signed

#14302 fix: fix the nil pointer error
  backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
  backend/store/model/database.go
Labels: cla-signed, backport release/3.0.0

#14306 chore: allow to cancel baseline task
  frontend/src/components/IssueV1/logic/action/task.ts
Labels: cla-signed

#14304 chore: update change history display
  frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
  frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/SyncDatabaseSchema/DatabaseSchemaSelector.vue
  frontend/src/utils/v1/changeHistory.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#14303 chore: mssql err expand recursively
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#14327 chore: always show grant request buttons
  frontend/src/layouts/ProjectV1Layout.vue
Labels: cla-signed

#14326 feat: changelog filter
  backend/api/v1/database_service.go
  backend/api/v1/database_service_changelog.go
  backend/runner/taskrun/executor.go
  backend/store/changelog.go
  backend/store/instance_change_history.go
  backend/store/instance_change_history_test.go
  frontend/src/types/proto/store/changelog.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/changelog.pb.go
  proto/store/changelog.proto
Labels: cla-signed

#14328 fix: export audit logs
  backend/api/v1/audit_log_service.go
  frontend/src/components/DataExportButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/auditLog.ts
  frontend/src/types/proto/v1/audit_log_service.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/audit_log_service.pb.go
  proto/v1/audit_log_service.proto
Labels: cla-signed

#14325 perf: optimize string concatenation in instance service
  backend/api/v1/instance_service.go
Labels: cla-signed

#14329 chore: disallow dml backfill
  backend/migrator/migration/prod/3.0/0001##disable_ddl_dml.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14331 chore: increase the size limit to 2M
  backend/common/util.go
  frontend/src/components/SQLCheck/SQLCheckButton.vue
Labels: cla-signed, backport release/3.0.0

#14333 chore: no default version & allow empty version
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/runner/taskrun/executor.go
  backend/store/release.go
Labels: cla-signed

#14324 chore(sql-editor): update isDatabaseV1Queryable logic
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/iam/permission.ts
  frontend/src/types/utils.ts
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#14337 chore: add role selector for postgres
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/context.ts
Labels: cla-signed

#14338 feat: implement query type for PG
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/query_type.go
  backend/plugin/parser/pg/test-data/query_span.yaml
Labels: cla-signed

#14339 feat(proto): create revision service
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14340 fix: mssql estimated rows float64
  backend/plugin/db/mssql/stats.go
Labels: cla-signed

#14341 chore: handle task schema version
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
Labels: cla-signed

#14336 chore: pricing v4
  backend/api/v1/auth_service.go
  backend/api/v1/environment_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/subscription_service.go
  backend/enterprise/api/license.go
  backend/enterprise/api/limit.go
  backend/enterprise/api/plan.yaml
  backend/enterprise/plugin/aws/aws.go
  backend/enterprise/service/license.go
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/subscription.ts
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/subscription_service.proto
Labels: cla-signed

#14342 chore: fix typo
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
Labels: cla-signed

#14344 feat: implement query type for oracle
  backend/api/v1/sql_service.go
  backend/plugin/parser/plsql/query_span_extractor.go
  backend/plugin/parser/plsql/query_type.go
  backend/plugin/parser/plsql/test-data/query_span.yaml
Labels: cla-signed

#14343 feat: impl create revision
  backend/api/v1/database_service_revision.go
  backend/api/v1/plan_service.go
  backend/api/v1/release_service.go
  backend/common/resource_name.go
Labels: cla-signed

#14345 chore: add `ListRollouts` endpoint definition and related permission
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14348 feat: TiDB Query Type
  backend/api/v1/sql_service.go
  backend/plugin/parser/tidb/query_span_extractor.go
  backend/plugin/parser/tidb/query_type.go
  backend/plugin/parser/tidb/test-data/query_span.yaml
Labels: cla-signed

#14347 chore: group owner check
  backend/api/v1/group_service.go
  frontend/src/components/Member/types.ts
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/SensitiveData/types.ts
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/components/User/Settings/UserDataTable/cells/GroupsCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberRoleSelect.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/index.vue
  frontend/src/components/v2/Select/GroupSelect.vue
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/v1/group.ts
  frontend/src/types/proto/v1/group_service.ts
  frontend/src/types/v1/group.ts
  frontend/src/views/SettingWorkspaceUsers.vue
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/group_service.pb.go
  proto/generated-go/v1/group_service.pb.gw.go
  proto/generated-go/v1/group_service_grpc.pb.go
  proto/v1/group_service.proto
Labels: cla-signed

#14349 fix: Revert "fix: redis get database with proxy"
  backend/plugin/db/redis/sync.go
Labels: cla-signed

#14350 chore: database count
  backend/plugin/db/redis/sync.go
Labels: cla-signed

#14351 chore: add creator, create_time and update_time to rollout
  backend/api/v1/rollout_service_converter.go
  backend/store/pipeline.go
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14354 chore(3.0.1): bump helm version
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#14353 feat: introduce explain analyze query type
  backend/plugin/parser/base/span.go
  backend/plugin/parser/mysql/query_type.go
  backend/plugin/parser/pg/query_type.go
  backend/plugin/parser/pg/test-data/query_span.yaml
  backend/plugin/parser/tidb/query_type.go
  backend/plugin/parser/tidb/test-data/query_span.yaml
Labels: cla-signed

#14355 chore: handle creator in rollout preview
  backend/api/v1/rollout_service_converter.go
Labels: cla-signed

#14356 chore: optimize select rules
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/components/SQLReview/components/SQLReviewRulesSelectPanel.vue
  frontend/src/components/SQLReview/components/SQLRuleFilter.vue
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
  frontend/src/components/SQLReview/components/SQLRuleTableWithFilter.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14358 chore(frontend): add placeholder for plan check run detail
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14359 fix: limit page size
  backend/api/v1/audit_log_service.go
  frontend/src/types/proto/v1/anomaly_service.ts
  frontend/src/types/proto/v1/audit_log_service.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/audit_log_service.pb.go
  proto/v1/anomaly_service.proto
  proto/v1/audit_log_service.proto
Labels: cla-signed, backport release/3.0.1

#14361 chore(sql-review-rule): disallow ddl/dml for specific tables
  backend/plugin/advisor/code.go
  backend/plugin/advisor/mysql/advisor_table_disallow_ddl.go
  backend/plugin/advisor/mysql/advisor_table_disallow_dml.go
  backend/plugin/advisor/sql_review.go
  frontend/src/types/sql-review-schema.yaml
  frontend/src/types/sql-review.prod.yaml
Labels: cla-signed

#14362 chore: batch query is available for pro plan
  backend/enterprise/api/plan.yaml
  backend/legacyapi/plan.go
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14363 fix: level=warning for large sql
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed, backport release/3.0.1

#14369 fix: advisor panic error
  backend/plugin/advisor/mysql/advisor_function_disallowed_list.go
  backend/plugin/parser/mysql/normalize.go
Labels: cla-signed

#14378 docs: update database permission link
  README.md
Labels: cla-signed

#14366 feat: impl batch create sheet
  backend/api/v1/sheet_service.go
  backend/component/sheet/sheet.go
  backend/store/sheet.go
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sheet_service.pb.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sheet_service_grpc.pb.go
  proto/v1/sheet_service.proto
Labels: cla-signed

#14380 chore: add issue to rollout
  backend/api/v1/rollout_service_converter.go
  backend/store/pipeline.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14381 fix: npe of getting rollout
  backend/api/v1/sql_service.go
  backend/store/rollout.go
Labels: cla-signed

#14383 chore: implement task data table for rollout detail page
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskExtraActionsButton.vue
  frontend/src/components/Project/ProjectRolloutsPanel.vue
  frontend/src/components/Rollout/RolloutDataTable.vue
  frontend/src/components/Rollout/RolloutDetail/BasicInfo.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Stages.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Tasks.vue
  frontend/src/components/Rollout/RolloutDetail/RolloutDetail.vue
  frontend/src/components/Rollout/RolloutDetail/RolloutDetailLayout.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDataTable/TaskDataTable.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDataTable/index.ts
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskDetail.vue
  frontend/src/components/Rollout/RolloutDetail/context.ts
  frontend/src/components/v2/Model/Instance/InstanceV1EngineIcon.vue
Labels: cla-signed

#14382 feat: simple sql server statement type
  backend/plugin/parser/tsql/query_span_extractor.go
  backend/plugin/parser/tsql/query_type.go
  backend/plugin/parser/tsql/test-data/query-span/case-sensitivity.yaml
  backend/plugin/parser/tsql/test-data/query-span/join.yaml
  backend/plugin/parser/tsql/test-data/query-span/standard.yaml
Labels: cla-signed

#14375 feat: added json logging flag
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
Labels: cla-signed

#14385 fix: database list value in sync schema
  frontend/src/components/SyncDatabaseSchema/index.vue
Labels: cla-signed

#14386 feat(query-type): treat SAFE set statement as select type
  backend/plugin/parser/base/span.go
  backend/plugin/parser/mysql/query_type.go
  backend/plugin/parser/mysql/test-data/query-span/query_type.yaml
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/query_span_test.go
  backend/plugin/parser/pg/query_type.go
  backend/plugin/parser/pg/test-data/query_span.yaml
  backend/plugin/parser/pg/test-data/query_type.yaml
  backend/plugin/parser/tidb/query_span_test.go
  backend/plugin/parser/tidb/query_type.go
  backend/plugin/parser/tidb/test-data/query_span.yaml
  backend/plugin/parser/tidb/test-data/query_type.yaml
  backend/plugin/parser/tsql/query_span_test.go
  backend/plugin/parser/tsql/query_type.go
  backend/plugin/parser/tsql/test-data/query-span/query_type.yaml
Labels: cla-signed

#14388 fix: button size
  frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
Labels: cla-signed

#14389 chore: filter audit log methods by audit option code
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/grpcweb/methods.ts
Labels: cla-signed

#14390 docs: update banner with DevSecOps
  docs/assets/banner.webp
Labels: cla-signed

#14392 feat(query-type): recognize sql server explain
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/interface_test.go
Labels: cla-signed

#14393 chore(sql-editor): use correct row index
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
Labels: cla-signed

#14384 chore: export data policy
  backend/api/v1/org_policy_service.go
  backend/api/v1/sql_service.go
  backend/legacyapi/policy.go
  backend/store/policy.go
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/GeneralSetting/MaximumRoleExpirationSetting.vue
  frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
  frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/GrantAccessForm.vue
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/slowQueryPolicy.ts
  frontend/src/store/modules/sqlReview.ts
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#14394 chore: add audit log to logout
  frontend/src/store/modules/auth.ts
  frontend/src/types/proto/v1/auth_service.ts
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#14395 chore: treat EXPLAIN ANALYZE as the inner statement type
  backend/plugin/parser/base/span.go
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/query_type.go
  backend/plugin/parser/mysql/test-data/query-span/query_type.yaml
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/query_type.go
  backend/plugin/parser/pg/test-data/query_type.yaml
  backend/plugin/parser/tidb/query_span_extractor.go
  backend/plugin/parser/tidb/query_span_test.go
  backend/plugin/parser/tidb/query_type.go
  backend/plugin/parser/tidb/test-data/query_type.yaml
Labels: cla-signed

#14396 chore: redirect to profile page
  frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
  frontend/src/components/Member/utils.ts
  frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#14397 chore: add user to login response
  backend/api/v1/audit.go
  backend/api/v1/auth_service.go
  frontend/src/components/AuditLog/JSONStringView.vue
  frontend/src/types/proto/v1/auth_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#14398 feat: set environment color
  backend/api/v1/environment_service.go
  backend/store/environment.go
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/store/modules/v1/environment.ts
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/environment_service.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/environment_service.pb.go
  proto/store/policy.proto
  proto/v1/environment_service.proto
Labels: cla-signed

#14400 fix: print ctx timeout duration
  backend/api/v1/sql_service.go
Labels: cla-signed

#14401 chore: tab color for sql editor
  backend/api/v1/environment_service.go
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
  frontend/src/views/sql-editor/TabList/TabItem/AdminLabel.vue
  frontend/src/views/sql-editor/TabList/TabItem/Label.vue
  frontend/src/views/sql-editor/TabList/TabItem/Prefix.vue
  frontend/src/views/sql-editor/TabList/TabItem/Suffix.vue
  frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
Labels: cla-signed

#14399 feat: use sheet_blob and remove sheet.database
  backend/api/v1/database_service_revision.go
  backend/api/v1/release_service.go
  backend/api/v1/rollout_service_task.go
  backend/api/v1/sheet_service.go
  backend/migrator/migration/prod/3.1/0000##sheet_blob.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/taskrun/executor.go
  backend/server/onboard.go
  backend/store/instance_change_history.go
  backend/store/sheet.go
  frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sheet_service.pb.go
  proto/v1/sheet_service.proto
Labels: cla-signed

#14403 fix(i18n): Fix japanese translations
  frontend/src/locales/ja-JP.json
Labels: cla-signed

#14404 feat(query-type): disallow running unknown statement type
  backend/api/v1/sql_service.go
Labels: cla-signed

#14405 fix: sheet blob
  backend/migrator/migration/prod/3.1/0000##sheet_blob.sql
  backend/migrator/migrator.go
Labels: cla-signed

#14406 feat: enable query type for sql server
  backend/api/v1/sql_service.go
Labels: cla-signed

#14407 chore: backfill postgres database tenant mode
  backend/migrator/migration/prod/3.1/0001##backfill_postgres_database_tenant_mode.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14408 fix: semi in use superuser privileges to execute statement for pg like
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#14409 chore: update task detail page
  frontend/src/components/Rollout/RolloutDetail/RolloutDetailLayout.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/BasicInfo.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/TaskRunLogs.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskDetail.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/utils.ts
  frontend/src/components/Rollout/RolloutDetail/context.ts
  frontend/src/components/Rollout/RolloutDetail/poll.ts
Labels: cla-signed

#14410 chore: fix instance engine icon styles
  frontend/src/components/Icon/EngineIcon.vue
  frontend/src/components/v2/Model/Instance/InstanceV1EngineIcon.vue
Labels: cla-signed

#14411 fix: handle unlimited seat
  backend/enterprise/service/license.go
  frontend/src/store/modules/v1/subscription.ts
Labels: cla-signed, backport release/3.0.1

#14412 feat(frontend): display package metadata for ORACLE
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/Icon/PackageIcon.vue
  frontend/src/components/Icon/index.ts
  frontend/src/components/PackageDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/instance.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PackageNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
  frontend/src/views/sql-editor/EditorPanel/GutterBar/TabItem.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/index.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
  frontend/src/views/sql-editor/EditorPanel/types.ts
Labels: cla-signed

#14414 refactor: retire sql service execute
  backend/api/v1/sql_service.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14415 chore: several fix
  backend/api/v1/auth_service.go
  backend/api/v1/group_service.go
  frontend/src/components/Quickstart.vue
Labels: cla-signed

#14418 chore: cel parse should not care about the expression order
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/IssueV1/components/GrantRequest/DatabaseResourceTable.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/components/SensitiveData/utils.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/types/member.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
Labels: cla-signed

#14416 feat: allow sql server declare variable
  backend/api/v1/sql_service.go
  backend/plugin/parser/tsql/query_span_extractor.go
  backend/plugin/parser/tsql/query_type.go
  backend/plugin/parser/tsql/test-data/query-span/query_type.yaml
  backend/plugin/parser/tsql/test-data/test_backup.yaml
  backend/plugin/parser/tsql/tsql.go
  go.mod
  go.sum
Labels: cla-signed

#14420 feat: expect no issue
  backend/api/v1/rollout_service.go
Labels: cla-signed

#14421 chore: implement Postgres database tenant mode
  backend/api/v1/sql_service.go
  backend/plugin/db/pg/pg.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/plancheck/statement_report_executor.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#14424 chore: fix engine icon styles
  frontend/src/components/Icon/EngineIcon.vue
  frontend/src/components/SyncDatabaseSchema/SelectTargetDatabasesView.vue
  frontend/src/components/v2/Model/Instance/InstanceV1EngineIcon.vue
  frontend/src/views/SchemaTemplate/FieldTemplates.vue
  frontend/src/views/SchemaTemplate/TableTemplates.vue
Labels: cla-signed

#14426 chore: bump version to `3.1.0`
  scripts/VERSION
Labels: cla-signed

#14425 chore(sql-editor): default NULL should be disabled when NOT NULL
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
Labels: cla-signed

#14427 chore: expect no issue 2
  backend/api/v1/database_service_revision.go
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#14428 chore(sql-editor): fix horizontal scrollbar visibility
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
Labels: cla-signed

#14430 chore: UI renovate
  frontend/public/help/routeMapList.json
  frontend/src/components/Changelist/ChangelistDashboard/NavBar.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskCenter.vue
  frontend/src/components/DataExportButton.vue
  frontend/src/components/Database/context.ts
  frontend/src/components/DeploymentConfigTool/DeploymentMatrix.vue
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/Project/ProjectIssuesPanel.vue
  frontend/src/components/Project/ProjectReleasesPanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/ProjectWebhookPanel.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/Quickstart.vue
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue
  frontend/src/components/SensitiveData/SemanticTypesView.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/customAppProfile.ts
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/shims-vue-router.d.ts
  frontend/src/types/appProfile.ts
  frontend/src/types/index.ts
  frontend/src/types/quickAction.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/MyIssues.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/SchemaTemplate/FieldTemplates.vue
  frontend/src/views/SchemaTemplate/TableTemplates.vue
  frontend/src/views/SettingWorkspaceMailDelivery.vue
  frontend/src/views/SettingWorkspaceSQLReview.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceVCS.vue
  frontend/src/views/project/ProjectDatabaseGroupDashboard.vue
  frontend/src/views/project/ProjectDatabaseMaskingAccess.vue
  frontend/src/views/project/ProjectVersionControlPanel.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  frontend/src/views/sql-editor/Setting/Project/Project.vue
Labels: cla-signed

#14431 chore: expect no issue 3
  backend/api/v1/rollout_service_converter.go
Labels: cla-signed

#14432 chore: last visit record and redirect
  frontend/src/DummyRootView.ts
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/views/project/ProjectDatabaseMaskingAccess.vue
Labels: cla-signed

#14433 chore: msg i18n
  backend/plugin/webhook/webhook.go
Labels: cla-signed, backport release/3.0.1

#14435 chore: fix link styles in task comment
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
Labels: cla-signed

#14436 chore: fix typo
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/types/appProfile.ts
Labels: cla-signed

#14437 feat: task run log prior backup
  backend/api/v1/rollout_service_converter.go
  backend/runner/taskrun/data_update_executor.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14438 fix: fix npe in disallow ddl
  backend/plugin/advisor/mysql/advisor_table_disallow_ddl.go
Labels: cla-signed

#14439 chore(sql-editor): more scrollbar fixes
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTableLite/DataTableLite.vue
Labels: cla-signed

#14440 chore: update transfer in action position
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/types/appProfile.ts
Labels: cla-signed

#14442 chore: set different default postgres role for sql review
  backend/api/v1/sql_service.go
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/pg/advisor_insert_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/pg/advisor_statement_object_owner_check.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils.go
  backend/plugin/advisor/utils_for_tests.go
  backend/runner/plancheck/statement_advise_executor.go
Labels: cla-signed

#14441 chore: remove unused
  backend/api/v1/audit.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14443 chore: show prior backup tables in task run log
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/DetailCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/ErrorCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/PriorBackupCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/common.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14444 feat(helm): add nodeAffinity
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#14445 chore: remove `StepSection` in plan detail page
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StepSection/StepCard.vue
  frontend/src/components/Plan/components/StepSection/StepSection.vue
  frontend/src/components/Plan/components/StepSection/index.ts
  frontend/src/components/Plan/components/index.ts
  frontend/src/components/Plan/logic/base.ts
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/utils.ts
Labels: cla-signed

#14447 chore: fix flatten spec list
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
Labels: cla-signed

#14446 chore: use popover instead of model to change current project
  frontend/src/components/Project/ProjectSwitchPopover.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/views/DashboardHeader.vue
Labels: cla-signed

#14449 fix: fix npe when convert priorBackupDetail
  backend/api/v1/rollout_service_converter.go
Labels: cla-signed

#14448 feat: implement MySQL backup, restore and prior backup rule v2
  backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/mysql/advisor_table_disallow_dml.go
  backend/plugin/parser/mysql/backup.go
  backend/plugin/parser/mysql/backup_test.go
  backend/plugin/parser/mysql/restore.go
  backend/plugin/parser/mysql/test-data/test_backup.yaml
  backend/plugin/parser/mysql/test-data/test_restore.yaml
Labels: cla-signed

#14452 chore: feature update
  backend/api/v1/idp_service.go
  backend/enterprise/api/plan.yaml
  backend/legacyapi/plan.go
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/subscription.ts
  frontend/src/utils/idp.ts
Labels: cla-signed

#14454 feat: implement 2M limit to backup
  backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#14451 feat: respect go command in sql server query
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mssql/stmt_type.go
  go.mod
Labels: cla-signed

#14455 chore: update postgres database tenant mode description
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14453 chore: migrate sql editor related permissions and roles
  README.md
  backend/api/v1/project_service.go
  backend/api/v1/project_service_test.go
  backend/api/v1/sql_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/legacyapi/member.go
  backend/migrator/migration/prod/3.1/0002##rename_project_querier.sql
  backend/migrator/migrator_test.go
  backend/runner/approval/runner.go
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/ExternalTableDetailDrawer.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
  frontend/src/components/IssueV1/components/GrantRequest/GrantRequestQuerierForm.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/Quickstart.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/v2/Select/ProjectRoleSelect.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/iam/permission.ts
  frontend/src/types/iam/role.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/utils/role.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx
  frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14456 chore: use `datetimerange` for `issue`/`audit log` advanced search
  frontend/src/components/AdvancedSearch/TimeRange.vue
Labels: cla-signed

#14457 chore: rename export permission
  backend/api/v1/sql_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/migrator/migration/prod/3.1/0002##rename_project_querier.sql
  frontend/src/types/iam/permission.ts
Labels: cla-signed

#14460 fix(mongo): decode uuid
  backend/plugin/db/mongodb/mongodb.go
Labels: backport release/3.0.0

#14479 feat: db group & base dir column for project vcs connectors page
  frontend/src/views/project/ProjectVersionControlPanel.vue
Labels: backport release/3.1.0

#14480 fix: ref value
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: backport release/3.1.0

#14485 fix: dbgroup selector
  frontend/src/components/v2/Select/DatabaseGroupSelect.vue
Labels: backport release/3.1.0

#14490 fix: page token
  backend/api/v1/audit_log_service.go
  backend/api/v1/common.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_changelog.go
  backend/api/v1/database_service_revision.go
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/release_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/sql_service.go
Labels: backport release/3.0.1, backport release/3.1.0

#14458 feat: MySQL DUMP from metadata
  backend/migrator/migrator.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/bigquery/dump.go
  backend/plugin/db/clickhouse/dump.go
  backend/plugin/db/cockroachdb/dump.go
  backend/plugin/db/databricks/dump.go
  backend/plugin/db/dm/dump.go
  backend/plugin/db/driver.go
  backend/plugin/db/dynamodb/dump.go
  backend/plugin/db/elasticsearch/dump.go
  backend/plugin/db/hive/dump.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mssql/dump.go
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/mysql/dump_test.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/dump.go
  backend/plugin/db/oracle/dump.go
  backend/plugin/db/pg/dump.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/dump.go
  backend/plugin/db/risingwave/dump.go
  backend/plugin/db/snowflake/dump.go
  backend/plugin/db/spanner/dump.go
  backend/plugin/db/sqlite/dump.go
  backend/plugin/db/starrocks/dump.go
  backend/plugin/db/tidb/dump.go
  backend/plugin/schema/mysql/stringify_table.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/utils/sdl_utils.go
  backend/tests/schema_update_test.go
  backend/tests/test-data/ghost_test_schema1.result
  backend/tests/test-data/ghost_test_schema2.result
Labels: cla-signed

#14531 feat: task rollout actions in task detail page
  frontend/src/components/Rollout/RolloutDetail/RolloutDetailLayout.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/BasicInfo.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/TaskRunLogs.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskDetail.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskStatusActions.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/context.ts
  frontend/src/components/Rollout/RolloutDetail/context.ts
  frontend/src/components/Rollout/RolloutDetail/poll.ts
  frontend/src/store/modules/v1/issue.ts
Labels: cla-signed

#14530 fix: disallow ddl/dml should in the paid plan
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
Labels: cla-signed

#14532 chore: always show on for allow ddl/dml in the free plan
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
Labels: cla-signed

#14527 feat: workspace landing page
  frontend/src/DummyRootView.ts
  frontend/src/assets/landing.webp
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchModal.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/IssueLayout.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/index.ts
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/router/useRecentVisit.ts
  frontend/src/store/modules/index.ts
  frontend/src/store/modules/quickLink.ts
  frontend/src/store/modules/v1/actuator.ts
  frontend/src/utils/index.ts
  frontend/src/utils/useDashboardSidebar.ts
  frontend/src/views/DashboardHeader.vue
  frontend/src/views/DashboardLanding.vue
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/SettingSidebar.vue
Labels: cla-signed

#14528 chore(frontend): support spanner "Default" schema
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/FunctionDataTable.vue
  frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
  frontend/src/components/PackageDataTable.vue
  frontend/src/components/SchemaDiagram/Navigator/TreeNode/Label.vue
  frontend/src/components/SchemaEditorLite/spec.ts
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/ViewDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/sqlEditor/editor.ts
  frontend/src/utils/v1/instance.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
  frontend/src/views/sql-editor/EditorCommon/SchemaChooser.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/common/SchemaSelectToolbar.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
Labels: cla-signed

#14533 chore: use selected task instead of active task in issue page
  frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueExtraActionButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/CombinedRolloutButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/RolloutActionButton.vue
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/OnlineMigrationAdviceExtra.vue
  frontend/src/components/IssueV1/components/Sidebar/useActiveTaskSheet.ts
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageSelect.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskExtraActionsButton.vue
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/context.ts
  frontend/src/components/IssueV1/logic/poll.ts
  frontend/src/utils/v1/issue/rollout.ts
Labels: cla-signed

#14534 chore: friendly err msg
  backend/api/v1/rollout_service.go
Labels: cla-signed

#14535 chore: record path when click the logo
  frontend/src/DummyRootView.ts
  frontend/src/components/BytebaseLogo.vue
Labels: cla-signed

#14537 chore(frontend): fix security vulnerability
  frontend/.pnpmfile.cjs
  frontend/pnpm-lock.yaml
Labels: cla-signed

#14540 chore: add database filter to apply database panel
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/ProjectDatabasesPanel.vue
Labels: cla-signed

#14541 chore: move disallow ddl/dml to free
  backend/api/v1/org_policy_service.go
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14539 chore(sql-editor): query permissions in free/pro plan
  backend/api/v1/sql_service.go
  frontend/src/utils/v1/database.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed, backport release/3.1.0

#14543 chore: redis commands on nodes
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#14542 feat: soft delete revisoin
  backend/api/v1/database_service_revision.go
  backend/api/v1/plan_service.go
  backend/migrator/migration/dev/202410140000002##release.sql
  backend/runner/taskrun/executor.go
  backend/store/revision.go
  frontend/src/types/proto/store/revision.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/revision.pb.go
  proto/generated-go/v1/actuator_service.pb.gw.go
  proto/generated-go/v1/anomaly_service.pb.gw.go
  proto/generated-go/v1/audit_log_service.pb.gw.go
  proto/generated-go/v1/auth_service.pb.gw.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/cel_service.pb.gw.go
  proto/generated-go/v1/changelist_service.pb.gw.go
  proto/generated-go/v1/database_group_service.pb.gw.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/environment_service.pb.gw.go
  proto/generated-go/v1/group_service.pb.gw.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/instance_role_service.pb.gw.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/issue_service.pb.gw.go
  proto/generated-go/v1/org_policy_service.pb.gw.go
  proto/generated-go/v1/plan_service.pb.gw.go
  proto/generated-go/v1/project_service.pb.gw.go
  proto/generated-go/v1/release_service.pb.gw.go
  proto/generated-go/v1/review_config_service.pb.gw.go
  proto/generated-go/v1/risk_service.pb.gw.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/setting_service.pb.gw.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/generated-go/v1/vcs_connector_service.pb.gw.go
  proto/generated-go/v1/vcs_provider_service.pb.gw.go
  proto/generated-go/v1/worksheet_service.pb.gw.go
  proto/generated-go/v1/workspace_service.pb.gw.go
  proto/store/revision.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14545 chore: add blocking task alter view
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue
Labels: cla-signed

#14546 chore: workspace id location
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/ReleaseRemindModal.vue
  frontend/src/components/WorkspaceInstanceLicenseStats.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#14547 fix: SqlService Query read only accordingly
  backend/api/v1/sql_service.go
Labels: cla-signed, backport release/3.1.0

#14550 chore(sql-editor): sql editor users should not see "Export Data" in sql editor in free/pro plan
  frontend/src/customAppProfile.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed, backport release/3.1.0

#14552 chore: update descriptions for the database change mode
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14555 chore(sql-editor): fix "request query" button in connection tree
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/OpenAIButton/Button.vue
Labels: cla-signed, backport release/3.1.0
