Repository bytebase/bytebase, pull requests merged in 2024-12, with the labels that each got.

#14572 chore(sql-editor): copy formatted value
  frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel/DetailPanel.vue
Labels: cla-signed

#14574 feat(spanner): spanner masking
  backend/api/v1/query_result_masker.go
  backend/plugin/parser/spanner/query_span.go
  backend/plugin/parser/spanner/query_span_extractor.go
  backend/plugin/parser/spanner/query_span_test.go
  backend/plugin/parser/spanner/spanner.go
  backend/plugin/parser/spanner/test-data/query-span/standard.yaml
Labels: cla-signed

#14575 chore: show sensitive column for spanner
  frontend/src/components/ColumnDataTable/index.vue
Labels: cla-signed

#14577 chore: bump version
  scripts/VERSION
Labels: cla-signed

#14581 chore: fix creating release drawer state
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/CreateReleaseFilesPanel.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/FileToCreateTable.vue
Labels: cla-signed

#14582 chore: update draggable icon
  frontend/src/views/DashboardLanding.vue
Labels: cla-signed

#14578 chore: set role for backup and restore
  backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
  backend/plugin/advisor/pg/test/column_comment.yaml
  backend/plugin/advisor/pg/test/table_comment.yaml
  backend/plugin/parser/pg/restore.go
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#14583 feat: support declare temp table
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/span.go
  backend/plugin/parser/tsql/query_span_extractor.go
  backend/plugin/parser/tsql/query_span_test.go
  backend/plugin/parser/tsql/test-data/query-span/standard.yaml
Labels: cla-signed

#14585 chore(frontend): upgrade vue-i18n and some other stuff
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/SchemaEditorLite/Aside/context-menu.ts
  frontend/src/components/SchemaEditorLite/context/tabs.ts
  frontend/src/plugins/i18n.ts
  frontend/src/shims-vue-globals.d.ts
  frontend/tsconfig.node.json
Labels: cla-signed

#14586 chore: update integration settings in dashboard sidebar
  frontend/src/utils/useDashboardSidebar.ts
Labels: cla-signed

#14587 fix: issue creator in test webhook
  backend/api/v1/project_service.go
Labels: cla-signed

#14584 chore(proto): check release definition
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/generated-go/v1/release_service.pb.gw.go
  proto/generated-go/v1/release_service_grpc.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14588 chore(frontend): fix grpc address
  frontend/src/grpcweb/index.ts
Labels: cla-signed, backport release/3.1.1

#14590 chore: fix plan checks placeholder display
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
Labels: cla-signed

#14591 feat: update changelog
  backend/api/v1/database_service_changelog.go
  backend/runner/taskrun/executor.go
  backend/store/changelog.go
  frontend/src/types/proto/store/changelog.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/changelog.pb.go
  proto/store/changelog.proto
Labels: cla-signed

#14595 chore: optimize databases
  frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
  frontend/src/store/modules/v1/database.ts
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#14596 fix: expiration timestamp
  frontend/src/components/ExpirationSelector.vue
Labels: cla-signed, backport release/3.1.1

#14594 feat: implement check release
  backend/api/gitops/webhook.go
  backend/api/v1/release_service.go
  backend/api/v1/sql_service.go
  backend/server/grpc_routes.go
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14599 fix: spanner open db
  backend/plugin/db/spanner/spanner.go
Labels: cla-signed

#14600 feat: listRoles rather than instanceResource
  backend/api/v1/instance_role_service.go
  backend/api/v1/instance_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
  frontend/src/grpcweb/index.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_role_service.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/instance_role_service.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#14592 feat: split by antlr
  backend/plugin/parser/tsql/restore.go
  backend/plugin/parser/tsql/split.go
  backend/plugin/parser/tsql/split_test.go
Labels: cla-signed

#14603 fix: mssql sync
  backend/plugin/db/mssql/sync.go
Labels: cla-signed, backport release/3.0.0, backport release/3.0.1, backport release/3.1.0, backport release/3.1.1

#14602 feat: sync sequence owner for pg
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14610 fix: init schema, use db owner
  backend/runner/taskrun/database_create_executor.go
Labels: cla-signed

#14613 fix: migrate context
  backend/runner/taskrun/database_create_executor.go
Labels: cla-signed

#14612 chore: api update
  backend/api/v1/project_service.go
  backend/api/v1/role_service.go
  backend/api/v1/vcs_connector_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/store/vcs_connector.go
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto/v1/role_service.ts
  frontend/src/views/project/ProjectVersionControlCreate.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/role_service.pb.go
  proto/generated-go/v1/role_service.pb.gw.go
  proto/generated-go/v1/role_service_grpc.pb.go
  proto/v1/role_service.proto
Labels: cla-signed

#14614 chore: update pg tenant mode backfill
  backend/migrator/migration/prod/3.1/0001##backfill_postgres_database_tenant_mode.sql
Labels: backport release/3.1.0, backport release/3.1.1

#14617 fix: allow never expire
  backend/api/v1/project_service.go
  frontend/src/components/ExpirationSelector.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
Labels: cla-signed, backport release/3.1.1

#14619 chore: upgrade plsql-parser
  go.mod
  go.sum
Labels: cla-signed

#14621 chore: remove part of db group in plan detail page
  frontend/src/components/Plan/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/logic/plan.ts
Labels: cla-signed

#14622 chore: get openid configuration in backend
  backend/api/v1/idp_service.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/oidc/oidc_test.go
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/utils/sso.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/idp_service.pb.go
  proto/v1/idp_service.proto
Labels: cla-signed

#14623 fix: use new driver to sync schema
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/utils/sdl_utils.go
Labels: cla-signed, backport release/3.1.1

#14624 cherrypick: use new driver to sync schema (cp #14623)
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/utils/sdl_utils.go
Labels: cla-signed

#14625 fix: send approval notif on re-requesting review
  backend/api/v1/issue_service.go
Labels: cla-signed

#14626 chore: remove dev sql
  backend/migrator/migration/dev/202410140000002##release.sql
Labels: backport release/3.1.1

#14628 fix: revoke role
  frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/Member/MemberDataTableByRole.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/views/SettingWorkspaceMembers.vue
Labels: cla-signed, backport release/3.1.1

#14630 feat: snowflake statement type
  backend/api/v1/sql_service.go
  backend/plugin/parser/snowflake/query_span_extractor.go
  backend/plugin/parser/snowflake/query_type.go
  backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
  backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
  backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
  backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
  backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
  go.mod
  go.sum
Labels: cla-signed

#14632 chore(snowflake): try set the default schema to public
  backend/plugin/db/snowflake/snowflake.go
Labels: cla-signed

#14633 feat: snowflake multiple statement
  backend/plugin/db/snowflake/snowflake.go
Labels: cla-signed

#14634 chore: check issue status in task detail page
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskStatusActions.vue
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14635 chore: disallow to delete readonly scopes in advanced search
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
Labels: cla-signed

#14636 chore: sync pg partition key
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14637 chore: tweak button icons in dashboard header
  frontend/src/views/DashboardHeader.vue
Labels: cla-signed

#14638 feat: webhook and im integration for Lark
  backend/api/v1/project_service.go
  backend/api/v1/setting_service.go
  backend/plugin/webhook/lark/app.go
  backend/plugin/webhook/lark/lark.go
  frontend/src/components/Project/WebhookTypeIcon.vue
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/views/SettingWorkspaceIM.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/project_service.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#14641 chore: advanced search for rollout tasks
  frontend/src/components/AdvancedSearch/ScopeMenu.vue
  frontend/src/components/AdvancedSearch/types.ts
  frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
  frontend/src/components/Rollout/RolloutDetail/Panels/TaskAdvancedSearch/TaskAdvancedSearch.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/TaskAdvancedSearch/index.ts
  frontend/src/components/Rollout/RolloutDetail/Panels/Tasks.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/advanced-search/common.ts
Labels: cla-signed

#14639 refactor(sql-editor): split tab large fields to IndexedDB
  frontend/src/store/modules/sqlEditor/extendedTab.ts
  frontend/src/store/modules/sqlEditor/tab.ts
Labels: cla-signed

#14642 chore: implement kv storage store to pass initial statements for creating issues
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/SlowQuery/Panel/IndexAdvisor.vue
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/store/modules/v1/index.ts
  frontend/src/store/modules/v1/storage.ts
  frontend/src/views/sql-editor/EditorCommon/ExecuteHint.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14643 chore: update `storage.get` types
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/SyncDatabaseSchema/index.vue
  frontend/src/store/modules/v1/storage.ts
Labels: cla-signed

#14644 chore: update vue globals definition
  frontend/src/main.ts
  frontend/src/shims-vue-globals.d.ts
  frontend/src/utils/util.ts
Labels: cla-signed

#14645 fix: mysql sync partition order by position
  backend/plugin/db/mysql/sync.go
Labels: cla-signed, backport release/3.1.1

#14647 chore(frontend): improve type definitions
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/main.ts
  frontend/src/shims-vue-globals.d.ts
Labels: cla-signed

#14648 fix: getSchemaFromPeerTenantDatabase should sync similardb schema
  backend/runner/taskrun/database_create_executor.go
Labels: cla-signed

#14650 chore: fix plan check run status count
  backend/store/plan.go
Labels: cla-signed

#14651 feat: migrate deployment config store to proto
  backend/api/v1/plan_service_plan_check.go
  backend/api/v1/project_service.go
  backend/api/v1/project_service_test.go
  backend/api/v1/rollout_service.go
  backend/migrator/migration/prod/3.1/0003##deployment_config_use_proto.sql
  backend/migrator/migrator_test.go
  backend/runner/taskrun/database_create_executor.go
  backend/store/deploy.go
  backend/utils/utils.go
  backend/utils/utils_test.go
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/types/proto/store/deployment_config.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/deployment_config.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/deployment_config.proto
  proto/v1/project_service.proto
Labels: cla-signed

#14654 fix: fix mysql dump index key part
  backend/plugin/schema/mysql/stringify_table.go
Labels: cla-signed, backport release/3.1.1

#14657 fix: add database name for backup table
  backend/plugin/parser/mysql/backup.go
  backend/plugin/parser/mysql/test-data/test_backup.yaml
  backend/plugin/parser/plsql/backup.go
  backend/plugin/parser/plsql/test-data/test_backup.yaml
  backend/plugin/parser/tidb/backup.go
  backend/plugin/parser/tidb/test-data/test_backup.yaml
  backend/plugin/parser/tsql/backup.go
  backend/plugin/parser/tsql/test-data/test_backup.yaml
Labels: cla-signed

#14652 chore(sql-editor): hover tooltips improvements
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/CodeViewer.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ColumnInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/CommonText.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/FunctionInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/InfoItem.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ProcedureInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TableInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ViewInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/hover-state.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ColumnNode.vue
  frontend/src/views/sql-editor/EditorCommon/hover-state.ts
Labels: cla-signed

#14658 chore: introduce partition indexes
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14659 feat: sync partition table indexes
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14660 chore: bump plsql-parser version
  backend/plugin/parser/plsql/split_test.go
  go.mod
  go.sum
Labels: cla-signed

#14661 chore: 3.1.2
  scripts/VERSION
Labels: cla-signed

#14662 fix: test
  backend/plugin/parser/plsql/split_test.go
Labels: cla-signed

#14656 chore: move masking data to database config
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/query_result_masker.go
  backend/runner/schemasync/syncer.go
  backend/server/init.go
  backend/server/onboard.go
  backend/server/server.go
  backend/store/model/database.go
  backend/store/policy.go
  backend/tests/sensitive_data_test.go
  backend/utils/database_config_merge.go
  frontend/src/components/ColumnDataTable/LabelsCell.vue
  frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/SensitiveData/index.ts
  frontend/src/components/SensitiveData/types.ts
  frontend/src/components/SensitiveData/useColumnMasking.ts
  frontend/src/components/SensitiveData/utils.ts
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/src/views/SettingWorkspaceDataMasking.vue
  frontend/src/views/sql-editor/EditorCommon/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/SensitiveDataIcon.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#14663 chore: add before unload handler
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
Labels: cla-signed

#14665 chore: reorder
  frontend/src/views/SettingWorkspaceIM.vue
Labels: cla-signed

#14666 feat: plan deployment snapshot
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/runner/approval/runner.go
  frontend/src/types/proto/store/plan.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/plan.pb.go
  proto/store/plan.proto
Labels: cla-signed

#14667 refactor: db config
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
Labels: cla-signed

#14669 chore: popup login modal if token expired
  frontend/src/AuthContext.vue
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/main.ts
  frontend/src/store/modules/auth.ts
  frontend/src/views/Setup/ProvideSetupContext.vue
  frontend/src/views/auth/Signin.vue
  frontend/src/views/auth/SigninModal.vue
Labels: cla-signed

#14671 refactor: database config converter
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/setting_service.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#14668 feat(mysql): fallback to full mask if the field come from expr
  backend/api/v1/query_result_masker.go
  backend/plugin/parser/base/span.go
  backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
  backend/plugin/parser/mysql/test-data/query-span/standard.yaml
  backend/plugin/parser/mysql/test-data/query-span/starrocks.yaml
  backend/plugin/parser/pg/test-data/query_span.yaml
  backend/plugin/parser/plsql/test-data/query_span.yaml
  backend/plugin/parser/snowflake/test-data/query-span/cte.yaml
  backend/plugin/parser/snowflake/test-data/query-span/pivot.yaml
  backend/plugin/parser/snowflake/test-data/query-span/set-operator.yaml
  backend/plugin/parser/snowflake/test-data/query-span/standard.yaml
  backend/plugin/parser/snowflake/test-data/query-span/subquery.yaml
  backend/plugin/parser/spanner/test-data/query-span/standard.yaml
  backend/plugin/parser/tidb/test-data/query_span.yaml
  backend/plugin/parser/tsql/test-data/query-span/case-sensitivity.yaml
  backend/plugin/parser/tsql/test-data/query-span/join.yaml
  backend/plugin/parser/tsql/test-data/query-span/standard.yaml
Labels: cla-signed

#14672 chore: alert before leave the issue page
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
Labels: cla-signed

#14673 chore: bump plsql-parser version
  go.mod
  go.sum
Labels: cla-signed

#14674 feat: introduce index parent
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14675 fix: upload icon
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue
Labels: cla-signed

#14676 chore: wrap branch message
  backend/api/v1/branch_service.go
  frontend/src/types/proto/store/branch.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/branch.pb.go
  proto/store/branch.proto
Labels: cla-signed

#14677 feat: sync pg index inheritance
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14678 feat(proto): config sync databases in the instance options
  frontend/src/types/proto/store/instance.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/instance.pb.go
  proto/store/instance.proto
Labels: cla-signed

#14680 feat: v1 api return deployment config snapshot
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/store/deploy.go
  backend/store/plan.go
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/store/plan.proto
  proto/v1/plan_service.proto
Labels: cla-signed

#14683 fix: redshift query
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#14682 feat: log the number of rows returned by the query in the audit log
  backend/api/v1/audit.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#14679 chore: Revert "chore: wrap branch message"
  backend/api/v1/branch_service.go
  frontend/src/types/proto/store/branch.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/branch.pb.go
  proto/store/branch.proto
Labels: cla-signed

#14681 feat(span): skip temporary table schema
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mssql/stmt_type.go
  backend/plugin/parser/tsql/query_span_extractor.go
Labels: cla-signed

#14685 feat(proto): stage_id in CreateRolloutRequest
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/rollout_service.pb.gw.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14684 fix: i18n
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14688 chore(sql-editor): ensure default datasource selection according to policy in SQL Editor
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/utils/sqlEditor.ts
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#14687 feat: query response include rowsCount
  backend/api/v1/audit.go
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/clickhouse/query.go
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/databricks/databricks.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/dynamodb/dynamodb.go
  backend/plugin/db/elasticsearch/elasticsearch.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/util/driverutil.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
Labels: cla-signed

#14653 feat: add model name setting when calling openai api instead of hardcode
  backend/api/v1/database_service.go
  backend/api/v1/setting_service.go
  backend/legacyapi/setting.go
  backend/server/init.go
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/ChatPanel.vue
  frontend/src/plugins/ai/components/ProvideAIContext.vue
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/plugins/ai/types/context.ts
  frontend/src/types/common.ts
  frontend/src/types/setting.ts
Labels: cla-signed

#14692 fix: default datasource
  backend/api/v1/sql_service.go
Labels: cla-signed

#14691 fix: hide policy in environment creation
  frontend/src/components/EnvironmentForm/Form.vue
Labels: backport release/3.1.2

#14693 chore: sync selected databases
  backend/api/v1/instance_service.go
  backend/runner/schemasync/syncer.go
  frontend/src/types/proto/store/instance.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/instance.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/store/instance.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#14694 chore: object schema proto
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#14698 chore: bump helm to 3.1.2
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#14697 chore: clarify pg tenant mode to stress database OWNER
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14700 chore(sql-editor): fail when no queriable data source
  frontend/src/composables/useExecuteSQL.ts
Labels: cla-signed

#14699 fix: sheet from task run
  backend/api/v1/rollout_service_converter.go
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14701 fix(clickhouse): sync column's default value
  backend/plugin/db/clickhouse/sync.go
Labels: cla-signed

#14712 feat(sync): ignore extension objects
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14713 feat(sql-editor): execute query in new tab
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
Labels: cla-signed

#14728 feat(clickhouse): sync primary keys and indexes
  backend/api/v1/database_converter.go
  backend/plugin/db/clickhouse/sync.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14729 chore(sql-editor): clicking query history improvements
  frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue
Labels: cla-signed

#14730 chore(sql-editor): sticky Add tab button
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#14731 feat: introduce enum type proto
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14732 fix: archived data
  frontend/src/components/SSO/IdentityProviderTable.vue
  frontend/src/store/modules/idp.ts
  frontend/src/views/Archive.vue
Labels: cla-signed, backport release/3.1.2

#14733 fix: z-index of issue list popover
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
Labels: cla-signed

#14737 fix: npe
  backend/runner/schemasync/syncer.go
Labels: cla-signed, backport release/3.1.2

#14738 feat: impl createRollout stage_id
  backend/api/v1/rollout_service.go
  backend/migrator/migration/prod/3.2/0000##stage_deployment_id.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/pipeline.go
  backend/store/stage.go
  backend/store/task.go
  backend/store/task_dag.go
Labels: cla-signed

#14741 feat: support mssql connection database
  backend/plugin/db/mssql/sync.go
  frontend/src/components/InstanceForm/specs.ts
Labels: cla-signed

#14740 feat: sync pg enum
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14743 feat: allow sync specific databases
  backend/api/v1/instance_service.go
  backend/legacyapi/plan.go
  backend/runner/schemasync/syncer.go
  backend/server/onboard.go
  frontend/src/components/InstanceForm/Buttons.vue
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/components/InstanceForm/MaximumConnectionsInput.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/components/InstanceForm/SyncDatabases.vue
  frontend/src/components/v2/Form/SearchBox.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/databaseList.ts
  frontend/src/store/modules/v1/instance.ts
  frontend/src/types/plan.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#14744 chore: database catalog API
  frontend/src/types/proto/v1/database_catalog_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/generated-go/v1/database_catalog_service.pb.gw.go
  proto/generated-go/v1/database_catalog_service_grpc.pb.go
  proto/v1/database_catalog_service.proto
Labels: cla-signed

#14745 chore(clickhouse): sync sorting key of table
  backend/api/v1/database_converter.go
  backend/plugin/db/clickhouse/sync.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14747 chore(clickhouse): metadata to string
  backend/api/v1/sql_service.go
  backend/plugin/schema/clickhouse/get_design_schema.go
  backend/plugin/schema/clickhouse/state.go
  backend/server/ultimate.go
Labels: cla-signed

#14746 chore: database catalog boilerplate
  backend/api/v1/database_catalog_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/server/grpc_routes.go
Labels: cla-signed

#14748 chore: update trigger proto
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14751 chore: golangci-lint version
  .github/workflows/backend-tests.yml
  backend/api/v1/branch_service.go
  backend/plugin/parser/mysql/differ.go
  backend/plugin/parser/tidb/differ.go
  backend/plugin/schema/clickhouse/state.go
Labels: cla-signed

#14752 chore: highlight the matched keyword
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SyncDatabaseSchema/TargetDatabasesSelectPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Name.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Model/DatabaseV1Table/cells/DatabaseNameCell.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/components/v2/Model/ProjectV1Name.vue
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#14754 chore: polyfill `String.prototype.replaceAll`
  frontend/src/main.ts
  frontend/src/polyfill.ts
Labels: cla-signed

#14749 feat: move filter stages outside store
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/store/pipeline.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14758 feat: CreateRollout ValidateOnly
  backend/api/v1/rollout_service.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14759 chore: database catalog message
  frontend/src/types/proto/v1/database_catalog_service.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_catalog_service.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14757 chore: move triggers into the table metadata
  backend/api/v1/database_converter.go
  backend/plugin/db/mysql/dump.go
  backend/plugin/db/mysql/sync.go
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/TriggerDataTable.vue
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
  frontend/src/views/sql-editor/EditorPanel/GutterBar/TabItem.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TableDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TriggersTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TriggersPanel/TriggersPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TriggersPanel/index.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/common/CodeViewer.vue
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
  frontend/src/views/sql-editor/EditorPanel/types.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14760 chore: get database catalog
  backend/api/v1/database_catalog_service.go
  backend/common/resource_name.go
Labels: cla-signed

#14753 fix(oracle): add limit for select statement only
  backend/plugin/db/oracle/query.go
Labels: cla-signed

#14761 fix: repeated environment name
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
Labels: cla-signed

#14762 feat(sql-editor): select and copy data by row/column
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/ColumnHeader.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
Labels: cla-signed

#14763 chore: update catalog
  backend/api/v1/database_catalog_service.go
Labels: cla-signed

#14765 chore: object schema in store
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_catalog_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/store/database.proto
  proto/v1/database_catalog_service.proto
Labels: cla-signed

#14766 chore: remove workspace-level role checks
  frontend/src/DummyRootView.ts
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/Quickstart.vue
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
  frontend/src/store/modules/user.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#14767 chore: populate object schema
  backend/api/v1/database_catalog_service.go
Labels: cla-signed

#14768 chore: catalog audit log
  backend/api/v1/audit.go
Labels: cla-signed

#14769 chore: migrate test for database catalog
  backend/tests/sensitive_data_test.go
  backend/tests/tests.go
Labels: cla-signed

#14770 chore: use vite legacy plugin
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/main.ts
  frontend/src/polyfill.ts
  frontend/vite.config.ts
Labels: cla-signed

#14771 chore: catalog store
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/v1/databaseCatalog.ts
  frontend/src/store/modules/v1/index.ts
Labels: cla-signed

#14772 chore: update changelog & revision
  backend/api/v1/database_service_revision.go
  backend/store/changelog.go
Labels: cla-signed

#14773 chore(sql-editor): implement multi-selection in data table
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/ColumnHeader.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
Labels: cla-signed

#14774 chore: update catalog
  frontend/src/components/ColumnDataTable/LabelsCell.vue
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/store/modules/v1/databaseCatalog.ts
Labels: cla-signed

#14775 chore(restore): check pg pk only for update
  backend/plugin/parser/pg/restore.go
Labels: cla-signed, backport release/3.1.2

#14776 chore: table catalog
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/store/modules/v1/databaseCatalog.ts
  frontend/src/store/modules/v1/dbSchema.ts
Labels: cla-signed

#14778 chore: column catalog
  frontend/src/components/ColumnDataTable/LabelsCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/SensitiveData/useColumnMasking.ts
  frontend/src/components/SensitiveData/useSemanticType.ts
  frontend/src/store/modules/v1/dbSchema.ts
Labels: cla-signed

#14779 feat: executor optional dump
  backend/api/v1/database_service_revision.go
  backend/runner/taskrun/executor.go
  backend/store/revision.go
  backend/store/sync_history.go
Labels: cla-signed

#14780 chore: remove fallback
  frontend/src/components/ColumnDataTable/utils.ts
Labels: cla-signed

#14782 chore: field template config
  backend/api/v1/database_catalog_service.go
  backend/api/v1/setting_service.go
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/views/SchemaTemplate/FieldTemplates.vue
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/setting_service.pb.go
  proto/v1/setting_service.proto
Labels: cla-signed

#14785 feat: sync pg triggers @rebelice
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14784 chore: catalog store rename
  backend/api/v1/branch_merge.go
  backend/api/v1/branch_merge_test.go
  backend/api/v1/branch_service.go
  backend/api/v1/branch_service_test.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/query_result_masker.go
  backend/api/v1/setting_service.go
  backend/runner/schemasync/syncer.go
  backend/store/model/database.go
  backend/utils/database_config_merge.go
  backend/utils/database_config_merge_test.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/store/setting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/store/setting.pb.go
  proto/store/database.proto
  proto/store/setting.proto
Labels: cla-signed

#14786 chore: less db catalog
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
Labels: cla-signed

#14787 feat: add table: revision, changelog, sync_history
  backend/migrator/migration/prod/3.2/0001##changelog.sql
  backend/migrator/migration/prod/3.2/0002##backfill_changelog.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14789 chore: add more comments for proto
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14788 chore: more catalog
  backend/api/v1/database_catalog_service.go
  backend/api/v1/setting_service.go
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/components/SchemaTemplate/TableTemplateTable.vue
  frontend/src/components/SchemaTemplate/utils.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/views/SchemaTemplate/TableTemplates.vue
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/setting_service.pb.go
  proto/v1/setting_service.proto
Labels: cla-signed

#14790 feat: sync pg comments
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14791 chore: catalog data DML
  backend/migrator/migration/prod/3.2/0003##catalog.sql
  backend/migrator/migrator_test.go
Labels: cla-signed
