Repository bytebase/bytebase, pull requests merged in 2024-08, with the labels that each got.

#13070 chore: explain 10 times
  backend/common/util.go
  backend/plugin/advisor/mysql/advisor_insert_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
  backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/mysql/advisor_statement_query_minumum_plan_level.go
  backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go
  backend/runner/plancheck/statement_report_executor.go
  backend/runner/plancheck/statement_report_executor_affected_rows.go
Labels: cla-signed

#13074 feat(audit): audit logs for SQLService Execute and Export
  backend/api/v1/audit.go
  frontend/src/types/proto/v1/sql_service.ts
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#13081 chore: remove duplicated useInstanceStore
  frontend/src/components/AnomalyCenter/AnomalyTable.vue
  frontend/src/components/SensitiveData/SensitiveColumnView.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
  frontend/src/components/SlowQuery/Settings/components/SlowQueryPolicyTable.vue
  frontend/src/components/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/layouts/InstanceLayout.vue
  frontend/src/router/dashboard/workspaceSetting.ts
  frontend/src/types/slowQuery.ts
  frontend/src/views/Archive.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#13082 chore: add permission checks for issue subscribe section
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscriberList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/Subscribers.vue
  frontend/src/components/IssueV1/logic/subscriber.ts
Labels: cla-signed

#13078 fix: wrong sql review table component
  frontend/src/views/SettingWorkspaceSQLReview.vue
Labels: cla-signed

#13083 feat: handle use system ca for mongodb
  backend/plugin/db/mongodb/mongodb.go
Labels: cla-signed

#13086 chore: tweak i18n
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13087 chore: skip fetch resource if no permission
  frontend/src/components/SQLReview/components/SQLReviewAttachedResource.vue
  frontend/src/components/SQLReview/components/useReviewConfigAttachedResource.ts
Labels: cla-signed

#13088 feat: support mongodb mutual tls
  backend/plugin/db/mongodb/mongodb.go
  frontend/src/components/InstanceForm/DataSourceSection/SslCertificateFormV1.vue
Labels: cla-signed

#13090 chore: issue comment subscriber
  backend/api/v1/issue_service.go
Labels: cla-signed

#13091 chore: use user context
  backend/api/v1/auth_service.go
Labels: cla-signed

#13092 feat(audit): logs for database service
  backend/api/v1/audit.go
  frontend/src/types/proto/v1/database_service.ts
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#13093 chore: add cel tests for db group labels
  backend/runner/taskrun/database_create_executor.go
  backend/utils/utils.go
  backend/utils/utils_test.go
Labels: cla-signed

#13106 feat(api): request metadata for audit logs
  frontend/src/types/proto/store/audit_log.ts
  frontend/src/types/proto/v1/audit_log_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/audit_log.pb.go
  proto/generated-go/v1/audit_log_service.pb.go
  proto/store/audit_log.proto
  proto/v1/audit_log_service.proto
Labels: cla-signed

#13107 chore: explain burnout
  backend/plugin/advisor/oracle/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/pg/advisor_insert_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/tidb/advisor_statement_dml_dry_run.go
Labels: cla-signed

#13108 chore: order by resource id
  backend/store/database.go
  backend/store/instance.go
  backend/store/project.go
Labels: cla-signed

#13109 chore: unify plan id
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/common/resource_name.go
Labels: cla-signed

#13110 chore: deprecate query util
  backend/plugin/db/dm/dm.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#13111 chore: snowflake MULTI_STATEMENT_COUNT 0
  backend/plugin/db/snowflake/snowflake.go
Labels: cla-signed, backport release/2.22.0

#13114 chore: add missing mock for gitops
  backend/tests/fake/azure.go
  backend/tests/fake/bitbucket.go
  backend/tests/fake/github.go
  backend/tests/fake/gitlab.go
Labels: cla-signed

#13073 chore(sql-editor): hide projects and environments when workspaceMode=EDITOR
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/MaximumConnectionsInput.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/components/InstanceForm/context.ts
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/ProfilePreview.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/customAppProfile.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/store/modules/v1/actuator.ts
  frontend/src/types/appProfile.ts
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/GroupingBar.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/SearchBox/index.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPanel.vue
  frontend/src/views/sql-editor/EditorCommon/ConnectionPathBar.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  frontend/src/views/sql-editor/Setting/Sidebar/Sidebar.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#13113 chore: more utils
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#13115 feat: no dump/sync for dml
  backend/plugin/db/driver.go
  backend/runner/taskrun/data_update_executor.go
  backend/tests/schema_update_test.go
  backend/utils/utils.go
Labels: cla-signed

#13117 chore: introduce all query
  backend/api/v1/sql_service.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/query.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/partiql/query.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/pg/query_test.go
  backend/plugin/parser/plsql/query.go
  backend/plugin/parser/redis/query.go
  backend/plugin/parser/redis/query_test.go
  backend/plugin/parser/standard/query.go
  backend/plugin/parser/standard/query_test.go
  backend/plugin/parser/tidb/query.go
  backend/plugin/parser/tsql/query.go
Labels: cla-signed

#13118 feat: selectively execute sequentially
  backend/legacyapi/task.go
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#13120 chore: remove execute detail flag
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#13122 chore: one mssql query
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#13125 chore: hide branch related views
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/ProjectSettingPanel.vue
Labels: cla-signed

#13124 chore: remove development audit flag
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
  backend/store/audit_log.go
Labels: cla-signed

#13126 chore: remove preUpdateBackup flag
  backend/api/v1/actuator_service.go
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
Labels: cla-signed

#13123 chore: mysql run statement
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/tests/sql_review_test.go
Labels: cla-signed

#13127 chore: tidb sr unified query
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#13128 chore: pg one query
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/tests/sql_editor_test.go
Labels: cla-signed

#13129 chore: remove unnecessary blocking session icon
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/PostgresSessionTable.vue
Labels: cla-signed

#13130 chore: cleanup unused type and utils
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/DataSourceSelect.vue
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/DatabaseName.vue
  frontend/src/components/ExternalTableDetailDrawer.vue
  frontend/src/components/FunctionDataTable.vue
  frontend/src/components/InstanceEngineIcon.vue
  frontend/src/components/InstanceUserTable.vue
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/TableSchemaViewer.vue
  frontend/src/components/ViewDataTable.vue
  frontend/src/main.ts
  frontend/src/shims-vue-globals.d.ts
  frontend/src/store/modules/user.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/vcs_provider.ts
  frontend/src/types/InstanceUser.ts
  frontend/src/types/common.ts
  frontend/src/types/dataSource.ts
  frontend/src/types/database.ts
  frontend/src/types/environment.ts
  frontend/src/types/id.ts
  frontend/src/types/index.ts
  frontend/src/types/instance.ts
  frontend/src/types/member.ts
  frontend/src/types/mfa.ts
  frontend/src/types/onboardingGuide.ts
  frontend/src/types/principal.ts
  frontend/src/types/project.ts
  frontend/src/types/repository.ts
  frontend/src/types/sql.ts
  frontend/src/types/sqlEditor/editor.ts
  frontend/src/types/v1/instance.ts
  frontend/src/types/v1/project.ts
  frontend/src/utils/common.ts
  frontend/src/utils/database.ts
  frontend/src/utils/environment.ts
  frontend/src/utils/id.ts
  frontend/src/utils/index.ts
  frontend/src/utils/instance.ts
  frontend/src/utils/project.ts
  frontend/src/utils/slowQuery.ts
  frontend/src/utils/v1/instance.ts
  frontend/src/views/auth/Activate.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/CodeViewer.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ExternalTableInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TableInfo.vue
Labels: cla-signed

#13131 chore: oracle one query
  backend/plugin/db/dm/dm.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#13132 fix: check permissions for instance license stats
  frontend/src/components/WorkspaceInstanceLicenseStats.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#13134 chore: update instance service
  backend/api/v1/database_service.go
  backend/api/v1/instance_service.go
  backend/store/instance.go
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/store/modules/v1/instance.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/v1/instance_service.proto
Labels: cla-signed

#13133 chore: snow one query
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/starrocks/starrocks.go
  backend/tests/sql_export_test.go
Labels: cla-signed

#13135 chore(frontend): request workspaceService.fetchIamPolicy after login
  frontend/src/App.vue
  frontend/src/store/modules/auth.ts
  frontend/src/views/OAuthCallback.vue
Labels: cla-signed, backport release/2.22.0

#13137 chore: remove run command util
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#13138 chore: improve SQL Editor button bar style
  frontend/src/views/sql-editor/EditorCommon/AdminModeButton.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#13139 chore: fix permission checks for audit log
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Changelist/ChangelistDetail/context.ts
  frontend/src/components/Database/context.ts
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceTabs.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/Quickstart.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/router/dashboard/workspace.ts
  frontend/src/shims-vue-router.d.ts
  frontend/src/store/modules/v1/permission.ts
  frontend/src/types/iam/index.ts
  frontend/src/types/iam/permission.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#13140 chore: validate snow query
  backend/plugin/db/dm/dm.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/parser/snowflake/query.go
  backend/plugin/parser/snowflake/query_test.go
  backend/plugin/parser/standard/query.go
Labels: cla-signed

#13141 chore: mssql rows
  backend/component/masker/masker.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#13142 chore: no mask
  backend/api/v1/query_result_masker.go
  backend/component/masker/masker.go
  backend/component/masker/masker_test.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#13143 refactor: driver
  backend/api/v1/sql_service.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/clickhouse/query.go
  backend/plugin/db/databricks/databricks.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/driver.go
  backend/plugin/db/dynamodb/dynamodb.go
  backend/plugin/db/elasticsearch/elasticsearch.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#13144 chore: no permission level
  backend/component/iam/acl.yaml
  backend/component/iam/manager.go
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/component/iam/permission_test.go
  frontend/src/components/Role/Setting/components/RolePanel.vue
  frontend/src/types/iam/index.ts
Labels: cla-signed

#13145 chore: burnout on number of statements
  backend/component/sheet/sheet.go
  backend/plugin/advisor/catalog/walk_through_test.go
  backend/plugin/advisor/sql_review.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#13146 chore: query IAM
  backend/api/v1/acl.go
  backend/api/v1/auth_service.go
  backend/api/v1/auth_service_test.go
  backend/api/v1/rollout_service.go
  backend/api/v1/sql_service.go
  backend/common/context.go
  backend/component/iam/manager.go
  backend/component/webhook/manager.go
  backend/runner/mail/slow_query_weekly_mail.go
Labels: cla-signed

#13147 refactor: auth code
  backend/component/iam/manager.go
Labels: cla-signed

#13148 refactor: iam
  backend/api/v1/role_service.go
  backend/api/v1/workspace_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/manager.go
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/component/iam/permission_test.go
Labels: cla-signed

#13149 refactor: roles
  backend/api/v1/database_service.go
  backend/api/v1/project_service.go
  backend/api/v1/role_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/workspace_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/manager.go
  backend/component/iam/permission.go
  backend/component/iam/permission_test.go
  backend/server/server.go
  backend/store/role.go
Labels: cla-signed

#13150 chore: fast check
  backend/component/iam/manager.go
  backend/component/iam/manager_test.go
  backend/component/iam/permission.go
Labels: cla-signed

#13151 chore: return early on large sql
  backend/runner/approval/runner.go
Labels: cla-signed

#13152 refactor: approval
  backend/runner/approval/runner.go
Labels: cla-signed

#13154 fix: update group iam
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/user_group_service.go
  backend/common/resource_name.go
  backend/utils/member.go
  frontend/src/types/proto/v1/user_group.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/user_group.pb.go
  proto/generated-go/v1/user_group_grpc.pb.go
  proto/v1/user_group.proto
Labels: cla-signed

#13153 chore: iam check group
  backend/api/v1/user_group_service.go
  backend/component/iam/manager.go
  backend/component/iam/manager_test.go
Labels: cla-signed

#13155 fix: shouldn't throw error if raw string has no content
  frontend/src/plugins/cel/logic/stringify.ts
Labels: cla-signed

#13156 chore: group proto restructure
  backend/api/v1/group_service.go
  backend/api/v1/project_service.go
  backend/common/resource_name.go
  backend/component/iam/acl.yaml
  backend/component/iam/manager.go
  backend/component/iam/manager_test.go
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/server/grpc_routes.go
  backend/store/group.go
  backend/store/store.go
  backend/utils/member.go
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/ProjectMember/types.ts
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/SensitiveData/GrantAccessDrawer.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/components/User/Settings/UserDataTable/cells/GroupsCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupMemberRoleSelect.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupNameCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/index.vue
  frontend/src/components/v2/Select/GroupSelect.vue
  frontend/src/components/v2/Select/index.ts
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/group.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto/store/group.ts
  frontend/src/types/proto/store/user_group.ts
  frontend/src/types/proto/v1/group.ts
  frontend/src/types/v1/group.ts
  frontend/src/utils/v1/iam.ts
  frontend/src/views/SettingWorkspaceMember.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/group.pb.go
  proto/generated-go/store/user_group.pb.go
  proto/generated-go/v1/group.pb.go
  proto/generated-go/v1/group.pb.gw.go
  proto/generated-go/v1/group_grpc.pb.go
  proto/generated-go/v1/user_group.pb.go
  proto/generated-go/v1/user_group_grpc.pb.go
  proto/store/group.proto
  proto/v1/group.proto
Labels: cla-signed

#13159 chore: improve table, schema, view icon
  frontend/src/components/Icon/SchemaIcon.vue
  frontend/src/components/Icon/TableIcon.vue
  frontend/src/components/Icon/ViewIcon.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
Labels: cla-signed

#13158 chore: optimize iam checks
  backend/api/gitops/webhook.go
  backend/api/v1/changelist_service.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_test.go
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/project_service.go
  backend/api/v1/sheet_service.go
  backend/common/context.go
  backend/store/issue.go
Labels: cla-signed

#13161 feat: wecom id cache
  backend/plugin/webhook/wecom/app.go
Labels: cla-signed

#13163 fix: error message when explaining redis command
  backend/plugin/db/redis/redis.go
Labels: cla-signed

#13164 chore: fix raw expression button checks
  frontend/src/components/ExprEditor/ConditionGroup.vue
Labels: cla-signed

#13160 feat: postgresql mutual tls and use system ca
  backend/plugin/db/pg/dump.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/util.go
Labels: cla-signed

#13167 chore: hack policy
  backend/api/v1/acl.go
Labels: cla-signed

#13169 fix(query-span): fix alias.* with join for plsql
  backend/plugin/parser/plsql/query_span_extractor.go
  backend/plugin/parser/plsql/test-data/query_span.yaml
Labels: cla-signed

#13170 chore: remove statement in error message
  backend/plugin/db/dynamodb/dynamodb.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#13168 chore: update masking algorithm
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/useSemanticType.ts
  frontend/src/components/v2/TabFilter/EnvironmentTabFilter.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/dbSchema.ts
Labels: cla-signed

#13172 chore: add multitenancy doc anchor
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
Labels: cla-signed

#13173 fix: list data source
  backend/api/v1/sql_service.go
Labels: cla-signed

#13171 chore: update task run comment view
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
Labels: cla-signed

#13174 chore: correct doc anchor format
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/types/v1/projectWebhook.ts
Labels: cla-signed

#13175 chore(sql-editor): hide export data button in iframe
  frontend/src/customAppProfile.ts
Labels: cla-signed

#13176 chore(frontend): remove permission checks for querying data source
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#13177 chore: remove unused vi docs
  frontend/public/help/vi/help.database.md
  frontend/public/help/vi/help.environment.md
  frontend/public/help/vi/help.instance.md
  frontend/public/help/vi/help.issue.detail.md
  frontend/public/help/vi/help.member.md
  frontend/public/help/vi/help.project.md
Labels: cla-signed

#13178 chore(frontend): invalid cache eagerly
  frontend/src/store/modules/user.ts
Labels: cla-signed, backport release/2.22.0

#13180 chore: tweak legacy type definitions
  frontend/src/directives/data-source-type.ts
  frontend/src/main.ts
  frontend/src/store/modules/auth.ts
  frontend/src/types/auth.ts
  frontend/src/types/common.ts
  frontend/src/types/error.ts
  frontend/src/types/externalApproval.ts
  frontend/src/types/index.ts
  frontend/src/types/oauth.ts
  frontend/src/types/review.ts
  frontend/src/types/sheet.ts
  frontend/src/types/sqlAdvice.ts
  frontend/src/types/utils.ts
  frontend/src/views/auth/Signup.vue
Labels: cla-signed

#13179 feat: scheduler info
  backend/api/v1/rollout_service_converter.go
  backend/component/state/state.go
  backend/runner/taskrun/schedulerv2.go
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/proto/store/task_run.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/task_run.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/task_run.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#13182 chore: permission guard for audit log
  backend/api/v1/instance_service.go
  frontend/src/router/dashboard/projectV1.ts
Labels: cla-signed

#13183 refactor: reuse code
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/plancheck/statement_report_executor.go
  backend/store/sheet.go
Labels: cla-signed

#13185 chore: deprecate plan_check_run dbgroupuid
  backend/api/v1/plan_service_plan_check.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/plancheck/statement_report_executor.go
  frontend/src/types/proto/store/plan_check_run.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/plan_check_run.pb.go
  proto/store/plan_check_run.proto
Labels: cla-signed

#13186 chore: refresh pages if login as another user
  frontend/src/App.vue
  frontend/src/AuthContext.vue
  frontend/src/components/Project/useRecentProjects.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/useRecentVisit.ts
  frontend/src/store/modules/auth.ts
  frontend/src/store/modules/v1/actuator.ts
Labels: cla-signed

#13188 fix: do not mask in explain
  backend/api/v1/query_result_masker.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#13190 chore: bb.branches.admin
  backend/api/v1/branch_service.go
  backend/api/v1/project_service.go
  backend/common/resource_name.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  frontend/src/types/proto/store/project.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/project.pb.go
  proto/store/project.proto
Labels: cla-signed

#13191 chore: no protection
  frontend/src/components/Project/CreateProjectBranchProtectionRulePanel.vue
  frontend/src/components/Project/Settings/ProjectBranchProtectionRulesSettingPanel.vue
  frontend/src/components/Project/Settings/index.ts
Labels: cla-signed

#13193 chore(branching): restrict to merge to parent
  frontend/src/components/Branch/BranchMergeView/BranchMergeView.vue
  frontend/src/components/Branch/BranchMergeView/MergeBranchSelect.vue
Labels: cla-signed

#13194 chore: no protection shield
  frontend/src/components/Branch/BranchDataTable/cells/AsyncBranchNameCell.vue
  frontend/src/components/Branch/BranchDataTable/cells/BranchNameCell.vue
  frontend/src/store/modules/v1/projectProtectionRoles.ts
Labels: cla-signed

#13197 fix: tab is crash
  frontend/src/views/SettingWorkspaceMember.vue
Labels: cla-signed

#13198 chore(query-span): support JSON_TABLE for MySQL
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/test-data/query-span/standard.yaml
Labels: cla-signed

#13200 chore(frontend): better row limit experience
  frontend/src/components/DataExportButton.vue
  frontend/src/components/Issue/panel/RequestExportPanel/MaxRowCountSelect.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13201 chore: branches.admin to delete main branch
  backend/component/iam/acl.yaml
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/types/iam/permission.ts
Labels: cla-signed

#13203 chore: main branch permission
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchRebaseView/BranchRebaseView.vue
Labels: cla-signed

#13195 chore: local storage with user
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/router/useRecentVisit.ts
  frontend/src/store/modules/uistate.ts
Labels: cla-signed

#13202 fix: expr editor intial value
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
  frontend/src/components/ExprEditor/ConditionGroup.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
Labels: cla-signed

#13208 chore(sql-editor): fetch database metadata when needed
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
Labels: cla-signed

#13209 chore: last modifier and source branch proto
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#13211 chore(sql-editor): hide environment tag when not needed
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
Labels: cla-signed

#13212 fix: eslint
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/Quickstart.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed

#13210 chore: add oauth2 template for microsoft entra
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/utils/idp.ts
Labels: cla-signed

#13207 chore(sql-editor): make AI-augmentation feature free
  backend/legacyapi/plan.go
Labels: cla-signed

#13206 chore: support Oracle sequence
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#13214 fix: close driver
  backend/api/v1/rollout_service.go
Labels: cla-signed

#13192 chore: deprecate deployment config as a target
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/tests/ghost_test.go
  backend/tests/tenant_test.go
Labels: cla-signed

#13216 chore: range proto
  frontend/src/types/proto/store/common.ts
  frontend/src/types/proto/store/instance_change_history.ts
  frontend/src/types/proto/v1/common.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/common.pb.go
  proto/generated-go/store/instance_change_history.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/common.proto
  proto/store/instance_change_history.proto
  proto/v1/common.proto
  proto/v1/database_service.proto
Labels: cla-signed

#13217 fix(hive): connections leakage in Dump()
  backend/plugin/db/hive/dump.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/hive/hive_conn_pool.go
Labels: backport release/2.22.0

#13218 chore(frontend): don't fetch workspace policy before oauth jumping to 2fa
  frontend/src/views/OAuthCallback.vue
Labels: cla-signed, backport release/2.22.0

#13220 chore(differ): ignore create table storage option
  backend/plugin/parser/plsql/differ.go
  backend/plugin/parser/plsql/test-data/test_differ_data.yaml
Labels: cla-signed

#13222 chore: fix list database group requests
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/store/modules/dbGroup.ts
  frontend/src/views/DatabaseGroupDetail.vue
Labels: cla-signed

#13221 chore: upgrade mysql parser for more bin and hex
  backend/plugin/db/mysql/mysql.go
  backend/plugin/parser/mysql/mysql_test.go
  backend/tests/sql_export_test.go
  go.mod
  go.sum
Labels: cla-signed

#13224 fix(frontend): improve some japanese
  frontend/src/locales/ja-JP.json
Labels: cla-signed

#13226 chore(hive): code style
  backend/plugin/db/hive/dump.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/hive/hive_conn_pool.go
  backend/plugin/db/hive/role.go
  backend/plugin/db/hive/sync.go
Labels: cla-signed

#13223 chore: add `latest_only` field to ListPlanCheckRuns
  backend/api/v1/plan_service.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/plan_check_run.go
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#13228 fix(sql-editor): default data source
  frontend/src/utils/sqlEditor.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#13229 fix: custom approval setting
  frontend/src/utils/workspaceApprovalSetting.ts
Labels: cla-signed

#13230 chore: set default data source
  backend/api/v1/sql_service.go
  backend/store/data_source.go
  backend/store/instance.go
Labels: cla-signed

#13231 chore(hive): remove connection pool
  backend/plugin/db/hive/dump.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/hive/hive_conn_pool.go
  backend/plugin/db/hive/role.go
  backend/plugin/db/hive/sync.go
Labels: cla-signed

#13232 refactor: cursor
  backend/plugin/db/hive/dump.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/hive/role.go
  backend/plugin/db/hive/sync.go
Labels: cla-signed

#13227 chore: more dynamic local storage
  frontend/src/components/Project/ProjectIssuesPanel.vue
  frontend/src/components/Project/useRecentProjects.ts
  frontend/src/composables/useLanguage.ts
  frontend/src/plugins/i18n.ts
  frontend/src/store/modules/uistate.ts
  frontend/src/views/MyIssues.vue
Labels: cla-signed

#13234 chore: bye assignee
  backend/api/gitops/webhook.go
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/legacyapi/policy.go
  backend/server/onboard.go
  backend/store/issue.go
  backend/tests/database.go
  backend/tests/project_test.go
  backend/tests/rollout.go
  backend/tests/schema_update_test.go
  backend/tests/sql_review_test.go
  frontend/src/components/Plan/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/HeaderSection/Title.vue
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/issue_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/v1/issue_service.proto
  proto/v1/project_service.proto
Labels: cla-signed

#13233 chore(sql-editor): override some auto-complete popup icons
  backend/api/lsp/completion.go
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/MonacoEditor/composables/index.ts
  frontend/src/components/MonacoEditor/composables/useOverrideSuggestIcons.ts
Labels: cla-signed

#13235 chore: syntax error plan check result
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#13236 chore(sql-editor): minor fixes
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
Labels: cla-signed

#13237 chore: return full view of db group in CreateDatabaseGroup/UpdateDatabaseGroup
  backend/api/v1/database_group_service.go
Labels: cla-signed

#13238 feat: handle last updater and source branches in create/update branch
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/common/resource_name.go
Labels: cla-signed

#13239 chore: update task list section style
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
Labels: cla-signed

#13240 fix: sort project by name
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/store/modules/v1/project.ts
  frontend/src/store/modules/v1/projectWebhook.ts
Labels: cla-signed

#13225 fix: task filter by deployment config
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
Labels: cla-signed

#13241 fix: developer update issue
  backend/component/iam/acl.yaml
Labels: cla-signed

#13242 chore: upgrade helm version to 2.22.1
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#13243 chore: fix permission yaml
  backend/component/iam/permission.yaml
Labels: cla-signed

#13244 chore: test permissions equal
  backend/component/iam/permission_test.go
Labels: cla-signed

#13245 chore: summary struct
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/plsql/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#13199 refactor: implement store list cache for projects/instances
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/components/SlowQuery/Settings/SlowQuerySettings.vue
  frontend/src/components/WorkspaceInstanceLicenseStats.vue
  frontend/src/components/v2/Select/EnvironmentSelect.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/store/modules/v1/cache.ts
  frontend/src/store/modules/v1/instance.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/views/Archive.vue
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  frontend/src/views/sql-editor/Setting/Project/Project.vue
Labels: cla-signed

#13246 chore: hide branch related permissions in frontend
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
  frontend/src/components/Role/Setting/components/RolePanel.vue
Labels: cla-signed

#13247 fix: filter plan check by deployment schedule
  backend/api/v1/plan_service_plan_check.go
Labels: cla-signed

#13249 chore: main branch apply
  frontend/src/components/Branch/BranchDetailView.vue
Labels: cla-signed

#13248 chore: custom roles can be deleted only when no policy references them
  backend/api/v1/role_service.go
  backend/store/role.go
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/utils.ts
Labels: cla-signed

#13250 feat: handle last updater in merge/rebase branch
  backend/api/v1/branch_service.go
  backend/runner/taskrun/executor.go
  backend/store/model/database.go
  backend/utils/database_config_merge.go
  backend/utils/database_config_merge_test.go
  frontend/src/components/Branch/BranchDetailView.vue
Labels: cla-signed

#13251 chore(sql-editor): icons improvements
  frontend/src/components/Icon/ColumnIcon.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ColumnNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DummyNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ExternalTableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PartitionTableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ProcedureNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TextNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ViewNode.vue
Labels: cla-signed

#13252 refactor: change resources
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/plsql/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#13253 chore: update useProjectV1Store cases
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/DatabaseResourceForm/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/QuickActionPanel.vue
  frontend/src/router/dashboard/workspace.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/store/modules/workspaceMailDeliverySetting.ts
  frontend/src/views/DatabaseGroupDetail.vue
  frontend/src/views/ReviewCenter/index.vue
  frontend/src/views/branch/BranchDetail.vue
  frontend/src/views/branch/BranchMerge.vue
  frontend/src/views/branch/BranchRebase.vue
  frontend/src/views/branch/BranchRollout.vue
  frontend/src/views/project/ProjectAnomalyCenterDashboard.vue
  frontend/src/views/project/ProjectBranchDashboard.vue
  frontend/src/views/project/ProjectChangeHistoryDashboard.vue
  frontend/src/views/project/ProjectChangelistDashboard.vue
  frontend/src/views/project/ProjectDatabaseDashboard.vue
  frontend/src/views/project/ProjectDatabaseGroupDashboard.vue
  frontend/src/views/project/ProjectDeploymentConfigPanel.vue
  frontend/src/views/project/ProjectIssueDashboard.vue
  frontend/src/views/project/ProjectMemberDashboard.vue
  frontend/src/views/project/ProjectSettingPanel.vue
  frontend/src/views/project/ProjectSlowQueryDashboard.vue
  frontend/src/views/project/ProjectSyncDatabasePanel.vue
  frontend/src/views/project/ProjectVersionControlCreate.vue
  frontend/src/views/project/ProjectVersionControlDetail.vue
  frontend/src/views/project/ProjectVersionControlPanel.vue
  frontend/src/views/project/ProjectWebhookCreate.vue
  frontend/src/views/project/ProjectWebhookDashboard.vue
  frontend/src/views/project/ProjectWebhookDetail.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
Labels: cla-signed

#13255 chore: record dmls
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/affected_rows.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/mysql/resource_change_test.go
  backend/runner/plancheck/statement_report_executor_affected_rows_test.go
Labels: cla-signed

#13256 chore: resource change ranges
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/mysql/resource_change_test.go
  backend/plugin/parser/plsql/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#13254 feat: make sql output size configurable
  backend/api/v1/setting_service.go
  backend/common/util.go
  backend/component/dbfactory/dbfactory.go
  backend/legacyapi/setting.go
  backend/migrator/migrator_test.go
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/clickhouse/query.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/driver.go
  backend/plugin/db/hive/dump.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/hive/sync.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/snowflake/snowflake_test.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/sqlite/sqlite.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/util/driverutil.go
  backend/resources/postgres/sample_instance.go
  backend/server/init.go
  backend/server/server.go
  backend/store/metadb.go
  backend/store/setting.go
  frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/setting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#13258 chore: fix resource list in archives
  frontend/src/views/Archive.vue
Labels: cla-signed

#13259 refactor: affected rows
  backend/plugin/parser/base/affected_rows.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/affected_rows.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/mysql/resource_change_test.go
  backend/plugin/parser/mysql/statement_type.go
  backend/plugin/parser/plsql/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
  backend/runner/plancheck/statement_report_executor_affected_rows.go
Labels: cla-signed

#13257 chore(frontend): display last update branch
  frontend/src/components/SchemaEditorLite/Aside/LastUpdate.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#13260 feat: source branch
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/utils/database_config_merge.go
Labels: cla-signed
