Repository bytebase/bytebase, pull requests merged in 2024-06, with the labels that each got.

#12242 chore: no sql rollback
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/component/state/state.go
  backend/legacyapi/task.go
  backend/plugin/db/mysql/binlog_stream_parser.go
  backend/plugin/db/mysql/binlog_stream_parser_test.go
  backend/plugin/db/mysql/rollback.go
  backend/plugin/db/mysql/rollback_test.go
  backend/runner/rollbackrun/runner.go
  backend/runner/taskrun/executor.go
  backend/server/server.go
  backend/store/task.go
  backend/tests/mysql.go
  backend/tests/rollback_test.go
  frontend/pnpm-lock.yaml
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackFromTips.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/LogButton.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/LoggingButton.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackSection.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackStatus.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/RollbackSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/RollbackSection/index.ts
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/IssueV1/logic/common.ts
  frontend/src/components/IssueV1/logic/index.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/issue.ts
  frontend/src/types/pipeline/task.ts
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/v1/plan_service.ts
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/plan.proto
  proto/v1/plan_service.proto
  proto/v1/rollout_service.proto
Labels: cla-signed

#12243 fix: remove duplicated instance form
  frontend/src/components/QuickActionPanel.vue
Labels: cla-signed

#12244 chore: upgrade pgx version
  go.mod
  go.sum
Labels: cla-signed

#12245 feat: enable partiql syntax check
  backend/common/util.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/partiql/partiql.go
  backend/plugin/parser/partiql/split_test.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#12246 fix: trigger twice when clear rollout time
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
Labels: cla-signed

#12247 chore: optimize change history table
  frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
  frontend/src/components/ChangeHistory/ChangeHistoryTable.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryChangeItem.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryForm.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/IssueUID.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseDetail/ChangeHistoryBrief.vue
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/RoleDescription.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/changeHistory.ts
  frontend/src/types/changeHistory.ts
  frontend/src/views/ReviewCenter/SQLReviewIssueDataTable/SQLReviewIssueDataTable.vue
Labels: cla-signed

#12199 feat(sql-editor): introducing "Add Instance" UI to SQL Editor
  frontend/src/components/CommonSidebar.vue
  frontend/src/components/InstanceForm/Buttons.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/ProvideSQLEditorSettingContext.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
  frontend/src/layouts/SQLEditorLayout.vue
  frontend/src/router/sqlEditor.ts
  frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/AddFactorButton.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
  frontend/src/views/sql-editor/SQLEditorSettingPage.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  frontend/src/views/sql-editor/Setting/Environment/index.ts
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
  frontend/src/views/sql-editor/Setting/Instance/index.ts
  frontend/src/views/sql-editor/Setting/Project/Project.vue
  frontend/src/views/sql-editor/Setting/Project/index.ts
  frontend/src/views/sql-editor/Setting/SettingButton.vue
  frontend/src/views/sql-editor/Setting/Sidebar/Sidebar.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
  frontend/src/views/sql-editor/Setting/Sidebar/index.ts
  frontend/src/views/sql-editor/Setting/context.ts
  frontend/src/views/sql-editor/Setting/index.ts
Labels: cla-signed

#12250 chore: fix button position
  frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
Labels: cla-signed

#12248 fix: revert update task
  backend/api/v1/plan_service.go
Labels: cla-signed

#12249 chore: warn if run into sp_rename
  backend/plugin/advisor/mssql/advisor_migration_compatibility.go
  backend/plugin/advisor/mssql/test/column_type_disallow_list.yaml
  backend/plugin/advisor/mssql/test/index_not_redundant.yaml
  backend/plugin/advisor/mssql/test/schema_backward_compatibility.yaml
  backend/plugin/advisor/mssql/test/statement_disallow_cross_db_queries.yaml
  backend/plugin/advisor/mssql/test/statement_where_disallow_functions_and_calculations.yaml
  backend/plugin/advisor/mssql/test/system_function_disallow_create.yaml
  backend/plugin/advisor/mssql/test/system_procedure_disallow_create.yaml
  backend/plugin/advisor/mssql/test/table_disallow_ddl.yaml
  backend/plugin/advisor/mssql/test/table_disallow_dml.yaml
Labels: cla-signed

#12252 chore: sheet manager
  backend/api/gitops/gitops.go
  backend/api/gitops/webhook.go
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/api/v1/sheet_service.go
  backend/component/sheet/sheet.go
  backend/runner/approval/runner.go
  backend/server/grpc_routes.go
  backend/server/onboard.go
  backend/server/server.go
Labels: cla-signed

#12254 chore: optimize sql review panel
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/Branch/BranchSQLCheckButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckSummary.vue
Labels: cla-signed

#12255 fix(sql-editor): resule view not show up
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#12256 chore: implement never expires for grant request issues
  backend/common/cel.go
  backend/runner/approval/runner.go
  frontend/src/components/Issue/panel/RequestExportPanel/index.vue
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/IssueV1/components/GrantRequest/GrantRequestQuerierForm.vue
Labels: cla-signed, backport release/2.18.0

#12257 feat: support query dynamodb
  backend/api/v1/sql_service.go
  backend/plugin/db/dynamodb/dynamodb.go
Labels: cla-signed

#12259 chore: fix expiration options filter
  frontend/src/components/ExpirationSelector.vue
Labels: cla-signed

#12260 feat: query span support database links for oracle
  backend/api/v1/sql_service.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/span.go
  backend/plugin/parser/errors/resources.go
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/mysql/query_span.go
  backend/plugin/parser/mysql/query_span_test.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/pg/query_span.go
  backend/plugin/parser/pg/query_span_test.go
  backend/plugin/parser/plsql/backup.go
  backend/plugin/parser/plsql/plsql.go
  backend/plugin/parser/plsql/query_span.go
  backend/plugin/parser/plsql/query_span_extractor.go
  backend/plugin/parser/plsql/query_span_test.go
  backend/plugin/parser/plsql/replace.go
  backend/plugin/parser/plsql/strings.go
  backend/plugin/parser/plsql/test-data/query_span.yaml
  backend/plugin/parser/snowflake/query_span.go
  backend/plugin/parser/snowflake/query_span_test.go
  backend/plugin/parser/tidb/query_span.go
  backend/plugin/parser/tidb/query_span_test.go
  backend/plugin/parser/tsql/completion.go
  backend/plugin/parser/tsql/query_span.go
  backend/plugin/parser/tsql/query_span_test.go
  backend/plugin/schema/oracle/get_design_schema.go
  backend/plugin/schema/oracle/parse_to_metadata.go
  backend/runner/taskrun/data_export_executor.go
  backend/store/model/database.go
Labels: cla-signed

#12261 chore: npe in export
  backend/api/v1/sql_service_export_utils.go
Labels: cla-signed

#12262 chore(proto): add sequence definition
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/actuator_service_grpc.pb.go
  proto/generated-go/v1/anomaly_service_grpc.pb.go
  proto/generated-go/v1/audit_log_service_grpc.pb.go
  proto/generated-go/v1/auth_service_grpc.pb.go
  proto/generated-go/v1/branch_service_grpc.pb.go
  proto/generated-go/v1/cel_service_grpc.pb.go
  proto/generated-go/v1/changelist_service_grpc.pb.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/generated-go/v1/environment_service_grpc.pb.go
  proto/generated-go/v1/idp_service_grpc.pb.go
  proto/generated-go/v1/instance_role_service_grpc.pb.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/generated-go/v1/issue_service_grpc.pb.go
  proto/generated-go/v1/org_policy_service_grpc.pb.go
  proto/generated-go/v1/plan_service_grpc.pb.go
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/generated-go/v1/risk_service_grpc.pb.go
  proto/generated-go/v1/role_service_grpc.pb.go
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/generated-go/v1/setting_service_grpc.pb.go
  proto/generated-go/v1/sheet_service_grpc.pb.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/generated-go/v1/subscription_service_grpc.pb.go
  proto/generated-go/v1/user_group_grpc.pb.go
  proto/generated-go/v1/vcs_connector_service_grpc.pb.go
  proto/generated-go/v1/vcs_provider_service_grpc.pb.go
  proto/generated-go/v1/worksheet_service_grpc.pb.go
  proto/store/database.proto
Labels: cla-signed

#12263 chore: dynamodb run statament
  backend/plugin/db/dynamodb/dynamodb.go
Labels: cla-signed

#12264 feat: dynamodb query validator
  backend/plugin/parser/partiql/query.go
Labels: cla-signed

#12267 chore: sync sequences for postgres
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#12268 feat: add payload to project_webhook
  backend/migrator/migration/prod/2.19/0001##project_webhook_payload.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#12265 feat(frontend): share ONE sheet among multiple tasks in an issue
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12269 feat: drop project_member
  backend/migrator/migration/prod/2.19/0002##drop_project_member.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#12270 fix: database filter & default project
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/ProjectStandardView.vue
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/ExternalTableDetailDrawer.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/components/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/MultipleDatabaseSelector.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/project.ts
  frontend/src/types/v1/project.ts
Labels: cla-signed

#12272 feat(proto): project webhook payload
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/project_webhook.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/project_webhook.pb.go
  proto/store/project_webhook.proto
Labels: cla-signed

#12271 chore: sheet lru structure
  backend/component/sheet/sheet.go
  go.mod
Labels: cla-signed

#12273 chore: use db schema store
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Branch/BranchCreateView.vue
  frontend/src/store/modules/v1/dbSchema.ts
Labels: cla-signed

#12275 chore: advice store
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/advice.ts
  frontend/src/types/proto/store/common.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/advice.pb.go
  proto/generated-go/store/common.pb.go
  proto/store/advice.proto
  proto/store/common.proto
Labels: cla-signed

#12274 feat: support sequence for postgres query span
  backend/plugin/parser/base/span.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/store/model/database.go
Labels: cla-signed

#12266 feat(databricks): init and sync
  backend/plugin/db/databricks/databricks.go
  backend/plugin/db/databricks/dump.go
  backend/plugin/db/databricks/role.go
  backend/plugin/db/databricks/sync.go
  backend/plugin/db/driver.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/common.ts
  frontend/src/types/proto/store/data_source.ts
  go.mod
  go.sum
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/common.pb.go
  proto/generated-go/store/data_source.pb.go
  proto/store/common.proto
  proto/store/data_source.proto
Labels: cla-signed

#12276 feat: convert create view statement for pg
  backend/plugin/parser/sql/ast/create_view_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
  backend/plugin/parser/sql/engine/pg/convert_test.go
Labels: cla-signed

#12277 refactor(frontend): code split for environment form
  frontend/src/components/EnvironmentForm.vue
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/components/EnvironmentForm/index.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
Labels: cla-signed

#12282 feat: toy dynamodb auto complete
  backend/api/lsp/completion.go
  backend/plugin/db/dynamodb/sync.go
  backend/plugin/parser/partiql/completion.go
  backend/plugin/parser/partiql/completion_test.go
  backend/plugin/parser/partiql/split.go
  backend/plugin/parser/partiql/test-data/test_completion.yaml
Labels: cla-signed

#12281 feat(sql-editor): environment management in sql editor
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#12283 chore: still use default
  backend/api/v1/rollout_service_task.go
Labels: cla-signed, backport release/2.18.0

#12280 fix: respect workspace level project role and all_users
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/store/modules/user.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/utils/iam/permission.ts
  frontend/src/utils/v1/project.ts
Labels: cla-signed

#12285 chore: return error if schema version is empty
  backend/runner/taskrun/executor.go
Labels: cla-signed

#12286 chore: reorg tags
  backend/plugin/advisor/advisor.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/sql_review.go
  backend/server/minimal.go
  backend/server/minimal_demo.go
  backend/server/ultimate.go
  backend/server/ultimate_linux.go
  backend/sql-server/advise.go
  backend/sql-server/metric.go
  backend/sql-server/profile.go
  backend/sql-server/server.go
  scripts/.air.toml
  scripts/Dockerfile.render-demo
Labels: cla-signed

#12287 fix: list databases request filter comment
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#12289 fix: rollout db group task
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/store/task.go
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12291 chore: datetime format for license expiration time
  frontend/src/store/modules/v1/subscription.ts
Labels: cla-signed

#12290 chore: use sheet manager
  backend/api/v1/sql_service.go
  backend/component/sheet/sheet.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/utils_for_tests.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/server/grpc_routes.go
  backend/server/server.go
  backend/store/catalog.go
Labels: cla-signed

#12288 fix: make go build work
  scripts/.air.toml
Labels: cla-signed

#12292 chore: 1224
  .github/workflows/backend-tests.yml
  .github/workflows/test_link.yml
  README.md
  go.mod
  scripts/Dockerfile
  scripts/Dockerfile.aws
  scripts/Dockerfile.depot
  scripts/Dockerfile.render-demo
  scripts/build_bytebase.sh
Labels: cla-signed

#12293 chore: update plan detail page
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
Labels: cla-signed

#12294 chore(frontend): update change history data table
  frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
  frontend/src/components/ChangeHistory/ChangeHistoryDetail.vue
  frontend/src/components/ChangeHistory/index.ts
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/ProjectChangeHistoryPanel.vue
  frontend/src/utils/v1/changeHistory.ts
Labels: cla-signed

#12295 docs: add product video link
  README.md
  docs/assets/product-video-thumbnail.webp
Labels: cla-signed

#12296 refactor: use query span instead of legacy masking function in mysql differ
  backend/plugin/parser/mysql/differ.go
  backend/plugin/parser/mysql/differ_test.go
  backend/plugin/parser/mysql/masking.go
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/test-data/differ/test_differ_view.yaml
Labels: cla-signed

#12297 feat: slack dm
  backend/api/v1/setting_service.go
  backend/component/webhook/manager.go
  backend/plugin/webhook/custom.go
  backend/plugin/webhook/dingtalk.go
  backend/plugin/webhook/discord.go
  backend/plugin/webhook/feishu.go
  backend/plugin/webhook/slack.go
  backend/plugin/webhook/slack/app.go
  backend/plugin/webhook/slack/slack.go
  backend/plugin/webhook/teams.go
  backend/plugin/webhook/webhook.go
  backend/plugin/webhook/webhook_test.go
  backend/plugin/webhook/wecom.go
  backend/server/minimal.go
  backend/server/ultimate.go
  backend/store/setting.go
Labels: cla-signed

#12299 chore: reuse ast
  backend/api/v1/sql_service.go
  backend/plugin/advisor/catalog/catalog.go
  backend/plugin/advisor/catalog/finder.go
  backend/plugin/advisor/catalog/walk_through.go
  backend/plugin/advisor/catalog/walk_through_for_mysql.go
  backend/plugin/advisor/catalog/walk_through_for_pg.go
  backend/plugin/advisor/catalog/walk_through_test.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/advisor/tidb/test/column_disallow_changing_order.yaml
  backend/runner/plancheck/statement_advise_executor.go
  backend/store/catalog.go
Labels: cla-signed

#12298 feat: implement pg sync schema for view
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
  backend/plugin/parser/sql/ast/create_view_stmt.go
  backend/plugin/parser/sql/ast/select_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
Labels: cla-signed

#12300 chore: reuse ast in reporter
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/mysql/query_test.go
  backend/plugin/parser/mysql/resource_change.go
  backend/plugin/parser/plsql/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
  backend/server/server.go
Labels: cla-signed

#12301 chore: remove unused `useSpecSheet`
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/useTempEditState.ts
  frontend/src/components/IssueV1/components/StatementSection/useEditSheet.ts
  frontend/src/components/IssueV1/components/StatementSection/useSpecSheet.ts
Labels: cla-signed

#12302 chore(sql-editor): minor updates for setting -> instance
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/utils/util.ts
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
Labels: cla-signed

#12303 feat: pg sync schema supports comments of views
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
  backend/plugin/parser/sql/ast/comment_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
  backend/plugin/parser/sql/engine/pg/deparse.go
Labels: cla-signed

#12305 chore: optimize request query in sql editor
  frontend/src/components/Issue/panel/RequestQueryPanel/index.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/RequestQueryButton.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#12306 fix: slack dm retry
  backend/common/retry.go
  backend/plugin/webhook/slack/slack.go
Labels: cla-signed

#12308 feat(frontend): implement pagination for change history table
  backend/api/v1/database_service.go
  frontend/src/components/ChangeHistory/AffectedTableSelect.vue
  frontend/src/components/ChangeHistory/ChangeHistoryDataTable.vue
  frontend/src/components/ChangeHistory/ChangeTypeSelect.vue
  frontend/src/components/ChangeHistory/PagedChangeHistoryTable.vue
  frontend/src/components/ChangeHistory/index.ts
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/types/changeHistory.ts
  scripts/.air.toml
Labels: cla-signed

#12309 feat: validate token for slack
  backend/api/v1/setting_service.go
  backend/plugin/webhook/slack/app.go
Labels: cla-signed

#12310 feat: add wecom setting
  backend/api/v1/setting_service.go
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#12311 fix: limit drawer max with
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/ExternalApprovalNodesPanel/NodeDrawer.vue
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/InstanceAssignment.vue
  frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
  frontend/src/components/LabelEditorDrawer.vue
  frontend/src/components/Project/ProjectCreatePanel.vue
  frontend/src/components/SensitiveData/components/SemanticTemplateDrawer.vue
  frontend/src/components/User/Settings/CreateUserDrawer.vue
Labels: cla-signed

#12307 fix: slack err cmp
  backend/plugin/webhook/slack/slack.go
Labels: cla-signed

#12312 feat: plan check run status count
  backend/api/v1/rollout_service_converter.go
  backend/store/plan.go
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/plan_service.proto
Labels: cla-signed

#12313 chore: 2.19.0
  scripts/VERSION
Labels: cla-signed

#12315 chore: support set im
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/store/modules/v1/setting.ts
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/views/DashboardSidebar.vue
  frontend/src/views/SettingWorkspaceIM.vue
  frontend/src/views/SettingWorkspaceIntegrationSlack.vue
Labels: cla-signed

#12316 chore: add plan check run status column
  frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
Labels: cla-signed

#12317 feat: validate slack token scopes
  backend/plugin/webhook/slack/app.go
Labels: cla-signed

#12318 chore: use `dbGroup.matchedDatabases` instead of fetching them
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/IssueV1/logic/plan.ts
Labels: cla-signed

#12319 fix: no trailing slash for base dir
  backend/api/v1/vcs_connector_service.go
Labels: cla-signed

#12320 chore: fetch db metadata skip cache in db change history list page
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/components/ProjectChangeHistoryPanel.vue
Labels: cla-signed

#12321 chore: remove release guard for review center
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/views/DashboardSidebar.vue
Labels: cla-signed

#12322 fix(frontend): refactor `sqlList` param to `sqlMap`
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/SyncDatabaseSchema/index.vue
Labels: cla-signed

#12323 chore: release dynamodb
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#12324 feat: implement prior backup for postgres
  backend/plugin/parser/pg/backup.go
  backend/plugin/parser/pg/backup_test.go
  backend/plugin/parser/pg/pg.go
  backend/plugin/parser/pg/test-data/test_backup.yaml
  backend/runner/taskrun/data_update_executor.go
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
Labels: cla-signed

#12325 fix(advisor): fix pg prior backup check
  backend/plugin/advisor/catalog/state.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/pg/advisor_statement_prior_backup_check.go
Labels: cla-signed

#12326 chore: sync schema ignore backup schema
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/system_objects.go
Labels: cla-signed

#12327 chore: run single do statement without txn for pg
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#12330 fix: hide lark and wecom in release
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/views/SettingWorkspaceIM.vue
Labels: cla-signed

#12328 feat(sql-editor): SQL Editor setting for project
  frontend/src/components/Project/ProjectCreatePanel.vue
  frontend/src/components/TransferDatabaseForm.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/router/sqlEditor.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/views/sql-editor/AsidePanel/GutterBar/GutterBar.vue
  frontend/src/views/sql-editor/Setting/Project/Detail.vue
  frontend/src/views/sql-editor/Setting/Project/Project.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#12331 fix: dm tip i18n
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12333 chore: use string fields
  backend/plugin/db/redis/redis.go
Labels: cla-signed

#12334 chore: optimize IM config
  backend/api/v1/setting_service.go
  frontend/src/components/ProjectWebhookForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceIM.vue
Labels: cla-signed

#12336 feat: view comments for oracle
  backend/api/v1/sql_service.go
Labels: cla-signed

#12335 chore: improve risk calculation speed
  backend/runner/approval/runner.go
Labels: cla-signed

#12338 chore(frontend): share one sheet among multiple specs in a plan
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/initialize/create.ts
Labels: cla-signed

#12339 fix(hive): npe in sync
  backend/plugin/db/hive/hive.go
Labels: cla-signed

#12340 chore: upgrade plsql parser
  go.mod
  go.sum
Labels: cla-signed

#12342 fix: fix obo schema metadata
  backend/plugin/db/obo/sync.go
Labels: cla-signed

#12343 fix(hive): avoid endless loop in cursor.HasMore()
  backend/plugin/db/hive/hive.go
Labels: cla-signed

#12345 chore: move feishu webhook to a separate pkg
  backend/plugin/webhook/custom.go
  backend/plugin/webhook/dingtalk.go
  backend/plugin/webhook/discord.go
  backend/plugin/webhook/feishu.go
  backend/plugin/webhook/feishu/feishu.go
  backend/plugin/webhook/slack/slack.go
  backend/plugin/webhook/teams.go
  backend/plugin/webhook/webhook.go
  backend/plugin/webhook/wecom.go
  backend/server/minimal.go
  backend/server/ultimate.go
Labels: cla-signed

#12346 fix: considering encrypted rsa private key
  backend/plugin/db/snowflake/snowflake.go
  go.mod
  go.sum
Labels: cla-signed

#12347 chore: shlex
  backend/plugin/db/redis/redis.go
  go.mod
  go.sum
Labels: cla-signed

#12349 chore: update im href
  frontend/src/views/SettingWorkspaceIM.vue
Labels: cla-signed

#12350 feat(completion): support insert for mysql
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/mysql/test-data/test_completion.yaml
Labels: cla-signed

#12351 chore: simplify webhook msg title
  backend/component/webhook/manager.go
  backend/plugin/webhook/webhook.go
Labels: cla-signed

#12352 fix: clear cache after sync
  frontend/src/store/modules/v1/database.ts
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#12353 chore(frontend): update affection table selector
  frontend/src/components/ChangeHistory/AffectedTablesSelect.vue
  frontend/src/components/ChangeHistory/index.ts
  frontend/src/components/Database/DatabaseChangeHistoryPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/changeHistory.ts
Labels: cla-signed

#12354 fix: hide unassign button in default project
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
Labels: cla-signed

#12355 chore(frontend): avoid unnecessary requests
  frontend/src/components/ProvideDashboardContext.vue
Labels: cla-signed

#12356 fix(hive): avoid parsing nil value
  backend/plugin/db/hive/hive.go
Labels: cla-signed

#12358 fix: set role for pg advisor query
  backend/plugin/advisor/mysql/advisor_insert_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_filesort.go
  backend/plugin/advisor/mysql/advisor_statement_disallow_using_temporary.go
  backend/plugin/advisor/mysql/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/mysql/advisor_statement_query_minumum_plan_level.go
  backend/plugin/advisor/mysql/advisor_statement_select_full_table_scan.go
  backend/plugin/advisor/pg/advisor_insert_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_affected_row_limit.go
  backend/plugin/advisor/pg/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/tidb/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/utils.go
Labels: cla-signed

#12361 chore: helm 2.19.0
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#12362 chore: simplify webhook msg title
  backend/component/webhook/manager.go
Labels: cla-signed

#12363 chore(frontend): fix affected table filter in changelist 🔥
  frontend/src/components/ChangeHistory/AffectedTableSelect.vue
Labels: cla-signed, backport release/2.19.0

#12364 fix: title
  backend/component/webhook/manager.go
Labels: cla-signed

#12348 refactor(sql-editor): namespacing local storage keys by user uid
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/utils/web-storage.ts
Labels: cla-signed

#12366 chore(frontend): adjust default column width for ChangeHistoryTable
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/ChangeHistoryTable.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangeHistoryTable/IssueUID.vue
Labels: cla-signed

#12367 chore: optimize project select in db transfer
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
Labels: cla-signed

#12369 feat: support sql server tls
  backend/plugin/db/mssql/mssql.go
  frontend/src/components/InstanceForm/DataSourceSection/SslCertificateForm.vue
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#12370 feat(databricks): fix sync
  backend/plugin/db/databricks/databricks.go
  backend/plugin/db/databricks/role.go
  backend/plugin/db/databricks/sync.go
  backend/plugin/db/driver.go
Labels: cla-signed

#12371 chore: update allUsers in IAM policy
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/component/webhook/manager.go
  backend/migrator/migration/prod/2.20/0000##iam_policy_all_users.sql
  backend/migrator/migrator_test.go
  backend/runner/mail/slow_query_weekly_mail.go
  backend/store/principal.go
  backend/utils/member.go
  backend/utils/utils.go
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/types/v1/user.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/ProfileDashboard.vue
Labels: cla-signed

#12372 feat: sync generated column info for mysql
  backend/api/v1/database_converter.go
  backend/plugin/db/mysql/sync.go
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#12373 chore: allow setting earliest allowed time to database group issues
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
Labels: cla-signed

#12374 fix: parse backup table name correctly
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_test.go
Labels: cla-signed, backport release/2.19.0

#12379 fix: nil pointer for role
  backend/component/iam/manager.go
Labels: cla-signed

#12378 chore: update archive text
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12380 chore: update remove role alert
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12382 fix(frontend): update button disabled 🔥
  frontend/src/components/EnvironmentForm/Form.vue
Labels: cla-signed, backport release/2.19.0

#12384 feat(databricks): add UI
  backend/api/v1/common.go
  backend/api/v1/instance_service.go
  backend/component/dbfactory/dbfactory.go
  backend/plugin/db/databricks/databricks.go
  backend/server/ultimate.go
  backend/store/data_source.go
  frontend/src/assets/db-databricks.svg
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/components/InstanceForm/constants.ts
  frontend/src/types/instance.ts
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/store/data_source.ts
  frontend/src/types/proto/v1/common.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/types/v1/instance.ts
  frontend/src/utils/v1/instance.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/data_source.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/store/data_source.proto
  proto/v1/common.proto
  proto/v1/database_service.proto
  proto/v1/instance_service.proto
  proto/v1/org_policy_service.proto
  proto/v1/rollout_service.proto
  proto/v1/sql_service.proto
Labels: cla-signed

#12385 feat: allow desc and show commands in sql editor read only mode for mysql
  backend/plugin/parser/mysql/query.go
  backend/plugin/parser/mysql/query_test.go
Labels: cla-signed

#12386 fix: remove dup codes
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#12387 feat: allow variable show statement in sql editor read only mode for postgresql
  backend/plugin/db/pg/pg.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/sql/ast/variable_show_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
  backend/plugin/parser/sql/engine/pg/convert_test.go
Labels: cla-signed

#12391 fix: fix panic in fingerprint
  backend/plugin/parser/mysql/fingerprint.go
  backend/plugin/parser/mysql/fingerprint_test.go
Labels: cla-signed

#12390 chore: workspace domain proto
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#12392 feat: allow desc and show commands in sql editor read only mode for tidb
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/tidb/query.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/parser/tidb/query.go
  backend/plugin/parser/tidb/query_span_extractor.go
Labels: cla-signed

#12393 chore: domain restriction
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#12394 fix(frontend): initialSQL check condition 🔥
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
Labels: cla-signed

#12395 chore: sync the sort order of index key
  backend/api/v1/database_converter.go
  backend/plugin/db/mysql/sync.go
  backend/tests/syncer_test.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#12398 chore: check domains for users and user groups
  backend/api/v1/auth_service.go
  backend/api/v1/user_group_service.go
Labels: cla-signed

#12397 chore: add appname in mongodb connection url
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/clickhouse/clickhouse.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/dynamodb/dynamodb.go
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redis/redis.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#12399 refactor: remove dead code
  backend/api/v1/sql_service.go
  backend/legacyapi/plan.go
  backend/plugin/advisor/db/db.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/driver.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/base/masking.go
Labels: cla-signed

#12400 chore(review-center): add confirm dialog
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12401 feat(databricks): query
  backend/plugin/db/databricks/databricks.go
  backend/plugin/db/databricks/sync.go
  backend/plugin/parser/standard/split.go
Labels: cla-signed

#12402 chore: sync check constraints for mysql
  backend/api/v1/database_converter.go
  backend/plugin/db/mysql/sync.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#12377 feat: stringify table for MySQL
  backend/api/v1/sql_service.go
  backend/plugin/schema/mysql/stringify_table.go
  backend/plugin/schema/schema.go
Labels: cla-signed

#12404 feat: impl feishu dm
  backend/plugin/webhook/feishu/app.go
  backend/plugin/webhook/feishu/feishu.go
  backend/plugin/webhook/slack/slack.go
  frontend/src/views/SettingWorkspaceIM.vue
Labels: cla-signed

#12406 fix: cannot open edit member panel
  frontend/src/components/ProjectMember/ProjectMemberDataTableByRole/index.vue
Labels: cla-signed, backport release/2.19.0

#12408 chore: copy data wording
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#12409 refactor: feishu app
  backend/plugin/webhook/feishu/feishu.go
Labels: cla-signed

#12403 feat: review config proto
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/store/review_config.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/types/proto/v1/review_config_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/store/review_config.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/generated-go/v1/review_config_service.pb.go
  proto/generated-go/v1/review_config_service.pb.gw.go
  proto/generated-go/v1/review_config_service_grpc.pb.go
  proto/store/policy.proto
  proto/store/review_config.proto
  proto/v1/org_policy_service.proto
  proto/v1/review_config_service.proto
Labels: cla-signed

#12411 feat(advisor): implement oracle dry run
  backend/plugin/advisor/code.go
  backend/plugin/advisor/oracle/advisor_statement_dml_dry_run.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/plsql/backup.go
  backend/runner/plancheck/statement_report_executor.go
  frontend/src/types/sql-review-schema.yaml
Labels: cla-signed, backport release/2.19.0

#12410 chore: migrate sql review policy
  backend/migrator/migration/prod/2.20/0001##review_config.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#12413 chore: 2.20.0
  scripts/VERSION
Labels: cla-signed

#12414 chore: enable feishu dm
  frontend/src/types/v1/projectWebhook.ts
Labels: cla-signed

#12415 fix: npe
  backend/api/v1/sql_service.go
  backend/runner/plancheck/statement_advise_executor.go
Labels: cla-signed

#12416 chore: validate feishu app
  backend/api/v1/setting_service.go
  backend/plugin/webhook/feishu/app.go
Labels: cla-signed

#12419 feat(frontend): domain restriction setting
  backend/api/v1/auth_service.go
  backend/api/v1/setting_service.go
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  go.mod
  go.sum
Labels: cla-signed

#12420 chore: update domain validator
  backend/api/v1/setting_service.go
  backend/api/v1/setting_service_test.go
  go.mod
  go.sum
Labels: cla-signed
