Repository bytebase/bytebase, pull requests merged in 2025-04, with the labels that each got.

#15684 chore: optimize database group
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupPanel.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/ProjectDatabaseGroupCreate.vue
  frontend/src/views/project/ProjectDatabaseGroupDetail.vue
Labels: cla-signed

#15685 chore: run sql check for all tasks before issue created
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/common.ts
  frontend/src/components/IssueV1/components/SQLCheckSection/context.ts
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/common.ts
Labels: cla-signed

#15686 chore: optimize expr select with remote fetch
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/ExprEditor/components/MultiSelect.vue
  frontend/src/components/ExprEditor/components/SingleSelect.vue
  frontend/src/components/ExprEditor/components/common.ts
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
Labels: cla-signed

#15687 feat: instance pagination in the frontend
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
  frontend/src/components/DatabaseGroup/utils.ts
  frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
  frontend/src/components/InstanceAssignment.vue
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
  frontend/src/components/v2/Model/Instance/PagedInstanceTable.vue
  frontend/src/components/v2/Model/Instance/index.ts
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/store/modules/v1/instance.ts
  frontend/src/store/modules/v1/instanceResource.ts
  frontend/src/utils/sqlEditor.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/utils/v1/instance.ts
  frontend/src/views/Archive.vue
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/Setting/Instance/Instance.vue
Labels: cla-signed

#15707 chore: remove empty database
  frontend/src/types/v1/database.ts
Labels: cla-signed

#15708 fix: ldap SecurityProtocolNone
  backend/plugin/idp/ldap/ldap.go
Labels: cla-signed

#15710 chore: update comment
  frontend/src/types/proto/v1/idp_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/idp_service.pb.go
  proto/v1/idp_service.proto
Labels: cla-signed

#15712 chore: show related resources when delete role failed
  backend/api/v1/role_service.go
  backend/store/principal.go
  backend/store/role.go
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15713 chore: deprecate the middle sidebar
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
  frontend/src/views/sql-editor/EditorPanel/GutterBar/GutterBar.vue
  frontend/src/views/sql-editor/EditorPanel/GutterBar/TabItem.vue
  frontend/src/views/sql-editor/EditorPanel/GutterBar/common.ts
  frontend/src/views/sql-editor/EditorPanel/GutterBar/index.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsPanel.vue
Labels: cla-signed

#15653 chore: fix copy binary values
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/binary-format-store.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
Labels: cla-signed

#15714 chore: action image
  .github/workflows/build-push-action-image.yml
  .github/workflows/docker-tag-latest.yml
  action/go.mod
  action/main.go
  scripts/Dockerfile.action
  scripts/build_bytebase_action.sh
Labels: cla-signed

#15715 fix: yml
  .github/workflows/build-push-action-image.yml
Labels: cla-signed

#15717 chore: bump monaco-languageclient
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/MonacoEditor/lsp-client.ts
Labels: cla-signed

#15719 chore: apply copilot suggestion
  frontend/src/components/MonacoEditor/lsp-client.ts
Labels: cla-signed

#15720 chore: action login
  action/api.go
  action/file.go
  action/go.mod
  action/main.go
  scripts/Dockerfile.action
Labels: cla-signed

#15721 chore: bump vscode-ws-jsonrpc
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#15723 fix: remove component pagination
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
Labels: cla-signed

#15724 chore: unify resource occupied alert
  frontend/src/bbkit/BBDialog.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/SQLReview/SQLReviewInfo.vue
  frontend/src/components/SQLReview/components/SQLReviewAttachResourcesPanel.vue
  frontend/src/components/SQLReview/components/SQLReviewAttachedResource.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicyDataTable.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicyTable.vue
  frontend/src/components/SQLReview/components/SQLReviewTemplateSelector.vue
  frontend/src/components/SQLReview/components/useReviewConfigAttachedResource.ts
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/components/v2/ResourceOccupiedModal/Resource.vue
  frontend/src/components/v2/ResourceOccupiedModal/ResourceOccupiedModal.vue
  frontend/src/components/v2/ResourceOccupiedModal/useResourceByName.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
Labels: cla-signed

#15722 chore: upgrade pg_query_go
  backend/plugin/advisor/pg/advisor_naming_fully_qualified.go
  backend/plugin/advisor/pg/advisor_statement_disallow_on_del_cascade.go
  backend/plugin/advisor/pg/advisor_statement_disallow_rm_tbl_cascade.go
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/pg/pg.go
  backend/plugin/parser/mybatis/mapper/parser_test.go
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/query_type.go
  backend/plugin/parser/sql/ast/create_function_stmt.go
  backend/plugin/parser/sql/ast/create_materialized_view_stmt.go
  backend/plugin/parser/sql/ast/create_view_stmt.go
  backend/plugin/parser/sql/ast/json.go
  backend/plugin/parser/sql/ast/node.go
  backend/plugin/parser/sql/ast/partition_def.go
  backend/plugin/parser/sql/ast/select_stmt.go
  backend/plugin/parser/sql/ast/update_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
  backend/plugin/parser/sql/engine/pg/convert_test.go
  backend/plugin/parser/sql/engine/pg/deparse.go
  backend/plugin/parser/sql/engine/pg/parser.go
  go.mod
  go.sum
Labels: cla-signed

#15725 chore: change statement type of release file to bytes
  action/file.go
  backend/api/v1/release_service.go
  backend/api/v1/release_service_check.go
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/PreviewPlanDetail.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/types/proto/v1/release_service.ts
  frontend/src/utils/index.ts
  frontend/src/utils/release.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#15726 chore: use resource occupied modal
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/SQLReview/SQLReviewInfo.vue
  frontend/src/components/SQLReview/components/SQLReviewAttachResourcesPanel.vue
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/components/v2/ResourceOccupiedModal/Resource.vue
  frontend/src/components/v2/ResourceOccupiedModal/ResourceOccupiedModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15728 feat: cassandra query
  backend/plugin/db/cassandra/cassandra.go
  backend/plugin/parser/standard/query.go
  frontend/src/utils/v1/sql.ts
  go.mod
Labels: cla-signed

#15729 chore: open new tab for view detail
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
Labels: cla-signed

#15731 chore: gitlab xml
  action/api.go
  action/file.go
  action/gitlab.go
  action/main.go
  scripts/Dockerfile.action
Labels: cla-signed

#15734 chore: show environment's title for stages
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/StageName.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview/StageCard.vue
Labels: cla-signed

#15735 fix: display valueValue
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#15736 feat: cassandra convert structpb
  backend/plugin/db/cassandra/cassandra.go
Labels: cla-signed

#15737 fix: check isNil
  backend/plugin/db/cassandra/cassandra.go
Labels: cla-signed

#15738 feat: filter dse system databases
  backend/plugin/db/cassandra/sync.go
Labels: cla-signed

#15739 fix: get member from policy
  backend/api/v1/user_service.go
Labels: backport release/3.5.1, cla-signed

#15741 feat: cassandra tls
  backend/plugin/db/cassandra/cassandra.go
  backend/plugin/db/util/ssl.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15742 chore: selectively display instance extra parameters
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
  frontend/src/components/InstanceForm/specs.ts
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15744 chore: support load more in database tree
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
Labels: cla-signed

#15743 chore: expose scopes config of oidc
  backend/api/v1/auth_service.go
  backend/api/v1/idp_service.go
  backend/migrator/migration/3.5/0017##oidc_scopes.sql
  backend/migrator/migrator_test.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/oidc/oidc_test.go
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/types/proto/store/idp.ts
  frontend/src/types/proto/v1/idp_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/idp.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/store/idp.proto
  proto/v1/idp_service.proto
Labels: cla-signed

#15745 chore: tab view state
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/store/modules/sqlEditor/index.ts
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/store/modules/sqlEditor/tabViewState.ts
  frontend/src/types/sqlEditor/index.ts
  frontend/src/types/sqlEditor/tabViewState.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTableColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ForeignKeysTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/IndexesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/PartitionsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TableDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TriggersTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DependencyColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/common/SchemaSelectToolbar.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
  frontend/src/views/sql-editor/EditorPanel/common/common.ts
  frontend/src/views/sql-editor/EditorPanel/context/index.ts
  frontend/src/views/sql-editor/EditorPanel/index.ts
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
  frontend/src/views/sql-editor/Sheet/common/Dropdown.vue
  frontend/src/views/sql-editor/TabList/ContextMenu.vue
  frontend/src/views/sql-editor/TabList/TabItem/Label.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#15747 chore: change release version
  scripts/VERSION
Labels: cla-signed

#15748 fix: release unknown fe commit hash
  frontend/package.json
Labels: cla-signed

#15749 chore: disable godot
  .golangci.yaml
Labels: cla-signed

#15718 feat: introduce new elastic search parser
  backend/plugin/db/elasticsearch/elasticsearch.go
  backend/plugin/db/elasticsearch/spliter.go
  backend/plugin/db/elasticsearch/spliter_test.go
  backend/plugin/parser/elasticsearch/parser.go
  backend/plugin/parser/elasticsearch/parser_test.go
  backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
  go.mod
  go.sum
Labels: cla-signed

#15750 chore(sql-editor): do not open new tab for single clicking
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
Labels: cla-signed

#15751 chore: fetch issue related databases per page
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/Plan/logic/plan.ts
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/views/project/ProjectDatabaseGroupDetail.vue
Labels: cla-signed

#15752 refactor: schedule auto rollout
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#15754 feat(diagnose): diagnose for es
  backend/plugin/db/elasticsearch/elasticsearch.go
  backend/plugin/parser/elasticsearch/diagnose.go
  backend/plugin/parser/elasticsearch/parser.go
  backend/plugin/parser/elasticsearch/parser_test.go
  backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
  backend/server/ultimate.go
Labels: cla-signed

#15756 chore: improve i18n
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15757 feat: hard delete environment
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15758 feat: task filters
  frontend/src/components/IssueV1/components/SQLCheckSection/AdviceStatusIcon.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/context.ts
  frontend/src/components/IssueV1/components/StageSection/StageSummary.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/filter.ts
  frontend/src/components/IssueV1/components/TaskStatusIconV1.vue
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/types/v1/instance.ts
Labels: cla-signed

#15759 chore: optimize the advanced search for remote fetch
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/AdvancedSearch/ScopeMenu.vue
  frontend/src/components/AdvancedSearch/ValueMenu.vue
  frontend/src/components/AdvancedSearch/types.ts
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/IssueV1/components/IssueSearch/useIssueSearchScopeOptions.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15760 chore(issue): current task view
  frontend/src/components/IssueV1/components/SQLCheckSection/AdviceStatusIcon.vue
  frontend/src/components/IssueV1/components/TaskListSection/CurrentTaskSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15761 feat: impl environment setting
  backend/api/v1/setting_service.go
  backend/legacyapi/setting.go
  backend/server/init.go
  backend/store/setting.go
Labels: cla-signed

#15763 feat(elastic): elastic search statement range
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/base/interface.go
  backend/plugin/parser/elasticsearch/parser.go
  backend/plugin/parser/elasticsearch/statement_ranges.go
  backend/plugin/parser/elasticsearch/statement_ranges_test.go
  backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
  backend/plugin/parser/elasticsearch/test-data/statement-ranges.yaml
Labels: cla-signed

#15764 chore: allow export should set in each result set
  backend/api/v1/audit.go
  backend/api/v1/sql_service.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_review_test.go
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/sqlEditor/webTerminal.ts
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/utils/iam/permission-utils.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#15767 fix: depot build
  .github/workflows/build-push-release-image.yml
Labels: cla-signed

#15768 fix: reset instance assignment state
  frontend/src/components/InstanceAssignment.vue
Labels: cla-signed

#15769 chore: allow no member and no owner in group
  frontend/src/components/User/Settings/CreateGroupDrawer.vue
Labels: cla-signed

#15770 chore: remove project filter
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
Labels: cla-signed

#15771 fix: props change
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepForm.vue
Labels: cla-signed

#15773 fix: engine checks for backup
  backend/runner/taskrun/data_update_executor.go
Labels: cla-signed

#15777 chore: remove depenedent column from schema pane
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
Labels: cla-signed

#15779 chore: use bytebaseci user
  .github/workflows/build-push-release-image.yml
Labels: cla-signed

#15765 chore: trino MVP
  backend/api/v1/common.go
  backend/plugin/db/trino/dump.go
  backend/plugin/db/trino/sync.go
  backend/plugin/db/trino/trino.go
  backend/server/ultimate.go
  frontend/src/assets/db/trino.svg
  frontend/src/components/InstanceForm/constants.ts
  frontend/src/utils/v1/instance.ts
  go.mod
  go.sum
Labels: cla-signed

#15781 chore: code quality json
  action/gitlab.go
  action/main.go
Labels: cla-signed

#15778 refactor: remove part of empty id
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDashboard/NavBar.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/release.ts
  frontend/src/types/v1/group.ts
  frontend/src/types/v1/projectWebhook.ts
  frontend/src/utils/v1/changelog.ts
Labels: cla-signed

#15783 feat: update environment_store to use environmentSetting
  frontend/src/store/modules/v1/environment.ts
  frontend/src/views/EnvironmentDetail.vue
Labels: cla-signed

#15784 chore: default expand all
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/types/sqlEditor/tree.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTags.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
Labels: cla-signed

#15787 fix: fix the position in monaco decoration
  frontend/src/components/MonacoEditor/composables/useAdvices.ts
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/utils/v1/position.ts
Labels: cla-signed

#15790 chore: update delete environment i18n
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15786 chore: less conversion
  action/api.go
Labels: cla-signed

#15791 chore: tweak data table style in project dashboard
  frontend/src/views/ProjectDashboard.vue
Labels: cla-signed

#15792 refactor: move pg statement ranges into base package
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/pg/statement_ranges.go
Labels: cla-signed

#15793 chore(proto): batch get databases
  backend/api/v1/acl.go
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#15795 chore: get menu actions by connection
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTableColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ExternalTablesPanel/ExternalTablesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/FunctionsPanel/FunctionsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/InfoPanel/InfoPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/PackagesPanel/PackagesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/Panels.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ProceduresPanel/ProceduresTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/SequencesPanel/SequencesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/ForeignKeysTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/IndexesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/PartitionsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TableDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TablesTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/TablesPanel/TriggersTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DependencyColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewDetail.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/common/SchemaSelectToolbar.vue
  frontend/src/views/sql-editor/EditorPanel/common/common.ts
  frontend/src/views/sql-editor/EditorPanel/context/viewState.tsx
  frontend/src/views/sql-editor/EditorPanel/index.ts
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
Labels: cla-signed

#15796 fix: potential nil panic
  backend/api/v1/query_result_masker.go
  backend/api/v1/setting_service.go
  backend/api/v1/sql_service.go
  backend/component/masker/masker.go
Labels: cla-signed

#15797 fix: zero index
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
Labels: cla-signed

#15800 chore: drifted proto
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#15799 refactor: database tree in aside panel
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/store/modules/v1/dbSchema.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ColumnInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/CommonText.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ExternalTableInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TableInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/TablePartitionInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/ViewInfo.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/hover-state.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ColumnNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DependencyColumnNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DummyNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ExternalTableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ForeignKeyNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/FunctionNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/IndexNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PackageNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/PartitionTableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ProcedureNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SchemaNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/SequenceNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TableNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TextNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/TriggerNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/ViewNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/click.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/tree.ts
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#15802 chore(action): azure devops
  action/azure_devops.go
  action/main.go
Labels: cla-signed

#15803 chore: set drifted
  backend/api/v1/database_service.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#15801 chore: always show the classification config
  frontend/src/components/ColumnDataTable/ClassificationCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
  frontend/src/components/SchemaEditorLite/context/index.ts
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
Labels: cla-signed

#15804 chore(action): code position for azure devops
  action/azure_devops.go
Labels: cla-signed

#15805 chore: remove anomaly center
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
  frontend/src/components/AnomalyCenter/AnomalyTable.vue
  frontend/src/components/AnomalyCenter/DatabaseSchemaDriftAnomalyModal.vue
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/ProjectAnomalyCenterDashboard.vue
Labels: cla-signed

#15806 fix: lint
  .github/workflows/backend-tests-default.yml
  .github/workflows/backend-tests.yml
  action/azure_devops.go
  action/main.go
Labels: cla-signed

#15809 chore: empty table engine
  backend/plugin/schema/mysql/get_database_definition.go
Labels: cla-signed, backport release/3.5.2

#15814 chore: update docs link
  frontend/public/help/en/help.instance.md
  frontend/public/help/ja/help.instance.md
  frontend/public/help/zh/help.instance.md
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
Labels: cla-signed

#15813 chore: show schema drift alert in database detail
  frontend/src/bbkit/BBAttention.vue
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/cells/DatabaseNameCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#15811 fix: limit the role expire time by setting
  frontend/src/components/ExpirationSelector.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
Labels: cla-signed

#15815 chore: support advanced search for database resource selector
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
Labels: cla-signed

#15817 chore: create bb report
  action/bitbucket.go
  action/main.go
Labels: cla-signed

#15816 chore: deprecate anomaly
  README.md
  backend/api/lsp/utils_test.go
  backend/api/v1/anomaly_service.go
  backend/api/v1/database_service.go
  backend/base/anomaly.go
  backend/migrator/migration/3.6/0000##deprecate_anomaly.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/schemasync/syncer.go
  backend/server/grpc_routes.go
  backend/store/anomaly.go
  docs/assets/anomaly-center.webp
  frontend/public/help/routeMapList.json
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/grpcweb/index.ts
  frontend/src/grpcweb/methods.ts
  frontend/src/store/modules/v1/anomaly.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/types/anomaly.ts
  frontend/src/types/index.ts
  frontend/src/types/proto/store/anomaly.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/tailwind.config.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/anomaly.pb.go
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/anomaly_service.pb.gw.go
  proto/generated-go/v1/anomaly_service_grpc.pb.go
  proto/store/anomaly.proto
  proto/v1/anomaly_service.proto
Labels: cla-signed

#15820 fix: sql
  backend/migrator/migration/3.6/0001##move_environment_to_setting.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#15819 refactor: correct position step 2
  backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/mysql/advisor_naming_identifier_no_keyword.go
  backend/plugin/advisor/mysql/advisor_online_migration.go
  backend/plugin/advisor/mysql/test/naming_identifier_no_keyword.yaml
  backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/advisor_statement_check_set_role_variable.go
  backend/plugin/advisor/pg/test/statement_check_set_role_variable.yaml
  backend/plugin/advisor/tidb/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/utils.go
Labels: cla-signed

#15821 feat: check environments used by databases
  backend/api/v1/setting_service.go
  backend/store/environment.go
Labels: cla-signed

#15823 fix: custom iam for create database group method
  backend/api/v1/database_group_service.go
  backend/api/v1/database_service.go
  backend/api/v1/group_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/user_service.go
  backend/api/v1/worksheet_service.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/v1/database_group_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_group_service.pb.go
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/database_group_service.proto
  proto/v1/instance_service.proto
Labels: cla-signed

#15825 chore: detailed pg error on startup
  backend/bin/server/cmd/root.go
  go.mod
  go.sum
Labels: cla-signed

#15826 feat: use bb.settings.* perms for environment setting
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/components/Quickstart.vue
  frontend/src/components/v2/ResourceOccupiedModal/useResourceByName.ts
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceSetting.ts
  frontend/src/router/sqlEditor.ts
  frontend/src/types/iam/permission.ts
  frontend/src/views/Archive.vue
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
Labels: cla-signed

#15827 chore: remove bb.environments.* perms from role
  backend/migrator/migration/3.6/0002##remove_environment_perms.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#15828 fix: sql
  backend/migrator/migration/3.6/0001##move_environment_to_setting.sql
Labels: cla-signed

#15831 feat: mongodb support extra parameters
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15833 fix: instance environment table
  frontend/src/store/modules/v1/environment.ts
Labels: cla-signed

#15834 fix: sync oracle
  backend/plugin/db/oracle/sync.go
  backend/plugin/schema/oracle/get_database_definition.go
Labels: backport release/3.5.1, cla-signed, backport release/3.5.2

#15837 chore: early close
  backend/plugin/db/tidb/dump.go
Labels: cla-signed

#15840 chore: fix readme markdown
  README.md
  docs/assets/grant-access.webp
Labels: cla-signed

#15782 chore: fix trino db-sync
  backend/plugin/db/trino/dump.go
  backend/plugin/db/trino/sync.go
  backend/plugin/db/trino/trino.go
  backend/plugin/schema/trino/get_database_definition.go
  backend/plugin/schema/trino/get_database_definition_test.go
  backend/server/ultimate.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15842 chore: add CLAUDE.md
  CLAUDE.md
Labels: cla-signed

#15841 chore: bitbucket risk report
  action/bitbucket.go
  action/gitlab.go
Labels: cla-signed

#15845 chore: minor updates
  frontend/src/components/Member/MemberDataTable/cells/UserRolesCell.vue
  frontend/src/components/Quickstart.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserRolesCell.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/IssueLayout.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
Labels: cla-signed

#15847 feat: action write github annotation
  action/github.go
  action/main.go
Labels: cla-signed

#15848 fix: nil optional access check
  backend/api/v1/sql_service.go
Labels: backport release/3.5.2

#15843 chore: idp hard-deletion
  backend/api/v1/idp_service.go
  backend/api/v1/user_service.go
  backend/migrator/migration/3.6/0003##idp_deleted.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/idp.go
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/idp.ts
  frontend/src/store/modules/v1/environment.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/views/Archive.vue
  frontend/src/views/SettingWorkspaceSSODetail.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/idp_service.pb.go
  proto/generated-go/v1/idp_service.pb.gw.go
  proto/generated-go/v1/idp_service_grpc.pb.go
  proto/v1/idp_service.proto
Labels: cla-signed

#15850 chore: deprecate GroupValue in the approval node in the frontend
  backend/api/v1/issue_service_convert.go
  backend/api/v1/issue_service_test.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/RoleSelect.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/logic/validate.ts
  frontend/src/components/IssueV1/logic/review.ts
  frontend/src/components/v2/Select/RoleSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/utils/workspaceApprovalSetting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/issue_service.pb.go
  proto/v1/issue_service.proto
Labels: cla-signed

#15851 fix: i18n key
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed, backport release/3.5.2

#15853 chore: update auth context
  frontend/src/App.vue
  frontend/src/AuthContext.vue
  frontend/src/components/PasswordSigninForm.vue
  frontend/src/components/v2/Model/PagedTable.vue
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/auth.ts
  frontend/src/views/auth/SigninModal.vue
Labels: cla-signed

#15855 fix: fetch issue database
  frontend/src/store/modules/v1/experimental-issue.ts
Labels: cla-signed, backport release/3.5.2

#15852 fix: pg date infinity
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/risingwave/query.go
Labels: cla-signed

#15858 chore: add auth check timer
  frontend/src/AuthContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/auth.ts
  frontend/src/utils/auth.ts
  frontend/src/views/auth/SigninModal.vue
Labels: cla-signed

#15857 refactor: correct parse syntax error position
  backend/api/v1/sql_service.go
  backend/common/position.go
  backend/common/position_test.go
  backend/component/sheet/sheet.go
  backend/plugin/parser/base/base.go
  backend/plugin/parser/base/diagnose.go
  backend/plugin/parser/bigquery/bigquery.go
  backend/plugin/parser/bigquery/dignose.go
  backend/plugin/parser/bigquery/query_span_test.go
  backend/plugin/parser/cosmosdb/cosmosdb.go
  backend/plugin/parser/elasticsearch/diagnose.go
  backend/plugin/parser/elasticsearch/parser.go
  backend/plugin/parser/elasticsearch/test-data/parse-elasticsearch-rest.yaml
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/mysql/diagnose.go
  backend/plugin/parser/mysql/mysql.go
  backend/plugin/parser/mysql/split.go
  backend/plugin/parser/partiql/completion.go
  backend/plugin/parser/partiql/partiql.go
  backend/plugin/parser/partiql/split.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/pg/diagnose.go
  backend/plugin/parser/pg/pg.go
  backend/plugin/parser/pg/pg_test.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/pg/split.go
  backend/plugin/parser/plsql/completion.go
  backend/plugin/parser/plsql/diagnose.go
  backend/plugin/parser/plsql/plsql.go
  backend/plugin/parser/plsql/plsql_test.go
  backend/plugin/parser/snowflake/diagnose.go
  backend/plugin/parser/snowflake/snowflake.go
  backend/plugin/parser/snowflake/snowflake_test.go
  backend/plugin/parser/spanner/dignose.go
  backend/plugin/parser/spanner/query_span_test.go
  backend/plugin/parser/spanner/spanner.go
  backend/plugin/parser/tidb/tidb.go
  backend/plugin/parser/tidb/tidb_test.go
  backend/plugin/parser/tsql/completion.go
  backend/plugin/parser/tsql/diagnose.go
  backend/plugin/parser/tsql/split.go
  backend/plugin/parser/tsql/tsql.go
Labels: cla-signed

#15859 chore: read command for redis and better error message
  backend/api/v1/error.go
  backend/api/v1/sql_service.go
  backend/plugin/parser/redis/query.go
  backend/plugin/parser/redis/query_test.go
Labels: cla-signed

#15860 refactor: less storepb position identifier usage
  backend/component/sheet/sheet.go
Labels: cla-signed

#15861 fix: hide intro if no required data
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/Quickstart.vue
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/worksheet.ts
Labels: cla-signed

#15862 feat: action github create comment for sql review results
  action/github.go
  action/github/api.go
  action/github/github.go
  action/main.go
  go.mod
  go.sum
Labels: cla-signed

#15863 chore: P branch 197
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/issue_service_test.go
  backend/component/webhook/manager.go
  backend/migrator/migration/3.6/0004##deprecate_approval_node_group_value.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/wrappers.ts
  frontend/src/types/proto/store/approval.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/approval.pb.go
  proto/store/approval.proto
Labels: cla-signed

#15864 chore: delete sso i18n update
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15865 chore: upgrade golang golangci-lint version
  .github/workflows/backend-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test_link.yml
  go.mod
  scripts/Dockerfile
  scripts/Dockerfile.action
  scripts/Dockerfile.aws
Labels: cla-signed

#15868 chore: use alpine image for xz
  .github/workflows/frontend-tests.yml
  frontend/package.json
  scripts/Dockerfile
  scripts/Dockerfile.aws
Labels: cla-signed

#15869 chore: simple-gcc
  scripts/Dockerfile
  scripts/Dockerfile.aws
Labels: cla-signed

#15872 chore: no console & no debugger
  frontend/eslint.config.mjs
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
Labels: cla-signed

#15873 fix: block creating issues
  backend/api/v1/release_service_check.go
Labels: cla-signed, backport release/3.5.2

#15877 feat: get pr number from event payload
  action/github/github.go
Labels: cla-signed

#15878 chore: check event name
  action/github/github.go
Labels: cla-signed

#15879 chore: cleanup environment archive/restore
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/views/EnvironmentDetail.vue
Labels: cla-signed

#15881 fix: error
  action/github/github.go
Labels: cla-signed

#15880 fix: ignore column in FROM clause
  backend/plugin/parser/tsql/completion.go
  backend/plugin/parser/tsql/test-data/test_completion.yaml
Labels: cla-signed

#15883 chore: update go.mod with trino-parser
  backend/plugin/parser/trino/trino.go
  go.mod
  go.sum
Labels: cla-signed

#15885 chore: add explain query to mssql
  CLAUDE.md
  backend/plugin/db/mssql/mssql.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15888 chore: update version
  scripts/VERSION
Labels: cla-signed

#15889 fix: invalid environment name
  frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/types/v1/environment.ts
  frontend/src/views/InstanceDetail.vue
Labels: cla-signed

#15890 fix: engineSupportCreateDatabase
  backend/base/engine.go
  backend/runner/taskrun/database_create_executor.go
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#15891 fix: infinite update for issue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/logic/poll.ts
Labels: cla-signed, backport release/3.5.2

#15893 chore: exhaustive switch case
  backend/base/engine.go
Labels: cla-signed

#15895 chore: reduce get schema request
  frontend/src/components/DatabaseDetail/SchemaDiagramButton.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
Labels: cla-signed

#15896 feat: cassandra execute
  backend/plugin/db/cassandra/cassandra.go
Labels: cla-signed

#15897 chore: batch sync databases asynchronously
  backend/api/v1/database_service.go
  backend/runner/schemasync/syncer.go
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/store/modules/v1/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/database_service.pb.gw.go
  proto/generated-go/v1/database_service_grpc.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#15898 chore: use alpine
  backend/server/ultimate_linux.go
  scripts/Dockerfile
  scripts/Dockerfile.aws
Labels: cla-signed

#15899 chore: split demo image build
  .github/workflows/build-push-release-image.yml
  .github/workflows/docker-tag-latest.yml
Labels: cla-signed

#15900 chore: use UpdateDatabase to resolve drifted
  frontend/src/components/Database/DatabaseChangelogPanel.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/issue/template.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#15902 feat: accept both canonical and relaxed mongodb extended json format
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/mongodb_test.go
Labels: cla-signed

#15901 fix: remove condition from binding
  backend/api/v1/project_service.go
  backend/api/v1/project_service_test.go
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/utils/issue/cel.ts
Labels: cla-signed

#15903 chore: add drifted filter to listing database
  backend/api/v1/database_service.go
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/database.ts
  frontend/src/utils/v1/advanced-search/common.ts
Labels: cla-signed

#15905 chore: bump mongodb driver to v2
  backend/plugin/db/mongodb/mongodb.go
  backend/plugin/db/mongodb/role.go
  backend/plugin/db/mongodb/sync.go
  go.mod
  go.sum
Labels: cla-signed

#15906 chore: show schema drifted warning before creating issue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15907 fix: delete environment
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/router/dashboard/environmentV1.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
Labels: cla-signed
