Repository bytebase/bytebase, pull requests merged in 2025-08, with the labels that each got.

#16985 chore: add aws-iam via OpenSearch-go-client
  backend/plugin/db/elasticsearch/elasticsearch.go
  backend/plugin/db/elasticsearch/role.go
  backend/plugin/db/elasticsearch/sync.go
  frontend/src/components/InstanceForm/DataSourceSection/DataSourceForm.vue
  go.mod
  go.sum
Labels: cla-signed

#16987 fix(mysql, tidb): remove redundant ON UPDATE clause from column definitions
  backend/plugin/schema/mysql/get_database_definition.go
  backend/plugin/schema/tidb/get_database_definition.go
Labels: cla-signed

#16991 feat(proto): storepb task type SDL
  backend/generated-go/store/task.pb.go
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/store/store/task.proto
Labels: cla-signed

#16990 feat(proto): search releases
  backend/generated-go/v1/release_service.pb.go
  backend/generated-go/v1/release_service.pb.gw.go
  backend/generated-go/v1/release_service_grpc.pb.go
  backend/generated-go/v1/v1connect/release_service.connect.go
  frontend/src/types/proto-es/v1/release_service_pb.d.ts
  frontend/src/types/proto-es/v1/release_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/release_service.proto
Labels: cla-signed

#16992 fix: databricks has schema property
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#17006 feat: impl search releases
  backend/api/v1/release_service.go
  backend/generated-go/v1/release_service.pb.go
  backend/store/release.go
  frontend/src/types/proto-es/v1/release_service_pb.d.ts
  frontend/src/types/proto-es/v1/release_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/release_service.proto
Labels: cla-signed

#17013 fix: rebuild pnpm-lock
  frontend/pnpm-lock.yaml
Labels: cla-signed

#17011 fix: pass computed ref to useSpecSheet hook
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/useSpecSheet.ts
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
Labels: cla-signed

#17012 feat(proto): release file type declarative
  backend/generated-go/store/release.pb.go
  backend/generated-go/v1/release_service.pb.go
  frontend/src/types/proto-es/v1/release_service_pb.d.ts
  frontend/src/types/proto-es/v1/release_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/release.proto
  proto/v1/v1/release_service.proto
Labels: cla-signed

#17014 refactor: remove driver.MigrationType
  backend/plugin/db/driver.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_executor.go
Labels: cla-signed

#17029 chore: optimize tab
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/types/dataSource.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/SaveSheetModal.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/StandardPanel.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue
  frontend/src/views/sql-editor/EditorPanel/Welcome/Welcome.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#17033 chore: update log msg
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#17034 fix: missing convert
  backend/api/v1/issue_service_convert.go
Labels: cla-signed

#17040 fix: handle scheduler states revertings
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#17042 fix: skip CONCURRENTLY check for indexes on newly created tables
  backend/plugin/advisor/pg/advisor_column_maximum_character_length.go
  backend/plugin/advisor/pg/advisor_index_create_concurrently.go
  backend/plugin/advisor/pg/test/index_create_concurrently.yaml
  backend/plugin/advisor/pg/utils.go
Labels: cla-signed

#17044 feat: sync tidb generated column
  backend/plugin/db/tidb/sync.go
Labels: cla-signed

#17046 chore: show running status for plan check runs
  backend/api/v1/rollout_service_converter.go
  backend/generated-go/v1/plan_service.pb.go
  backend/store/plan.go
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/proto-es/v1/plan_service_pb.d.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#17047 fix(parser): initialize sourceColumnsInFunction in subquery extractor
  backend/plugin/parser/pg/query_span_extractor.go
Labels: cla-signed

#17067 chore: update typescript to 5.9.2 and fix arraybuffer compatibility
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/DataExportButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
  frontend/src/store/modules/v1/auditLog.ts
Labels: cla-signed

#17070 fix: redirect to correct url
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#17071 fix: filter users in the project
  backend/store/principal.go
Labels: cla-signed

#17073 fix: new created issue's title and description
  backend/store/issue.go
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
Labels: cla-signed

#17076 chore: update
  backend/api/v1/database_service.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/executor.go
  backend/store/database.go
Labels: cla-signed

#17075 chore: add webhook tests
  backend/tests/webhook_test.go
Labels: cla-signed

#17078 feat: convert changelog type from task type in executor
  backend/api/v1/database_service_changelog.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#17077 chore(helm-charts): remove tolerance for all taint
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#17068 fix(executor): update task type handling for database tasks
  backend/runner/taskrun/executor.go
  backend/tests/schema_update_test.go
Labels: cla-signed, backport release/3.8.0

#17080 fix: dml task dumping
  backend/plugin/db/driver.go
  backend/runner/taskrun/executor.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#17081 refactor: prefer proto.CloneOf
  backend/api/v1/audit.go
  backend/api/v1/instance_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/component/masker/masker.go
  backend/runner/schemasync/syncer.go
  backend/store/instance.go
Labels: cla-signed

#17083 chore: unify plan check run status count display across components
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
  frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanCheckStatusCount.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/logic/index.ts
  frontend/src/components/Plan/logic/usePlanCheckStatus.ts
Labels: cla-signed

#17087 feat: handle revision type in begin migration
  backend/api/v1/release_service_check.go
  backend/common/util.go
  backend/runner/taskrun/executor.go
  backend/store/revision.go
Labels: cla-signed

#17090 fix: engine sql
  backend/migrator/migration/3.9/0009##cleanup_deprecated_engines.sql
Labels: cla-signed

#17091 feat: handle sdl case in get rollout from plan
  backend/api/v1/release_service.go
  backend/api/v1/release_service_check.go
  backend/api/v1/rollout_service_task.go
  backend/runner/taskrun/executor.go
  backend/store/model/version.go
  backend/store/revision.go
  backend/tests/action_test.go
Labels: cla-signed

#17092 chore: improve task run time display in rollout views
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
Labels: cla-signed

#17094 chore: update comment
  backend/api/v1/plan_service_plan_check.go
Labels: cla-signed

#17096 fix: action targets input validation
  action/command/root.go
  action/common/resource_name.go
  backend/tests/action_test.go
Labels: cla-signed

#17098 chore: disallow create plan check runs for plan with release
  backend/api/v1/plan_service.go
  backend/api/v1/plan_service_plan_check.go
Labels: cla-signed

#17099 chore: hide plan check runs for specs with release
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/logic/usePlanCheckStatus.ts
Labels: cla-signed

#17104 fix: no dump means no dump
  backend/runner/taskrun/executor.go
Labels: cla-signed

#17108 chore: README broken links
  README.md
Labels: cla-signed

#17115 feat: prevent navigation when editing SQL statements in plan editor
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/useEditorState.ts
  frontend/src/components/Plan/logic/useNavigationGuard.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/CICDLayout.vue
Labels: cla-signed

#17119 fix: component re-render cause the state reset
  frontend/src/components/ExprEditor/ConditionGroup.vue
Labels: cla-signed

#17122 chore: update ux for query result limit
  frontend/src/components/GrantRequestPanel/MaxRowCountSelect.vue
  frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/setting.ts
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
  frontend/src/views/sql-editor/EditorCommon/ResultLimitSelect.vue
Labels: cla-signed

#17123 feat(action): use release digest to deduplicate
  action/command/api.go
  action/command/check.go
  action/command/file.go
  action/command/rollout.go
  backend/tests/action_test.go
Labels: cla-signed

#17128 chore: ignore update ElasticSearch driver
  renovate.json
Labels: cla-signed

#17129 refactor: remove deprecated --pg flag
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
Labels: cla-signed, breaking

#17133 chore: use linear email to triage support tickets
  README.md
Labels: cla-signed

#17131 feat: show SDL for task badge
  frontend/src/components/IssueV1/logic/rollout.ts
Labels: cla-signed

#17134 feat: use execFunc for sdl task executor
  backend/runner/taskrun/schema_update_sdl_executor.go
Labels: cla-signed

#17132 feat: add forced database connection cleanup after timeout
  backend/store/db_connection.go
Labels: cla-signed

#17136 chore: add navigation from tasks to related spec changes
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/Plan/logic/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/issue/plan.ts
Labels: cla-signed

#17140 fix: i18n
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DetailCell/AffectedRowsCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17142 refactor: remove --disable-sample flag and create SampleInstanceManager component
  backend/api/v1/actuator_service.go
  backend/api/v1/instance_service.go
  backend/bin/server/cmd/profile.go
  backend/bin/server/cmd/root.go
  backend/component/config/profile.go
  backend/component/sampleinstance/manager.go
  backend/server/grpc_routes.go
  backend/server/server.go
  backend/store/instance.go
  backend/tests/tests.go
  frontend/src/views/Setup/AdminSetup.vue
Labels: cla-signed

#17145 chore: remove --disable-sample and --disable-metric flags
  README.md
  docs/bytebase-1.1.1.tgz
  docs/dev-guide.md
  docs/index.yaml
  helm-charts/bytebase/README.md
  helm-charts/bytebase/templates/statefulset.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#17148 chore: remove .claude folder and lint command
  .claude/commands/lint.md
Labels: cla-signed

#17149 chore: debug
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed, backport release/3.9.0

#17152 chore: downgrade es
  go.mod
  go.sum
Labels: cla-signed

#17153 fix: prevent nil pointer panic in sample instance manager shutdown
  backend/server/server.go
Labels: cla-signed

#17155 fix: search audit log by level
  frontend/src/store/modules/v1/auditLog.ts
Labels: cla-signed

#17157 feat: validate sql for redshift
  backend/plugin/db/redshift/redshift.go
  backend/plugin/parser/pg/query.go
  backend/plugin/parser/redshift/query.go
  backend/plugin/parser/redshift/query_test.go
Labels: cla-signed

#17158 chore: handle null environment
  frontend/src/bbkit/BBAlert.vue
  frontend/src/bbkit/BBButtonConfirm.vue
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/AdvancedSearch/ScopeTags.vue
  frontend/src/components/AdvancedSearch/ValueMenu.vue
  frontend/src/components/AdvancedSearch/types.ts
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/components/Rollout/RolloutDataTable.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/grpcweb/methods.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/instance.ts
  frontend/src/utils/v1/environment.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/tree.ts
Labels: cla-signed

#17160 fix: only for select add limit
  backend/plugin/db/oracle/query.go
Labels: cla-signed

#17161 refactor: oracle add limit
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/query.go
  backend/plugin/db/oracle/query_test.go
Labels: cla-signed

#17164 fix: index name
  backend/migrator/migration/LATEST.sql
Labels: cla-signed

#17166 fix: reset search_path after loading demo data to prevent migration errors
  backend/demo/demo.go
Labels: cla-signed

#17169 feat(action): supprot declarative
  action/command/file.go
  action/command/rollout.go
  action/command/root.go
  action/world/world.go
  backend/runner/taskrun/executor.go
  backend/store/model/version.go
  backend/tests/action_test.go
Labels: cla-signed

#17171 chore: use environment name component
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/StageName.vue
  frontend/src/components/Plan/components/RolloutView/StageView.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/views/project/RolloutDetailLayout.vue
Labels: cla-signed

#17177 fix: load groups before workspace IAM policy to resolve dependencies
  frontend/src/AuthContext.vue
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/index.vue
  frontend/src/layouts/SQLEditorLayout.vue
  frontend/src/store/modules/v1/group.ts
Labels: cla-signed

#17180 fix: index compare for mysql
  backend/plugin/schema/mysql/get_database_metadata.go
  backend/plugin/schema/mysql/get_database_metadata_testcontainer_test.go
Labels: cla-signed

#17184 feat: implement syntax check for sdl
  backend/api/v1/release_service_check.go
Labels: cla-signed

#17187 fix: group table and selectors showing only partial groups
  frontend/src/AuthContext.vue
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/v2/Select/GroupSelect.vue
  frontend/src/store/modules/v1/group.ts
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#17185 fix: declarative version check, disallow equal or less versions.
  backend/api/v1/release_service_check.go
  backend/api/v1/rollout_service_task.go
  backend/runner/taskrun/executor.go
  backend/store/model/version.go
  backend/tests/action_test.go
Labels: cla-signed

#17194 fix: password rotation checks
  backend/api/v1/auth_service.go
Labels: cla-signed

#17191 chore: update release validation
  backend/api/v1/release_service.go
Labels: cla-signed

#17192 chore: move declarative to root
  action/command/check.go
  action/command/file.go
  action/command/rollout.go
  action/command/root.go
  action/world/world.go
Labels: cla-signed

#17195 refactor: router navigation
  frontend/src/AuthContext.vue
  frontend/src/components/ProvideDashboardContext.vue
  frontend/src/router/index.ts
Labels: cla-signed

#17209 chore: update parser dependency
  go.mod
  go.sum
Labels: cla-signed

#17210 fix: get latest taskrun
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
Labels: cla-signed, backport release/3.9.1

#17213 fix: infinite redirect in navigation guard
  frontend/src/router/index.ts
Labels: cla-signed

#17215 feat(UI): show revision type
  frontend/src/components/Revision/RevisionDataTable.vue
Labels: cla-signed

#17217 chore(action): update readme
  action/README.md
Labels: cla-signed

#17218 refactor: simplify Oracle query handling code
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/oracle/query.go
Labels: cla-signed

#17219 feat: support hard-delete the project
  backend/api/v1/project_service.go
  backend/generated-go/v1/project_service.pb.go
  backend/store/project.go
  frontend/src/components/Project/ProjectArchiveRestoreButton.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/store/modules/v1/project.ts
  frontend/src/types/proto-es/v1/project_service_pb.d.ts
  frontend/src/types/proto-es/v1/project_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/project_service.proto
Labels: cla-signed

#17223 fix: handle null environments in rollout UI
  frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/StageView.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/router/dashboard/projectV1.ts
Labels: cla-signed

#17224 refactor: remove pg_query_go usage in sync
  backend/plugin/db/pg/sync.go
  backend/plugin/schema/pg/get_database_metadata_testcontainer_test.go
  backend/tests/syncer_test.go
Labels: cla-signed

#17233 refactor: remove `ComposedRelease` type
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Release/ReleaseDetail/context.ts
  frontend/src/components/Revision/CreateRevisionDrawer.vue
  frontend/src/store/modules/release.ts
  frontend/src/types/release.ts
Labels: cla-signed

#17234 fix: string single quote only for mysql comment in sync
  backend/plugin/db/mysql/sync.go
Labels: cla-signed

#17235 docs: add fish to README.md
  README.md
  docs/assets/change-query-secure-govern.webp
  docs/assets/data-model-v2.webp
  docs/assets/fish.webp
  docs/assets/grant-access.webp
  docs/assets/issue-detail.webp
  docs/assets/org-role-mapping.webp
  docs/assets/product-video-thumbnail.webp
  docs/assets/sql-editor.webp
  docs/assets/sql-review-policy.webp
  docs/assets/techstack.webp
  docs/assets/your-dev-vs-competitor-hitman.webp
Labels: cla-signed

#17236 perf: sql editor (part1)
  backend/api/lsp/fs_handler.go
  backend/api/lsp/handler.go
  backend/api/lsp/performance_optimizer.go
  frontend/src/components/MonacoEditor/composables/useAutoComplete.ts
  frontend/src/components/MonacoEditor/composables/useContent.ts
  frontend/src/components/MonacoEditor/lsp-client.ts
  frontend/src/components/MonacoEditor/text-model.ts
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/utils/performance.ts
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/CompactSQLEditor.vue
Labels: cla-signed

#17238 perf: sql editor (part2)
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/MonacoEditor/composables/useActiveRangeByCursor.ts
  frontend/src/components/MonacoEditor/composables/useSelection.ts
  frontend/src/store/modules/sqlEditor/tab.ts
Labels: cla-signed

#17239 chore: move plan description from sidebar for main view
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/index.ts
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
  frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue
Labels: cla-signed

#17240 fix: UpdatePolicy update mask
  backend/api/v1/org_policy_service.go
  frontend/src/store/modules/v1/policy.ts
Labels: cla-signed, breaking

#17241 chore: add workaround for MySQL 0 time
  backend/plugin/db/mysql/query.go
Labels: cla-signed

#17244 feat: implement direct issue creation from plan without drawer
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/index.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Sidebar/CommonSidebar.vue
  frontend/src/layouts/BodyLayout.vue
Labels: cla-signed

#17252 chore: make declarative flag as experimental
  action/README.md
  action/command/root.go
Labels: cla-signed

#17253 fix: section visibility in plan
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
Labels: cla-signed

#17251 chore: introduce sdl test and fix bugs
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/generate_migration_testcontainer_test.go
  backend/plugin/schema/pg/get_database_metadata.go
  backend/plugin/schema/pg/sdl_validation_testcontainer_test.go
  backend/plugin/schema/pg/view_comparer.go
Labels: cla-signed

#17254 chore(action-image): latest or versioned
  .github/workflows/build-push-action-image.yml
  .github/workflows/docker-tag-latest.yml
Labels: cla-signed

#17256 feat: improve issue detail page UI for better readability
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentSection.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionCreator.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentView.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
Labels: cla-signed

#17260 fix: fk on update/delete options
  backend/plugin/schema/pg/get_database_definition.go
  backend/plugin/schema/pg/get_database_definition_testcontainer_test.go
  backend/plugin/schema/pg/sdl_validation_testcontainer_test.go
Labels: cla-signed

#17259 chore: add description input for plans without issue
  frontend/src/components/Plan/components/HeaderSection/DescriptionInput.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
Labels: cla-signed

#17262 chore: tweak description section styles
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/HeaderSection/DescriptionInput.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckV1Section/SQLCheckV1Section.vue
  frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/StatementSection/StatementSection.vue
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/es-ES.json
  frontend/src/locales/sql-review/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/sql-review/zh-CN.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/vi-VN.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17265 fix: several fix
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/v2/Model/PagedTable.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#17266 chore: support clear environment in instance and database
  frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/layouts/ProjectV1Layout.vue
Labels: cla-signed

#17268 fix: i18n
  frontend/src/locales/en-US.json
Labels: cla-signed

#17269 fix: improve plan spec validation reactivity and auto-enable editing
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/Plan/components/common/validateSpec.ts
Labels: cla-signed

#17263 chore: enhance expression comparer
  backend/plugin/schema/pg/ast/expression_ast.go
  backend/plugin/schema/pg/ast/expression_comparer_production_test.go
  backend/plugin/schema/pg/ast/expression_comparer_strict_test.go
  backend/plugin/schema/pg/ast/expression_normalizer.go
  backend/plugin/schema/pg/ast/expression_parser.go
  backend/plugin/schema/pg/ast/expression_parser_parentheses_test.go
  backend/plugin/schema/pg/ast/expression_visitor.go
  backend/plugin/schema/pg/get_database_metadata.go
  backend/plugin/schema/pg/get_database_metadata_testcontainer_test.go
Labels: cla-signed

#17271 chore: replace all sparkles icon
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#17272 chore(action): wake up cloud
  action/command/root.go
Labels: cla-signed

#17276 feat: implement expression comparison interface and clean up PostgreSQL codebase
  backend/plugin/schema/differ.go
  backend/plugin/schema/expression_comparer.go
  backend/plugin/schema/pg/ast/expression_comparer.go
  backend/plugin/schema/pg/ast/expression_comparer_production_test.go
  backend/plugin/schema/pg/ast/expression_comparer_strict_test.go
  backend/plugin/schema/pg/ast/expression_comparer_test.go
Labels: cla-signed

#17277 fix: resolve race condition in plan creation causing empty statement editor
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/StatementSection/StatementSection.vue
Labels: cla-signed

#17283 feat: implement collapsed view for plan description section
  frontend/src/components/Plan/components/HeaderSection/DescriptionSection.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17284 fix: sql editor initial
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/views/sql-editor/Sheet/context.ts
Labels: cla-signed

#17282 fix(mongodb): fix mongodb collection name contains special characters
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#17281 chore: check sheets for plan check run creates
  backend/api/v1/plan_service_plan_check.go
Labels: cla-signed

#17250 chore: add cassandra data masking
  backend/common/engine.go
  backend/plugin/db/cassandra/sync.go
  backend/plugin/parser/cassandra/query_span.go
  backend/plugin/parser/cassandra/query_span_extractor.go
  backend/plugin/parser/cassandra/query_span_test.go
  backend/plugin/parser/cassandra/split.go
  backend/server/ultimate.go
  frontend/src/components/ColumnDataTable/index.vue
Labels: cla-signed

#17292 chore: go parser dep upgrade
  go.mod
  go.sum
Labels: cla-signed

#17294 feat: improve plan description field UX
  frontend/src/components/Plan/components/HeaderSection/DescriptionSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17295 feat: improve plan detail page description UX
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
Labels: cla-signed

#17296 feat: file type in release view
  frontend/src/components/Plan/components/StatementSection/ReleaseView/ReleaseView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17298 chore: support gemini & claude
  backend/api/v1/sql_service_ai.go
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17301 feat: add issue created comment with editable description
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedComment.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedCommentV1.vue
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
  frontend/src/components/Plan/components/HeaderSection/DescriptionSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DescriptionSection/index.ts
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17302 chore: show environment color
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceV1Table.vue
Labels: cla-signed

#17306 chore: remove `strictProject` field from SQL editor store
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/TabList/TabList.vue
Labels: cla-signed

#17307 chore: remove ComposedTaskRun type
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedCommentV1.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSection.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunTable.vue
  frontend/src/components/Plan/components/SpecDetailView/FailedTaskRunsSection.vue
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/taskRunLog.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/types/v1/issue/rollout.ts
Labels: cla-signed

#17308 chore: fix demo version
  .github/workflows/build-push-demo-image.yml
Labels: cla-signed

#17312 feat: check automatic rollout policy when run tasks
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17316 feat(pg): sync opclass related info
  backend/api/v1/database_converter.go
  backend/generated-go/store/database.pb.go
  backend/generated-go/v1/database_service.pb.go
  backend/plugin/db/pg/sync.go
  backend/tests/syncer_test.go
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/database.proto
  proto/v1/v1/database_service.proto
Labels: cla-signed
