Repository bytebase/bytebase, pull requests merged in 2025-02, with the labels that each got.

#15106 chore: bump pnpm version
  .github/workflows/build-push-ci-image-depot.yml
  .github/workflows/build-push-release-image.yml
  .github/workflows/frontend-tests.yml
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#15108 fix: ux
  frontend/src/components/MonacoEditor/composables/useSelectedContent.ts
  frontend/src/components/SensitiveData/ClassificationView.vue
Labels: cla-signed, backport release/3.3.1

#15111 chore: add target to release check result
  backend/api/v1/release_service.go
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#15112 chore: remove unused check
  backend/server/routers.go
Labels: cla-signed

#15113 chore: fix comment typo
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service_grpc.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#15114 feat(mssql): sync mssql foreign key
  backend/plugin/db/mssql/sync.go
Labels: cla-signed

#15107 chore: add columnType to convertValue; add accuracy to timestamp display
  backend/plugin/db/clickhouse/query.go
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/dm/query.go
  backend/plugin/db/mssql/query.go
  backend/plugin/db/mysql/query.go
  backend/plugin/db/obo/query.go
  backend/plugin/db/oracle/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/risingwave/query.go
  backend/plugin/db/starrocks/query.go
  backend/plugin/db/tidb/query.go
  backend/plugin/db/util/driverutil.go
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#15115 fix: loading
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/store/modules/v1/policy.ts
Labels: cla-signed, backport release/3.3.1

#15117 chore: change date/time output to string
  backend/plugin/db/mssql/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/pg/query_test.go
Labels: cla-signed

#15120 fix(mssql): npe for one table including multiple foreign keys in syncing
  backend/plugin/db/mssql/sync.go
Labels: cla-signed

#15124 feat: support statement report for redshift
  backend/common/util.go
  backend/component/sheet/sheet.go
  backend/plugin/db/redshift/stats.go
  backend/plugin/parser/pg/resource_change.go
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#15125 chore: align table cells for changelog and revision
  frontend/src/components/Changelog/ChangelogDataTable.vue
  frontend/src/components/Revision/RevisionDataTable.vue
Labels: cla-signed

#15127 chore: remove fallback version to changes
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDataTable.vue
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangelogForm.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/Changelist/common.ts
Labels: cla-signed

#15126 chore: optimize pagination UX
  frontend/src/components/AuditLog/AuditLogDataTable.vue
  frontend/src/components/Changelog/ChangelogDataTable.vue
  frontend/src/components/Project/ProjectIssuesPanel.vue
  frontend/src/components/Project/ProjectReleasesPanel.vue
  frontend/src/components/Project/ProjectRolloutsPanel.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/v2/Model/PagedTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/MyIssues.vue
  frontend/src/views/ReviewCenter/index.vue
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed

#15130 chore: 340
  scripts/VERSION
Labels: cla-signed

#15132 chore: rebase latest schema and no owner
  backend/demo/data/default/README.md
  backend/demo/data/default/dump.sql
  backend/demo/demo.go
  backend/server/server.go
Labels: cla-signed

#15135 chore: dev user
  backend/bin/server/cmd/profile_dev.go
Labels: cla-signed

#15136 chore: update demo data for bb user
  backend/demo/data/default/dump.sql
Labels: cla-signed

#15134 feat: Add Vietnamese (vi-VN) translations
  frontend/i18n.ts
  frontend/src/components/ProfileDropdown.vue
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/subscription/vi-VN.json
  frontend/src/locales/vi-VN.json
  frontend/src/plugins/i18n.ts
  frontend/src/views/auth/AuthFooter.vue
Labels: cla-signed

#15137 chore: remove combine latest data
  backend/legacyapi/principal.go
  backend/legacyapi/project.go
  backend/migrator/migration/3.4/0001##cleanup.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migration/LATEST_DATA.sql
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  docs/schema-update-guide.md
Labels: cla-signed

#15138 refactor: instance history
  backend/store/changelog.go
  backend/store/changelog_test.go
  backend/store/instance_change_history.go
Labels: cla-signed

#15139 chore: refactor history
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  backend/plugin/db/sqlite/sqlite_migration_schema.sql
  backend/server/server.go
  backend/store/instance_change_history.go
  docs/README.md
  docs/assets/codereview1.png
  docs/assets/codereview2.png
  docs/assets/data-model-v1.webp
  docs/assets/old-to-new-world.webp
  docs/assets/preview-env1.png
  docs/assets/preview-env2.png
  docs/assets/reset-bytebase-data.png
  docs/assets/sql-editor-admin-mode.webp
  docs/assets/staging-env1.png
  docs/assets/versioncontrol.webp
  docs/design/README.md
  docs/design/assets/code-structure.png
  docs/design/assets/gh-ost-general-flow.png
  docs/design/assets/gh-ost-operation-modes.png
  docs/design/assets/sql-review-overview.webp
  docs/design/db-plugin-development-guide.md
  docs/design/gh-ost-integration.md
  docs/design/pipeline.md
  docs/design/pitr-mysql.md
  docs/design/source-code-tour.snb.md
  docs/design/sql-review-source-code-tour.snb.md
  docs/design/tenancy.md
  docs/testing.md
  docs/writing-guide.md
  proto/gen/grpc-doc/index.html
Labels: cla-signed

#15141 chore: clean schema
  backend/api/directory-sync/webhook.go
  backend/api/v1/anomaly_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_group_service.go
  backend/api/v1/environment_service.go
  backend/api/v1/group_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_config_service.go
  backend/api/v1/risk_service.go
  backend/api/v1/role_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/vcs_connector_service.go
  backend/api/v1/vcs_provider_service.go
  backend/api/v1/workspace_service.go
  backend/component/iam/manager.go
  backend/enterprise/plugin/hub/hub.go
  backend/migrator/migration/3.4/0002##less_creator.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/relay/runner.go
  backend/runner/schemasync/syncer.go
  backend/runner/slowquerysync/syncer.go
  backend/server/init.go
  backend/server/onboard.go
  backend/store/anomaly.go
  backend/store/data_source.go
  backend/store/database_group.go
  backend/store/deploy.go
  backend/store/environment.go
  backend/store/external_approval.go
  backend/store/group.go
  backend/store/idp.go
  backend/store/instance.go
  backend/store/issue_comment.go
  backend/store/policy.go
  backend/store/project.go
  backend/store/project_webhook.go
  backend/store/review_config.go
  backend/store/risk.go
  backend/store/role.go
  backend/store/setting.go
  backend/store/slow_query.go
  backend/store/sync_history.go
  backend/store/task_dag.go
  backend/store/vcs_connector.go
  backend/store/vcs_provider.go
  backend/utils/utils.go
Labels: cla-signed

#15143 chore: instance change history schema
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator.go
  backend/store/instance_change_history.go
Labels: cla-signed

#15144 chore: reference c
  backend/migrator/migrator.go
  backend/store/external_approval.go
Labels: cla-signed

#15147 chore: error condition
  backend/migrator/migrator.go
Labels: cla-signed

#15148 chore: retire project's key in frontend
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/KBar/useProjectActions.ts
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Project/ProjectCreatePanel.vue
  frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/database.ts
  frontend/src/utils/v1/project.ts
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  frontend/src/views/ReviewCenter/SQLReviewIssueDataTable/SQLReviewIssueDataTable.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
Labels: cla-signed

#15149 chore: changelist cleanup
  backend/api/v1/changelist_service.go
  backend/migrator/migration/3.4/0002##less_creator.sql
  backend/migrator/migration/LATEST.sql
  backend/store/changelist.go
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDataTable.vue
  frontend/src/types/proto/v1/changelist_service.ts
  frontend/src/types/v1/changelist.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/changelist_service.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/v1/changelist_service.proto
  proto/v1/issue_service.proto
Labels: cla-signed

#15151 chore: less api fields
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/sheet_service.go
  frontend/src/types/proto/v1/rollout_service.ts
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/generated-go/v1/sheet_service.pb.go
  proto/v1/rollout_service.proto
  proto/v1/sheet_service.proto
Labels: cla-signed

#15153 chore: add project column to issue table
  frontend/src/components/IssueV1/components/IssueTableV1.vue
Labels: cla-signed

#15154 feat: check sensitive predicate columns for MSSQL
  backend/api/v1/predicate_columns_check.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#15156 fix: missing user in login audit
  backend/api/v1/audit.go
Labels: cla-signed

#15152 chore: less creator 2
  backend/api/directory-sync/webhook.go
  backend/api/gitops/webhook.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_changelog.go
  backend/api/v1/database_service_revision.go
  backend/api/v1/instance_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/plan_service_plan_check.go
  backend/api/v1/project_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/worksheet_service.go
  backend/component/ghost/config.go
  backend/component/webhook/manager.go
  backend/migrator/migration/3.4/0004##less_creator_2.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/plugin/db/driver.go
  backend/runner/approval/runner.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/plancheck/scheduler.go
  backend/runner/relay/runner.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/data_export_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_ghost_sync_executor.go
  backend/server/init.go
  backend/server/onboard.go
  backend/store/changelog.go
  backend/store/database.go
  backend/store/db_schema.go
  backend/store/issue.go
  backend/store/pipeline.go
  backend/store/plan.go
  backend/store/plan_check_run.go
  backend/store/principal.go
  backend/store/revision.go
  backend/store/sheet.go
  backend/store/stage.go
  backend/store/task.go
  backend/store/task_run.go
  backend/store/worksheet.go
  frontend/src/components/Changelog/ChangelogDataTable.vue
  frontend/src/components/Changelog/ChangelogDetail.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/v1/database_service.proto
Labels: cla-signed

#15155 fix: close conn
  backend/migrator/migrator.go
Labels: cla-signed

#15158 fix: batch update db
  backend/store/database.go
Labels: cla-signed

#15159 fix: migration
  backend/migrator/migration/3.4/0002##less_creator.sql
  backend/migrator/migration/3.4/0004##less_creator_2.sql
Labels: cla-signed

#15160 chore: index advisor and share sql free
  backend/legacyapi/plan.go
Labels: cla-signed

#15163 chore: update go.mod
  go.mod
  go.sum
Labels: cla-signed

#15161 chore: remove double quotes from label
  backend/api/lsp/completion.go
Labels: cla-signed

#15162 chore: filter SET commands from creating a new tab
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#15164 fix: visualize explain cannot handle multiple query results
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#15165 chore: several updates
  backend/api/v1/auth_service.go
  backend/api/v1/setting_service.go
  backend/enterprise/api/plan.yaml
  backend/legacyapi/plan.go
  backend/store/instance.go
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
  frontend/src/locales/dynamic/en-US.json
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/subscription.ts
  frontend/src/types/plan.ts
Labels: cla-signed

#15166 chore: created_at
  backend/migrator/migration/3.4/0005##created_at.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/changelog.go
  backend/store/database.go
  backend/store/policy.go
  backend/store/release.go
  backend/store/revision.go
  backend/store/sync_history.go
  backend/store/task_run_log.go
Labels: cla-signed

#15167 feat: implement backup dml for mssql v2
  backend/plugin/advisor/mssql/advisor_builtin_prior_backup_check.go
  backend/plugin/parser/tsql/backup.go
  backend/plugin/parser/tsql/test-data/test_backup.yaml
Labels: cla-signed

#15168 feat: statement types for mssql
  backend/plugin/parser/tsql/statement_type.go
  backend/plugin/parser/tsql/statement_type_test.go
  backend/plugin/parser/tsql/test-data/test_statement_type.yaml
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#15169 feat: statement types for oracle
  backend/plugin/parser/plsql/statement_type.go
  backend/plugin/parser/plsql/statement_type_test.go
  backend/plugin/parser/plsql/test-data/test_statement_type.yaml
  backend/runner/plancheck/statement_report_executor.go
Labels: cla-signed

#15171 feat: implement pg backup v2
  backend/plugin/advisor/pg/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/pg/test/builtin_prior_backup_check.yaml
  backend/plugin/parser/pg/backup.go
  backend/plugin/parser/pg/test-data/test_backup.yaml
Labels: cla-signed

#15172 fix: query for revision index
  backend/migrator/migration/3.4/0005##created_at.sql
Labels: cla-signed

#15170 chore: timestamptz for storage time
  backend/api/v1/anomaly_service.go
  backend/api/v1/audit_log_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/changelist_service.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_changelog.go
  backend/api/v1/database_service_revision.go
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/plan_service.go
  backend/api/v1/release_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/api/v1/sheet_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/worksheet_service.go
  backend/enterprise/api/subscription.go
  backend/legacyapi/task.go
  backend/migrator/migration/3.4/0006##created_at2.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/anomaly.go
  backend/store/audit_log.go
  backend/store/changelist.go
  backend/store/changelog.go
  backend/store/database.go
  backend/store/export_archive.go
  backend/store/issue.go
  backend/store/issue_comment.go
  backend/store/pipeline.go
  backend/store/plan.go
  backend/store/plan_check_run.go
  backend/store/policy.go
  backend/store/principal.go
  backend/store/query_history.go
  backend/store/release.go
  backend/store/revision.go
  backend/store/sheet.go
  backend/store/sync_history.go
  backend/store/task.go
  backend/store/task_run.go
  backend/store/worksheet.go
  backend/utils/utils.go
Labels: cla-signed

#15174 fix: metric
  backend/metric/collector/sheet_count.go
  backend/metric/metric.go
  backend/store/stats.go
Labels: cla-signed

#15176 fix: list database page size
  backend/api/v1/database_service.go
Labels: cla-signed

#15175 chore: format JSON in data export
  frontend/src/components/DataExportButton.vue
Labels: cla-signed

#15177 chore: allow the user to close the prompt hint
  frontend/src/components/v2/Model/PagedTable.vue
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/DynamicSuggestions.vue
Labels: cla-signed

#15178 fix: mssql close
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#15179 chore: add width to project id cell
  frontend/src/components/v2/Model/ProjectV1Table.vue
Labels: cla-signed

#15181 chore: consistent with latest schema
  backend/migrator/migration/3.4/0008##latest_consistent.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#15183 refactor: task find and patch
  backend/api/v1/plan_service.go
  backend/api/v1/plan_service_plan_check.go
  backend/api/v1/rollout_service.go
  backend/api/v1/sql_service.go
  backend/legacyapi/task.go
  backend/migrator/migration/3.4/0007##less_id.sql
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/rollout.go
  backend/store/task.go
Labels: cla-signed

#15184 chore: support audit for delete & undelete user
  frontend/src/components/User/Settings/UserDataTable/cells/UserOperationsCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/auth_service.ts
  proto/generated-go/v1/auth_service.pb.go
  proto/v1/auth_service.proto
Labels: cla-signed

#15185 chore: lower-case column type
  backend/migrator/migration/LATEST.sql
Labels: cla-signed

#15186 chore(proto): affected rows and risk level in check release response
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#15187 chore: fallback 3.5
  backend/api/v1/database_service.go
Labels: cla-signed

#15191 fix: pg timestamp scale and bring pg to pg-like databases
  backend/plugin/db/cockroachdb/query.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/redshift/query.go
  backend/plugin/db/risingwave/query.go
  go.mod
  go.sum
Labels: cla-signed

#15192 chore: add reserved keyword check in pg
  backend/plugin/parser/pg/completion.go
  go.mod
  go.sum
Labels: cla-signed

#15193 chore: change auto-close quote to never
  frontend/src/components/MonacoEditor/editor.ts
Labels: cla-signed

#15194 chore(helm): bump version
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
  scripts/VERSION
Labels: cla-signed

#15196 chore: remove brackets for mssql
  backend/api/lsp/completion.go
Labels: cla-signed

#15197 chore: helm use latest image
  docs/bytebase-1.1.0.tgz
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
  scripts/bump_version.sh
Labels: cla-signed

#15198 fix: nil pointer
  backend/api/v1/audit.go
  backend/runner/schemasync/syncer.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/database_catalog_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/generated-go/v1/database_catalog_service.pb.gw.go
  proto/v1/database_catalog_service.proto
Labels: cla-signed

#15199 chore: remove unused
  backend/api/v1/rollout_service_task.go
Labels: cla-signed

#15200 refactor: unused version
  backend/common/util.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_baseline_executor.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_sdl_executor.go
Labels: cla-signed

#15201 fix: batch create sheets
  backend/api/v1/sheet_service.go
  backend/component/sheet/sheet.go
  backend/store/sheet.go
Labels: cla-signed

#15202 fix: sql project id
  backend/store/changelist.go
  backend/store/pipeline.go
  backend/store/plan.go
Labels: cla-signed

#15204 fix: response could be nil
  backend/api/v1/audit.go
Labels: cla-signed

#15206 chore: policy resource
  backend/api/v1/instance_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/predicate_columns_check.go
  backend/api/v1/project_service.go
  backend/api/v1/query_result_masker.go
  backend/api/v1/review_config_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/sql_service.go
  backend/component/iam/manager.go
  backend/component/webhook/manager.go
  backend/metric/collector/policy_count.go
  backend/migrator/migration/3.4/0009##policy_resource.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/mail/slow_query_weekly_mail.go
  backend/runner/slowquerysync/syncer.go
  backend/server/onboard.go
  backend/store/environment.go
  backend/store/policy.go
  backend/store/project.go
  backend/store/sql_review.go
  backend/store/store.go
  backend/utils/utils.go
Labels: cla-signed

#15208 fix: add all user in the cache
  frontend/src/store/modules/user.ts
Labels: cla-signed

#15207 chore: no database policy
  backend/api/v1/org_policy_service.go
  backend/api/v1/review_config_service.go
  backend/legacyapi/policy.go
  backend/migrator/migration/3.4/0010##no_policy_database.sql
  backend/migrator/migrator_test.go
  backend/store/policy.go
Labels: cla-signed

#15209 chore: remove resource type enum
  backend/migrator/migration/3.4/0011##resource_type_enum.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#15210 fix: filter all user
  frontend/src/store/modules/user.ts
Labels: cla-signed

#15211 feat: risk level in release check
  backend/api/v1/release_service.go
  backend/api/v1/release_service_check.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#15214 chore: simple metrics
  backend/metric/collector/issue_count.go
  backend/metric/collector/member_count.go
  backend/metric/collector/sheet_count.go
  backend/metric/collector/user_count.go
  backend/metric/metric.go
  backend/server/init.go
  backend/store/stats.go
Labels: cla-signed

#15215 fix: update user
  backend/store/principal.go
Labels: cla-signed, backport release/3.4.0

#15217 chore: skip plan checks for release
  backend/api/v1/plan_service.go
Labels: cla-signed

#15218 chore: no environment uid
  backend/api/v1/environment_service.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/environment.go
  backend/store/store.go
Labels: cla-signed

#15219 fix: npe in release check
  backend/api/v1/release_service_check.go
Labels: cla-signed

#15221 chore: create database payload cleanup
  backend/api/v1/rollout_service_task.go
  backend/migrator/migration/3.4/0013##create_database_project.sql
  backend/migrator/migrator_test.go
  backend/plugin/db/driver.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  frontend/src/types/proto/store/task.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/task.pb.go
  proto/store/task.proto
Labels: cla-signed

#15223 chore(dump): add if not exists for schema
  backend/plugin/db/pg/dump.go
Labels: cla-signed

#15222 chore: less project uid
  backend/api/v1/project_service.go
  backend/api/v1/rollout_service.go
  backend/component/webhook/event.go
  backend/runner/mail/slow_query_weekly_mail.go
  backend/runner/taskrun/database_create_executor.go
  backend/store/changelist.go
  backend/store/project.go
  backend/store/store.go
  backend/utils/utils.go
Labels: cla-signed

#15224 chore: less database group uid
  backend/api/v1/database_group_service.go
  backend/api/v1/instance_service.go
  backend/migrator/migration/3.4/0009##policy_resource.sql
  backend/migrator/migration/3.4/0014##update_resource.sql
  backend/migrator/migrator_test.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/taskrun/schema_update_ghost_sync_executor.go
  backend/store/changelist.go
  backend/store/database_group.go
  backend/store/idp.go
  backend/store/instance.go
  backend/store/store.go
Labels: cla-signed

#15226 fix: issue find query
  backend/api/v1/issue_service.go
  backend/api/v1/predicate_columns_check.go
  backend/api/v1/query_result_masker.go
  backend/runner/taskrun/database_create_executor.go
  backend/store/issue.go
  backend/store/policy.go
Labels: cla-signed

#15229 chore: expose semantic type id in ui
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
Labels: cla-signed

#15230 fix: policy updated at
  .github/workflows/backend-tests.yml
  .golangci.yaml
  backend/store/policy.go
Labels: cla-signed

#15232 chore: use user
  backend/api/v1/query_result_masker.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#15233 chore: use check release in sql check button
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
Labels: cla-signed

#15234 fix: use user for sensitive predicate
  backend/api/v1/predicate_columns_check.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#15203 feat: ghost task executor
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/legacyapi/task.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_executor.go
  backend/server/server.go
Labels: cla-signed

#15235 chore: allow change risk source
  backend/api/v1/risk_service.go
  backend/store/risk.go
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskSourceSelect.vue
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/store/modules/risk.ts
Labels: cla-signed

#15237 chore: show risk level and affected rows of release check result
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/utils/util.ts
Labels: cla-signed

#15238 chore: ignore extension schema
  backend/plugin/db/pg/sync.go
Labels: cla-signed, backport release/3.3.1

#15240 chore: add new task type for ghost
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/runner/taskrun/executor.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#15241 chore: handle ghost task in frontend
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/logic/action/task.ts
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/rollout.ts
  frontend/src/types/v1/issue/rollout.ts
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#15243 chore: update go.mod for plsql
  go.mod
  go.sum
Labels: cla-signed

#15242 chore(frontend): remove old task type
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/IssueV1/logic/action/task.ts
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/rollout.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/components/Rollout/RolloutDetail/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/v1/issue/rollout.ts
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#15244 chore: remove branch
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/Role/Setting/components/ImportPermissionFromRoleModal.vue
  frontend/src/components/Role/Setting/components/RolePanel.vue
  frontend/src/store/modules/v1/common.ts
  frontend/src/types/iam/permission.ts
  frontend/src/types/v1/changelist.ts
  frontend/src/types/v1/schemaEditor/state.ts
Labels: cla-signed

#15247 fix: join environment policy
  backend/store/environment.go
Labels: cla-signed, backport release/3.4.0

#15249 fix: changelog paged table
  frontend/src/components/Database/DatabaseChangelogPanel.vue
Labels: cla-signed

#15250 fix: fix sync sequence owner
  backend/plugin/db/driver.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed, backport release/3.3.1

#15252 chore: unify the resource selector
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangelogForm.vue
  frontend/src/components/EllipsisText.vue
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/RepositoryForm.vue
  frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
  frontend/src/components/v2/Select/DatabaseGroupSelect.vue
  frontend/src/components/v2/Select/DatabaseSelect.vue
  frontend/src/components/v2/Select/EnvironmentSelect.vue
  frontend/src/components/v2/Select/GroupSelect.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/components/v2/Select/ResourceSelect.vue
  frontend/src/components/v2/Select/UserSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/sql-review/vi-VN.json
  frontend/src/locales/subscription/vi-VN.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/ProjectMaskingExemption.vue
Labels: cla-signed

#15256 feat(masking): support cosmosdb masking object and atomic type
  backend/api/v1/catalog_masking.go
  backend/api/v1/catalog_masking_test.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#15253 chore: rollout role
  backend/api/v1/issue_service_convert.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/rollout_service.go
  backend/component/webhook/manager.go
  backend/migrator/migration/3.4/0017##rollout_policy_role.sql
  backend/migrator/migrator_test.go
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/types/v1/role.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#15255 feat: ghost temp tables in bbdataarchive
  backend/component/ghost/config.go
  backend/tests/ghost_test.go
  backend/tests/test-data/ghost_test_schema2.result
  go.mod
  go.sum
Labels: cla-signed

#15259 chore: remove trim database metadata
  backend/api/v1/database_service.go
  backend/api/v1/release_service_check.go
  backend/api/v1/sql_service.go
  backend/common/db_schema.go
  backend/common/db_schema_test.go
  backend/runner/schemasync/syncer.go
  backend/runner/schemasync/syncer_test.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_baseline_executor.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_ghost_executor.go
  backend/runner/taskrun/schema_update_sdl_executor.go
  backend/server/onboard.go
Labels: cla-signed

#15260 chore: remove ghost table name hack
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/utils/index.ts
  frontend/src/utils/table.ts
Labels: cla-signed

#15261 feat(masking): mask cosmosdb array
  backend/api/v1/catalog_masking.go
  backend/api/v1/catalog_masking_test.go
Labels: cla-signed

#15262 test: more cosmosdb masking test cases
  backend/api/v1/catalog_masking_test.go
Labels: cla-signed

#15263 chore: activate tparallel linter
  .golangci.yaml
  backend/tests/grouping_change_test.go
  backend/tests/vcs_test.go
Labels: cla-signed

#15265 chore: support sql statement check in risk
  backend/api/v1/release_service_check.go
  backend/common/cel.go
  backend/runner/approval/runner.go
  backend/store/sheet.go
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/plugins/cel/types/operator.ts
  frontend/src/views/EnvironmentDashboard.vue
Labels: cla-signed

#15268 refactor: using GetSymbol().GetTokenIndex() to keep consistency
  backend/plugin/db/mssql/query.go
Labels: cla-signed

#15271 chore: use testcontainers to spawn mysql instances
  backend/tests/ghost_test.go
  backend/tests/mysql.go
  backend/tests/testcontainer.go
  go.mod
  go.sum
Labels: cla-signed

#15273 chore: change grpcruntime marshal option
  backend/server/server.go
Labels: cla-signed

#15274 chore(frontend): update gh-ost section
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/OnlineMigrationAdviceExtra.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/OnlineMigrationAdviceExtra.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSection.vue
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/context.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/components/SyncDatabaseSchemaV1/index.vue
  frontend/src/components/misc/ErrorList.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/database.ts
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#15275 chore: remove legacy ghost
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/legacyapi/task.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  backend/runner/taskrun/schema_update_ghost_sync_executor.go
  backend/server/server.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#15276 chore: check database exists in ghost
  backend/plugin/advisor/mysql/advisor_online_migration.go
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15277 chore: fix gh-ost check order
  backend/plugin/advisor/mysql/advisor_online_migration.go
Labels: cla-signed

#15279 chore: unify setting update UX
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/EnvironmentForm/context.ts
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/GeneralSetting/MaximumRoleExpirationSetting.vue
  frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectSecuritySettingPanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/components/SQLReview/components/SQLReviewForResource.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceGeneral.vue
Labels: cla-signed

#15280 refactor: connection string
  backend/plugin/db/pg/pg.go
Labels: cla-signed

#15278 chore: more test containers
  backend/resources/mysql/fetch_mysql.sh
  backend/resources/mysql/mysql.go
  backend/resources/mysql/resources_darwin_arm64.go
  backend/resources/mysql/resources_linux_amd64.go
  backend/resources/mysql/resources_linux_arm64.go
  backend/tests/change_history_test.go
  backend/tests/data_source_test.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
  backend/tests/start_test.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/testcontainer.go
  backend/tests/tests.go
Labels: cla-signed

#15283 chore: update UX for review policy setting
  frontend/src/components/SQLReview/components/SQLReviewForResource.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicySelectPanel.vue
Labels: cla-signed

#15282 chore: no sleep
  backend/tests/testcontainer.go
Labels: cla-signed

#15285 chore: optimize setting update button
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceGeneral.vue
Labels: cla-signed

#15286 chore: combine db icons
  frontend/src/assets/db/bigquery.svg
  frontend/src/assets/db/clickhouse.png
  frontend/src/assets/db/cockroachdb.png
  frontend/src/assets/db/cosmosdb.svg
  frontend/src/assets/db/databricks.svg
  frontend/src/assets/db/dm.png
  frontend/src/assets/db/doris.png
  frontend/src/assets/db/dynamodb.svg
  frontend/src/assets/db/elasticsearch.svg
  frontend/src/assets/db/hive.svg
  frontend/src/assets/db/mariadb.png
  frontend/src/assets/db/mongodb.png
  frontend/src/assets/db/mssql.svg
  frontend/src/assets/db/mysql.png
  frontend/src/assets/db/oceanbase-mysql.svg
  frontend/src/assets/db/oceanbase-oracle.svg
  frontend/src/assets/db/oracle.svg
  frontend/src/assets/db/postgres.png
  frontend/src/assets/db/redis.png
  frontend/src/assets/db/redshift.svg
  frontend/src/assets/db/risingwave.png
  frontend/src/assets/db/snowflake.png
  frontend/src/assets/db/spanner.png
  frontend/src/assets/db/starrocks.png
  frontend/src/assets/db/tidb.png
  frontend/src/assets/plan-enterprise.png
  frontend/src/assets/plan-free.png
  frontend/src/assets/plan-team.png
  frontend/src/components/InstanceForm/constants.ts
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/components/PricingTable/types.ts
Labels: cla-signed

#15287 chore: unify setting ux for project/instance/environment/workspace
  frontend/src/components/EnvironmentForm/Buttons.vue
  frontend/src/components/EnvironmentForm/Form.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/GeneralSetting/AnnouncementSetting.vue
  frontend/src/components/GeneralSetting/BrandingSetting.vue
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/GeneralSetting/MaximumRoleExpirationSetting.vue
  frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
  frontend/src/components/GeneralSetting/NetworkSetting.vue
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/GeneralSetting/SignInFrequencySetting.vue
  frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
  frontend/src/components/InstanceForm/Buttons.vue
  frontend/src/components/InstanceForm/InstanceForm.vue
  frontend/src/components/InstanceForm/context.ts
  frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectSecuritySettingPanel.vue
  frontend/src/components/ProjectSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/SettingWorkspaceGeneral.vue
Labels: cla-signed

#15288 chore: update gh-ost check order
  backend/plugin/advisor/mysql/advisor_online_migration.go
Labels: cla-signed

#15289 chore: unify setting for deployment config
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/components/ProjectDeploymentConfigPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/deploymentConfig.ts
Labels: cla-signed

#15290 chore: remove feature compare
  frontend/src/components/PricingTable/FeatureItem.vue
  frontend/src/components/PricingTable/PricingTable.vue
  frontend/src/components/PricingTable/index.ts
  frontend/src/components/PricingTable/types.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/subscription/en-US.json
  frontend/src/locales/subscription/es-ES.json
  frontend/src/locales/subscription/ja-JP.json
  frontend/src/locales/subscription/vi-VN.json
  frontend/src/locales/subscription/zh-CN.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/plan.ts
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#15291 feat: add ghost flags
  backend/component/ghost/config.go
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/FlagsForm/constants.ts
Labels: cla-signed

#15293 chore: trim trailing semicolons for ghost
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/taskrun/schema_update_ghost_executor.go
Labels: cla-signed

#15294 chore: add skip dump for schema metadata
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/dump.go
  backend/plugin/db/pg/sync.go
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#15292 chore: add syntax advices to CheckRelease
  backend/api/v1/release_service_check.go
Labels: cla-signed

#15295 chore: update subscription page
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#15296 chore: bump version
  scripts/VERSION
Labels: cla-signed

#15297 fix: pg error line
  backend/component/sheet/sheet.go
Labels: cla-signed

#15299 fix: remove mysqlutil in dockerfile
  scripts/Dockerfile
  scripts/Dockerfile.aws
  scripts/Dockerfile.depot
  scripts/Dockerfile.render-demo
Labels: cla-signed

#15298 chore: optimize resource selector in expr editor
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/ExprEditor/components/MultiSelect.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/components/utils.ts
Labels: cla-signed

#15301 chore: support filter in expr selector
  frontend/src/components/ExprEditor/components/MultiSelect.vue
  frontend/src/components/ExprEditor/components/SingleSelect.vue
Labels: cla-signed

#15305 chore: remove debug
  frontend/src/components/ProjectDatabasesPanel.vue
Labels: cla-signed

#15304 chore: instance change history version format
  backend/migrator/migrator.go
  backend/migrator/migrator_test.go
  backend/store/instance_change_history.go
  backend/store/model/change_history.go
  backend/store/model/change_history_test.go
Labels: cla-signed

#15307 fix: update domain restriction
  backend/api/v1/setting_service.go
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
Labels: cla-signed

#15312 fix: environment tab style
  frontend/src/views/EnvironmentDashboard.vue
Labels: cla-signed

#15308 fix: update domain restriction
  backend/api/v1/setting_service.go
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
Labels: cla-signed

#15310 chore: show affected rows in sql check bar
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
Labels: cla-signed
