Repository bytebase/bytebase, pull requests merged in 2025-01, with the labels that each got.

#14830 chore: migrate catalog
  backend/api/v1/masking_evaluator.go
  backend/api/v1/query_result_masker.go
  backend/server/init.go
  backend/server/onboard.go
  backend/server/server.go
  backend/store/db_schema.go
  backend/tests/sensitive_data_test.go
Labels: cla-signed

#14845 fix: stringify metadata engine checks
  frontend/src/utils/v1/instance.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
Labels: cla-signed

#14846 chore: deprecate algorithms tab
  frontend/src/components/SensitiveData/MaskingAlgorithmsView.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
  frontend/src/views/SettingWorkspaceDataMasking.vue
Labels: cla-signed

#14848 fix: sample instance port
  backend/resources/postgres/sample_instance.go
Labels: cla-signed

#14849 chore: semantic type global
  backend/api/v1/masking_evaluator.go
  backend/api/v1/masking_evaluator_test.go
  backend/api/v1/org_policy_service.go
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/policy.pb.go
  proto/generated-go/v1/org_policy_service.pb.go
  proto/store/policy.proto
  proto/v1/org_policy_service.proto
Labels: cla-signed

#14850 chore: global rule dml
  backend/migrator/migration/prod/3.2/0006##global_rules.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14851 chore: no catagory
  frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
  frontend/src/components/SensitiveData/components/MaskingAlgorithmsTable.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#14852 chore: remove algorithm category
  backend/api/v1/setting_service.go
Labels: cla-signed

#14853 fix: sync schema with changelog
  frontend/src/components/SyncDatabaseSchemaV1/index.vue
Labels: cla-signed

#14856 chore: remove dev guard for database revision tab
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#14857 chore: backfill default and default partial semantic type
  backend/migrator/migration/prod/3.2/0007##default_semantic.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14859 chore: refactor default algorithm
  backend/api/v1/common.go
  backend/api/v1/masking_evaluator.go
  backend/api/v1/masking_evaluator_test.go
  backend/api/v1/query_result_masker.go
  backend/api/v1/setting_service.go
  backend/tests/sensitive_data_test.go
Labels: cla-signed

#14860 chore: helm 3.2.0
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#14861 chore: remove dump for migrator
  backend/migrator/migrator.go
Labels: cla-signed

#14862 fix: approval condidate filters
  frontend/src/store/modules/v1/issue.ts
Labels: cla-signed

#14864 fix: types sql
  backend/migrator/migration/prod/3.2/0007##default_semantic.sql
Labels: cla-signed

#14865 fix: oidc check 200
  backend/api/v1/idp_service.go
  backend/plugin/idp/oidc/oidc.go
Labels: cla-signed

#14866 chore: set semantic type for global masking rule
  frontend/src/components/SensitiveData/components/MaskingActionDropdown.vue
  frontend/src/components/SensitiveData/components/MaskingLevelDropdown.vue
  frontend/src/components/SensitiveData/components/MaskingRuleConfig.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14867 fix: oidc auth endpoint
  backend/api/v1/idp_service.go
  backend/plugin/idp/oidc/oidc.go
  frontend/src/utils/sso.ts
Labels: cla-signed, backport release/3.1.2, backport release/3.2.0

#14872 chore: deprecate algorithms
  backend/api/v1/setting_service.go
  backend/legacyapi/setting.go
  backend/migrator/migration/prod/3.2/0008##deprecate_algorithms.sql
  backend/migrator/migrator_test.go
  backend/store/setting.go
  frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/types.ts
  frontend/src/components/SensitiveData/useColumnMasking.ts
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/setting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#14873 feat: use changelog for drift detection
  backend/runner/schemasync/syncer.go
  backend/store/changelog.go
Labels: cla-signed, backport release/3.2.0

#14593 feat: get PostgreSQL DUMP from metadata
  backend/plugin/db/pg/dump.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/pg/topo_sort.go
  backend/runner/taskrun/database_create_executor.go
  backend/tests/schema_update_test.go
  backend/tests/syncer_test.go
Labels: cla-signed

#14875 chore: add validate_only to create identity provider request
  backend/api/v1/idp_service.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/oidc/oidc_test.go
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/views/SettingWorkspaceSSO.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/idp_service.pb.go
  proto/v1/idp_service.proto
Labels: cla-signed

#14876 chore: check db engine for stringify metadata
  frontend/src/components/TableDetailDrawer.vue
Labels: cla-signed

#14877 chore: deprecate mask level and algorithm in the database catalog
  frontend/src/components/ColumnDataTable/MaskingLevelCell.vue
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/components/SensitiveData/SensitiveColumnDrawer.vue
  frontend/src/components/SensitiveData/components/MaskingLevelDropdown.vue
  frontend/src/components/SensitiveData/components/MaskingLevelRadioGroup.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/SensitiveData/types.ts
  frontend/src/components/SensitiveData/useColumnMasking.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/common.ts
  frontend/src/types/proto/v1/database_catalog_service.ts
  frontend/src/types/proto/v1/idp_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/common.pb.go
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/generated-go/v1/idp_service.pb.go
  proto/store/database.proto
  proto/v1/common.proto
  proto/v1/database_catalog_service.proto
Labels: cla-signed

#14878 chore: keep deprecated store fields for migration
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/database.pb.go
  proto/store/database.proto
Labels: cla-signed

#14879 fix: changelog
  backend/api/v1/database_service_changelog.go
  backend/store/changelog.go
Labels: cla-signed, backport release/3.2.0

#14880 chore: refine sync sequence owner
  backend/plugin/db/driver.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed, backport release/3.2.0

#14881 chore: refactor test about semantic type ID
  backend/api/v1/masking_evaluator.go
  backend/api/v1/masking_evaluator_test.go
  backend/api/v1/query_result_masker.go
Labels: cla-signed

#14884 chore: update action buttons in sql check panel
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/Branch/BranchDetailView.vue
  frontend/src/components/Branch/BranchRolloutView/BranchRolloutView.vue
  frontend/src/components/Branch/SchemaDesignEditorLite.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/components/SchemaEditorLite/common.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/experimental-issue.ts
Labels: cla-signed

#14885 chore: simplify algorithm proto
  frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
  frontend/src/types/proto/store/setting.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/setting.proto
  proto/v1/setting_service.proto
Labels: cla-signed

#14886 chore: always show task list section
  frontend/src/components/IssueV1/components/StageSection/StageCard.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/DatabaseInfo.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageInfo.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/StageSelect.vue
  frontend/src/components/IssueV1/components/StageSection/StageInfo/index.ts
  frontend/src/components/IssueV1/components/StageSection/StageSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
Labels: cla-signed

#14887 chore: add `allow_self_approval` to project setting
  backend/api/v1/project_service.go
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/project.ts
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/project.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/store/project.proto
  proto/v1/project_service.proto
Labels: cla-signed

#14888 chore: implement allow self-approval setting
  backend/api/v1/issue_service.go
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/issue.ts
Labels: cla-signed

#14889 chore: update UI for semantic algorithm
  frontend/src/components/GeneralSetting/AccountSetting.vue
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/SensitiveData/components/MaskingAlgorithmsCreateDrawer.vue
  frontend/src/components/SensitiveData/components/SemanticTypesDrawer.vue
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
  frontend/src/components/SensitiveData/components/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14890 chore: semantic type wording
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
Labels: cla-signed

#14893 chore: update wording about catalog tab
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/useDashboardSidebar.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#14891 chore: rename proto and add semantic type to schema object proto
  backend/api/v1/branch_merge_test.go
  backend/api/v1/branch_service.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/masking_evaluator.go
  backend/api/v1/masking_evaluator_test.go
  backend/migrator/migration/prod/3.2/0009##catalog_id.sql
  backend/migrator/migrator_test.go
  backend/runner/schemasync/syncer.go
  backend/server/init.go
  backend/server/onboard.go
  backend/store/model/database.go
  backend/tests/sensitive_data_test.go
  backend/utils/database_config_merge.go
  backend/utils/database_config_merge_test.go
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/components/SchemaTemplate/TableTemplateTable.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/SensitiveData/useSemanticType.ts
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TableDetailDrawer.vue
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_catalog_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_catalog_service.pb.go
  proto/store/database.proto
  proto/v1/database_catalog_service.proto
Labels: cla-signed

#14895 chore: table column size
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
Labels: cla-signed

#14894 chore: update risk center to risks
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RiskTips.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/utils/useDashboardSidebar.ts
Labels: cla-signed

#14896 chore: catalog ui update
  frontend/src/components/ColumnDataTable/ClassificationCell.vue
  frontend/src/components/ColumnDataTable/SemanticTypeCell.vue
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/components/TableDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14898 chore: baby version of built-in semantic types
  backend/api/v1/query_result_masker.go
  backend/migrator/migration/prod/3.2/0006##global_rules.sql
  backend/migrator/migration/prod/3.2/0007##default_semantic.sql
  backend/server/init.go
Labels: cla-signed

#14899 chore: add tips to copy query result
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SelectionCopyTooltips.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14901 chore: masking exemption wording
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/ProjectDatabaseMaskingAccess.vue
  frontend/src/views/project/ProjectDatabaseMaskingAccessCreate.vue
Labels: cla-signed

#14902 chore: no air
  README.md
Labels: cla-signed

#14903 chore: masking access to masking exemption
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/ProjectMaskingExemption.vue
  frontend/src/views/project/ProjectMaskingExemptionCreate.vue
Labels: cla-signed

#14900 feat: changelog view
  backend/api/v1/database_service_changelog.go
  backend/runner/schemasync/syncer.go
  backend/store/changelog.go
  backend/tests/schema_update_test.go
  backend/tests/sync_schema_test.go
  backend/tests/vcs_test.go
Labels: cla-signed, backport release/3.2.0

#14904 chore: built-in semantic types
  frontend/src/components/SensitiveData/SemanticTypesView.vue
  frontend/src/components/SensitiveData/components/SemanticTemplateDrawer.vue
  frontend/src/components/SensitiveData/components/SemanticTypesTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/semantic-types.yaml
  frontend/src/types/semanticTypes.ts
Labels: cla-signed

#14906 chore: global data masking wording
  frontend/src/components/User/Settings/RemoveGroupButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/router/sqlEditor.ts
  frontend/src/utils/useDashboardSidebar.ts
  frontend/src/views/sql-editor/EditorCommon/DataTable/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/SensitiveDataIcon.vue
  frontend/src/views/sql-editor/Setting/Sidebar/common.ts
Labels: cla-signed

#14907 fix: err msg
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14908 fix: sql
  backend/store/changelog.go
Labels: cla-signed, backport release/3.2.0

#14911 feat(sql): release
  backend/migrator/migration/prod/3.3/0000##release.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14910 feat(differ): support materialized view for PostgreSQL
  backend/plugin/db/pg/dump.go
  backend/plugin/parser/base/topo_sort.go
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
Labels: cla-signed

#14912 feat(cosmos): support cosmosdb query simply
  backend/plugin/db/cosmosdb/cosmosdb.go
  backend/plugin/db/driver.go
  go.mod
  go.sum
Labels: cla-signed

#14913 chore(sql): clean instance change history
  backend/migrator/migration/prod/3.3/0001##clean_instance_change_history.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14915 fix: failed to update exception policy
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
Labels: cla-signed

#14917 fix(differ): append ignore function body check setting
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/test-data/test_differ_constraint.yaml
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
  backend/plugin/parser/pg/test-data/test_differ_merge.yaml
  backend/plugin/parser/pg/test-data/test_differ_schema.yaml
  backend/plugin/parser/pg/test-data/test_differ_sequence.yaml
  backend/tests/sync_schema_test.go
Labels: cla-signed

#14918 feat: introduce function dependency in proto
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14919 chore: sync pg dependency
  backend/api/v1/database_converter.go
  backend/plugin/db/pg/sync.go
Labels: cla-signed

#14916 chore: unused i18n warning
  frontend/eslint.config.mjs
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#14920 chore: rename dependent to dependency
  backend/api/v1/database_converter.go
  backend/plugin/advisor/catalog/state.go
  backend/plugin/advisor/catalog/walk_through_for_pg.go
  backend/plugin/advisor/catalog/walk_through_test.go
  backend/plugin/db/cockroachdb/sync.go
  backend/plugin/db/databricks/sync.go
  backend/plugin/db/pg/dump.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/tests/syncer_test.go
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/utils/schemaEditor/filter.ts
  frontend/src/utils/v1/dbSchema.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/DependencyColumnNode.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/common.ts
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/DependencyColumnsTable.vue
  frontend/src/views/sql-editor/EditorPanel/Panels/ViewsPanel/ViewDetail.vue
  frontend/src/views/sql-editor/EditorPanel/types.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/database.proto
  proto/v1/database_service.proto
Labels: cla-signed

#14921 chore: update eslint config
  frontend/eslint.config.mjs
  frontend/package.json
Labels: cla-signed

#14924 chore(sql-editor): update data table lite
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataBlock.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable/index.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/ColumnHeader.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/index.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite/useTableResize.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/index.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14923 chore: remove task version
  backend/migrator/migration/prod/3.2/0010##remove_task_version.sql
Labels: cla-signed, backport release/3.2.0

#14922 chore: change history & model.Version in migrator, clear everywhere else
  backend/migrator/migrator.go
  backend/plugin/db/driver.go
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/store/changelog.go
  backend/store/database.go
  backend/store/instance_change_history.go
Labels: cla-signed

#14925 fix: use protojson
  backend/api/v1/rollout_service_task.go
Labels: cla-signed

#14926 chore: cherrypick PR/14923
  backend/migrator/migration/prod/3.2/0005##remove_task_version.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14928 chore: reorder 3.2 migrations
  backend/migrator/migration/prod/3.2/0005##remove_task_version.sql
  backend/migrator/migration/prod/3.3/0002##algorithm.sql
  backend/migrator/migration/prod/3.3/0003##global_rules.sql
  backend/migrator/migration/prod/3.3/0004##default_semantic.sql
  backend/migrator/migration/prod/3.3/0005##deprecate_algorithms.sql
  backend/migrator/migration/prod/3.3/0006##catalog_id.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14932 chore: update trigger of approval flow node popover
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/TimelineIcon.vue
Labels: cla-signed

#14931 chore: return file path
  backend/api/v1/release_service.go
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14930 chore: improve no stage create errmsg
  backend/api/v1/rollout_service.go
Labels: cla-signed

#14934 fix(differ): fix the safe order for functions and tables
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
  backend/plugin/parser/sql/ast/create_function_stmt.go
  backend/plugin/parser/sql/engine/pg/convert.go
Labels: cla-signed

#14933 chore: update extract row value
  frontend/src/utils/v1/sql.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel/DetailPanel.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#14935 fix: unescaped quote for mysql dump
  backend/plugin/db/mysql/sync.go
Labels: cla-signed

#14936 chore: add database link to task card
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
Labels: cla-signed

#14938 chore: audit logs plural
  frontend/eslint.config.mjs
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
Labels: cla-signed

#14937 fix(walk-through): ignore view for pg alter table
  backend/plugin/advisor/catalog/walk_through.go
  backend/plugin/advisor/catalog/walk_through_for_pg.go
Labels: cla-signed

#14939 chore: remove dev guard of releases
  frontend/src/components/Project/ProjectReleasesPanel.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14940 refactor: executor
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
Labels: cla-signed

#14941 fix: dump supports pg 9.6+
  backend/plugin/db/pg/dump.go
  backend/tests/schema_update_test.go
Labels: cla-signed

#14942 chore: tweak sql oversized tips
  frontend/src/components/PlanCheckRun/PlanCheckRunModal.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14943 feat(cosmos): handle cosmosdb query result
  backend/plugin/db/cosmosdb/cosmosdb.go
  go.mod
  go.sum
Labels: cla-signed

#14946 perf: unmarshal once
  backend/plugin/db/cosmosdb/cosmosdb.go
Labels: cla-signed

#14948 chore: double click cosmosdb container quick query
  frontend/src/utils/v1/sql.ts
Labels: cla-signed

#14949 fix: export changelogs
  frontend/src/components/Database/DatabaseChangelogPanel.vue
Labels: cla-signed

#14947 fix: data export policy
  backend/api/v1/sql_service.go
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/export.ts
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14951 fix: export data button
  frontend/src/layouts/ProjectV1Layout.vue
Labels: cla-signed

#14954 chore: use format
  backend/runner/taskrun/data_export_executor.go
Labels: cla-signed

#14955 feat: skip version-applied tasks
  backend/runner/taskrun/database_create_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schema_update_ghost_cutover_executor.go
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
Labels: cla-signed

#14953 chore: remove cosmosdb dev guard
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#14956 chore: deprecate instance anomalies
  backend/api/v1/anomaly_service.go
  backend/legacyapi/anomaly.go
  backend/migrator/migration/prod/3.3/0007##instance_anomaly.sql
  backend/migrator/migrator_test.go
  backend/runner/schemasync/syncer.go
  frontend/src/components/AnomalyCenter/AnomalyTable.vue
  frontend/src/store/modules/v1/anomaly.ts
  frontend/src/types/anomaly.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/anomaly_service.pb.go
  proto/v1/anomaly_service.proto
Labels: cla-signed

#14957 refactor: converge anomaly frontend usage pattern
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
  frontend/src/store/modules/v1/anomaly.ts
Labels: cla-signed

#14959 chore: introduce project parent in searchAnomaly
  frontend/src/types/proto/v1/anomaly_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/anomaly_service.pb.go
  proto/generated-go/v1/anomaly_service.pb.gw.go
  proto/v1/anomaly_service.proto
Labels: cla-signed

#14961 chore: set project parent
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
  frontend/src/store/modules/v1/anomaly.ts
  frontend/src/views/AnomalyCenterDashboard.vue
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#14962 chore: anomaly project
  backend/migrator/migration/prod/3.3/0008##anomaly_project.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#14964 chore(sql-editor): tweak data table
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#14965 chore: tweak fetch anomaly list
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
Labels: cla-signed

#14960 chore: move release to prod
  backend/legacyapi/task.go
  backend/runner/taskrun/executor.go
Labels: cla-signed

#14966 chore: use project filter
  backend/api/v1/anomaly_service.go
  backend/store/anomaly.go
Labels: cla-signed

#14967 chore(anomaly): database schema drift modal
  backend/api/v1/anomaly_service.go
  frontend/src/components/AnomalyCenter/AnomalyTable.vue
  frontend/src/components/AnomalyCenter/DatabaseSchemaDriftAnomalyModal.vue
  frontend/src/store/modules/v1/changelog.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/v1/anomaly_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/anomaly_service.pb.go
  proto/v1/anomaly_service.proto
Labels: cla-signed

#14968 chore: optimize es connect
  backend/plugin/db/elasticsearch/elasticsearch.go
Labels: cla-signed

#14969 chore: tweak project anomalies page
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
Labels: cla-signed

#14958 feat: implement oracle prior backup v2
  backend/plugin/advisor/mysql/advisor_builtin_prior_backup_check.go
  backend/plugin/advisor/oracle/advisor_builtin_prior_backup_check.go
  backend/plugin/parser/plsql/backup.go
  backend/plugin/parser/plsql/test-data/test_backup.yaml
Labels: cla-signed

#14970 chore: update catalog permission
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/components/SensitiveData/components/SensitiveColumnTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/databaseCatalog.ts
  frontend/src/types/iam/permission.ts
Labels: cla-signed

#14971 chore: make vcs url more general
  backend/api/gitops/webhook.go
  backend/api/v1/release_service.go
  frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
  frontend/src/types/proto/store/release.ts
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/release.pb.go
  proto/generated-go/v1/release_service.pb.go
  proto/store/release.proto
  proto/v1/release_service.proto
Labels: cla-signed

#14972 chore: tweak plan check runs in issue context
  frontend/src/components/AnomalyCenter/AnomalyCenterDashboard.vue
  frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/IssueV1/components/Sidebar/VCSInfo.vue
  frontend/src/components/IssueV1/logic/plan-check.ts
  frontend/src/components/PlanCheckRun/PlanCheckRunBadge.vue
  frontend/src/components/PlanCheckRun/PlanCheckRunBadgeBar.vue
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/plan.ts
Labels: cla-signed

#14974 chore: update schema sync supported db
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14976 chore: remove custom color
  frontend/src/customAppProfile.ts
  frontend/src/types/appProfile.ts
Labels: cla-signed

#14975 chore: update anomaly store code
  backend/api/v1/anomaly_service.go
  backend/migrator/migration/prod/3.3/0007##instance_anomaly.sql
  backend/migrator/migration/prod/3.3/0008##anomaly_project.sql
  backend/migrator/migration/prod/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/executor.go
  backend/store/anomaly.go
Labels: cla-signed

#14978 fix: semantic non-exist case
  backend/migrator/migration/prod/3.3/0004##default_semantic.sql
Labels: cla-signed

#14979 feat: release iam
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  frontend/src/types/proto/v1/release_service.ts
  proto/generated-go/v1/release_service.pb.go
  proto/v1/release_service.proto
Labels: cla-signed

#14980 fix: default select statement for es
  frontend/src/components/TransferDatabaseForm/TransferDatabaseForm.vue
  frontend/src/components/TransferOutDatabaseForm/TransferOutDatabaseForm.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/utils/v1/sql.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#14982 chore: upgrade version
  scripts/VERSION
Labels: cla-signed

#14981 fix: source schema radio value
  frontend/src/components/SyncDatabaseSchemaV1/index.vue
Labels: cla-signed

#14983 chore: show source schema info
  frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
  frontend/src/components/SyncDatabaseSchemaV1/RawSQLEditor.vue
  frontend/src/components/SyncDatabaseSchemaV1/SelectTargetDatabasesView.vue
  frontend/src/components/SyncDatabaseSchemaV1/SourceSchemaInfo.vue
  frontend/src/components/SyncDatabaseSchemaV1/index.vue
Labels: cla-signed

#14984 fix: expect no issue
  backend/store/pipeline.go
Labels: cla-signed

#14985 fix(instance_service): correct project ID usage in database listing
  backend/api/v1/instance_service.go
Labels: cla-signed

#14987 chore: handle empty semantic types
  backend/migrator/migration/prod/3.3/0002##algorithm.sql
  backend/migrator/migration/prod/3.3/0004##default_semantic.sql
Labels: cla-signed

#14986 chore: optimize the sql query error message
  backend/api/v1/sql_service.go
  frontend/src/store/modules/v1/sql.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/AdviceItem.vue
Labels: cla-signed

#14988 chore(sql-editor): allow select table cell to copy
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/common/selection-logic.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#14989 chore: add warning about previous unrolled stages
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#14990 chore: simplify the plan check advice
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/sql_service.go
  backend/plugin/advisor/sql_review.go
  backend/plugin/parser/mysql/statement_type_check.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/plancheck/statement_report_executor.go
  backend/tests/test-data/sql_review_mysql.yaml
  backend/tests/test-data/sql_review_pg.yaml
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/OnlineMigrationAdviceExtra.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/OnlineMigrationAdviceExtra.vue
  frontend/src/components/IssueV1/components/StatementSection/useSQLAdviceMarkers.ts
  frontend/src/components/Plan/components/StatementSection/useSQLAdviceMarkers.ts
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/components/PlanCheckRun/detail/OnlineMigrationDetail.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/proto/store/advice.ts
  frontend/src/types/proto/store/plan_check_run.ts
  frontend/src/types/proto/v1/plan_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/advice.pb.go
  proto/generated-go/store/plan_check_run.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/store/advice.proto
  proto/store/plan_check_run.proto
  proto/v1/plan_service.proto
  proto/v1/sql_service.proto
Labels: cla-signed

#14991 feat: make stage_id optional
  backend/api/v1/rollout_service.go
  backend/store/pipeline.go
  backend/store/release.go
  backend/store/stage.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/rollout_service.proto
Labels: cla-signed

#14992 chore: preview rollout stages
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview/Overview.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview/StageCard.vue
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview/index.ts
  frontend/src/components/Rollout/RolloutDetail/RolloutDetail.vue
  frontend/src/components/Rollout/RolloutDetail/context.ts
Labels: cla-signed

#14994 chore: fix merged stages
  frontend/src/components/Rollout/RolloutDetail/Panels/Overview/Overview.vue
Labels: cla-signed

#14996 chore(sql-editor): use native scrollbar
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
Labels: cla-signed

#14997 fix: slow query search
  frontend/src/components/SlowQuery/Panel/LogFilter.vue
  frontend/src/components/SlowQuery/Panel/SlowQueryPanel.vue
  frontend/src/components/SlowQuery/Panel/types.ts
Labels: cla-signed

#14999 fix: set plan in validateOnly
  backend/api/v1/rollout_service.go
Labels: cla-signed

#14998 fix: use int64 instead of int32 for slow query
  backend/api/v1/database_service.go
  backend/plugin/db/cockroachdb/sync.go
  backend/plugin/db/pg/sync.go
  backend/runner/mail/slow_query_weekly_mail.go
  backend/store/slow_query.go
  frontend/src/components/SlowQuery/Panel/LogTable.vue
  frontend/src/types/proto/store/slow_query.ts
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/slow_query.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/slow_query.proto
  proto/v1/database_service.proto
Labels: cla-signed

#15000 fix: filter deleted revision
  backend/store/database.go
Labels: cla-signed

#15001 chore: cosmosdb port
  frontend/src/components/InstanceForm/constants.ts
Labels: cla-signed

#15002 fix: column catalog
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/SemanticTypeCell.vue
  frontend/src/components/SchemaEditorLite/context/config.ts
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/store/modules/v1/databaseCatalog.ts
Labels: cla-signed

#15003 chore: move environment related actions into NTabs
  frontend/src/views/EnvironmentDashboard.vue
Labels: cla-signed

#15004 chore: delete unused code
  backend/plugin/schema/pg/parse_to_metadata.go
  backend/plugin/schema/pg/parse_to_metadata_test.go
  backend/plugin/schema/pg/state.go
  backend/plugin/schema/pg/testdata/parse_to_metadata.yaml
Labels: cla-signed

#15005 fix: missing row key
  frontend/src/components/ColumnDataTable/index.vue
  frontend/src/components/DBExtensionDataTable.vue
  frontend/src/components/ExternalTableDataTable.vue
  frontend/src/components/FunctionDataTable.vue
  frontend/src/components/PackageDataTable.vue
  frontend/src/components/PartitionTablesDataTable.vue
  frontend/src/components/ProjectWebhookPanel.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/index.vue
  frontend/src/components/SequenceDataTable.vue
  frontend/src/components/TableDataTable.vue
  frontend/src/components/TriggerDataTable.vue
  frontend/src/components/ViewDataTable.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceVCS.vue
  frontend/src/views/project/ProjectVersionControlPanel.vue
Labels: cla-signed

#15006 chore: cosmos query time
  backend/plugin/db/cosmosdb/cosmosdb.go
Labels: cla-signed

#15007 chore: retire data table lite
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTableLite.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/index.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/useTableResize.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#15015 chore: update keys
  frontend/eslint.config.mjs
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15018 chore: no symbol
  README.md
Labels: cla-signed

#15020 chore: masking chinese wording
  frontend/src/locales/en-US.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#15022 chore: bump google-sql-parser version
  backend/plugin/parser/bigquery/query_span_extractor.go
  backend/plugin/parser/spanner/query_span_extractor.go
  go.mod
  go.sum
Labels: cla-signed

#15023 fix(differ): print header if needed
  backend/plugin/parser/pg/differ.go
  backend/plugin/parser/pg/test-data/test_differ_constraint.yaml
  backend/plugin/parser/pg/test-data/test_differ_data.yaml
  backend/plugin/parser/pg/test-data/test_differ_merge.yaml
  backend/plugin/parser/pg/test-data/test_differ_schema.yaml
  backend/plugin/parser/pg/test-data/test_differ_sequence.yaml
  backend/tests/sync_schema_test.go
Labels: cla-signed

#15025 chore: upgrade helm
  docs/bytebase-1.1.1.tgz
  docs/index.yaml
  helm-charts/bytebase/values.yaml
Labels: cla-signed

#15026 chore: engine type bq/spanner
  frontend/src/components/InstanceForm/constants.ts
Labels: cla-signed, backport release/3.3.0

#15029 feat: spanner diagnose
  backend/api/lsp/fs_handler.go
  backend/plugin/parser/spanner/dignose.go
Labels: cla-signed

#15031 chore: unused parse to metadata
  backend/api/v1/branch_service.go
  backend/api/v1/database_converter.go
  backend/api/v1/database_service.go
  backend/api/v1/plan_service_plan_check.go
  backend/api/v1/sheet_service.go
  backend/api/v1/sql_service.go
  backend/plugin/schema/mysql/parse_to_metadata.go
  backend/plugin/schema/mysql/parse_to_metadata_test.go
  backend/plugin/schema/mysql/state.go
  backend/plugin/schema/mysql/testdata/parse-to-metadata/partition.yaml
  backend/plugin/schema/mysql/testdata/parse-to-metadata/routine.yaml
  backend/plugin/schema/mysql/testdata/parse-to-metadata/standard.yaml
  backend/plugin/schema/mysql/testdata/parse-to-metadata/view.yaml
  backend/plugin/schema/mysql/utils.go
  backend/plugin/schema/oracle/get_design_schema.go
  backend/plugin/schema/oracle/parse_to_metadata.go
  backend/plugin/schema/oracle/parse_to_metadata_test.go
  backend/plugin/schema/oracle/state.go
  backend/plugin/schema/oracle/testdata/parse_to_metadata.yaml
  backend/plugin/schema/schema.go
  backend/plugin/schema/tidb/parse_to_metadata.go
  backend/plugin/schema/tidb/parse_to_metadata_test.go
  backend/plugin/schema/tidb/state.go
  backend/plugin/schema/tidb/testdata/parse_to_metadata.yaml
  backend/plugin/schema/tidb/utils.go
  backend/runner/taskrun/executor.go
  backend/utils/database_config_merge.go
  backend/utils/database_config_merge_test.go
  frontend/src/components/SchemaEditorLite/Panels/ViewEditor.vue
  frontend/src/components/SchemaEditorLite/algorithm/utils.ts
  frontend/src/types/proto/store/database.ts
  frontend/src/types/proto/store/plan.ts
  frontend/src/types/proto/store/sheet.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/store/plan.pb.go
  proto/generated-go/store/sheet.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/sheet_service.pb.go
  proto/store/database.proto
  proto/store/plan.proto
  proto/store/sheet.proto
  proto/v1/database_service.proto
  proto/v1/sheet_service.proto
Labels: cla-signed

#15034 chore: fix eslint warnings
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed

#15033 chore: move diff metadata
  backend/api/v1/branch_service.go
  backend/api/v1/sql_service.go
  backend/server/grpc_routes.go
  frontend/src/components/SchemaEditorLite/common.ts
  frontend/src/grpcweb/index.ts
  frontend/src/grpcweb/methods.ts
  frontend/src/types/proto/store/branch.ts
  frontend/src/types/proto/v1/branch_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/branch_service.pb.go
  proto/generated-go/v1/branch_service.pb.gw.go
  proto/generated-go/v1/branch_service_grpc.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/v1/branch_service.proto
  proto/v1/sql_service.proto
Labels: cla-signed

#15035 chore: catalog in DiffMetadata
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/sql_service.proto
Labels: cla-signed

#15027 feat: support bigquery/spanner statement type
  backend/api/v1/sql_service.go
  backend/plugin/parser/bigquery/query_span_extractor.go
  backend/plugin/parser/bigquery/query_type.go
  backend/plugin/parser/spanner/query_span_extractor.go
  backend/plugin/parser/spanner/query_type.go
Labels: cla-signed
