Repository bytebase/bytebase, pull requests merged in 2025-05, with the labels that each got.

#15936 chore: add completion
  backend/base/engine.go
  backend/plugin/parser/trino/completion.go
  backend/plugin/parser/trino/completion_test.go
  backend/plugin/parser/trino/test-data/completion/t_c.yaml
  backend/plugin/parser/trino/test-data/completion/t_cc.yaml
  backend/plugin/parser/trino/test-data/completion/test_completion.yaml
  backend/server/ultimate.go
Labels: cla-signed

#16034 fix: earliest allowed ts should be nil when task created
  backend/store/task.go
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue
Labels: cla-signed

#16035 chore: fix schema special char
  backend/plugin/db/trino/trino.go
Labels: cla-signed

#16037 fix: approval i18n
  frontend/src/utils/workspaceApprovalSetting.ts
Labels: cla-signed

#16036 chore: update pg ac
  backend/api/lsp/completion.go
  backend/plugin/parser/pg/completion.go
Labels: cla-signed

#16039 chore: update
  README.md
Labels: cla-signed

#16040 chore: upgrade trino deps
  go.mod
  go.sum
Labels: cla-signed

#16041 fix: undefined ctx.Identifier
  backend/plugin/parser/trino/query_span_listener.go
Labels: cla-signed

#16042 chore: trino ac rules
  backend/plugin/parser/trino/completion.go
Labels: cla-signed

#16043 chore: several ui fix & code refactor
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/HelpDrawer/HelpDrawer.vue
  frontend/src/layouts/DashboardLayout.vue
  frontend/src/store/modules/auth.ts
  frontend/src/views/EnvironmentDashboard.vue
  frontend/src/views/EnvironmentDetail.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/Setup/Setup.vue
  frontend/src/views/Setup/WorkspaceMode.vue
  frontend/src/views/auth/Signup.vue
  frontend/src/views/sql-editor/Setting/Environment/Environment.vue
Labels: cla-signed

#16044 fix: handle no available project scenario
  frontend/src/components/ProvideSQLEditorContext.vue
Labels: cla-signed

#16045 chore: simplify the initial password restriction
  backend/server/init.go
Labels: cla-signed

#16046 chore: update column-alias
  backend/plugin/parser/trino/completion.go
Labels: cla-signed

#16047 chore: display report time
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16049 fix: watch sources for resetting tasks index
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
Labels: cla-signed

#16050 chore: support select multiple databases to batch query in the connection panel
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/SearchBox/index.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/SearchBox/useSearchHistory.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPanel.vue
  frontend/src/views/sql-editor/EditorCommon/BatchQueryDatabasesSelector.vue
  frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
Labels: cla-signed

#16051 fix: release resource limiter
  backend/base/instance.go
  backend/runner/plancheck/scheduler.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16052 fix: i18n
  frontend/src/bbkit/BBAlert.vue
  frontend/src/components/v2/Form/StepTab.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16053 chore: output json
  action/README.md
  action/main.go
Labels: cla-signed

#16054 fix: unknown database in task detail
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/TaskDetail.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/context.ts
  frontend/src/components/Rollout/RolloutDetail/context.ts
Labels: cla-signed

#16055 fix: post run on cmd
  action/main.go
Labels: cla-signed

#16056 chore: optimize
  backend/api/v1/instance_service.go
  frontend/src/components/v2/Model/DatabaseV1Name.vue
  frontend/src/components/v2/Model/EnvironmentV1Name.vue
  frontend/src/components/v2/Model/HighlightLabelText.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Name.vue
  frontend/src/components/v2/Model/ProjectV1Name.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/components/v2/Model/RichDatabaseName.vue
  frontend/src/components/v2/Model/index.ts
  frontend/src/store/modules/v1/instance.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/TreeNode/CommonNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/EnvironmentNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/HighlightLabelText.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/InstanceNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/LabelNode.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
  frontend/src/views/sql-editor/TabList/TabItem/TabItem.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_service.pb.go
  proto/v1/v1/instance_service.proto
Labels: cla-signed

#16057 fix: update task type
  backend/api/v1/plan_service.go
Labels: cla-signed

#16059 feat: sync mssql triggers
  backend/plugin/db/mssql/sync.go
Labels: cla-signed

#16060 fix: errors wrapf
  action/main.go
Labels: cla-signed

#16061 fix: duplicate key
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/tree.ts
Labels: cla-signed

#16062 fix: get active statement range
  frontend/src/components/MonacoEditor/MonacoTextModelEditor.vue
  frontend/src/components/MonacoEditor/composables/useActiveRangeByCursor.ts
Labels: cla-signed

#16064 chore: tag mongosh version
  scripts/Dockerfile
  scripts/Dockerfile.aws
Labels: cla-signed

#16065 chore: bump to 3.6.1
  scripts/VERSION
Labels: cla-signed

#16066 fix(sql-editor): unknown database
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
Labels: cla-signed

#16067 feat(action): rollout plan
  action/api.go
  action/main.go
  scripts/Dockerfile.action
Labels: cla-signed

#16068 refactor: simplify the feature guard
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/Toolbar.vue
  frontend/src/components/Database/DatabaseSensitiveDataPanel.vue
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureAttentionForInstanceLicense.vue
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/FeatureGuard/FeatureBadgeForInstanceLicense.vue
  frontend/src/components/FeatureGuard/index.ts
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/Role/Setting/RoleSetting.vue
  frontend/src/components/Role/Setting/components/RolePanel.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/v2/Model/DatabaseView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingWorkspaceCustomApproval.vue
  frontend/src/views/SettingWorkspaceRiskCenter.vue
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceSemanticTypes.vue
  frontend/src/views/SettingWorkspaceUsers.vue
  frontend/src/views/project/ProjectDatabaseGroupDashboard.vue
  frontend/src/views/project/ProjectDatabaseGroupDetail.vue
  frontend/src/views/project/ProjectMaskingExemption.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataBlock.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/DataTable.vue
Labels: cla-signed

#16069 chore: update action readme
  action/README.md
Labels: cla-signed

#16071 fix: tidb zero time
  backend/plugin/db/tidb/sync.go
  backend/plugin/parser/tidb/tidb.go
Labels: cla-signed

#16070 fix: switch issue stage
  frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
Labels: cla-signed

#16072 chore: show notification if custom approval flow is not enabled
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/utils.ts
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/components/Plan/logic/plan.ts
  frontend/src/components/Rollout/RolloutDetail/utils.ts
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/instanceResource.ts
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#16074 chore(action): ignore unversioned file
  action/file.go
Labels: cla-signed

#16076 fix: no need to limit the environment title
  backend/api/v1/setting_service.go
  backend/base/environment.go
Labels: backport release/3.6.1

#16078 fix: reactive instance
  frontend/src/components/InstanceAssignment.vue
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/utils.ts
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/store/modules/v1/database.ts
  frontend/src/store/modules/v1/instanceResource.ts
Labels: cla-signed

#16079 fix: computed project name
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/views/ExportCenter/index.vue
  frontend/src/views/ReviewCenter/index.vue
Labels: cla-signed

#16080 feat: tag action image & print commit hash
  .github/workflows/build-push-action-image.yml
  action/args/version.go
  action/main.go
  scripts/Dockerfile.action
Labels: cla-signed

#16082 fix: use instance resource
  frontend/src/store/modules/v1/instanceResource.ts
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
Labels: cla-signed

#16083 chore: remove tasks param
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed

#16084 chore: action bar for database info
  frontend/src/views/sql-editor/AsidePanel/ActionBar/ActionBar.vue
  frontend/src/views/sql-editor/AsidePanel/ActionBar/TabItem.vue
  frontend/src/views/sql-editor/AsidePanel/ActionBar/common.ts
  frontend/src/views/sql-editor/AsidePanel/ActionBar/index.ts
  frontend/src/views/sql-editor/AsidePanel/AsidePanel.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
Labels: cla-signed

#16087 chore: use tidb_indexes
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/tidb/sync.go
Labels: cla-signed

#16088 chore: fix height of project layout
  frontend/src/layouts/ProjectV1Layout.vue
Labels: cla-signed

#16089 chore: implement get risk
  backend/api/v1/risk_service.go
  frontend/src/types/proto/v1/risk_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/risk_service.pb.go
  proto/generated-go/v1/risk_service.pb.gw.go
  proto/generated-go/v1/risk_service_grpc.pb.go
  proto/v1/v1/risk_service.proto
Labels: cla-signed

#16090 chore: update spec list section
  frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
  frontend/src/components/IssueV1/components/TaskListSection/filter.ts
  frontend/src/components/Plan/components/SpecListSection/CurrentSpecSection.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/SpecListSection/SpecFilter.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Plan/components/SpecListSection/filter.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/locales/en-US.json
  frontend/src/store/modules/v1/plan.ts
Labels: cla-signed

#16086 fix: avoid unnecessary CREATE TRIGGER when trigger definition is unchanged in schema diff
  backend/plugin/parser/mysql/differ.go
  backend/plugin/parser/mysql/test-data/differ/test_differ_trigger.yaml
Labels: cla-signed

#16091 chore: show removed users and groups in the IAM
  frontend/src/components/Member/MemberDataTable/cells/UserNameCell.vue
  frontend/src/components/Member/MemberDataTable/cells/UserOperationsCell.vue
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/Member/MemberDataTableByRole.vue
  frontend/src/components/Member/types.ts
  frontend/src/components/Member/utils.ts
  frontend/src/components/ProjectMember/ProjectMemberPanel.vue
  frontend/src/components/User/Settings/UserDataTableByGroup/cells/GroupNameCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceMembers.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#16092 fix: actions in task card
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
Labels: cla-signed

#16093 fix: tidb require default for separate primary key definition
  backend/plugin/advisor/mysql/advisor_column_require_default.go
  backend/plugin/advisor/mysql/advisor_column_set_default_for_not_null.go
  backend/plugin/advisor/mysql/test/column_require_default.yaml
  backend/plugin/advisor/pg/test/column_require_default.yaml
  backend/plugin/advisor/tidb/advisor_column_require_default.go
  backend/plugin/advisor/tidb/test/column_require_default.yaml
Labels: cla-signed

#16095 chore(action): add bash
  scripts/Dockerfile.action
Labels: cla-signed

#16094 chore: delete order by
  backend/plugin/db/tidb/sync.go
Labels: cla-signed

#16096 chore: batch get users
  backend/api/v1/user_service.go
  frontend/src/types/proto/v1/user_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/user_service.pb.go
  proto/generated-go/v1/user_service.pb.gw.go
  proto/generated-go/v1/user_service_grpc.pb.go
  proto/v1/v1/user_service.proto
Labels: cla-signed

#16097 chore(action): add gcompat
  scripts/Dockerfile.action
Labels: cla-signed

#16098 chore: build debian-based action image
  .github/workflows/build-push-action-image.yml
  scripts/Dockerfile.action-debian
Labels: cla-signed

#16100 chore: use batchGetUsers in frontend
  frontend/src/components/IssueV1/components/CurrentApproverV1.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/IssueV1/logic/review.ts
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
  frontend/src/store/modules/release.ts
  frontend/src/store/modules/rollout.ts
  frontend/src/store/modules/user.ts
  frontend/src/store/modules/v1/changelist.ts
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/group.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/store/modules/v1/projectIamPolicy.ts
  frontend/src/store/modules/v1/worksheet.ts
  frontend/src/store/modules/workspaceApprovalSetting.ts
  frontend/src/utils/v1/advanced-search/issue/ui-filter.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/SettingWorkspaceMailDelivery.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed

#16101 fix: user name checks
  frontend/src/store/modules/user.ts
Labels: cla-signed

#16102 fix(action): skip annotate
  action/bitbucket.go
Labels: cla-signed

#16103 chore: unify debounce delay value
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/ExprEditor/components/MultiSelect.vue
  frontend/src/components/ExprEditor/components/SingleSelect.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscriberList.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
  frontend/src/components/v2/Select/DatabaseSelect.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/components/v2/Select/UserSelect.vue
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/types/common.ts
  frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#16105 chore: cache query result
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/types/sqlEditor/tab.ts
  frontend/src/utils/sqlEditor.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/TerminalPanel.vue
Labels: cla-signed

#16107 fix: remove not existed database from result
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
Labels: cla-signed

#16110 fix: missing provide issue instance context
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
Labels: cla-signed

#16111 chore: tweak tabs' padding
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
Labels: cla-signed

#16113 chore: update comment
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16112 chore(sql-editor): update tab's padding
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
Labels: cla-signed

#16114 chore: only keep at most 10 results
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
Labels: cla-signed

#16115 fix: is plain field only supports mysql
  backend/api/v1/query_result_masker.go
  backend/base/engine.go
  backend/plugin/parser/tidb/test-data/query_span.yaml
  backend/plugin/parser/trino/test-data/query-span/case-sensitivity.yaml
  backend/plugin/parser/trino/test-data/query-span/join.yaml
  backend/plugin/parser/trino/test-data/query-span/query_type.yaml
  backend/plugin/parser/trino/test-data/query-span/standard.yaml
  backend/plugin/parser/trino/test-data/query-span/trino-specific.yaml
Labels: cla-signed

#16116 chore: use dml as default change type
  frontend/src/components/IssueV1/components/SQLCheckSection/common.ts
Labels: cla-signed

#16117 chore: update database group message
  backend/api/v1/database_group_service.go
  backend/tests/grouping_change_test.go
  backend/tests/tenant_test.go
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/components/v2/Model/DatabaseGroupName.vue
  frontend/src/components/v2/Select/DatabaseGroupSelect.vue
  frontend/src/store/modules/dbGroup.ts
  frontend/src/types/dbGroup.ts
  frontend/src/types/proto/v1/database_group_service.ts
  frontend/src/utils/databaseGroup/issue.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_group_service.pb.go
  proto/v1/v1/database_group_service.proto
Labels: cla-signed

#16118 chore(plan): tweak comment
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#15988 feat: get notice for pg
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/clickhouse/query.go
  backend/plugin/db/cockroachdb/cockroachdb.go
  backend/plugin/db/dm/dm.go
  backend/plugin/db/driver.go
  backend/plugin/db/mssql/mssql.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/obo/obo.go
  backend/plugin/db/oracle/oracle.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/db/risingwave/risingwave.go
  backend/plugin/db/snowflake/snowflake.go
  backend/plugin/db/spanner/spanner.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
  backend/plugin/db/trino/trino.go
  backend/plugin/db/util/driverutil.go
Labels: cla-signed

#16121 chore: 3.6.2
  scripts/VERSION
Labels: cla-signed

#16122 chore: tweak data source query restriction policy wording
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16123 feat: query lazy load & support database group in batch query
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/dbGroup.ts
  frontend/src/store/modules/export.ts
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/sqlEditor/tab.ts
  frontend/src/utils/sqlEditor.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/HoverPanel/HoverPanel.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/BatchQueryDatabaseGroupSelector.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/DatabaseGroupTag.vue
  frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/DatabaseQueryContext.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
Labels: cla-signed

#16124 chore: refuse empty data source id in SQLService.Query
  backend/api/v1/sql_service.go
  backend/tests/sql_export_test.go
Labels: cla-signed

#16125 fix: several fix
  backend/api/v1/database_group_service.go
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/SQLReview/SQLReviewCreation.vue
  frontend/src/components/SQLReview/SQLReviewInfo.vue
  frontend/src/types/proto/v1/database_group_service.ts
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_group_service.pb.go
  proto/v1/v1/database_group_service.proto
Labels: cla-signed

#16126 fix: expr selector
  frontend/src/components/ExprEditor/components/MultiSelect.vue
  frontend/src/components/ExprEditor/components/SingleSelect.vue
Labels: cla-signed

#16127 chore: no VERSION
  .github/workflows/build-push-release-image.yml
  .github/workflows/docker-tag-latest.yml
  scripts/VERSION
  scripts/build_init.sh
Labels: cla-signed

#16128 feat: block tasks within the same pipeline
  backend/runner/taskrun/schedulerv2.go
  backend/store/task.go
Labels: cla-signed

#16129 refactor: pre-backup setting section
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/common.ts
  frontend/src/components/IssueV1/logic/index.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/plan.ts
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckBadge.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckSection.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/index.ts
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/utils.ts
  frontend/src/components/Plan/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Sidebar/index.ts
  frontend/src/components/Plan/components/SpecListSection/CurrentSpecSection.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/index.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/initialize/util.ts
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/components/Plan/logic/plan.ts
  frontend/src/components/Plan/logic/sidebar.ts
  frontend/src/components/SchemaEditorLite/common.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/logic/useDynamicSuggestions.ts
  frontend/src/utils/web-storage.ts
  frontend/src/views/ReviewCenter/SQLReviewIssueDataTable/SQLReviewIssueDataTable.vue
Labels: cla-signed

#16130 fix: context key
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
Labels: cla-signed

#16132 chore: clean non-semantic version
  backend/migrator/migration/3.6/0005##backfill_task_version.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16131 feat: default to ro data source
  frontend/src/utils/sqlEditor.ts
Labels: cla-signed

#16134 chore: remove unused activity types
  backend/api/v1/project_service.go
  frontend/src/types/proto/v1/project_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/project_service.pb.go
  proto/v1/v1/project_service.proto
Labels: cla-signed

#16133 chore: update plan utils
  frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/RolloutTaskDatabaseName.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/utils.ts
  frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/AffectedRowsView.vue
  frontend/src/components/IssueV1/components/Sidebar/TaskCheckSummarySection/FailedTasksView.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/CurrentTaskSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/IssueV1/logic/plan-check.ts
  frontend/src/components/IssueV1/logic/poll.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
  frontend/src/components/Plan/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Rollout/RolloutDetail/index.ts
  frontend/src/components/Rollout/RolloutDetail/utils.ts
  frontend/src/types/issue.ts
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
Labels: cla-signed

#16135 feat: rollout task key + instance
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16136 fix: connect instead of batch if no connection
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
Labels: cla-signed

#16138 fix: rollout task key
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16137 chore: version model
  backend/store/model/version.go
  backend/store/model/version_test.go
Labels: cla-signed

#16139 chore: semantic version compare
  backend/store/task.go
Labels: cla-signed

#16140 fix: env args for cacl risk level
  backend/api/v1/release_service_check.go
Labels: cla-signed

#16141 chore: validate and sort versions
  backend/api/v1/release_service.go
  backend/store/model/version.go
Labels: cla-signed

#16143 refactor: request role
  backend/api/v1/project_service.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleForm.vue
  frontend/src/components/CustomApproval/Settings/components/common/RequiredStar.vue
  frontend/src/components/CustomApproval/Settings/components/common/index.ts
  frontend/src/components/ExpirationSelector.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
  frontend/src/components/IssueV1/components/GrantRequest/GrantRequestExporterForm.vue
  frontend/src/components/IssueV1/components/GrantRequest/GrantRequestQuerierForm.vue
  frontend/src/components/IssueV1/components/GrantRequest/index.ts
  frontend/src/components/Member/MembersBindingSelect.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMembersPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Select/ResourceSelect.vue
  frontend/src/components/v2/Select/RoleSelect.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/issue/issue.ts
Labels: cla-signed

#16144 chore(action): update readme
  action/README.md
Labels: cla-signed

#16145 chore: risk level calculate func
  backend/api/v1/release_service_check.go
  backend/api/v1/risk_service_calculator.go
  backend/runner/approval/runner.go
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
Labels: cla-signed

#16147 chore: always tag action latest
  .github/workflows/build-push-action-image.yml
Labels: cla-signed

#16149 chore: log
  action/main.go
Labels: cla-signed

#16148 fix: double release file
  backend/api/v1/release_service.go
Labels: cla-signed

#16150 chore: optimize loop
  backend/api/v1/release_service.go
Labels: cla-signed

#16151 fix: drift git commit
  backend/api/v1/database_service.go
  backend/runner/taskrun/executor.go
Labels: cla-signed, backport release/3.6.1

#16154 chore: dummy version zero
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
Labels: cla-signed

#16156 chore: mssql schema text
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#16157 fix: layout in small screen
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
Labels: cla-signed

#16159 chore: control c3 recursion depth
  backend/plugin/parser/base/c3.go
Labels: cla-signed

#16158 chore: dynamic import `monaco-vscode-api`
  frontend/package.json
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/DurationCell.vue
  frontend/src/components/MonacoEditor/services.ts
  frontend/src/main.ts
  frontend/src/shims-vue-globals.d.ts
Labels: cla-signed

#16161 chore: fix masking
  backend/base/engine.go
  backend/plugin/parser/trino/query_span_dac.go
  backend/plugin/parser/trino/query_span_dac_test.go
  backend/plugin/parser/trino/query_span_extractor.go
  backend/plugin/parser/trino/query_span_listener.go
  backend/plugin/parser/trino/query_span_predicate.go
  backend/plugin/parser/trino/query_span_test.go
  backend/plugin/parser/trino/test-data/query-span/masking.yaml
Labels: cla-signed

#16153 feat: request any roles
  backend/api/v1/risk_service.go
  backend/runner/approval/runner.go
  backend/store/risk.go
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/plugins/cel/types/operator.ts
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/risk.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/views/auth/Signup.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/risk_service.pb.go
  proto/v1/v1/risk_service.proto
Labels: cla-signed

#16160 refactor: gh-ost setting section
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostConfigButton.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/IssueV1/components/Sidebar/GhostSection/common.ts
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/FlagsForm/BoolFlag.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/FlagsForm/FlagsForm.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/FlagsForm/constants.ts
  frontend/src/components/Plan/components/Sidebar/GhostSection/FlagsForm/index.ts
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/common.ts
  frontend/src/components/Plan/components/Sidebar/GhostSection/context.ts
  frontend/src/components/Plan/components/Sidebar/GhostSection/index.ts
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
  frontend/src/components/Plan/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Sidebar/index.ts
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16162 chore: use show to prevent reloading
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
Labels: cla-signed

#16163 chore: unify risk source for request role
  backend/api/v1/risk_service.go
  backend/runner/approval/runner.go
  backend/store/risk.go
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/risk.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/risk_service.pb.go
  proto/v1/v1/risk_service.proto
Labels: cla-signed

#16164 chore: update risk factors
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
Labels: cla-signed

#16165 fix: risk cel variables
  backend/common/cel.go
Labels: cla-signed

#16166 chore: set role attribute
  backend/runner/approval/runner.go
Labels: cla-signed

#16167 chore: use partial eval consistently
  backend/runner/approval/runner.go
Labels: cla-signed

#16169 chore: update approval runner
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_task.go
  backend/runner/approval/runner.go
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
Labels: cla-signed

#16171 chore: update trino mask frontend
  frontend/src/components/ColumnDataTable/index.vue
Labels: cla-signed

#16172 fix: handle undefined db groups
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/types/sqlEditor/tab.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/EditorCommon/DatabaseChooser.vue
Labels: cla-signed, backport release/3.6.2

#16174 chore: custom approval is not a instance limit feature
  backend/base/plan.go
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/utils.ts
  frontend/src/components/v2/Select/RoleSelect.vue
  frontend/src/types/plan.ts
Labels: cla-signed

#16176 chore: clean frontend dependencies
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/main.ts
Labels: cla-signed

#16177 chore: backfill request query export risk
  backend/migrator/migration/3.6/0006##risk_role.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16178 feat: taskrun run at
  backend/migrator/migration/3.7/0000##taskrun_rollout_at.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16180 feat(proto): taskrun run time
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16179 chore: approval template no creator
  backend/api/v1/setting_service.go
  backend/migrator/migration/3.7/0001##approval_template_creator.sql
  backend/migrator/migration/3.7/0002##risk_role.sql
  backend/migrator/migrator_test.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleForm.vue
  frontend/src/store/modules/workspaceApprovalSetting.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/utils/workspaceApprovalSetting.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/approval.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/store/store/approval.proto
  proto/v1/v1/issue_service.proto
Labels: cla-signed

#16182 feat: impl taskRun runAt
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/task.go
  backend/store/task_run.go
Labels: cla-signed

#16183 refactor: unify sql check section in plan&issue
  frontend/i18n.ts
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/IssueV1/components/SQLCheckSection/context.ts
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/IssueV1/components/StatementSection/useTaskSheet.ts
  frontend/src/components/IssueV1/components/TaskListSection/TaskFilter.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/filter.ts
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/IssueV1/components/index.ts
  frontend/src/components/IssueV1/logic/index.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/IssueV1/logic/sheet.ts
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/SQLCheckSection/AdviceStatusIcon.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckSection/common.ts
  frontend/src/components/Plan/components/SQLCheckSection/context.ts
  frontend/src/components/Plan/components/SQLCheckSection/index.ts
  frontend/src/components/Plan/components/SQLCheckSectionV1/AdviceStatusIcon.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckBadge.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckSectionV1/common.ts
  frontend/src/components/Plan/components/SQLCheckSectionV1/context.ts
  frontend/src/components/Plan/components/SQLCheckSectionV1/index.ts
  frontend/src/components/Plan/components/SpecListSection/SpecFilter.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Plan/components/SpecListSection/filter.ts
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/useTempEditState.ts
  frontend/src/components/Plan/components/StatementSection/useSpecSheet.ts
  frontend/src/components/Plan/components/index.ts
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
Labels: cla-signed

#16184 chore: backfill approval rules
  backend/migrator/migration/3.7/0003##approval_setting_cleanup.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16186 chore: sync and dump pg check constraints
  backend/plugin/db/pg/sync.go
  backend/plugin/schema/pg/get_database_definition.go
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/store/database.proto
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16189 chore: use tidb yacc parser to diagnose
  backend/plugin/parser/mysql/diagnose.go
  backend/plugin/parser/tidb/diagnose.go
Labels: cla-signed

#16190 feat: set StartAt when it really starts
  backend/runner/taskrun/schedulerv2.go
  backend/store/task_run.go
Labels: cla-signed

#16195 fix: show feature attention
  frontend/src/components/FeatureGuard/FeatureAttention.vue
Labels: cla-signed

#16197 chore: batch create sheets - rename
  backend/api/v1/release_service.go
  backend/api/v1/sheet_service.go
  backend/component/sheet/sheet.go
  frontend/src/types/proto/v1/sheet_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/sheet_service.pb.go
  proto/generated-go/v1/sheet_service.pb.gw.go
  proto/generated-go/v1/sheet_service_grpc.pb.go
  proto/v1/v1/sheet_service.proto
Labels: cla-signed

#16191 chore: deprecate earliest_allowed_time
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/migrator/migration/3.7/0004##remove_task_earliest_allowed_at.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/task.go
  frontend/src/components/IssueV1/components/Sidebar/EarliestAllowedTime.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/plan.pb.go
  proto/generated-go/v1/plan_service.pb.go
  proto/store/store/plan.proto
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#16196 chore: batch create revisions
  backend/api/v1/revision_service.go
  frontend/src/types/proto/v1/revision_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/revision_service.pb.go
  proto/generated-go/v1/revision_service.pb.gw.go
  proto/generated-go/v1/revision_service_grpc.pb.go
  proto/v1/v1/revision_service.proto
Labels: cla-signed

#16198 chore: remove issue comment earliest allowed time
  backend/api/v1/issue_service_convert.go
  backend/migrator/migration/3.7/0005##remove_issue_comment_earliest_allowed_at.sql
  backend/migrator/migrator_test.go
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionSentence.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/v1/issue_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/issue_comment.pb.go
  proto/generated-go/v1/issue_service.pb.go
  proto/store/store/issue_comment.proto
  proto/v1/v1/issue_service.proto
Labels: cla-signed

#16201 feat: set run time in task rollout panel
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16199 fix: should not skip the check when instance not support sql review
  backend/api/v1/release_service_check.go
Labels: cla-signed

#16203 fix: export with ds
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: backport release/3.6.2

#16209 fix: refresh changelog table after establish baseline
  frontend/src/components/Changelog/ChangelogDataTable.vue
  frontend/src/components/Database/DatabaseChangelogPanel.vue
Labels: cla-signed

#16217 chore: prune migration files
  backend/migrator/migration/2.22/0000##update_policy.sql
  backend/migrator/migration/2.22/0001##workspace_iam_policy.sql
  backend/migrator/migration/2.22/0002##drop_env_index.sql
  backend/migrator/migration/2.22/0003##data_source_query_env_policy.sql
  backend/migrator/migration/2.22/0004##db_schema_json.sql
  backend/migrator/migration/2.23/0000##principal_profile.sql
  backend/migrator/migration/2.23/0001##deprecate_member.sql
Labels: cla-signed

#16218 chore: remove creator entity from composed issue
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscriberList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/Subscribers.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/Plan/components/SQLCheckSection/index.ts
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/v1/issue/issue.ts
Labels: cla-signed

#16219 chore: update i18n
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16220 fix: data source id is optional in export
  backend/api/v1/sql_service.go
  proto/gen/grpc-doc/openapi.yaml
  proto/generated-go/v1/sql_service.pb.go
  proto/v1/v1/sql_service.proto
Labels: cla-signed

#16227 refactor: remove projectEntity from composed plan
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
  frontend/src/components/IssueV1/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/review/IssueReviewButtonGroup.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/Subscribers.vue
  frontend/src/components/IssueV1/components/Panel/IssueReviewActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/RolloutTaskDatabaseName.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/IssueV1/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/PreBackupSection.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/IssueV1/components/StageSection/StageSection.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/CurrentTaskSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/context.ts
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/DescriptionSection/DescriptionSection.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/Plan/components/HeaderSection/Title.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/SpecListSection/CurrentSpecSection.vue
  frontend/src/components/Plan/components/SpecListSection/SpecCard.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/components/Plan/logic/utils.ts
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/store/modules/v1/plan.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/types/v1/issue/plan.ts
Labels: cla-signed

#16230 feat: prompt to refresh if versions mismatch
  frontend/index.html
  frontend/src/components/misc/Version.vue
  frontend/src/components/misc/Watermark.vue
  frontend/src/layouts/BodyLayout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/actuator.ts
Labels: cla-signed

#16231 chore: use const
  backend/api/v1/instance_service.go
Labels: cla-signed

#16232 chore: debounce for params update
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
Labels: cla-signed

#16233 chore: random mysql ssh connection scheme
  backend/plugin/db/mysql/mysql.go
  backend/plugin/db/starrocks/starrocks.go
  backend/plugin/db/tidb/tidb.go
Labels: cla-signed

#16235 fix: export ds ignore the policy
  backend/api/v1/sql_service.go
Labels: cla-signed
