Repository bytebase/bytebase, pull requests merged in 2025-06, with the labels that each got.

#16356 chore: some minor updates
  backend/api/directory-sync/webhook.go
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/SchemaPane.vue
Labels: cla-signed

#16369 chore: adjust gh-ost and backup checks in frontend
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSection.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/context.ts
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/context.ts
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16370 chore: move expand keys to local storage
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/types/sqlEditor/tree.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
Labels: cla-signed

#16371 chore: fix current spec section display
  frontend/src/components/IssueV1/components/TaskListSection/TaskListSection.vue
  frontend/src/components/Plan/components/SpecListSection/SpecListSection.vue
Labels: cla-signed

#16372 chore: remove unused type
  backend/base/policy.go
Labels: cla-signed

#16374 chore(action): update defaults & log hint
  action/main.go
Labels: cla-signed

#16375 chore: store issue status protofying
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/plan_service.go
  backend/api/v1/project_service.go
  backend/base/issue.go
  backend/component/webhook/manager.go
  backend/runner/approval/runner.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/issue.go
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/issue.pb.go
  proto/store/store/issue.proto
Labels: cla-signed

#16379 feat: implement get database schema metadata for SQL Server
  backend/plugin/advisor/mssql/advisor_column_no_null.go
  backend/plugin/advisor/mssql/advisor_index_not_redundant.go
  backend/plugin/schema/mssql/get_database_metadata.go
  backend/plugin/schema/mssql/get_database_metadata_test.go
  backend/plugin/schema/mssql/test-data/test_get_database_metadata.yaml
  backend/plugin/schema/schema.go
  go.mod
  go.sum
Labels: cla-signed

#16384 chore: update ignored rs db
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#16378 feat: impl code complete cancellation
  backend/api/lsp/handler.go
  backend/plugin/parser/base/c3.go
  backend/plugin/parser/mysql/completion.go
  backend/plugin/parser/partiql/completion.go
  backend/plugin/parser/pg/completion.go
  backend/plugin/parser/plsql/completion.go
  backend/plugin/parser/trino/completion.go
  backend/plugin/parser/tsql/completion.go
Labels: cla-signed

#16385 chore: tweak layout padding
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Sidebar/GhostSection/GhostSwitch.vue
  frontend/src/components/Plan/components/Sidebar/PreBackupSection/PreBackupSwitch.vue
  frontend/src/components/Plan/components/Sidebar/Sidebar.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/views/project/ProjectIssueDetail.vue
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16387 chore: use LocaleString
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunComment.vue
Labels: cla-signed

#16386 chore: protofying store user type
  .vscode/settings.json
  backend/api/directory-sync/webhook.go
  backend/api/v1/actuator_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/group_service.go
  backend/api/v1/user_service.go
  backend/api/v1/workspace_service.go
  backend/base/principal.go
  backend/base/task_run.go
  backend/component/webhook/manager.go
  backend/store/principal.go
  backend/store/stats.go
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/user.pb.go
  proto/store/store/user.proto
Labels: cla-signed

#16391 feat: remind role expiration
  frontend/src/components/IAMRemindModal.vue
  frontend/src/components/IssueV1/components/GrantRequest/DatabaseResourceTable.vue
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/RoleExpiredTip.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/components/ReleaseRemindModal.vue
  frontend/src/components/misc/Version.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/permission.ts
  frontend/src/store/modules/v1/workspace.ts
  frontend/src/utils/v1/iam.ts
  frontend/src/views/DashboardLanding.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
  frontend/src/views/sql-editor/Setting/Project/Project.vue
Labels: cla-signed

#16394 chore: update edit statement checks
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/logic/rollout.ts
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16395 fix: auto reset in selector
  frontend/src/components/v2/Select/DatabaseSelect.vue
  frontend/src/components/v2/Select/InstanceSelect.vue
  frontend/src/components/v2/Select/UserSelect.vue
Labels: cla-signed

#16398 chore: update claude.md
  CLAUDE.md
Labels: cla-signed

#16397 chore: unify bbdataarchive references
  backend/api/v1/sql_service.go
  backend/base/database.go
  backend/component/ghost/config.go
  backend/plugin/advisor/mysql/advisor_online_migration.go
  backend/plugin/advisor/utils_for_tests.go
  backend/plugin/schema/pg/get_database_definition.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/schemasync/syncer.go
  backend/runner/taskrun/schema_update_ghost_executor.go
  backend/tests/ghost_test.go
Labels: cla-signed

#16401 chore: fix display of plan check runs
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
Labels: cla-signed

#16400 chore: task type proto
  backend/api/v1/issue_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/base/policy.go
  backend/base/task.go
  backend/migrator/migration/3.7/0017##backfill_task_type.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/approval/runner.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/server/server.go
  backend/store/issue.go
  backend/store/task.go
  frontend/src/components/IssueV1/logic/action/task.ts
  frontend/src/components/IssueV1/logic/poll.ts
  frontend/src/components/IssueV1/logic/utils.ts
  frontend/src/components/Rollout/RolloutDetail/utils.ts
  frontend/src/types/proto/v1/rollout_service.ts
  frontend/src/types/v1/issue/rollout.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/task.pb.go
  proto/generated-go/v1/rollout_service.pb.go
  proto/store/store/task.proto
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16405 chore: some code & ui optimize
  frontend/src/bbkit/BBButtonConfirm.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/FlowsPanel/FlowTable.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RulesPanel/RuleSelect.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskTable.vue
  frontend/src/components/CustomApproval/Settings/components/common/SpinnerButton.vue
  frontend/src/components/CustomApproval/Settings/components/common/SpinnerSwitch.vue
  frontend/src/components/CustomApproval/Settings/components/common/index.ts
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/DatabaseChangeModeSetting.vue
  frontend/src/components/GeneralSetting/DomainRestrictionSetting.vue
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
  frontend/src/components/Member/MemberDataTable/index.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicyDataTable.vue
  frontend/src/components/SQLReview/components/SQLReviewPolicyTable.vue
  frontend/src/components/SensitiveData/MaskingExceptionUserTable.vue
  frontend/src/components/v2/Form/SpinnerSelect.vue
  frontend/src/components/v2/Form/SpinnerSwitch.vue
  frontend/src/components/v2/Form/index.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/views/Setup/WorkspaceMode.vue
Labels: cla-signed

#16406 chore: policy type proto
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_config_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/workspace_service.go
  backend/base/policy.go
  backend/migrator/migration/3.7/0018##migrate_policy_type.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/policy.go
  backend/store/principal.go
  backend/store/project.go
  backend/store/role.go
  backend/store/store.go
  backend/utils/utils.go
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/policy.pb.go
  proto/store/store/policy.proto
Labels: cla-signed

#16407 chore: remove unused policy resource
  CLAUDE.md
  backend/api/v1/org_policy_service.go
  backend/base/policy.go
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/org_policy_service.pb.go
  proto/v1/v1/org_policy_service.proto
Labels: cla-signed

#16411 feat: batch update instances
  backend/api/v1/instance_service.go
  frontend/src/components/EditEnvironmentDrawer.vue
  frontend/src/components/Instance/InstanceSyncButton.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/components/v2/Model/Instance/InstanceV1Table/InstanceOperations.vue
  frontend/src/store/modules/v1/instance.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/InstanceDetail.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/instance_service.pb.go
  proto/generated-go/v1/instance_service.pb.gw.go
  proto/generated-go/v1/instance_service_grpc.pb.go
  proto/v1/v1/instance_service.proto
Labels: cla-signed

#16404 chore: use environment as stage id, remove stage
  backend/api/v1/issue_service.go
  backend/api/v1/issue_service_convert.go
  backend/api/v1/plan_service.go
  backend/api/v1/revision_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/api/v1/rollout_service_task.go
  backend/api/v1/sql_service.go
  backend/common/resource_name.go
  backend/migrator/migration/3.7/0020##add_and_migrate_task_environment_change_stage_uid_to_envid_remove_stage.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/approval/runner.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/pipeline.go
  backend/store/rollout.go
  backend/store/stage.go
  backend/store/task.go
  backend/store/task_run.go
  frontend/src/components/IssueV1/logic/base.ts
  frontend/src/components/IssueV1/logic/initialize/create.ts
  frontend/src/utils/v1/issue/rollout.ts
Labels: cla-signed

#16414 fix: data race in license service
  backend/enterprise/service/license.go
Labels: cla-signed

#16413 chore: implement database schema metadata differ
  backend/plugin/schema/differ.go
Labels: cla-signed

#16412 fix: stage status update event url
  backend/component/webhook/event.go
  backend/component/webhook/manager.go
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16419 chore: update demo data from 3.6.2 to 3.7.0
  backend/demo/README.md
  backend/demo/data/dump.sql
Labels: cla-signed

#16417 chore(proto): update stage comment
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16420 chore: proto policy resource type
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_config_service.go
  backend/api/v1/role_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/workspace_service.go
  backend/base/policy.go
  backend/migrator/migration/3.7/0022##policy_resource_type_check_drop.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/policy.go
  backend/store/principal.go
  backend/store/project.go
  backend/store/role.go
  backend/store/store.go
  backend/utils/utils.go
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/generated-go/store/policy.pb.go
  proto/store/store/policy.proto
Labels: cla-signed

#16422 fix: stage environment format
  backend/api/v1/rollout_service_converter.go
  frontend/src/types/proto/v1/rollout_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/rollout_service.pb.go
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16426 feat(action): impl check-release flag for check command
  action/README.md
  action/main.go
Labels: cla-signed

#16431 feat(action): print version and check server version
  .github/workflows/build-push-action-image.yml
  action/api.go
  action/args/version.go
  action/main.go
  scripts/Dockerfile.action
  scripts/Dockerfile.action-debian
Labels: cla-signed

#16436 feat: view safe order with topo sort for sql server
  backend/plugin/schema/mssql/generate_migration.go
  backend/plugin/schema/mssql/generate_migration_test.go
  backend/plugin/schema/mssql/test-data/test_migration_constraints.yaml
  backend/plugin/schema/mssql/test-data/test_migration_functions.yaml
  backend/plugin/schema/mssql/test-data/test_migration_indexes.yaml
  backend/plugin/schema/mssql/test-data/test_migration_procedures.yaml
  backend/plugin/schema/mssql/test-data/test_migration_safe_order.yaml
  backend/plugin/schema/mssql/test-data/test_migration_tables.yaml
  backend/plugin/schema/mssql/test-data/test_migration_views.yaml
Labels: cla-signed

#16438 chore: fix demo data
  backend/demo/data/dump.sql
Labels: cla-signed

#16439 chore: fix feature typo
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
Labels: cla-signed

#16440 chore: add rollout to plan
  backend/api/v1/rollout_service_converter.go
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#16442 fix: use strconv
  action/github/github.go
Labels: cla-signed

#16445 fix: check update binding
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
Labels: cla-signed

#16447 fix(parser): use proto name for table and view identifiers
  backend/plugin/parser/bigquery/query_span_extractor.go
  backend/plugin/parser/bigquery/test-data/query-span/standard.yaml
  backend/plugin/parser/mysql/query_span_extractor.go
  backend/plugin/parser/mysql/test-data/query-span/case_insensitive.yaml
  backend/plugin/parser/pg/query_span_extractor.go
  backend/plugin/parser/plsql/query_span_extractor.go
  backend/plugin/parser/snowflake/query_span_extractor.go
  backend/plugin/parser/spanner/query_span_extractor.go
  backend/plugin/parser/spanner/test-data/query-span/standard.yaml
  backend/plugin/parser/tidb/query_span_extractor.go
  backend/plugin/parser/trino/query_span_listener.go
  backend/plugin/parser/trino/test-data/query-span/masking.yaml
  backend/plugin/parser/trino/test-data/query-span/trino-specific.yaml
  backend/plugin/parser/tsql/query_span_extractor.go
Labels: cla-signed

#16451 refactor: use switch for branches
  backend/runner/taskrun/schedulerv2.go
Labels: cla-signed

#16453 chore: simple features
  backend/base/plan.go
  backend/enterprise/api/plan.yaml
  frontend/src/types/plan.ts
Labels: cla-signed

#16452 refactor: remove `ComposedPlan` type
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/Plan/components/Navigator.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanCheckSection/SpecBasedPlanCheckSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/useSQLAdviceMarkers.ts
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/components/Plan/logic/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/v1/issue/plan.ts
  frontend/src/views/ReviewCenter/index.vue
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16456 refactor(mysql): extract charset and sql mode writes into helper
  backend/plugin/schema/mysql/get_database_definition.go
Labels: cla-signed

#16460 fix: icon
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
Labels: cla-signed

#16463 chore: use proto string
  backend/enterprise/api/plan.yaml
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16465 chore: remove unused code
  frontend/src/layouts/BodyLayout.vue
Labels: cla-signed

#16466 fix: use the camel case for key
  backend/enterprise/api/plan.yaml
Labels: cla-signed

#16469 chore: refactor backend features
  backend/api/directory-sync/webhook.go
  backend/api/v1/actuator_service.go
  backend/api/v1/audit_log_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_group_service.go
  backend/api/v1/database_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_config_service.go
  backend/api/v1/risk_service.go
  backend/api/v1/role_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/subscription_service.go
  backend/api/v1/user_service.go
  backend/base/plan.go
  backend/component/iam/manager.go
  backend/enterprise/api/license.go
  backend/enterprise/api/limit.go
  backend/enterprise/api/plan.yaml
  backend/enterprise/service/license.go
  backend/runner/approval/runner.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/tests/data_source_test.go
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16467 fix: empty sha256 for release file statement
  backend/api/v1/release_service.go
  backend/api/v1/release_service_check.go
  frontend/src/types/proto/v1/release_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/release_service.pb.go
  proto/v1/v1/release_service.proto
Labels: cla-signed, backport release/3.7.0

#16472 chore: optimize connection
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
Labels: cla-signed

#16473 feat: get database metadata for pg
  backend/plugin/parser/pg/pg.go
  backend/plugin/schema/pg/get_database_metadata.go
  backend/plugin/schema/pg/get_database_metadata_test.go
  backend/plugin/schema/pg/testdata/get_database_metadata.yaml
  go.mod
  go.sum
Labels: cla-signed

#16474 chore: skip dump for differ
  backend/plugin/schema/differ.go
Labels: cla-signed

#16477 chore: handle release in creating plan check runs
  backend/api/v1/plan_service_plan_check.go
Labels: cla-signed

#16476 feat: gitops tests
  backend/tests/gitops_test.go
  backend/tests/tests.go
Labels: cla-signed

#16481 chore: remove free feature guard and remove GetFeatureMatrix call
  backend/api/v1/org_policy_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/subscription_service.go
  backend/component/iam/manager.go
  backend/enterprise/api/plan.yaml
  backend/runner/plancheck/statement_advise_executor.go
  frontend/src/components/Database/context.ts
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/components/GeneralSetting/QueryDataPolicySetting.vue
  frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/IssueV1/components/StatementSection/SDLView/SDLView.vue
  frontend/src/components/IssueV1/components/StatementSection/SDLView/index.ts
  frontend/src/components/IssueV1/components/StatementSection/SDLView/useSDLState.ts
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableList/TableList.vue
  frontend/src/components/SchemaTemplate/TableTemplateForm.vue
  frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto/v1/subscription_service.ts
  frontend/src/utils/v1/database.ts
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingWorkspaceMembers.vue
  frontend/src/views/SettingWorkspaceSQLReviewCreate.vue
  frontend/src/views/SettingWorkspaceSQLReviewDetail.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/EditorCommon/EditorAction.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/generated-go/v1/subscription_service_grpc.pb.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16483 chore: feature i18n
  CLAUDE.md
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/locales/dynamic/en-US.json
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/BannerUpgradeSubscription.vue
Labels: cla-signed

#16485 fix: reintroduce from json
  frontend/src/store/modules/sqlEditor/webTerminal.ts
  frontend/src/types/proto/google/api/expr/v1alpha1/syntax.ts
  frontend/src/types/proto/google/api/http.ts
  frontend/src/types/proto/google/api/resource.ts
  frontend/src/types/proto/google/protobuf/any.ts
  frontend/src/types/proto/google/protobuf/descriptor.ts
  frontend/src/types/proto/google/protobuf/duration.ts
  frontend/src/types/proto/google/protobuf/empty.ts
  frontend/src/types/proto/google/protobuf/field_mask.ts
  frontend/src/types/proto/google/protobuf/struct.ts
  frontend/src/types/proto/google/protobuf/timestamp.ts
  frontend/src/types/proto/google/rpc/status.ts
  frontend/src/types/proto/google/type/expr.ts
  frontend/src/types/proto/v1/actuator_service.ts
  frontend/src/types/proto/v1/audit_log_service.ts
  frontend/src/types/proto/v1/auth_service.ts
  frontend/src/types/proto/v1/cel_service.ts
  frontend/src/types/proto/v1/changelist_service.ts
  frontend/src/types/proto/v1/common.ts
  frontend/src/types/proto/v1/database_catalog_service.ts
  frontend/src/types/proto/v1/database_group_service.ts
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/types/proto/v1/group_service.ts
  frontend/src/types/proto/v1/iam_policy.ts
  frontend/src/types/proto/v1/idp_service.ts
  frontend/src/types/proto/v1/instance_role_service.ts
  frontend/src/types/proto/v1/instance_service.ts
  frontend/src/types/proto/v1/issue_service.ts
  frontend/src/types/proto/v1/org_policy_service.ts
  frontend/src/types/proto/v1/plan_service.ts
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/proto/v1/release_service.ts
  frontend/src/types/proto/v1/review_config_service.ts
  frontend/src/types/proto/v1/revision_service.ts
  frontend/src/types/proto/v1/risk_service.ts
  frontend/src/types/proto/v1/role_service.ts
  frontend/src/types/proto/v1/rollout_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  frontend/src/types/proto/v1/sheet_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/types/proto/v1/subscription_service.ts
  frontend/src/types/proto/v1/user_service.ts
  frontend/src/types/proto/v1/worksheet_service.ts
  proto/buf.gen.yaml
Labels: cla-signed

#16487 chore: simplify subscription helper
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/components/TrialModal.vue
  frontend/src/components/UpgradeSubscriptionButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/subscription.ts
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#16491 chore: optimize query result
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/ResultPanel.vue
Labels: cla-signed

#16493 fix: ignore deleted database in BatchGetDatabases
  backend/api/v1/database_service.go
  backend/api/v1/worksheet_service.go
  frontend/src/views/sql-editor/EditorCommon/SharePopover.vue
Labels: cla-signed

#16495 fix: skip no permission database
  backend/api/v1/database_service.go
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/proto/v1/database_service.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  proto/generated-go/v1/database_service.pb.go
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16496 chore: reorg enterprise code
  backend/api/auth/auth.go
  backend/api/directory-sync/directory_sync.go
  backend/api/v1/actuator_service.go
  backend/api/v1/audit_log_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/database_group_service.go
  backend/api/v1/database_service.go
  backend/api/v1/group_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/project_service.go
  backend/api/v1/review_config_service.go
  backend/api/v1/risk_service.go
  backend/api/v1/role_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sheet_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/subscription_service.go
  backend/api/v1/user_service.go
  backend/component/iam/manager.go
  backend/enterprise/api/license.go
  backend/enterprise/license.go
  backend/enterprise/limit.go
  backend/enterprise/plan.yaml
  backend/enterprise/provider_aws.go
  backend/enterprise/provider_hub.go
  backend/runner/approval/runner.go
  backend/runner/metricreport/reporter.go
  backend/runner/plancheck/scheduler.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/taskrun/data_export_executor.go
  backend/runner/taskrun/data_update_executor.go
  backend/runner/taskrun/schedulerv2.go
  backend/runner/taskrun/schema_update_executor.go
  backend/runner/taskrun/schema_update_ghost_executor.go
  backend/server/grpc_routes.go
  backend/server/server.go
Labels: cla-signed

#16497 chore: refactor limit
  backend/api/v1/instance_service.go
  backend/api/v1/user_service.go
  backend/enterprise/license.go
  backend/enterprise/limit.go
  backend/enterprise/plugin/aws/aws.go
  backend/enterprise/plugin/hub/hub.go
Labels: cla-signed

#16498 chore: refactor license code and api
  .github/workflows/frontend-tests.yml
  backend/api/v1/acl_test.go
  backend/api/v1/subscription_service.go
  backend/enterprise/license.go
  backend/tests/subscription.go
  frontend/scripts/copy_config_files.sh
  frontend/src/components/FeatureGuard/FeatureAttention.vue
  frontend/src/components/FeatureGuard/FeatureBadge.vue
  frontend/src/components/FeatureGuard/FeatureModal.vue
  frontend/src/components/SQLReview/components/SQLRuleTable.vue
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/components/TrialModal.vue
  frontend/src/store/modules/v1/subscription.ts
  frontend/src/types/plan.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.d.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.js
  frontend/src/types/proto/v1/subscription_service.ts
  frontend/src/views/BannerUpgradeSubscription.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/generated-go/v1/subscription_service.pb.gw.go
  proto/generated-go/v1/subscription_service_grpc.pb.go
  proto/generated-go/v1/v1connect/subscription_service.connect.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16499 chore: sso feature guard backend
  backend/api/v1/idp_service.go
Labels: cla-signed

#16500 chore(es): fetch with credentials:include
  frontend/src/grpcweb/index.ts
Labels: cla-signed

#16501 chore: update fe feature guard
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/SSO/IdentityProviderCreateForm.vue
  frontend/src/components/SensitiveData/ClassificationView.vue
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#16502 chore: unify new plan drawer in review center
  frontend/eslint.config.mjs
  frontend/src/components/AlterSchemaPrepForm/AlterSchemaPrepForm.vue
  frontend/src/components/AlterSchemaPrepForm/index.ts
  frontend/src/components/Plan/components/AddSpecDrawer.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/CurrentSpecSelector.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/SpecsView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/ReviewCenter/index.vue
Labels: cla-signed

#16505 chore: improve expiration time selection UI
  frontend/src/components/ExpirationSelector.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16503 chore: implement filter to ListPlanCheckRunsRequest
  backend/api/v1/issue_service_test.go
  backend/api/v1/plan_service.go
  backend/api/v1/plan_service_test.go
  backend/store/plan_check_run.go
  frontend/src/types/proto-es/v1/plan_service_pb.d.ts
  frontend/src/types/proto-es/v1/plan_service_pb.js
  frontend/src/types/proto/v1/plan_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#16508 chore: emit predefined
  frontend/src/components/ExpirationSelector.vue
Labels: cla-signed

#16509 chore: add testcontainer-based test for get database metadata
  backend/plugin/schema/pg/get_database_metadata.go
  backend/plugin/schema/pg/get_database_metadata_test.go
  backend/plugin/schema/pg/get_database_metadata_testcontainer_test.go
  backend/plugin/schema/pg/testdata/get_database_metadata.yaml
  go.mod
  go.sum
Labels: cla-signed

#16510 fix: null check
  frontend/src/store/modules/sqlEditor/webTerminal.ts
Labels: cla-signed

#16511 fix: add missing feature guard
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
Labels: cla-signed

#16512 chore: tweak plan pages
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/AddSpecDrawer.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/SpecDetailView/AllTargetsDrawer.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/experimental-issue.ts
  frontend/src/store/modules/v1/plan.ts
  frontend/src/store/modules/v1/project.ts
  frontend/src/views/ReviewCenter/index.vue
  frontend/src/views/SettingWorkspaceSSO.vue
Labels: cla-signed

#16514 fix: export find task run
  backend/api/v1/sql_service.go
Labels: cla-signed

#16516 feat: migrate tests to using connect rpc clients
  backend/server/server.go
  backend/tests/change_history_test.go
  backend/tests/data_source_test.go
  backend/tests/database.go
  backend/tests/environment.go
  backend/tests/environment_test.go
  backend/tests/ghost_test.go
  backend/tests/gitops_test.go
  backend/tests/grouping_change_test.go
  backend/tests/project_test.go
  backend/tests/rollout.go
  backend/tests/schema_update_test.go
  backend/tests/sensitive_data_test.go
  backend/tests/sql.go
  backend/tests/sql_editor_test.go
  backend/tests/sql_export_test.go
  backend/tests/sql_review_test.go
  backend/tests/subscription.go
  backend/tests/sync_schema_test.go
  backend/tests/syncer_test.go
  backend/tests/tenant_test.go
  backend/tests/tests.go
  backend/tests/user_test.go
  go.mod
Labels: cla-signed

#16515 chore: external secret manager effective based on instance license
  backend/api/v1/auth_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/sql_service.go
  backend/common/util.go
  backend/component/dbfactory/dbfactory.go
  backend/enterprise/plan.yaml
  backend/server/server.go
  frontend/src/components/InstanceForm/ScanIntervalInput.vue
  frontend/src/locales/dynamic/en-US.json
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16519 chore: no mybatis
  backend/api/v1/sql_service.go
  frontend/src/types/proto-es/v1/project_service_pb.d.ts
  frontend/src/types/proto-es/v1/sql_service_pb.d.ts
  frontend/src/types/proto-es/v1/sql_service_pb.js
  frontend/src/types/proto-es/v1/subscription_service_pb.d.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.js
  frontend/src/types/proto/v1/project_service.ts
  frontend/src/types/proto/v1/sql_service.ts
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/project_service_grpc.pb.go
  proto/generated-go/v1/sql_service.pb.go
  proto/generated-go/v1/sql_service.pb.gw.go
  proto/generated-go/v1/sql_service_grpc.pb.go
  proto/generated-go/v1/subscription_service.pb.go
  proto/generated-go/v1/v1connect/project_service.connect.go
  proto/generated-go/v1/v1connect/sql_service.connect.go
  proto/v1/v1/project_service.proto
  proto/v1/v1/sql_service.proto
Labels: cla-signed

#16521 fix: cmux grpc
  backend/server/grpc_routes.go
Labels: cla-signed

#16525 chore: add parallel tasks prompt into `CLAUDE.md`
  CLAUDE.md
Labels: cla-signed

#16527 chore: update secret variable pricing
  backend/enterprise/plan.yaml
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16528 chore: reorder feature order
  backend/api/v1/sql_service.go
  backend/enterprise/plan.yaml
  frontend/src/components/EnvironmentForm/AccessControlConfigure.vue
  frontend/src/components/GeneralSetting/QueryDataPolicySetting.vue
  frontend/src/locales/dynamic/en-US.json
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  frontend/src/types/proto-es/v1/subscription_service_pb.d.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.js
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16533 chore: some ux fix and optimize
  frontend/src/components/IdentityProvider/IdentityProviderCreateWizard.vue
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
Labels: cla-signed

#16538 chore: user group feature guard
  backend/api/v1/group_service.go
Labels: cla-signed

#16539 chore: feature check auth
  backend/api/v1/auth_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/user_service.go
Labels: cla-signed

#16540 feat: generate migration for pg
  backend/plugin/schema/differ.go
  backend/plugin/schema/mssql/test-data/test_migration_safe_order.yaml
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/generate_migration_testcontainer_test.go
Labels: cla-signed

#16544 chore: feature fields
  backend/api/v1/org_policy_service.go
  frontend/src/types/proto-es/v1/subscription_service_pb.d.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.js
  frontend/src/types/proto/v1/subscription_service.ts
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/subscription_service.pb.go
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16545 feat: add raw claims to the response of test identity provider
  backend/api/v1/auth_service.go
  backend/api/v1/idp_service.go
  backend/plugin/idp/oauth2/oauth2.go
  backend/plugin/idp/oauth2/oauth2_test.go
  backend/plugin/idp/oidc/oidc.go
  backend/plugin/idp/oidc/oidc_test.go
  frontend/src/components/IdentityProvider/IdentityProviderCreateWizard.vue
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/components/IdentityProvider/IdentityProviderForm.vue
  frontend/src/components/IdentityProvider/TestConnection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/types/proto-es/v1/idp_service_pb.d.ts
  frontend/src/types/proto-es/v1/idp_service_pb.js
  frontend/src/types/proto/v1/idp_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/idp_service.pb.go
  proto/v1/v1/idp_service.proto
Labels: cla-signed

#16550 chore: fix i18n of sso
  frontend/src/components/IdentityProvider/IdentityProviderCreateWizard.vue
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16549 feat(backend): migrate to connectrpc
  backend/api/auth/auth.go
  backend/api/v1/acl.go
  backend/api/v1/actuator_service.go
  backend/api/v1/audit.go
  backend/api/v1/audit_log_service.go
  backend/api/v1/auth_service.go
  backend/api/v1/cel_service.go
  backend/api/v1/changelist_service.go
  backend/api/v1/database_catalog_service.go
  backend/api/v1/database_group_service.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_changelog.go
  backend/api/v1/debug_interceptor.go
  backend/api/v1/group_service.go
  backend/api/v1/idp_service.go
  backend/api/v1/instance_role_service.go
  backend/api/v1/instance_service.go
  backend/api/v1/issue_service.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/project_service.go
  backend/api/v1/release_service.go
  backend/api/v1/release_service_check.go
  backend/api/v1/review_config_service.go
  backend/api/v1/revision_service.go
  backend/api/v1/risk_service.go
  backend/api/v1/role_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/sheet_service.go
  backend/api/v1/sql_service.go
  backend/api/v1/sql_service_ai.go
  backend/api/v1/subscription_service.go
  backend/api/v1/user_service.go
  backend/api/v1/worksheet_service.go
  backend/api/v1/workspace_service.go
  backend/common/util.go
  backend/server/grpc_routes.go
  backend/server/routers.go
  backend/server/server.go
  backend/tests/tests.go
  go.mod
  go.sum
Labels: cla-signed

#16553 feat: implement mysql generate migration
  backend/plugin/db/mysql/sync.go
  backend/plugin/schema/differ.go
  backend/plugin/schema/mysql/generate_migration.go
  backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
Labels: cla-signed

#16554 chore: remove cmux
  backend/server/server.go
  go.mod
  go.sum
Labels: cla-signed

#16555 chore: fix release context
  frontend/src/components/Release/ReleaseCreate/context.ts
Labels: cla-signed

#16557 chore: guard undelete instances
  backend/api/v1/instance_service.go
Labels: cla-signed

#16560 fix: event listener for testing IdP
  frontend/src/components/IdentityProvider/TestConnection.vue
Labels: cla-signed

#16564 feat: implement generate migration for TiDB
  backend/plugin/schema/tidb/generate_migration.go
  backend/plugin/schema/tidb/generate_migration_testcontainer_test.go
Labels: cla-signed

#16566 fix: filter only done changelogs in sync schema
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/SyncDatabaseSchemaV1/DatabaseSchemaSelector.vue
Labels: cla-signed

#16568 chore: update instruction
  frontend/src/components/InstanceForm/Form.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16571 chore: external link in database group table
  frontend/src/components/DatabaseAndGroupSelector/DatabaseAndGroupSelector.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/BatchQueryDatabaseGroupSelector.vue
Labels: cla-signed

#16572 feat: grpc reflection
  backend/server/grpc_routes.go
  go.mod
  go.sum
Labels: cla-signed

#16573 chore: remove timeout middleware
  backend/server/routers.go
Labels: cla-signed

#16575 refactor: cors handlers to echo server
  backend/server/grpc_routes.go
  backend/server/routers.go
  go.mod
  go.sum
Labels: cla-signed

#16576 chore: deprecate outbound_ip_list
  backend/api/v1/setting_service.go
  backend/migrator/migration/3.7/0025##remove_outbound_ip_list.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto-es/v1/setting_service_pb.d.ts
  frontend/src/types/proto-es/v1/setting_service_pb.js
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/store/setting.proto
  proto/v1/v1/setting_service.proto
Labels: cla-signed

#16580 chore: fix bugs and add tests for oracle dump
  backend/common/testcontainer/testcontainer.go
  backend/plugin/schema/oracle/get_database_definition.go
  backend/plugin/schema/oracle/get_database_definition_testcontainer_test.go
Labels: cla-signed

#16583 chore: fix bugs and add tests for mssql dump
  backend/plugin/schema/mssql/get_database_definition.go
  backend/plugin/schema/mssql/get_database_definition_testcontainer_test.go
Labels: cla-signed

#16582 chore: try catch for `fetchIdentityProviderList`
  frontend/src/views/auth/Signin.vue
Labels: cla-signed

#16581 feat(fe): connect rpc clients interceptors
  frontend/src/grpcweb/context-key/ignored_codes.ts
  frontend/src/grpcweb/context-key/index.ts
  frontend/src/grpcweb/context-key/silent.ts
  frontend/src/grpcweb/index.ts
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts
Labels: cla-signed

#16585 fix: not show project selection by default
  frontend/src/components/v2/Model/PagedProjectTable.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/views/ProjectDashboard.vue
Labels: cla-signed

#16588 refactor: copy button
  frontend/src/components/AdvancedSearch/AdvancedSearch.vue
  frontend/src/components/Changelog/ChangelogDetail.vue
  frontend/src/components/IdentityProvider/IdentityProviderExternalURL.vue
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunLogTable/StatementCell.vue
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunSession/Cells/StatementCell.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/components/Rollout/RolloutDetail/TaskDetail/Panels/Overview.vue
  frontend/src/components/SensitiveData/components/DataExampleModal.vue
  frontend/src/components/SyncDatabaseSchemaV1/DiffViewPanel.vue
  frontend/src/components/SyncDatabaseSchemaV1/SelectTargetDatabasesView.vue
  frontend/src/components/TableSchemaViewer.vue
  frontend/src/components/User/Settings/AADSyncDrawer.vue
  frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
  frontend/src/components/User/Settings/UserDataTable/index.vue
  frontend/src/components/User/Settings/common.ts
  frontend/src/components/v2/Button/CopyButton.vue
  frontend/src/components/v2/Button/index.ts
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/plugins/ai/components/ChatView/Markdown/CodeBlock.vue
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/SettingWorkspaceSubscription.vue
  frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DetailPanel/DetailPanel.vue
  frontend/src/views/sql-editor/EditorCommon/SharePopover.vue
Labels: cla-signed

#16589 chore: cleanup agent url
  backend/api/v1/setting_service.go
  backend/component/config/profile.go
  backend/enterprise/plugin/hub/hub.go
  backend/enterprise/plugin/hub/remote_provider.go
  backend/enterprise/plugin/hub/utils.go
  backend/migrator/migration/3.7/0026##remove_plugin_agent_setting.sql
  backend/migrator/migrator_test.go
  frontend/src/types/proto-es/v1/setting_service_pb.d.ts
  frontend/src/types/proto-es/v1/setting_service_pb.js
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/setting.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/store/setting.proto
  proto/v1/v1/setting_service.proto
Labels: cla-signed

#16590 fix: missing engine
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#16592 chore: rename sso routes
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/components/IdentityProvider/IdentityProviderTable.vue
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/store/modules/v1/common.ts
  frontend/src/utils/idp.ts
  frontend/src/utils/useDashboardSidebar.ts
  frontend/src/views/SettingWorkspaceSSO.vue
  frontend/src/views/SettingWorkspaceSSODetail.vue
  frontend/src/views/sql-editor/Setting/SSO/SSO.vue
Labels: cla-signed

#16591 feat: set-cookie on connect handlers. grpc-gateway propagates set-cookie header
  backend/api/auth/header.go
  backend/api/v1/auth_service.go
Labels: cla-signed

#16596 chore: remove instance license checks for gh-ost
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostSwitch.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
Labels: cla-signed

#16597 fix: backup setting display
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackSection.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Configuration/PreBackupSection/PreBackupSection.vue
  frontend/src/components/Plan/components/Configuration/PreBackupSection/context.ts
Labels: cla-signed

#16599 chore: remove creating release page
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/IdentityProvider/IdentityProviderTable.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Project/ProjectReleasesPanel.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/CreateReleaseFilesPanel.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/FileToCreateTable.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/ImportFilesFromReleasePanel.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Release/ReleaseCreate/FileToCreateTable/index.ts
  frontend/src/components/Release/ReleaseCreate/ReleaseCreate.vue
  frontend/src/components/Release/ReleaseCreate/context.ts
  frontend/src/components/Release/ReleaseCreate/index.ts
  frontend/src/components/UploadFilesButton.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/router/dashboard/workspace.ts
  frontend/src/router/dashboard/workspaceRoutes.ts
  frontend/src/views/SettingWorkspaceSSO.vue
Labels: cla-signed

#16598 feat: fe connect rpc: migrate audit log services
  frontend/src/components/AuditLog/AuditLogDataTable.vue
  frontend/src/components/AuditLog/AuditLogSearch/AuditLogSearch.vue
  frontend/src/components/AuditLog/AuditLogSearch/utils.ts
  frontend/src/components/DataExportButton.vue
  frontend/src/grpcweb/index.ts
  frontend/src/store/modules/v1/auditLog.ts
  frontend/src/types/auditLog.ts
  frontend/src/types/timestamp.ts
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
Labels: cla-signed

#16600 chore(identity-provider): add detailed delete confirmation message
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16602 chore: update query result
  frontend/src/utils/v1/sql.ts
  frontend/src/views/sql-editor/EditorPanel/ResultPanel/BatchQuerySelect.vue
Labels: cla-signed

#16604 chore: add tests for tidb dump
  backend/common/testcontainer/testcontainer.go
  backend/plugin/schema/tidb/get_database_definition.go
  backend/plugin/schema/tidb/get_database_definition_testcontainer_test.go
Labels: cla-signed

#16603 fix: clickhouse uuid
  backend/plugin/db/clickhouse/query.go
  go.mod
Labels: cla-signed

#16615 chore: add route for issue detail page v1
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/Subscribers/SubscribeButton.vue
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/IssueV1/components/Sidebar/IssueLabels.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/Configuration/GhostSection/common.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
  frontend/src/components/Plan/components/HeaderSection/TitleInput.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/plan.ts
  frontend/src/components/Project/ProjectSidebarV1.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
  frontend/src/components/Project/useCurrentProject.ts
  frontend/src/components/Release/ReleaseDetail/NavBar/ApplyToDatabasePanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/utils/v1/issue/issue.ts
  frontend/src/utils/v1/issue/rollout.ts
  frontend/src/views/DashboardHeader.vue
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  frontend/src/views/project/ProjectIssueDetail.vue
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16616 chore: fix get current project
  frontend/src/store/modules/v1/project.ts
Labels: cla-signed

#16618 fix: overflow wrap in gh-ost setting
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostSection.vue
Labels: cla-signed

#16619 chore: refactor issue approval flow section
  frontend/src/bbkit/BBAvatar.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Approver.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/ReviewSection.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/RiskLevelTag.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/Timeline.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/TimelineIcon.vue
  frontend/src/components/IssueV1/components/Sidebar/ReviewSection/index.ts
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/ApprovalCandidate.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/ApprovalFlowSection.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/ApprovalStepItem.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/ApprovalUserView.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/PotentialApprovers.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/index.ts
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/index.ts
  frontend/src/components/Plan/components/IssueReviewView/index.ts
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/SpecsView.vue
  frontend/src/components/User/UserView.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16620 chore: support pagination in switch project modal
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/AuditLog/AuditLogDataTable.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
  frontend/src/components/v2/Model/PagedProjectTable.vue
Labels: cla-signed

#16621 fix: export log page size
  frontend/src/views/SettingWorkspaceAuditLog.vue
  frontend/src/views/project/ProjectAuditLogDashboard.vue
Labels: cla-signed, backport release/3.7.0, backport release/3.7.1

#16625 fix(i18n): Fix japanese translations
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/ja-JP.json
Labels: cla-signed

#16627 chore: slow query improvement
  backend/store/instance.go
Labels: cla-signed

#16631 fix: err details
  backend/api/v1/sql_service.go
Labels: cla-signed

#16632 chore: issue activities in review section
  frontend/src/components/Plan/components/HeaderSection/TitleInput.vue
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/index.ts
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue
Labels: cla-signed

#16633 fix: use connect sentinel errors
  backend/api/v1/error.go
  backend/api/v1/sql_service.go
Labels: cla-signed

#16636 feat: use new differ for schema editor and fix bugs
  backend/api/v1/sql_service.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/schema/mssql/generate_migration.go
  backend/plugin/schema/mssql/generate_migration_testcontainer_test.go
  backend/plugin/schema/mssql/test-data/test_migration_safe_order.yaml
  backend/plugin/schema/mysql/generate_migration.go
  backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
  backend/plugin/schema/oracle/generate_migration_testcontainer_test.go
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/generate_migration_testcontainer_test.go
  backend/plugin/schema/tidb/generate_migration.go
  backend/plugin/schema/tidb/generate_migration_testcontainer_test.go
Labels: cla-signed

#16641 cherrypick: [release/3.6.1] fix: fetch project
  frontend/src/store/modules/v1/project.ts
Labels: cla-signed

#16640 chore: grouping databases by environment
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/ProvideSQLEditorContext.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/sqlEditor/editor.ts
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/AddFactorButton.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorItem.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorPanel.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTag.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/FactorTags.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/GroupingBar.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/GroupingBar/index.ts
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/DatabaseNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/InstanceNode.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/TreeNode/Label.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/tree.ts
Labels: cla-signed

#16643 fix: cannot apply the template
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/SchemaTemplate/TableTemplateTable.vue
Labels: cla-signed

#16646 fix: bytebase-action rollout
  action/main.go
Labels: cla-signed

#16644 fix: instance query
  backend/store/instance.go
Labels: cla-signed, backport release/3.7.1

#16645 fix: oracle skip add limit for query
  backend/plugin/db/oracle/oracle.go
Labels: cla-signed

#16638 feat: handle comments
  backend/api/v1/database_converter.go
  backend/common/testcontainer/testcontainer.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/db/mysql/sync.go
  backend/plugin/db/oracle/sync.go
  backend/plugin/db/pg/sync.go
  backend/plugin/db/tidb/sync.go
  backend/plugin/schema/differ.go
  backend/plugin/schema/mssql/generate_migration.go
  backend/plugin/schema/mssql/generate_migration_testcontainer_test.go
  backend/plugin/schema/mssql/get_database_metadata.go
  backend/plugin/schema/mssql/test-data/test_get_database_metadata.yaml
  backend/plugin/schema/mysql/generate_migration.go
  backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
  backend/plugin/schema/oracle/generate_migration.go
  backend/plugin/schema/oracle/generate_migration_testcontainer_test.go
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/generate_migration_testcontainer_test.go
  backend/plugin/schema/tidb/generate_migration.go
  backend/plugin/schema/tidb/generate_migration_testcontainer_test.go
  backend/tests/schema_update_test.go
  backend/tests/syncer_test.go
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/store/database.proto
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16651 fix: failed to convert proto
  frontend/src/store/modules/v1/worksheet.ts
Labels: cla-signed

#16652 chore: make rollout more robust
  action/main.go
Labels: cla-signed

#16650 feat: handle mssql default
  backend/api/v1/database_converter.go
  backend/plugin/db/mssql/sync.go
  backend/plugin/schema/mssql/generate_migration.go
  backend/plugin/schema/mssql/generate_migration_testcontainer_test.go
  backend/plugin/schema/mssql/test-data/test_migration_tables.yaml
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/proto/v1/database_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/database.pb.go
  proto/generated-go/v1/database_service.pb.go
  proto/store/store/database.proto
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16653 chore: issue status/review actions in plan detail page
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/ActionIcon.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedComment.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/common.ts
  frontend/src/components/IssueV1/components/IssueTableV1.vue
  frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
  frontend/src/components/IssueV1/components/Sidebar/Sidebar.vue
  frontend/src/components/MarkdownEditor/MarkdownEditor.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateIssueButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueReviewActionPanel.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueStatusActionPanel.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/index.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/index.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/types.ts
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/issue-review.ts
  frontend/src/components/Plan/logic/poll.ts
  frontend/src/store/modules/v1/issue.ts
  frontend/src/utils/v1/issue/rollout.ts
  frontend/src/views/ExportCenter/DataExportIssueDataTable/DataExportIssueDataTable.vue
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16655 chore: run pre-checks for database change issues only
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed

#16657 feat(action): allow empty target-stage to create an empty rollout
  action/main.go
Labels: cla-signed

#16659 chore: worksheet permission check
  backend/api/v1/worksheet_service.go
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/SettingWorkspaceGeneral.vue
Labels: cla-signed
