Repository bytebase/bytebase, pull requests merged in 2025-07, with the labels that each got.

#16717 chore: warning for walkthrough refernece other database
  backend/plugin/advisor/catalog/walk_through.go
  backend/plugin/advisor/code.go
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#16718 feat: use simple input block for PostgreSQL column default in schema editor
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16720 feat: fe connect rpc migration
  frontend/src/store/modules/sqlReview.ts
Labels: cla-signed

#16722 feat: fe connect rpc migration
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorSQLCheckButton/SchemaEditorSQLCheckButton.vue
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDashboard.vue
  frontend/src/components/Changelist/ChangelistDashboard/ChangelistDataTable.vue
  frontend/src/components/Changelist/ChangelistDashboard/CreateChangelistPanel.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/AddChangePanel.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/context.ts
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangelogChangeItem.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/form/ChangelogForm.vue
  frontend/src/components/Changelist/ChangelistDetail/AddChangePanel/utils.ts
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/ChangeTable.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/DatabaseForChange.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/ReorderButtons.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/SQL.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangeTable/Source.vue
  frontend/src/components/Changelist/ChangelistDetail/ChangelistDetail.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/ImportButton.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/TitleEditor.vue
  frontend/src/components/Changelist/ChangelistDetail/NavBar/export.ts
  frontend/src/components/Changelist/ChangelistDetail/common.ts
  frontend/src/components/Changelist/ChangelistDetail/context.ts
  frontend/src/components/Database/DatabaseRevisionPanel.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/Sidebar/ReleaseInfo.vue
  frontend/src/components/IssueV1/components/StatementSection/StatementSection.vue
  frontend/src/components/IssueV1/components/TaskListSection/filter.ts
  frontend/src/components/IssueV1/components/TaskStatusIcon.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckSection/common.ts
  frontend/src/components/Plan/components/SQLCheckSection/context.ts
  frontend/src/components/Plan/components/SQLCheckV1Section/SQLCheckV1Section.vue
  frontend/src/components/Plan/components/StatementSection/ReleaseView/ReleaseView.vue
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Release/ReleaseDetail/BasicInfo.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/NavBar.vue
  frontend/src/components/Release/ReleaseDetail/NavBar/TitleEditor.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseArchiveRestoreButton.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseDetail.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileDetailPanel.vue
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
  frontend/src/components/Revision/RevisionDataTable.vue
  frontend/src/components/Revision/RevisionDetailPanel.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/store/modules/release.ts
  frontend/src/store/modules/revision.ts
  frontend/src/store/modules/v1/changelist.ts
  frontend/src/types/release.ts
  frontend/src/types/v1/changelist.ts
  frontend/src/utils/release.ts
  frontend/src/utils/v1/changelist.ts
  frontend/src/utils/v1/common-conversions.ts
  frontend/src/utils/v1/sql-conversions.ts
Labels: cla-signed

#16728 chore: update checks in task rollout panel
  frontend/src/components/Plan/components/RolloutView/RunTasksButton.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/TaskOperations.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
  frontend/src/components/Plan/components/RolloutView/context.ts
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Plan/logic/poller/utils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16742 chore: mssql latency
  backend/plugin/db/mssql/mssql.go
Labels: cla-signed

#16743 fix: boolean bug
  backend/common/engine.go
  backend/runner/migrator/column_default_migrator.go
  backend/runner/schemasync/syncer.go
  backend/runner/schemasync/syncer_test.go
Labels: cla-signed

#16746 fix: visibility enum
  frontend/src/store/modules/v1/worksheet.ts
Labels: cla-signed

#16744 chore: rpc latency
  backend/api/v1/audit.go
  frontend/src/types/proto-es/v1/audit_log_service_pb.d.ts
  frontend/src/types/proto-es/v1/audit_log_service_pb.js
  frontend/src/types/proto-es/v1/setting_service_pb.d.ts
  frontend/src/types/proto/v1/audit_log_service.ts
  frontend/src/types/proto/v1/setting_service.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/store/audit_log.pb.go
  proto/generated-go/v1/audit_log_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/store/store/audit_log.proto
  proto/v1/v1/audit_log_service.proto
Labels: cla-signed

#16721 feat: implement oracle get database metadata
  backend/plugin/db/oracle/sync.go
  backend/plugin/schema/oracle/generate_migration.go
  backend/plugin/schema/oracle/get_database_definition.go
  backend/plugin/schema/oracle/get_database_metadata.go
  backend/plugin/schema/oracle/get_database_metadata_test.go
Labels: cla-signed

#16752 chore: rpc latency
  backend/api/v1/audit_log_service.go
  frontend/src/components/AuditLog/AuditLogDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/util.ts
Labels: cla-signed

#16753 fix: handle legacy enum value in localStorage
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/sqlEditor/editor.ts
Labels: cla-signed

#16754 chore: unify enum format
  backend/api/v1/database_converter.go
  backend/api/v1/project_service.go
  backend/api/v1/worksheet_service.go
  frontend/src/components/StreamTable.vue
  frontend/src/store/modules/v1/worksheet.ts
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/proto-es/v1/project_service_pb.d.ts
  frontend/src/types/proto-es/v1/project_service_pb.js
  frontend/src/types/proto-es/v1/setting_service_pb.d.ts
  frontend/src/types/proto-es/v1/setting_service_pb.js
  frontend/src/types/proto-es/v1/worksheet_service_pb.d.ts
  frontend/src/types/proto-es/v1/worksheet_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/database_service.pb.go
  proto/generated-go/v1/project_service.pb.go
  proto/generated-go/v1/setting_service.pb.go
  proto/generated-go/v1/worksheet_service.pb.go
  proto/v1/v1/database_service.proto
  proto/v1/v1/project_service.proto
  proto/v1/v1/setting_service.proto
  proto/v1/v1/worksheet_service.proto
Labels: cla-signed

#16755 chore: convert connect error in audit log
  backend/api/v1/audit.go
Labels: cla-signed

#16757 feat(schema-editor): unify default value input for Postgres and MySQL
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16758 fix: mysql schema model bugs
  backend/plugin/schema/mysql/generate_migration.go
  backend/plugin/schema/mysql/generate_migration_testcontainer_test.go
  backend/plugin/schema/mysql/get_database_metadata.go
Labels: cla-signed

#16759 chore: remove unused components
  frontend/src/components/Plan/PlanDetailPage.vue
  frontend/src/components/Plan/components/CurrentSpecSelector.vue
  frontend/src/components/Plan/components/SpecDetailView/context.ts
  frontend/src/components/Plan/components/common/utils.ts
  frontend/src/components/Plan/index.ts
  frontend/src/views/project/CICDLayout.vue
  frontend/src/views/project/ProjectPlanDetail.vue
Labels: cla-signed

#16760 fix: issue type filter
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/v1/issue/issue.ts
Labels: cla-signed

#16762 feat: use connect rpc errors
  frontend/src/App.vue
  frontend/src/components/DatabaseDetail/SyncDatabaseButton.vue
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/Instance/InstanceSyncButton.vue
  frontend/src/components/Role/Setting/components/RoleDataTable/cells/RoleOperationsCell.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/grpcweb/middlewares/authInterceptorMiddleware.ts
  frontend/src/grpcweb/middlewares/errorNotificationMiddleware.ts
  frontend/src/grpcweb/middlewares/index.ts
  frontend/src/grpcweb/middlewares/simulateLatencyMiddleware.ts
  frontend/src/layouts/ProjectV1Layout.vue
  frontend/src/store/modules/sqlEditor/webTerminal.ts
  frontend/src/store/modules/v1/sql.ts
  frontend/src/types/v1/sql.ts
  frontend/src/utils/grpcweb.ts
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/ErrorView.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/ResultViewV1.vue
Labels: cla-signed

#16763 chore: remove dependencies
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#16764 fix: task status icon text
  frontend/src/components/IssueV1/components/TaskStatusIconV1.vue
Labels: cla-signed

#16765 fix(mssql): align default value handling with other engines
  backend/common/engine.go
  backend/plugin/db/mssql/sync.go
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
Labels: cla-signed

#16771 refactor: enum to string
  frontend/src/components/DataExportButton.vue
Labels: cla-signed

#16773 refactor: less any
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/Changelist/ChangelistDetail/ApplyToDatabasePanel/ApplyToDatabasePanel.vue
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
  frontend/src/components/IssueV1/components/Sidebar/PreBackupSection/TaskRollbackButton.vue
  frontend/src/components/MonacoEditor/utils.ts
  frontend/src/components/SyncDatabaseSchemaV1/index.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/utils/databaseGroup/issue.ts
  frontend/src/views/DatabaseDetail/DatabaseDetail.vue
  frontend/src/views/ReviewCenter/index.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#16774 fix: add limit for PostgreSQL
  backend/api/v1/sql_service.go
  backend/plugin/db/pg/pg.go
  backend/plugin/db/pg/query.go
  backend/plugin/db/pg/query_limit_test.go
Labels: cla-signed

#16776 chore: fix display of plan check run type enum
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
Labels: cla-signed

#16780 chore: update resource poller
  frontend/eslint.config.mjs
  frontend/src/components/Plan/PollerProvider.vue
  frontend/src/components/Plan/components/ChecksView/ChecksDrawer.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/SQLCheckV1Section/SQLCheckV1Section.vue
  frontend/src/components/Plan/logic/poller/index.ts
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/TransferDatabaseForm/TransferSourceSelector.vue
  frontend/src/views/project/CICDLayout.vue
Labels: cla-signed

#16781 fix: less any
  frontend/src/components/ColumnDataTable/utils.ts
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/components/IdentityProvider/IdentityProviderForm.vue
  frontend/src/components/IssueV1/components/Panel/IssueStatusActionPanel.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
  frontend/src/composables/utils.ts
  frontend/src/plugins/cel/logic/validate.ts
Labels: cla-signed

#16782 chore: fix binary display issue
  backend/plugin/db/pg/query.go
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
Labels: cla-signed

#16783 chore: type constraint
  frontend/src/components/IdentityProvider/IdentityProviderForm.vue
Labels: cla-signed

#16788 chore: less any
  frontend/src/components/IdentityProvider/TestConnection.vue
  frontend/src/router/index.ts
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/auth/AuthFooter.vue
Labels: cla-signed

#16789 fix: less any
  frontend/src/components/Database/DatabaseOverviewPanel.vue
  frontend/src/components/ExprEditor/ConditionGroup.vue
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
  frontend/src/components/IssueV1/components/Panel/BatchIssueStatusActionPanel.vue
  frontend/src/components/MonacoEditor/editor.ts
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/v2/TabFilter/types.ts
Labels: cla-signed

#16791 chore: check enableSample for quick start
  frontend/src/layouts/BodyLayout.vue
  frontend/src/layouts/IssuesLayout.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
Labels: cla-signed

#16792 chore: update i18n
  frontend/src/components/GeneralSetting/MaximumSQLResultSizeSetting.vue
  frontend/src/components/GeneralSetting/QueryDataPolicySetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/Setup/WorkspaceMode.vue
Labels: cla-signed

#16795 refactor: bytebase-action no global vars
  action/check_cmd.go
  action/main.go
  action/rollout_cmd.go
  action/root_cmd.go
  action/world/world.go
Labels: cla-signed

#16797 chore: saas default setting
  backend/api/v1/actuator_service.go
  backend/api/v1/setting_service.go
  backend/api/v1/user_service.go
  proto/buf.yaml
Labels: cla-signed

#16798 chore: update i18n for pro plan
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16801 chore: stage page
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostFlagsPanel.vue
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostSwitch.vue
  frontend/src/components/Plan/components/Configuration/PreBackupSection/context.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/RolloutView/RolloutView.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/StageView.vue
  frontend/src/components/Plan/components/RolloutView/TaskFilter.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskTableView.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/components/SQLCheckV1Section/SQLCheckV1Section.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/SpecDetailView/context.ts
  frontend/src/components/Plan/components/SpecsView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/useTempEditState.ts
  frontend/src/components/Plan/components/StatementSection/ReleaseView/ReleaseView.vue
  frontend/src/components/Plan/components/StatementSection/StatementSection.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/initialize/index.ts
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/CICDLayout.vue
  frontend/src/views/project/PlanSpecDetailView.vue
  frontend/src/views/project/PlanSpecsView.vue
  frontend/src/views/project/RolloutDetailLayout.vue
  frontend/src/views/project/RolloutDetailView.vue
Labels: cla-signed

#16800 chore: support spatial index for mssql
  backend/plugin/schema/mssql/generate_migration.go
  backend/plugin/schema/mssql/get_database_definition.go
  backend/plugin/schema/mssql/get_database_metadata.go
  backend/plugin/schema/mssql/test-data/test_get_database_metadata.yaml
  go.mod
  go.sum
Labels: cla-signed

#16804 refactor: action pkgs
  action/command/api.go
  action/command/azure_devops.go
  action/command/bitbucket.go
  action/command/check.go
  action/command/file.go
  action/command/file_test.go
  action/command/gitlab.go
  action/command/platform.go
  action/command/rollout.go
  action/command/root.go
  action/main.go
Labels: cla-signed

#16805 chore: feature switch for database CI/CD
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/StatementSection/StatementSection.vue
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/components/Rollout/RolloutDataTable.vue
  frontend/src/composables/useIssueLayoutVersion.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/IssueDetailV1View.vue
  frontend/src/views/project/IssueDetailView.vue
  frontend/src/views/project/ProjectPlanDashboard.vue
Labels: cla-signed

#16807 feat: bump go to 1.24.4
  .github/workflows/backend-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test_link.yml
  go.mod
  scripts/Dockerfile
  scripts/Dockerfile.action
  scripts/Dockerfile.action-debian
  scripts/Dockerfile.aws
  scripts/build_init.sh
Labels: cla-signed

#16808 feat: migrate column default for other niche engines
  backend/common/engine.go
  backend/plugin/db/clickhouse/sync.go
  backend/plugin/db/cockroachdb/sync.go
  backend/plugin/db/dm/sync.go
  backend/plugin/db/obo/sync.go
  backend/plugin/db/redshift/sync.go
  backend/plugin/db/risingwave/sync.go
  backend/plugin/db/snowflake/sync.go
  backend/plugin/db/spanner/sync.go
  backend/plugin/db/starrocks/sync.go
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
Labels: cla-signed

#16809 chore: update checks in creating issue panel
  frontend/src/components/AlterSchemaPrepForm/SchemaEditorModal.vue
  frontend/src/components/IssueV1/components/Panel/CommonDrawer.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/Sidebar.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/RolloutView/RolloutView.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/StagesView.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Release/ReleaseDataTable.vue
  frontend/src/components/Rollout/kits/TaskStatus.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/databaseGroup/issue.ts
  frontend/src/views/project/ProjectPlanDashboard.vue
Labels: cla-signed

#16812 fix: compare bigint
  frontend/src/components/Changelist/ChangelistDetail/RawSQLPanel/RawSQLPanel.vue
  frontend/src/components/Changelog/ChangelogDetail.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/store/modules/v1/worksheet.ts
Labels: cla-signed, bacport release/3.8.0

#16814 chore: update rollout stages
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/RolloutView/RolloutView.vue
  frontend/src/components/Plan/components/RolloutView/RunTasksButton.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/StageView.vue
  frontend/src/components/Plan/components/RolloutView/StagesView.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Rollout/RolloutDataTable.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/issue/rollout.ts
Labels: cla-signed

#16816 feat(dep): remove long and protobufjs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Changelist/ChangelistDetail/RawSQLPanel/RawSQLPanel.vue
  frontend/src/components/Changelog/ChangelogDetail.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/main.ts
  frontend/src/store/modules/v1/worksheet.ts
  frontend/src/types/v1/schemaEditor/atomType.ts
  frontend/src/utils/sheet.ts
  frontend/src/utils/v1/sql.ts
  frontend/vite.config.ts
Labels: cla-signed

#16818 feat(dep): remove unused
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: cla-signed

#16820 chore: demo repo
  .github/workflows/docker-tag-latest.yml
Labels: cla-signed

#16822 chore(action): optimize binary size
  scripts/Dockerfile.action
Labels: cla-signed

#16821 chore(action): no imports from bytebase/backend
  action/command/azure_devops.go
  action/command/bitbucket.go
  action/command/gitlab.go
  action/common/common.go
  action/github/github.go
  action/main.go
Labels: cla-signed

#16823 chore: add title.matches to search plans
  backend/api/v1/plan_service.go
  backend/store/plan.go
  frontend/src/store/modules/v1/plan.ts
  frontend/src/types/proto-es/v1/plan_service_pb.d.ts
  frontend/src/views/project/ProjectPlanDashboard.vue
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/generated-go/v1/plan_service.pb.go
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#16824 fix: issue path
  frontend/src/components/GrantRequestPanel/GrantRequestPanel.vue
Labels: cla-signed

#16825 fix: risk source string
  frontend/src/utils/workspaceApprovalSetting.ts
Labels: cla-signed, bacport release/3.8.0

#16826 chore: redirect to legacy issue page
  frontend/src/views/project/CICDLayout.vue
Labels: cla-signed

#16827 chore: remove fixed creator scope in search plans
  frontend/src/views/project/ProjectPlanDashboard.vue
Labels: cla-signed

#16832 chore: merge tabs in new ci/cd page
  frontend/src/components/Plan/components/AddSpecDrawer.vue
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
  frontend/src/components/Plan/components/IssueReviewView/IssueReviewView.vue
  frontend/src/components/Plan/components/IssueReviewView/OverviewSection.vue
  frontend/src/components/Plan/components/Overview.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Project/useProjectSidebar.ts
  frontend/src/composables/useIssueLayoutVersion.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/router/dashboard/projectV1.ts
  frontend/src/views/project/CICDLayout.vue
  frontend/src/views/project/PlanSpecsView.vue
Labels: cla-signed

#16834 chore: hide empty environments by default
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/tree.ts
Labels: cla-signed

#16835 fix: add missing env tier guard
  backend/api/v1/setting_service.go
Labels: cla-signed

#16836 chore: sqlEditorUser bb.databases.sync
  backend/component/iam/acl.yaml
Labels: cla-signed

#16837 fix: admin mode
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/store/modules/sqlEditor/webTerminal.ts
Labels: cla-signed, backport release/3.8.0

#16839 chore: build bytebase-demo
  .github/workflows/build-push-demo-image.yml
Labels: cla-signed

#16840 chore: bytebase demo
  .github/workflows/build-push-demo-image.yml
  .github/workflows/demo-daily-deploy.yml
  .github/workflows/docker-tag-latest.yml
Labels: cla-signed

#16842 chore: change image version name
  .github/workflows/build-push-demo-image.yml
Labels: cla-signed

#16844 feat(database): replace deprecated default_string with default field
  backend/api/v1/database_converter.go
  backend/generated-go/v1/database_service.pb.go
  backend/tests/schema_update_test.go
  backend/tests/syncer_test.go
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorLite/utils/columnDefaultValue.ts
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/v1/schemaEditor/atomType.ts
  frontend/src/utils/schemaEditor/filter.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16843 fix: remove database owner role switching in schema migration
  backend/migrator/migrator.go
Labels: cla-signed

#16846 refactor(database): unify column default value handling
  backend/api/v1/database_converter.go
  backend/generated-go/v1/database_service.pb.go
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/TableColumnEditor.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/DefaultValueCell.vue
  frontend/src/components/SchemaEditorLite/Panels/TableEditor.vue
  frontend/src/components/SchemaEditorLite/utils/columnDefaultValue.ts
  frontend/src/components/SchemaTemplate/FieldTemplateForm.vue
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/v1/schemaEditor/atomType.ts
  frontend/src/utils/schemaEditor/filter.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/database_service.proto
Labels: cla-signed

#16848 feat: allow to return rollout without tasks
  action/command/rollout.go
  backend/api/v1/rollout_service.go
  backend/tests/action_test.go
  backend/tests/gitops_test.go
Labels: cla-signed

#16849 chore: minor fix
  frontend/src/components/GeneralSetting/PasswordRestrictionSetting.vue
  frontend/src/components/User/Settings/UserPassword.vue
  frontend/src/views/ProfileDashboard.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#16853 chore: change schema object owner
  backend/migrator/migration/3.8/0003##change_table_ownership_to_current_user.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16860 refactor(proto): move release file type emun inside the message
  action/command/file.go
  backend/api/v1/release_service.go
  backend/generated-go/store/release.pb.go
  backend/generated-go/v1/release_service.pb.go
  backend/tests/gitops_test.go
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckButton.vue
  frontend/src/components/Plan/components/SQLCheckV1Section/SQLCheckV1Section.vue
  frontend/src/components/Plan/components/StatementSection/ReleaseView/ReleaseView.vue
  frontend/src/components/SQLCheck/SQLCheckButton.vue
  frontend/src/types/proto-es/v1/release_service_pb.d.ts
  frontend/src/types/proto-es/v1/release_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/release.proto
  proto/v1/v1/release_service.proto
Labels: cla-signed

#16862 chore: show tasks for active stage
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Rollout/kits/TaskStatus.vue
Labels: cla-signed

#16861 refactor: cleanup redshift magic
  backend/plugin/db/redshift/redshift.go
Labels: cla-signed

#16864 fix: state enum in list instances
  frontend/src/store/modules/v1/instance.ts
Labels: cla-signed

#16863 chore: add run time to task from latest task run
  backend/api/v1/rollout_service_converter.go
  backend/generated-go/v1/rollout_service.pb.go
  backend/store/task.go
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/TaskName.vue
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/IssueStatusSection.vue
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/logic/poller/utils.ts
  frontend/src/components/Rollout/kits/TaskStatus.vue
  frontend/src/locales/en-US.json
  frontend/src/types/proto-es/v1/rollout_service_pb.d.ts
  frontend/src/types/proto-es/v1/rollout_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16865 chore: update resources poller
  frontend/src/components/Plan/components/PlanCheckRunStatusIcon.vue
  frontend/src/components/Plan/components/RefreshIndicator.vue
  frontend/src/components/Plan/logic/poller/index.ts
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/components/Plan/logic/poller/utils.ts
Labels: cla-signed

#16868 chore: add icon
  frontend/src/views/sql-editor/EditorCommon/QueryContextSettingPopover.vue
Labels: cla-signed

#16871 chore: remove `bb.plans.preview` permission
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/migrator/migration/3.8/0004##remove_plans_preview_permission.sql
  backend/migrator/migrator_test.go
  frontend/src/types/iam/permission.ts
Labels: cla-signed

#16876 chore: fix page hang when restore instance/project
  frontend/src/AppRootContext.ts
  frontend/src/components/Instance/InstanceArchiveRestoreButton.vue
  frontend/src/components/Project/ProjectArchiveRestoreButton.vue
  frontend/src/store/modules/v1/cache.ts
Labels: cla-signed

#16877 chore(action): get env var in pre run
  action/command/root.go
Labels: cla-signed

#16879 fix: convert workspace profile
  backend/api/v1/setting_service.go
Labels: cla-signed

#16881 chore: no bytebase prefix
  backend/plugin/parser/base/transaction_mode.go
  backend/plugin/parser/base/transaction_mode_test.go
Labels: cla-signed

#16878 chore: add filter to list rollouts request
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/generated-go/v1/rollout_service.pb.go
  backend/store/pipeline.go
  frontend/src/components/Project/ProjectRolloutsPanel.vue
  frontend/src/store/modules/rollout.ts
  frontend/src/types/proto-es/v1/rollout_service_pb.d.ts
  frontend/src/types/proto-es/v1/rollout_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16883 test: add retries and sleep for test
  backend/plugin/db/mssql/sync_spatial_testcontainer_test.go
Labels: cla-signed

#16886 feat(editor): add transaction mode toggle for Redshift DDL/DML tasks
  frontend/src/components/IssueV1/components/StatementSection/EditorView/EditorActionPopover.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/InstanceRoleSelect.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/TransactionModeToggle.vue
  frontend/src/components/IssueV1/components/StatementSection/EditorView/directiveUtils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#16888 feat(db): add generic transaction mode execution support
  backend/common/engine.go
  backend/plugin/db/redshift/redshift.go
  backend/plugin/parser/base/transaction_mode.go
  backend/plugin/parser/base/transaction_mode_test.go
  frontend/src/components/IssueV1/components/StatementSection/EditorView/TransactionModeToggle.vue
  frontend/src/utils/v1/instance.ts
Labels: cla-signed

#16889 chore: not allow manually upload license in the saas mode
  backend/api/v1/subscription_service.go
  backend/enterprise/license.go
  frontend/src/views/SettingWorkspaceSubscription.vue
Labels: cla-signed

#16890 chore: show specs directly instead of dropdown
  frontend/src/components/Plan/components/CurrentSpecSelector.vue
  frontend/src/components/Plan/components/HeaderSection/HeaderSection.vue
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/CICDLayout.vue
Labels: cla-signed

#16892 refactor(db): remove unused transaction mode parsing in drivers
  backend/plugin/db/bigquery/bigquery.go
  backend/plugin/db/hive/hive.go
  backend/plugin/db/trino/trino.go
Labels: cla-signed

#16894 chore: fix i18n of issue status
  frontend/src/components/IssueV1/components/IssueStatusIcon.vue
  frontend/src/components/Plan/components/SpecDetailView/AllTargetsDrawer.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/components/v2/Model/DatabaseGroupName.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16897 chore: prepare databases
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/StageView.vue
  frontend/src/components/Plan/components/RolloutView/TaskFilter.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
Labels: cla-signed

#16903 chore: add deleted to plan table
  backend/migrator/migration/3.9/0000##plan_deleted.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16904 chore: add state to plan message
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service_converter.go
  backend/generated-go/v1/plan_service.pb.go
  backend/store/plan.go
  frontend/src/types/proto-es/v1/plan_service_pb.d.ts
  frontend/src/types/proto-es/v1/plan_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/plan_service.proto
Labels: cla-signed

#16905 chore: refactor GetQueriableDataSource
  backend/api/v1/sql_service.go
Labels: cla-signed

#16906 chore: no database secret
  backend/api/v1/audit.go
  backend/api/v1/database_service.go
  backend/api/v1/database_service_test.go
  backend/common/resource_name.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/enterprise/plan.yaml
  backend/generated-go/store/database.pb.go
  backend/generated-go/v1/database_service.pb.go
  backend/generated-go/v1/database_service.pb.gw.go
  backend/generated-go/v1/database_service_grpc.pb.go
  backend/generated-go/v1/subscription_service.pb.go
  backend/generated-go/v1/v1connect/database_service.connect.go
  backend/migrator/migration/3.9/0001##remove_database_secret_permissions.sql
  backend/migrator/migrator_test.go
  backend/runner/plancheck/ghost_sync_executor.go
  backend/runner/plancheck/statement_advise_executor.go
  backend/runner/plancheck/statement_report_executor.go
  backend/runner/taskrun/executor.go
  backend/utils/utils.go
  backend/utils/utils_test.go
  frontend/src/components/Database/context.ts
  frontend/src/components/DatabaseDetail/Settings/DatabaseSettingsPanel.vue
  frontend/src/components/DatabaseDetail/Settings/components/Secrets.vue
  frontend/src/locales/dynamic/en-US.json
  frontend/src/locales/dynamic/es-ES.json
  frontend/src/locales/dynamic/ja-JP.json
  frontend/src/locales/dynamic/vi-VN.json
  frontend/src/locales/dynamic/zh-CN.json
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/common.ts
  frontend/src/store/modules/v1/databaseSecret.ts
  frontend/src/store/modules/v1/index.ts
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto-es/v1/database_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_service_pb.js
  frontend/src/types/proto-es/v1/subscription_service_pb.d.ts
  frontend/src/types/proto-es/v1/subscription_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/database.proto
  proto/v1/v1/database_service.proto
  proto/v1/v1/subscription_service.proto
Labels: cla-signed

#16907 chore: move unused permissions
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/generated-go/v1/instance_role_service.pb.go
  backend/generated-go/v1/instance_role_service_grpc.pb.go
  backend/generated-go/v1/v1connect/instance_role_service.connect.go
  backend/migrator/migration/3.9/0002##remove_unused_permissions.sql
  backend/migrator/migrator_test.go
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto-es/v1/instance_role_service_pb.d.ts
  frontend/src/types/proto-es/v1/instance_role_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/instance_role_service.proto
Labels: cla-signed

#16909 chore: cleanup secret
  backend/migrator/migration/3.9/0003##remove_database_metadata_secrets.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16913 chore: show latest task run detail in task table
  frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
Labels: cla-signed

#16911 chore: show schema editor in create plan drawer
  frontend/src/components/Plan/components/AddSpecDrawer.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecListSection.vue
  frontend/src/components/Plan/components/common/utils.ts
  frontend/src/components/SchemaEditorLite/Aside/Tree.vue
  frontend/src/components/SchemaEditorLite/Editor.vue
  frontend/src/components/SchemaEditorLite/Panels/DatabaseEditor.vue
  frontend/src/components/SchemaEditorLite/TabsContainer.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/InstanceDashboard.vue
  frontend/src/views/project/ProjectPlanDashboard.vue
Labels: cla-signed

#16914 fix: handle negative time interval
  backend/plugin/db/pg/query.go
  backend/plugin/db/pg/query_test.go
Labels: cla-signed

#16910 fix: typo build_bytebase_aws.sh
  scripts/build_bytebase_aws.sh
Labels: cla-signed

#16919 fix: redirect to legacy page for issues without plan
  frontend/src/components/Plan/logic/initialize/index.ts
Labels: cla-signed, backport release/3.8.1

#16924 chore: unify timestamp display
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskTable.vue
  frontend/src/components/Rollout/RolloutDataTable.vue
  frontend/src/components/misc/Timestamp.vue
Labels: cla-signed

#16928 fix: support clear classification
  backend/api/v1/setting_service.go
Labels: cla-signed

#16929 fix: any type errors of check results
  frontend/src/components/PlanCheckRun/PlanCheckRunDetail.vue
Labels: cla-signed

#16932 fix: enum to string
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
Labels: cla-signed, backport release/3.8.1

#16936 chore: add claude lint command
  .claude/commands/lint.md
Labels: cla-signed

#16937 fix: npe of get columns
  backend/plugin/parser/mysql/backup.go
Labels: cla-signed

#16942 chore: remove unknown group
  frontend/src/types/v1/group.ts
  frontend/src/types/v1/index.ts
Labels: cla-signed

#16952 chore: go version
  .github/workflows/backend-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test_link.yml
  backend/common/cel.go
  backend/common/cel_test.go
  backend/common/config.go
  backend/common/config_dev.go
  backend/common/config_release.go
  backend/common/context.go
  backend/common/db_schema_test.go
  backend/common/engine.go
  backend/common/position.go
  backend/common/resource_name.go
  backend/common/resource_name_test.go
  backend/common/util.go
  backend/common/util_test.go
  backend/plugin/db/util/connection.go
  backend/plugin/db/util/driverutil.go
  backend/plugin/db/util/sasl.go
  backend/plugin/db/util/ssh.go
  backend/utils/member.go
  go.mod
  scripts/Dockerfile
  scripts/Dockerfile.action
  scripts/Dockerfile.action-debian
  scripts/Dockerfile.aws
Labels: cla-signed

#16954 chore: drop `pipeline.name`
  backend/api/v1/plan_service.go
  backend/api/v1/rollout_service.go
  backend/api/v1/rollout_service_converter.go
  backend/component/webhook/event.go
  backend/component/webhook/manager.go
  backend/generated-go/v1/rollout_service.pb.go
  backend/migrator/migration/3.9/0005##drop_pipeline_name.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/runner/approval/runner.go
  backend/store/pipeline.go
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueCreationActionPanel.vue
  frontend/src/types/proto-es/v1/rollout_service_pb.d.ts
  frontend/src/types/proto-es/v1/rollout_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/rollout_service.proto
Labels: cla-signed

#16955 chore: remove rollout-title in actions
  action/README.md
  action/command/rollout.go
  action/world/world.go
  backend/tests/action_test.go
Labels: cla-signed, breaking

#16957 chore: clean `isDev` guard in frontend
  frontend/src/components/IssueV1/components/TaskListSection/TaskCard.vue
Labels: cla-signed

#16958 refactor: remove convertProtoToProto
  backend/api/v1/actuator_service.go
  backend/api/v1/setting_service.go
Labels: cla-signed

#16959 chore: remove axios dependency
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/axios.ts
  frontend/src/main.ts
  frontend/src/store/modules/v1/actuator.ts
  frontend/vite.config.ts
Labels: cla-signed

#16961 chore: add ellipsis to plan data table
  frontend/src/components/Plan/components/PlanDataTable/PlanDataTable.vue
Labels: cla-signed

#16963 fix: allow to run canceled tasks
  frontend/src/components/Plan/components/RolloutView/TaskOperations.vue
  frontend/src/components/Plan/components/RolloutView/TaskStatusActions.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
Labels: cla-signed

#16964 chore: add title to rollout data table
  frontend/src/components/Rollout/RolloutDataTable.vue
Labels: cla-signed

#16965 fix: create plan with title
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed

#16966 feat: link to db (some)
  frontend/src/components/Plan/components/RolloutView/StageCard.vue
  frontend/src/components/Plan/components/RolloutView/TaskRunRollbackDrawer.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/components/common/DatabaseDisplay.vue
  frontend/src/utils/v1/database.ts
Labels: cla-signed

#16968 fix: plan poller for issue/rollout refresh
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/RefreshIndicator.vue
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/Plan/logic/issue-review.ts
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/views/project/CICDLayout.vue
Labels: cla-signed

#16970 chore: add alert to approved issues
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentList.vue
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCommentAction.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueReviewActionPanel.vue
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#16971 fix: set issue title
  frontend/src/components/IssueV1/logic/initialize/create.ts
Labels: cla-signed

#16974 fix: create a new config instead of in-place changes to avoid shared-map
  backend/api/v1/query_result_masker.go
  backend/api/v1/sql_service.go
  backend/runner/schemasync/syncer.go
  backend/store/model/database.go
Labels: cla-signed

#16975 feat(schema): release digest
  backend/migrator/migration/3.9/0006##release_digest.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
Labels: cla-signed

#16976 chore: filter out archive objects
  backend/api/v1/database_service.go
Labels: cla-signed

#16979 fix: task run permission checks
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/RolloutView/taskPermissions.ts
Labels: cla-signed

#16980 fix: order of using hook
  frontend/src/components/Plan/components/IssueReviewView/ActivitySection/ActivitySection.vue
Labels: cla-signed
