Repository bytebase/bytebase, pull requests merged in 2025-09, with the labels that each got.

#17317 chore: release table width and resizable
  frontend/src/components/Release/ReleaseDataTable.vue
Labels: cla-signed

#17318 chore(action): default release title
  action/command/rollout.go
Labels: cla-signed

#17319 refactor: creating database issue page
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueReviewActionPanel.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/panels/IssueStatusActionPanel.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/types.ts
  frontend/src/components/Plan/components/IssueReviewView/DatabaseChangeView.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseCreateView.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView.vue
  frontend/src/components/Plan/components/IssueReviewView/IssueBaseLayout.vue
  frontend/src/components/Plan/components/IssueReviewView/index.ts
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
  frontend/src/components/Plan/logic/poller/poller.ts
  frontend/src/utils/v1/issue/rollout.ts
  frontend/src/views/project/CICDLayout.vue
  frontend/src/views/project/IssueDetailV1View.vue
Labels: cla-signed

#17309 chore: update cassandra query span
  backend/plugin/parser/cassandra/query_span_extractor.go
  backend/plugin/parser/cassandra/query_span_test.go
Labels: cla-signed

#17324 fix: schema rule type
  backend/plugin/advisor/sql_review.go
Labels: cla-signed

#17325 chore: upgrade Go from 1.24.5 to 1.25.0
  .github/workflows/backend-tests.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test_link.yml
  go.mod
  scripts/Dockerfile
  scripts/Dockerfile.action
  scripts/Dockerfile.action-debian
  scripts/Dockerfile.aws
Labels: cla-signed

#17326 fix: resolve Vue warnings
  frontend/src/components/DatabaseInfo.vue
  frontend/src/components/IssueV1/components/HeaderSection/HeaderSection.vue
  frontend/src/components/Plan/components/PlanCheckSection/PlanCheckSection.vue
  frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
  frontend/src/views/project/PlanSpecsView.vue
Labels: cla-signed

#17329 chore: update release description in all translations
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17330 feat: display release file type
  frontend/src/components/Release/ReleaseDetail/ReleaseFileTable/ReleaseFileTable.vue
Labels: cla-signed

#17331 chore: tweak CreateDatabasePrepPanel.vue code structure
  frontend/src/components/CreateDatabasePrepForm/CreateDatabasePrepPanel.vue
Labels: cla-signed

#17335 chore(action): readme declarative mode usage
  action/README.md
Labels: cla-signed

#17336 refactor: simplify loop
  backend/api/v1/rollout_service.go
Labels: cla-signed

#17334 chore: disable ai setting in the saas mode
  backend/api/v1/setting_service.go
  frontend/src/components/GeneralSetting/AIAugmentationSetting.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17337 chore: fix environment setting doc link
  frontend/src/components/EnvironmentForm/Form.vue
Labels: cla-signed

#17339 feat: batch create task runs
  backend/api/v1/rollout_service.go
  backend/runner/taskrun/schedulerv2.go
  backend/store/task_run.go
Labels: cla-signed

#17343 refactor: remove ComposedDatabaseGroup type and simplify data flow
  frontend/src/components/DatabaseGroup/DatabaseGroupDataTable.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/DatabaseGroup/ProjectDatabaseGroupPanel.vue
  frontend/src/store/modules/dbGroup.ts
  frontend/src/types/dbGroup.ts
  frontend/src/utils/databaseGroup/issue.ts
Labels: cla-signed

#17346 fix: fallback to instance resource name from target
  frontend/src/components/Plan/components/IssueReviewView/DatabaseCreateView.vue
Labels: cla-signed

#17347 fix: description in legacy issue page
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/GrantRequestIssueDetailPage.vue
  frontend/src/components/IssueV1/IssueDetailPage.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
Labels: cla-signed, backport release/3.9.1

#17351 chore: update
  backend/plugin/db/redis/sync.go
Labels: cla-signed

#17356 chore: add description tooltip for SQL review check
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/Plan/components/ChecksView/ChecksView.vue
  frontend/src/components/Plan/components/SQLCheckSection/SQLCheckBadge.vue
  frontend/src/components/PlanCheckRun/PlanCheckRunBadge.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/shims-3rd-party.d.ts
Labels: cla-signed

#17359 fix: engine in instance filter
  frontend/src/views/InstanceDashboard.vue
Labels: cla-signed

#17362 refactor: use NewColumnNotExistsError
  backend/plugin/advisor/catalog/walk_through.go
Labels: cla-signed

#17361 fix: improve advanced search filter tag layout structure
  frontend/src/components/AdvancedSearch/ScopeTags.vue
Labels: cla-signed

#17364 feat(action): job summary
  action/command/rollout.go
  action/command/root.go
  action/world/world.go
Labels: cla-signed

#17366 refactor: action pkgs
  action/azure/azure.go
  action/bitbucket/bitbucket.go
  action/command/check.go
  action/command/cloud/cloud.go
  action/command/output/output.go
  action/command/rollout.go
  action/command/root.go
  action/command/validation/flags.go
  action/github/summary.go
  action/gitlab/gitlab.go
Labels: cla-signed

#17367 refactor: drop deprecated data_source table
  backend/migrator/migration/3.10/0002##drop_data_source_table.sql
  backend/migrator/migration/LATEST.sql
  backend/migrator/migrator_test.go
  backend/store/instance.go
Labels: cla-signed

#17368 fix: mitigate flaky test TestSyncSpatialIndexWithTestcontainer
  backend/plugin/db/mssql/sync_spatial_testcontainer_test.go
Labels: cla-signed

#17369 fix: handle PostgreSQL partition table syntax in tokenizer
  backend/plugin/parser/tokenizer/tokenizer.go
  backend/plugin/parser/tokenizer/tokenizer_test.go
Labels: cla-signed

#17376 fix: should throw error if cannot found slack user
  backend/plugin/webhook/slack/slack.go
Labels: cla-signed

#17378 chore: optimize result selection/copy
  frontend/src/components/User/Settings/UserDataTable/cells/UserNameCell.vue
  frontend/src/components/v2/Button/CopyButton.vue
  frontend/src/components/v2/Form/ResourceIdField.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/VirtualDataBlock.vue
Labels: cla-signed

#17380 fix: permission checks for editing description
  frontend/src/components/IssueV1/components/IssueCommentSection/IssueCommentView/IssueCreatedCommentV1.vue
Labels: cla-signed

#17381 chore: not include the service account
  backend/metric/collector/user_count.go
  backend/metric/metric.go
  backend/store/stats.go
  frontend/src/components/ProfileDropdown.vue
  frontend/src/components/Quickstart.vue
  frontend/src/store/modules/v1/actuator.ts
  frontend/src/views/SettingWorkspaceSubscription.vue
  frontend/src/views/SettingWorkspaceUsers.vue
Labels: cla-signed

#17383 fix: tab content is not cached correctly
  frontend/src/store/modules/sqlEditor/tab.ts
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/FlatTableList.vue
Labels: cla-signed, backport release/3.9.2

#17385 chore: improve editor height and responsive layout
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/StatementSection.vue
Labels: cla-signed

#17386 chore: improve mobile UI responsiveness
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
  frontend/src/views/DashboardHeader.vue
Labels: cla-signed

#17388 fix(gh-ost): remove unnecessary check for database instance activation
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostSwitch.vue
Labels: cla-signed

#17417 chore: default width
  frontend/src/components/Changelog/ChangelogDataTable.vue
  frontend/src/components/Revision/RevisionDataTable.vue
Labels: cla-signed

#17418 refactor: auth reduce getUser calls
  backend/api/auth/auth.go
Labels: cla-signed

#17419 fix: transaction mode switch initialization and api calls
  frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSwitch.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/utils.ts
Labels: cla-signed

#17421 fix: instance role section api calls and ui improvements
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/Configuration/InstanceRoleSection/InstanceRoleSection.vue
  frontend/src/components/Plan/components/Configuration/InstanceRoleSection/InstanceRoleSelect.vue
  frontend/src/components/Plan/components/StatementSection/directiveUtils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17422 fix(action): remove ext
  action/command/file.go
Labels: cla-signed

#17423 chore: calculate the unmatched databases
  backend/api/v1/database_group_service.go
  backend/api/v1/plan_service.go
  backend/api/v1/release_service_check.go
  backend/generated-go/v1/database_group_service.pb.go
  backend/store/policy.go
  backend/tests/grouping_change_test.go
  backend/utils/utils.go
  frontend/src/components/DatabaseGroup/MatchedDatabaseView.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetListSection.vue
  frontend/src/components/Plan/logic/plan-check.ts
  frontend/src/composables/useExecuteSQL.ts
  frontend/src/store/modules/dbGroup.ts
  frontend/src/types/proto-es/v1/database_group_service_pb.d.ts
  frontend/src/types/proto-es/v1/database_group_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/database_group_service.proto
Labels: cla-signed

#17427 chore: support instance_id in risk condition
  backend/api/v1/release_service_check.go
  backend/common/cel.go
  backend/runner/approval/runner.go
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleDialog.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/RuleDialog/RuleForm.vue
  frontend/src/components/CustomApproval/Settings/components/CustomApproval/common/StepsTable.vue
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
Labels: cla-signed

#17426 chore: remove "format on save" checkbox from plan editor
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/components/StatementSection/EditorView/FormatOnSaveCheckbox.vue
Labels: cla-signed

#17429 feat: support pg view in SDL differ
  backend/plugin/schema/differ.go
  backend/plugin/schema/pg/get_sdl_diff.go
  backend/plugin/schema/pg/view_sdl_diff_test.go
Labels: cla-signed

#17436 feat: generate view migration for AST only diff
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/view_migration_integration_test.go
Labels: cla-signed

#17443 chore: remove instance-level additional bindings from SQL service
  backend/generated-go/v1/sql_service.pb.go
  backend/generated-go/v1/sql_service.pb.gw.go
  frontend/src/types/proto-es/v1/sql_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/sql_service.proto
Labels: cla-signed

#17445 feat: support generate pg sequence migration for ast-only
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/sequence_migration_integration_test.go
Labels: cla-signed

#17446 chore: audit log api enforcement
  backend/api/v1/audit_log_service.go
  backend/api/v1/audit_log_service_test.go
  backend/enterprise/license.go
Labels: cla-signed

#17428 chore: add transaction isolation level to MySQL
  backend/common/engine.go
  backend/plugin/db/mysql/mysql.go
  backend/plugin/parser/base/transaction_mode.go
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSection.vue
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSelect.vue
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/context.ts
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/index.ts
  frontend/src/components/Plan/components/StatementSection/directiveUtils.ts
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17450 chore: add labels to proto
  backend/generated-go/store/project.pb.go
  backend/generated-go/v1/project_service.pb.go
  frontend/src/types/proto-es/v1/project_service_pb.d.ts
  frontend/src/types/proto-es/v1/project_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/project.proto
  proto/v1/v1/project_service.proto
Labels: cla-signed

#17453 fix: lint
  frontend/src/components/CustomApproval/Settings/components/RiskCenter/RiskDialog/RiskForm.vue
  frontend/src/components/CustomApproval/Settings/components/common/utils.ts
  frontend/src/components/DatabaseDetail/SQLEditorButtonV1.vue
  frontend/src/components/DatabaseGroup/DatabaseGroupForm.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/common.ts
  frontend/src/components/IdentityProvider/IdentityProviderEditForm.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/TinySQLEditorButton.vue
  frontend/src/components/IssueV1/components/IssueLabelSelector.vue
  frontend/src/components/IssueV1/components/Panel/TaskRolloutActionPanel.vue
  frontend/src/components/MonacoEditor/utils.ts
  frontend/src/components/Plan/components/Configuration/InstanceRoleSection/context.ts
  frontend/src/components/Plan/components/Configuration/TransactionModeSection/context.ts
  frontend/src/components/Plan/logic/context.ts
  frontend/src/components/SensitiveData/GlobalMaskingRulesView.vue
  frontend/src/composables/useDataLabelAttrs.ts
  frontend/src/plugins/cel/types/factor.ts
  frontend/src/plugins/cel/types/operator.ts
  frontend/src/store/modules/quickLink.ts
  frontend/src/store/modules/sqlEditor/tree.ts
  frontend/src/store/modules/sqlReview.ts
  frontend/src/types/plan.ts
  frontend/src/utils/issue/cel.ts
  frontend/src/utils/web-storage.ts
  frontend/src/views/SchemaTemplate/ColumnTypes.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/actions.tsx
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
  frontend/src/views/sql-editor/EditorCommon/hover-state.ts
  frontend/src/views/sql-editor/EditorPanel/TerminalPanel/useAttractFocus.ts
Labels: cla-signed

#17456 feat: support genereate pg index migration for ast-only
  backend/plugin/schema/pg/generate_migration.go
  backend/plugin/schema/pg/table_migration_integration_test.go
Labels: cla-signed

#17458 refactor: database export issue
  frontend/src/components/DataExportPrepForm/DataExportPrepForm.vue
  frontend/src/components/IssueV1/DataExportIssueDetailPage.vue
  frontend/src/components/IssueV1/components/DataExportSection/DataExportSection.vue
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/ExportOptionSection.vue
  frontend/src/components/IssueV1/components/DataExportSection/ExportOptionSection/index.ts
  frontend/src/components/IssueV1/components/DataExportSection/index.ts
  frontend/src/components/IssueV1/components/HeaderSection/Actions/common/IssueExtraActionButtonGroup.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/common/index.ts
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportArchiveDownloadButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/ExportCenterButton.vue
  frontend/src/components/IssueV1/components/HeaderSection/Actions/request/index.ts
  frontend/src/components/IssueV1/components/HeaderSection/Actions/rollout/CombinedRolloutButtonGroup.vue
  frontend/src/components/IssueV1/components/index.ts
  frontend/src/components/IssueV1/index.ts
  frontend/src/components/Plan/components/ExportOption/ExportFormatSelector.vue
  frontend/src/components/Plan/components/ExportOption/ExportPasswordInputer.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/create/CreateButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/export/ExportArchiveDownloadAction.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/export/index.ts
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionButton.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/types.ts
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/OptionsSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/TasksSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/index.ts
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/SpecDetailView/DataExportOptionsSection.vue
  frontend/src/components/Plan/components/SpecDetailView/SpecDetailView.vue
  frontend/src/components/Plan/components/SpecDetailView/context.ts
  frontend/src/components/Plan/components/StatementSection/EditorView/EditorView.vue
  frontend/src/components/Plan/logic/initialize/create.ts
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseOperations.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/project/CICDLayout.vue
  frontend/src/views/project/ProjectIssueDetail.vue
  frontend/src/views/sql-editor/EditorCommon/ResultView/SingleResultViewV1.vue
Labels: cla-signed

#17451 chore: add labels to projects with simple CEL filtering (for now)
  backend/api/v1/database_service.go
  backend/api/v1/project_service.go
  backend/api/v1/project_service_test.go
  frontend/src/components/AdvancedSearch/index.ts
  frontend/src/components/AdvancedSearch/useCommonSearchScopeOptions.ts
  frontend/src/components/ColumnDataTable/LabelsCell.vue
  frontend/src/components/GrantRequestPanel/DatabaseResourceForm/DatabaseResourceSelector.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchContent.vue
  frontend/src/components/Project/ProjectSwitch/ProjectSwitchPopover.vue
  frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
  frontend/src/components/ProjectDatabasesPanel.vue
  frontend/src/components/SchemaEditorLite/Panels/TableColumnEditor/components/LabelsCell.vue
  frontend/src/components/SchemaTemplate/FieldTemplateTable.vue
  frontend/src/components/v2/Model/DatabaseV1Table/DatabaseV1Table.vue
  frontend/src/components/v2/Model/DatabaseV1Table/cells/index.ts
  frontend/src/components/v2/Model/PagedProjectTable.vue
  frontend/src/components/v2/Model/ProjectV1Table.vue
  frontend/src/components/v2/Model/cells/DatabaseNameCell.vue
  frontend/src/components/v2/Model/cells/LabelsCell.vue
  frontend/src/components/v2/Model/cells/ProjectNameCell.vue
  frontend/src/components/v2/Model/cells/index.ts
  frontend/src/components/v2/ResourceOccupiedModal/useResourceByName.ts
  frontend/src/components/v2/Select/ProjectSelect.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/project.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/views/DatabaseDashboard.vue
  frontend/src/views/InstanceDetail.vue
  frontend/src/views/ProjectDashboard.vue
  frontend/src/views/sql-editor/ConnectionPanel/ConnectionPane/ConnectionPane.vue
  proto/v1/v1/project_service.proto
Labels: cla-signed

#17459 refactor: improve plan task rollout UI and code organization
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
  frontend/src/components/Plan/components/SpecDetailView/TargetsSelectorDrawer.vue
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17460 chore: grpc gateway routing error
  backend/server/grpc_routes.go
Labels: cla-signed

#17461 chore: improve export archive task run handling
  backend/api/v1/sql_service.go
  frontend/src/components/Plan/components/HeaderSection/Actions/export/ExportArchiveDownloadAction.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/unified/UnifiedActionGroup.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
Labels: cla-signed

#17463 refactor: improve plan configuration UI and component consistency
  frontend/src/components/Plan/components/Configuration/Configuration.vue
  frontend/src/components/Plan/components/Configuration/GhostSection/GhostSection.vue
  frontend/src/components/Plan/components/Configuration/InstanceRoleSection/InstanceRoleSection.vue
  frontend/src/components/Plan/components/Configuration/InstanceRoleSection/context.ts
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSection.vue
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/IsolationLevelSelect.vue
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/context.ts
  frontend/src/components/Plan/components/Configuration/IsolationLevelSection/index.ts
  frontend/src/components/Plan/components/Configuration/PreBackupSection/PreBackupSection.vue
  frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSection.vue
  frontend/src/components/Plan/components/Configuration/TransactionModeSection/TransactionModeSwitch.vue
  frontend/src/components/Plan/components/Configuration/TransactionModeSection/context.ts
Labels: cla-signed

#17465 chore: not change the schema when navigating between different database objects
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
Labels: cla-signed

#17478 fix: pg readonly user grant statement
  frontend/src/components/InstanceForm/DataSourceSection/CreateDataSourceExample.vue
Labels: cla-signed

#17479 fix: hide automatic rollout info when tasks have task runs
  frontend/src/components/Plan/components/RolloutView/TaskRolloutActionPanel.vue
Labels: cla-signed

#17481 fix: pg statement type
  backend/plugin/parser/pg/statement_type.go
Labels: cla-signed

#17482 chore: sql editor fix and optimize
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/views/sql-editor/AsidePanel/HistoryPane/HistoryPane.vue
  frontend/src/views/sql-editor/AsidePanel/SchemaPane/actions.tsx
  frontend/src/views/sql-editor/EditorCommon/ResultView/ErrorView/AdviceItem.vue
  frontend/src/views/sql-editor/EditorPanel/StandardPanel/SQLEditor.vue
  frontend/src/views/sql-editor/SQLEditorHomePage.vue
  frontend/src/views/sql-editor/context.ts
Labels: cla-signed

#17483 refactor: restrict RESTRICT_ISSUE_CREATION_FOR_SQL_REVIEW policy to project level only
  backend/api/v1/org_policy_service.go
  backend/migrator/migration/3.10/0005##migrate_restrict_issue_creation_for_sql_review_policy.sql
  backend/migrator/migrator_test.go
  frontend/src/components/GeneralSetting/SecuritySetting.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
Labels: cla-signed

#17485 feat: support pg sdl format dump
  backend/api/v1/database_service.go
  backend/plugin/schema/pg/get_database_definition.go
  backend/plugin/schema/pg/get_database_definition_sdl_test.go
  backend/plugin/schema/schema.go
Labels: cla-signed

#17487 chore: support sdl init
  backend/plugin/schema/pg/get_sdl_diff.go
  backend/plugin/schema/pg/get_sdl_diff_test.go
Labels: cla-signed

#17489 refactor: deprecate RESTRICT_ISSUE_CREATION_FOR_SQL_REVIEW policy
  backend/api/v1/org_policy_service.go
  backend/api/v1/project_service.go
  backend/generated-go/store/policy.pb.go
  backend/generated-go/store/policy_equal.pb.go
  backend/generated-go/store/project.pb.go
  backend/generated-go/store/project_equal.pb.go
  backend/generated-go/v1/org_policy_service.pb.go
  backend/generated-go/v1/org_policy_service_equal.pb.go
  backend/generated-go/v1/project_service.pb.go
  backend/generated-go/v1/project_service_equal.pb.go
  backend/migrator/migration/3.10/0006##migrate_enforce_sql_review_to_project.sql
  backend/migrator/migrator_test.go
  frontend/src/components/GeneralSetting/RestrictIssueCreationConfigure.vue
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectSecuritySettingPanel.vue
  frontend/src/components/SQLCheck/SQLCheckPanel.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto-es/v1/org_policy_service_pb.d.ts
  frontend/src/types/proto-es/v1/org_policy_service_pb.js
  frontend/src/types/proto-es/v1/project_service_pb.d.ts
  frontend/src/types/proto-es/v1/project_service_pb.js
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/policy.proto
  proto/store/store/project.proto
  proto/v1/v1/org_policy_service.proto
  proto/v1/v1/project_service.proto
Labels: cla-signed

#17484 refactor: remove confusing task selection in database export view
  frontend/src/components/IssueV1/components/TaskRunSection/TaskRunDetail.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/ExecutionHistorySection.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/TasksSection.vue
  frontend/src/components/Plan/components/IssueReviewView/DatabaseExportView/index.ts
  frontend/src/components/Plan/components/RolloutView/TaskRunTable.vue
  frontend/src/components/Plan/components/RolloutView/TaskView.vue
Labels: cla-signed

#17492 feat: use new sdl workflow
  backend/plugin/schema/pg/get_database_definition.go
  backend/runner/taskrun/schema_update_sdl_executor.go
  backend/runner/taskrun/schema_update_sdl_executor_test.go
  backend/tests/action_test.go
Labels: cla-signed

#17493 chore: getTaskTypeFromSpec total
  backend/api/v1/plan_service.go
Labels: cla-signed

#17494 refactor: remove redundant get issue
  backend/api/v1/plan_service.go
Labels: cla-signed

#17495 chore: more strict update check
  backend/api/v1/plan_service.go
Labels: cla-signed

#17470 chore: deprecate the bb.sql.export permission and projectExporter role
  backend/api/v1/sql_service.go
  backend/component/iam/acl.yaml
  backend/component/iam/permission.go
  backend/component/iam/permission.yaml
  backend/generated-go/v1/iam_policy.pb.go
  backend/migrator/migration/3.10/0007##remove_exporter_role.sql
  backend/migrator/migration/3.10/0008##remove_exporter_permission.sql
  backend/migrator/migrator_test.go
  backend/store/policy.go
  frontend/src/components/ProjectMember/AddProjectMember/AddProjectMemberForm.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/EditProjectRolePanel.vue
  frontend/src/components/ProjectMember/ProjectMemberRolePanel/index.vue
  frontend/src/types/iam/permission.ts
  frontend/src/types/proto-es/v1/iam_policy_pb.d.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/iam_policy.proto
Labels: cla-signed

#17501 chore: remove deprecated Issue Creator and Last Issue Approver rollout policy options
  backend/api/v1/issue_service_convert.go
  backend/api/v1/org_policy_service.go
  backend/api/v1/rollout_service.go
  backend/component/webhook/manager.go
  backend/generated-go/store/policy.pb.go
  backend/generated-go/store/policy_equal.pb.go
  backend/generated-go/v1/org_policy_service.pb.go
  backend/generated-go/v1/org_policy_service_equal.pb.go
  backend/migrator/migration/3.11/0000##cleanup_rollout_policy_issue_roles.sql
  backend/migrator/migrator_test.go
  frontend/src/components/EnvironmentForm/EnvironmentForm.vue
  frontend/src/components/EnvironmentForm/RolloutPolicyConfig.vue
  frontend/src/locales/en-US.json
  frontend/src/locales/es-ES.json
  frontend/src/locales/ja-JP.json
  frontend/src/locales/vi-VN.json
  frontend/src/locales/zh-CN.json
  frontend/src/store/modules/v1/policy.ts
  frontend/src/types/proto-es/v1/org_policy_service_pb.d.ts
  frontend/src/types/proto-es/v1/org_policy_service_pb.js
  frontend/src/types/v1/role.ts
  proto/gen/grpc-doc/store/README.md
  proto/gen/grpc-doc/store/index.html
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/store/store/policy.proto
  proto/v1/v1/org_policy_service.proto
Labels: cla-signed

#17503 feat: update task types to DML
  backend/api/v1/plan_service.go
Labels: cla-signed

#17504 feat: handle column drift in SDL workflow
  backend/plugin/schema/pg/column_rewrite_test.go
  backend/plugin/schema/pg/get_database_definition.go
  backend/plugin/schema/pg/get_sdl_diff.go
Labels: cla-signed

#17507 fix: allow export issue creators to see Export button without bb.taskRuns.create permission
  frontend/src/components/Plan/components/HeaderSection/Actions/Actions.vue
Labels: cla-signed

#17511 feat: handle table constraint drift in SDL workflow
  backend/plugin/schema/pg/column_rewrite_test.go
  backend/plugin/schema/pg/constraint_rewrite_test.go
  backend/plugin/schema/pg/get_database_definition.go
  backend/plugin/schema/pg/get_database_definition_sdl_test.go
  backend/plugin/schema/pg/get_sdl_diff.go
Labels: cla-signed

#17512 feat: handle index drift in SDL workflow
  backend/plugin/schema/pg/constraint_rewrite_test.go
  backend/plugin/schema/pg/get_database_definition.go
  backend/plugin/schema/pg/get_database_definition_sdl_test.go
  backend/plugin/schema/pg/get_sdl_diff.go
  backend/plugin/schema/pg/index_rewrite_test.go
  backend/plugin/schema/pg/sdl_validation_testcontainer_test.go
Labels: cla-signed

#17523 fix: issue search params
  backend/api/v1/issue_service.go
  backend/generated-go/v1/issue_service.pb.go
  backend/store/issue.go
  frontend/src/components/IssueV1/components/IssueSearch/IssueSearch.vue
  frontend/src/components/Project/Settings/ProjectGeneralSettingPanel.vue
  frontend/src/components/Project/Settings/ProjectIssueRelatedSettingPanel.vue
  frontend/src/store/modules/v1/issue.ts
  frontend/src/types/proto-es/v1/issue_service_pb.d.ts
  frontend/src/types/v1/issue/issue.ts
  frontend/src/utils/v1/advanced-search/common.ts
  frontend/src/utils/v1/advanced-search/issue/ui-filter.ts
  frontend/src/utils/v1/advanced-search/issue/utils.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/issue_service.proto
Labels: cla-signed

#17526 chore: persist member order
  frontend/src/components/Member/MemberDataTableByRole.vue
  frontend/src/components/Member/utils.ts
  frontend/src/components/Plan/components/IssueReviewView/Sidebar/ApprovalFlowSection/ApprovalStepItem.vue
Labels: cla-signed

#17524 chore: allow select & copy partial value
  frontend/src/views/sql-editor/EditorCommon/ResultView/DataTable/TableCell.vue
Labels: cla-signed

#17527 refactor: merge DatabaseSchemaUpdate and DatabaseDataUpdate into DatabaseUpdate
  backend/api/v1/rollout_service_converter.go
  backend/generated-go/v1/rollout_service.pb.go
  backend/generated-go/v1/rollout_service_equal.pb.go
  frontend/src/types/proto-es/v1/rollout_service_pb.d.ts
  frontend/src/types/proto-es/v1/rollout_service_pb.js
  frontend/src/utils/v1/issue/rollout.ts
  proto/gen/grpc-doc/openapi.yaml
  proto/gen/grpc-doc/v1/README.md
  proto/gen/grpc-doc/v1/index.html
  proto/v1/v1/rollout_service.proto
Labels: cla-signed
